/**
 * Content verification state. THIS FILE IS REWRITTEN by scripts/content/merge-verdicts.ts after a
 * verification run; edit it by hand only to set `authoredBy` notes. Anything not listed here is
 * treated as 'draft' (AI-drafted, not yet independently verified) and is labelled that way in the app.
 *
 * Status ladder (each rung needs the one below):
 *   draft              authored (by a person or AI) but not independently checked
 *   machine-verified   two independent blind checks agree with the answer key, and no check flagged it
 *   sourced            machine-verified AND every checked claim carries a cited source
 *   educator-reviewed  sourced AND two credentialed educators on the platform signed off
 *   disputed           a check or a learner report contradicts it; withheld from practice until resolved
 */
export type VerifyStatus = 'draft' | 'machine-verified' | 'sourced' | 'educator-reviewed' | 'disputed';

export interface CourseVerification {
  status: VerifyStatus;
  /** How the content was written. */
  authoredBy: 'human' | 'ai-assisted' | 'ai-generated' | 'computed';
  /** ISO date of the last verification run. */
  checkedAt?: string;
  /** Plain-language description of what was done. */
  method?: string;
  /** Names of the two credentialed educators who signed off (required for 'educator-reviewed'). */
  reviewers?: string[];
  coverage?: { questions: number; agreed: number; flagged: number; claims?: number; claimsSupported?: number };
}

export interface FlaggedItem {
  /** 'flag' = checks disagreed with the key; 'fix' = confirmed wrong, awaiting correction; 'report' = learner report under review. */
  s: 'flag' | 'fix' | 'report';
  note?: string;
}

/** Courses with a known verification state. Everything else is 'draft'. GENERATED by scripts/content/merge-verdicts.ts. */
export const COURSE_STATUS: Record<string, CourseVerification> = {
  "math-generated": {
    "status": "machine-verified",
    "authoredBy": "computed",
    "method": "Every problem is generated by code; the answers are recomputed independently in automated tests."
  },
  "context-math": {
    "status": "machine-verified",
    "authoredBy": "computed",
    "method": "Every problem is generated by code; the answers are recomputed independently in automated tests."
  },
  "art-movements-classical": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 140,
      "flagged": 0,
      "claims": 156,
      "claimsSupported": 0
    }
  },
  "art-movements-modern": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 139,
      "flagged": 1,
      "claims": 158,
      "claimsSupported": 0
    }
  },
  "audio-engineering": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 130,
      "agreed": 128,
      "flagged": 2,
      "claims": 145,
      "claimsSupported": 0
    }
  },
  "color-theory": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 99,
      "flagged": 1,
      "claims": 111,
      "claimsSupported": 0
    }
  },
  "design-movements": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 110,
      "agreed": 109,
      "flagged": 1,
      "claims": 126,
      "claimsSupported": 0
    }
  },
  "entertainment-finance": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 120,
      "agreed": 119,
      "flagged": 1,
      "claims": 137,
      "claimsSupported": 0
    }
  },
  "film-business": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 95,
      "agreed": 93,
      "flagged": 2,
      "claims": 111,
      "claimsSupported": 0
    }
  },
  "film-directing": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 120,
      "agreed": 120,
      "flagged": 0,
      "claims": 142,
      "claimsSupported": 0
    }
  },
  "film-genres": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 120,
      "agreed": 119,
      "flagged": 1,
      "claims": 138,
      "claimsSupported": 0
    }
  },
  "film-producing": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 110,
      "agreed": 110,
      "flagged": 0,
      "claims": 124,
      "claimsSupported": 0
    }
  },
  "graphic-design": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 120,
      "agreed": 120,
      "flagged": 0,
      "claims": 133,
      "claimsSupported": 0
    }
  },
  "history-arab-world": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 140,
      "flagged": 0,
      "claims": 155,
      "claimsSupported": 0
    }
  },
  "history-asia": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 160,
      "agreed": 160,
      "flagged": 0,
      "claims": 182,
      "claimsSupported": 0
    }
  },
  "history-europe": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 160,
      "agreed": 160,
      "flagged": 0,
      "claims": 182,
      "claimsSupported": 0
    }
  },
  "history-north-america": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 160,
      "agreed": 160,
      "flagged": 0,
      "claims": 176,
      "claimsSupported": 0
    }
  },
  "history-south-america": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 139,
      "flagged": 1,
      "claims": 152,
      "claimsSupported": 0
    }
  },
  "ip-protection": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 96,
      "flagged": 4,
      "claims": 118,
      "claimsSupported": 0
    }
  },
  "law-admin": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 87,
      "flagged": 3,
      "claims": 124,
      "claimsSupported": 0
    }
  },
  "law-business-orgs": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 99,
      "flagged": 1,
      "claims": 80,
      "claimsSupported": 0
    }
  },
  "law-civpro": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 98,
      "flagged": 2,
      "claims": 120,
      "claimsSupported": 0
    }
  },
  "law-college": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 108,
      "agreed": 106,
      "flagged": 2,
      "claims": 108,
      "claimsSupported": 0
    }
  },
  "law-conlaw": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 85,
      "agreed": 85,
      "flagged": 0,
      "claims": 102,
      "claimsSupported": 2
    }
  },
  "law-contracts": {
    "status": "disputed",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 75,
      "flagged": 15,
      "claims": 56,
      "claimsSupported": 0
    }
  },
  "law-crimlaw": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 105,
      "agreed": 102,
      "flagged": 3,
      "claims": 124,
      "claimsSupported": 0
    }
  },
  "law-crimpro": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 93,
      "flagged": 7,
      "claims": 123,
      "claimsSupported": 0
    }
  },
  "law-evidence": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 97,
      "flagged": 3,
      "claims": 120,
      "claimsSupported": 0
    }
  },
  "law-intl-human-rights": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 89,
      "flagged": 1,
      "claims": 108,
      "claimsSupported": 0
    }
  },
  "law-intl-humanitarian-criminal": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 99,
      "flagged": 1,
      "claims": 120,
      "claimsSupported": 0
    }
  },
  "law-intl-public": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 91,
      "flagged": 9,
      "claims": 120,
      "claimsSupported": 0
    }
  },
  "law-intl-trade-business": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 100,
      "flagged": 0,
      "claims": 120,
      "claimsSupported": 0
    }
  },
  "law-legalwriting": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 93,
      "flagged": 7,
      "claims": 120,
      "claimsSupported": 0
    }
  },
  "law-profresp": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 105,
      "agreed": 105,
      "flagged": 0,
      "claims": 78,
      "claimsSupported": 0
    }
  },
  "law-property": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 85,
      "agreed": 83,
      "flagged": 2,
      "claims": 53,
      "claimsSupported": 0
    }
  },
  "law-torts": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 84,
      "flagged": 6,
      "claims": 56,
      "claimsSupported": 0
    }
  },
  "lighting-design": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 100,
      "flagged": 0,
      "claims": 116,
      "claimsSupported": 0
    }
  },
  "lit-studies-early": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 140,
      "flagged": 0,
      "claims": 158,
      "claimsSupported": 0
    }
  },
  "lit-studies-modern": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 139,
      "flagged": 1,
      "claims": 163,
      "claimsSupported": 0
    }
  },
  "med-clin-em": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 87,
      "flagged": 3,
      "claims": 109,
      "claimsSupported": 53
    }
  },
  "med-clin-fm": {
    "status": "disputed",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 25,
      "flagged": 65,
      "claims": 76,
      "claimsSupported": 0
    }
  },
  "med-clin-im": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 100,
      "flagged": 0,
      "claims": 121,
      "claimsSupported": 0
    }
  },
  "med-clin-obgyn": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 87,
      "flagged": 3,
      "claims": 110,
      "claimsSupported": 0
    }
  },
  "med-clin-peds": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 88,
      "flagged": 2,
      "claims": 108,
      "claimsSupported": 0
    }
  },
  "med-clin-psych": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 89,
      "flagged": 1,
      "claims": 109,
      "claimsSupported": 0
    }
  },
  "med-clin-surgery": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 98,
      "flagged": 2,
      "claims": 117,
      "claimsSupported": 0
    }
  },
  "med-ethics-prof": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 105,
      "agreed": 105,
      "flagged": 0,
      "claims": 137,
      "claimsSupported": 0
    }
  },
  "med-g912": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 80,
      "agreed": 79,
      "flagged": 1,
      "claims": 122,
      "claimsSupported": 0
    }
  },
  "med-global-health": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 99,
      "flagged": 1,
      "claims": 120,
      "claimsSupported": 0
    }
  },
  "med-micro": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 100,
      "flagged": 0,
      "claims": 122,
      "claimsSupported": 0
    }
  },
  "med-pharm-principles": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 98,
      "flagged": 2,
      "claims": 120,
      "claimsSupported": 25
    }
  },
  "med-pharm-systems": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 138,
      "flagged": 2,
      "claims": 168,
      "claimsSupported": 15
    }
  },
  "med-skills": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 90,
      "agreed": 90,
      "flagged": 0,
      "claims": 108,
      "claimsSupported": 0
    }
  },
  "music-business": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 95,
      "agreed": 94,
      "flagged": 1,
      "claims": 109,
      "claimsSupported": 0
    }
  },
  "music-genres": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 139,
      "flagged": 1,
      "claims": 155,
      "claimsSupported": 0
    }
  },
  "music-history-eras": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 140,
      "flagged": 0,
      "claims": 159,
      "claimsSupported": 0
    }
  },
  "music-theory-college": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 140,
      "agreed": 139,
      "flagged": 1,
      "claims": 157,
      "claimsSupported": 40
    }
  },
  "music-theory-early": {
    "status": "draft",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 80,
      "agreed": 78,
      "flagged": 2,
      "claims": 31,
      "claimsSupported": 0
    }
  },
  "music-theory-elementary": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 99,
      "flagged": 1,
      "claims": 117,
      "claimsSupported": 0
    }
  },
  "music-theory-secondary": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 120,
      "agreed": 119,
      "flagged": 1,
      "claims": 141,
      "claimsSupported": 0
    }
  },
  "music-theory": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 56,
      "agreed": 55,
      "flagged": 1,
      "claims": 78,
      "claimsSupported": 0
    }
  },
  "publishing-business": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 100,
      "agreed": 100,
      "flagged": 0,
      "claims": 110,
      "claimsSupported": 0
    }
  },
  "world-mythology": {
    "status": "machine-verified",
    "authoredBy": "ai-assisted",
    "checkedAt": "2026-10-02",
    "method": "2 independent blind checks (A, B) answered every question without seeing the key, and checked the factual claims in each lesson against cited sources. Items the checks disputed are withheld from practice.",
    "coverage": {
      "questions": 160,
      "agreed": 158,
      "flagged": 2,
      "claims": 181,
      "claimsSupported": 0
    }
  }
};

/** Question / lesson ids withheld from practice until resolved. GENERATED by scripts/content/merge-verdicts.ts. */
export const FLAGGED: Record<string, FlaggedItem> = {
  "art-movements-modern.l18.q5": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "audio-engineering.l09.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "audio-engineering.l14.q1": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "color-theory.l15.q4": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "design-movements.l15.q5": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "design-movements.l04": {
    "s": "flag",
    "note": "claim contradicted: Loos, Ornament and Crime, 'lecture and essay of 1908'"
  },
  "entertainment-finance.l02.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "film-genres.l03.q4": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "history-south-america.l21.q4": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "ip-protection.l06.q2": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "law-admin.l01.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-admin.l03.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-admin.l12.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-admin.l01": {
    "s": "flag",
    "note": "claim contradicted: Independent agencies such as the FTC have statutory for-cause removal limits whose validity \"now sits at the center of a constitutional dispute\"."
  },
  "law-admin.l03": {
    "s": "flag",
    "note": "claim contradicted: The FTC removal case asking whether Humphrey's Executor should be overruled is pending, and the lesson presents the Humphrey's multimember-body exception as current law."
  },
  "law-business-orgs.l10.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-business-orgs.l05": {
    "s": "flag",
    "note": "claim contradicted: Delaware's 2025 SB 21: 'the effects and constitutionality of those changes continue to be litigated and debated.'"
  },
  "law-business-orgs.l10": {
    "s": "flag",
    "note": "claim contradicted: SB 21's validity challenges 'are being worked out' and Delaware law is in transition."
  },
  "law-civpro.l04.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-civpro.l08.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-civpro.l08": {
    "s": "flag",
    "note": "claim contradicted: Worked example: company subject to personal jurisdiction in Colorado but events in Arizona means Colorado venue may be improper under 1391(b)(2)"
  },
  "law-civpro.l12": {
    "s": "flag",
    "note": "claim contradicted: Rule 15(a)(1): amend once as of course within 21 days after serving, or 21 days after responsive pleading or 12(b),(e),(f) motion, whichever is later"
  },
  "law-college.l03.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-college.l12.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-conlaw.l02": {
    "s": "flag",
    "note": "claim contradicted: Whether Humphrey's Executor survives remains a live question as of this writing"
  },
  "law-conlaw.l12": {
    "s": "flag",
    "note": "claim contradicted: TikTok v. Garland (2025) upheld the divest-or-ban law 'assuming without deciding that intermediate scrutiny applied'"
  },
  "law-conlaw.l16": {
    "s": "flag",
    "note": "claim contradicted: Allen v. Milligan (2023) applied the Section 2 results test, and 'the Court later considered related questions'"
  },
  "law-contracts.l01.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l02.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l04.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l07.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l11.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l11.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l11.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l11.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l12.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l12.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l12.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l12.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l12.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l13.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-contracts.l14.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimlaw.l06.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimlaw.l11.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimlaw.l16.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimlaw.l07": {
    "s": "flag",
    "note": "claim contradicted: Commonwealth v. Redline (Pa. 1958) is cited for the rule that felons are not liable when a police officer or victim kills \"a bystander or a co-felon\"."
  },
  "law-crimlaw.l09": {
    "s": "flag",
    "note": "claim contradicted: The ALI revised Article 213 (approved 2022) defines offenses by the absence of affirmative consent."
  },
  "law-crimpro.l04.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimpro.l05.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimpro.l08.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimpro.l13.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimpro.l15.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimpro.l16.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimpro.l16.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-crimpro.l01": {
    "s": "flag",
    "note": "claim contradicted: Carpenter (2018) held acquiring historical CSLI (seven days) is a search, called its holding narrow, and lower courts continue to sort out tower dumps, real-time location and similar data"
  },
  "law-crimpro.l18": {
    "s": "flag",
    "note": "claim contradicted: Weaver v. Massachusetts (2017): some structural claims, \"when raised on direct review through a claim of ineffective assistance,\" still require prejudice"
  },
  "law-evidence.l06.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-evidence.l06.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-evidence.l12.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-evidence.l04": {
    "s": "flag",
    "note": "claim contradicted: In a criminal case the prosecutor must give reasonable written notice before trial \"if the defendant asks for it\" (Rule 404(b))."
  },
  "law-evidence.l12": {
    "s": "flag",
    "note": "claim contradicted: Distinguish Rule 1006 summaries from Rule 611(a) pedagogical aids."
  },
  "law-evidence.l14": {
    "s": "flag",
    "note": "claim contradicted: Rule 613(b): extrinsic evidence admissible only if witness given opportunity to explain or deny and adverse party opportunity to examine, \"or if justice so requires\"."
  },
  "law-evidence.l06": {
    "s": "flag",
    "note": "claim contradicted: Rule 801(d)(1)(A) exempts a prior inconsistent statement only if given under penalty of perjury at a trial, hearing, other proceeding or deposition."
  },
  "law-intl-human-rights.l09.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-human-rights.l16": {
    "s": "flag",
    "note": "claim contradicted: The EU CSDDD (2024) scope and timeline are 'under political revision' and should be checked."
  },
  "law-intl-humanitarian-criminal.l10.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l10.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l11.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l12.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l14.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l17.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l17.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l18.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l18.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l20.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-intl-public.l19": {
    "s": "flag",
    "note": "claim contradicted: Paris Agreement: adopted 2015, in force 2016, well below 2C and 1.5C, NDCs; level of ambition largely left to states"
  },
  "law-intl-public.l03": {
    "s": "flag",
    "note": "claim contradicted: Fisheries case (1951): Norway applied its baseline method consistently and the UK did not object for decades, \"so the rule was not opposable to Norway\"."
  },
  "law-intl-public.l18": {
    "s": "flag",
    "note": "claim contradicted: UNCLOS entered into force in 1994 and \"the United States has signed but not ratified it\"."
  },
  "law-intl-trade-business.l05": {
    "s": "flag",
    "note": "claim contradicted: USMCA joint review scheduled for 2026 and its result is uncertain as of this writing"
  },
  "law-intl-trade-business.l14": {
    "s": "flag",
    "note": "claim contradicted: As of this writing the EU has moved to withdraw from the Energy Charter Treaty"
  },
  "law-legalwriting.l01.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-legalwriting.l02.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-legalwriting.l07.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-legalwriting.l13.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-legalwriting.l14.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-legalwriting.l15.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-legalwriting.l19.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-profresp.l01": {
    "s": "flag",
    "note": "claim contradicted: Rule 8.5(b)(2): for non-tribunal conduct the rules of the jurisdiction where the conduct \"predominantly occurred\" apply, with a safe harbor for reasonable belief about predominant effect"
  },
  "law-profresp.l10": {
    "s": "flag",
    "note": "claim contradicted: The Model Rules' screening provisions do not rescue a lawyer who obtained material confidential information in a substantial role (and the worked example: even screening states unlikely to save Firm B)"
  },
  "law-profresp.l11": {
    "s": "flag",
    "note": "claim contradicted: Rule 1.8(e) financial assistance is limited to advancing costs and paying them for indigent clients"
  },
  "law-property.l07.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-property.l08.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-property.l05": {
    "s": "flag",
    "note": "claim contradicted: Worked example: 'to A for life, then to B if B survives A' gives B an ALTERNATIVE contingent remainder"
  },
  "law-property.l06": {
    "s": "flag",
    "note": "claim contradicted: Unborn widow: 'a gift to the widow's children is void'"
  },
  "law-torts.l01.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-torts.l02.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-torts.l03.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-torts.l05.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-torts.l11.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-torts.l16.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "law-torts.l15": {
    "s": "flag",
    "note": "claim contradicted: Test that interference is actionable if harm is serious and the financial burden of compensating would not make continuation unfeasible is in Restatement section 829A."
  },
  "lit-studies-modern.l25.q1": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "med-clin-em.l07.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-em.l12.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-em.l18.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-em.l08": {
    "s": "flag",
    "note": "claim contradicted: Factor Xa inhibitors (rivaroxaban, apixaban) are reversed by andexanet alfa or PCC."
  },
  "med-clin-em.l12": {
    "s": "flag",
    "note": "claim contradicted: DKA hyperglycemia is above about 250 mg/dL."
  },
  "med-clin-fm.l06.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l06.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l06.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l06.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l06.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l07.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l07.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l07.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l07.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l07.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l08.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l08.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l08.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l08.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l08.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l09.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l09.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l09.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l09.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l09.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l10.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l10.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l10.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l10.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l10.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l11.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l11.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l11.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l11.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l11.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l12.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l12.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l12.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l12.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l12.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l13.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l13.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l13.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l13.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l13.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l14.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l14.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l14.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l14.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l14.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l15.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l15.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l15.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l15.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l15.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l16.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l16.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l16.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l16.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l16.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l17.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l17.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l17.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l17.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l17.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l18.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l18.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l18.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l18.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l18.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-fm.l05": {
    "s": "flag",
    "note": "claim contradicted: Syphilis screening: USPSTF 2022 for people at increased risk, 2018 for all pregnant people."
  },
  "med-clin-fm.l12": {
    "s": "flag",
    "note": "claim contradicted: USPSTF (2018) recommends DXA screening for women 65+ and younger postmenopausal women at increased risk."
  },
  "med-clin-fm.l13": {
    "s": "flag",
    "note": "claim contradicted: The 2024 USPSTF falls statement recommends against vitamin D to prevent falls (grade D)."
  },
  "med-clin-im.l04": {
    "s": "flag",
    "note": "claim contradicted: Endocarditis echocardiography is interpreted with the modified Duke criteria; at least three blood-culture sets from separate sites."
  },
  "med-clin-im.l05": {
    "s": "flag",
    "note": "claim contradicted: GOLD (report of 2024): long-acting bronchodilator base therapy; ICS added for continued exacerbations with eosinophils >=300/uL."
  },
  "med-clin-im.l06": {
    "s": "flag",
    "note": "claim contradicted: ATS/IDSA 2019 CAP guideline regimens"
  },
  "med-clin-im.l11": {
    "s": "flag",
    "note": "claim contradicted: The ADA Standards of Care of 2024 (updated annually) keep metformin as a common first drug; GLP-1 RA or SGLT2i favored in ASCVD, HF or CKD independent of A1c."
  },
  "med-clin-im.l14": {
    "s": "flag",
    "note": "claim contradicted: Apixaban and rivaroxaban are reversed with andexanet alfa or prothrombin complex concentrate."
  },
  "med-clin-im.l17": {
    "s": "flag",
    "note": "claim contradicted: The Surviving Sepsis Campaign guideline of 2021: antimicrobials within 1 hour in shock/probable sepsis, ~30 mL/kg balanced crystalloid, norepinephrine first-line, MAP 65."
  },
  "med-clin-im.l08": {
    "s": "flag",
    "note": "claim contradicted: Hepatitis C screening is recommended once for all adults by the USPSTF of 2020."
  },
  "med-clin-im.l12": {
    "s": "flag",
    "note": "claim contradicted: An adrenal incidentaloma should always prompt checking metanephrines, an aldosterone-to-renin ratio if hypertensive, and a dexamethasone suppression test."
  },
  "med-clin-obgyn.l05.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-obgyn.l10.q1": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-obgyn.l16.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-obgyn.l11": {
    "s": "flag",
    "note": "claim contradicted: The implant is highly effective and lasts about 3 years"
  },
  "med-clin-obgyn.l12": {
    "s": "flag",
    "note": "claim contradicted: The FDA approved mifepristone in 2000 for use through 10 weeks of pregnancy."
  },
  "med-clin-obgyn.l16": {
    "s": "flag",
    "note": "claim contradicted: Self-collected HPV samples are approved; guideline bodies are \"moving toward\" including them; consult current recommendations."
  },
  "med-clin-obgyn.l18": {
    "s": "flag",
    "note": "claim contradicted: ACOG recommends offering screening from 40, starting no later than 50, through shared decision-making."
  },
  "med-clin-peds.l06.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-peds.l09.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-peds.l07": {
    "s": "flag",
    "note": "claim contradicted: Lesson lists HepB, rotavirus, flu, HepA as stable routine recommendations while saying CDC schedule under revision"
  },
  "med-clin-peds.l08": {
    "s": "flag",
    "note": "claim contradicted: All febrile infants 28 days or younger get blood, urine and CSF cultures, empirical IV antibiotics and admission."
  },
  "med-clin-peds.l14": {
    "s": "flag",
    "note": "claim contradicted: AAP 2011: after a simple febrile seizure, no routine imaging, EEG or labs; LP considered with meningeal signs, incomplete immunization, and in those under 12 months."
  },
  "med-clin-psych.l02.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-psych.l15": {
    "s": "flag",
    "note": "claim contradicted: Esketamine nasal spray is approved with an antidepressant for treatment-resistant depression under supervised administration."
  },
  "med-clin-psych.l11": {
    "s": "flag",
    "note": "claim contradicted: Alzheimer drug therapy is presented only as cholinesterase inhibitors and memantine, which give modest symptomatic benefit without altering the course."
  },
  "med-clin-psych.l14": {
    "s": "flag",
    "note": "claim contradicted: Antipsychotics block dopamine D2 receptors."
  },
  "med-clin-surgery.l06.q3": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-surgery.l14.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-clin-surgery.l14": {
    "s": "flag",
    "note": "claim contradicted: After splenectomy or splenic embolization, vaccination against encapsulated organisms is given"
  },
  "med-clin-surgery.l18": {
    "s": "flag",
    "note": "claim contradicted: Adrenal incidentalomas above about 4 cm or with suspicious imaging are generally resected"
  },
  "med-ethics-prof.l11": {
    "s": "flag",
    "note": "claim contradicted: Assisting suicide remains a crime in England and Wales and Parliament has been considering legislation as of this writing"
  },
  "med-ethics-prof.l15": {
    "s": "flag",
    "note": "claim contradicted: NICE uses a threshold of about twenty to thirty thousand pounds per QALY"
  },
  "med-ethics-prof.l18": {
    "s": "flag",
    "note": "claim contradicted: A minority of jurisdictions recognise loss of chance; most require more-likely-than-not proof"
  },
  "med-g912.l06.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-g912.l10": {
    "s": "flag",
    "note": "claim contradicted: In the United States, the 2017 ACC/AHA guideline defines hypertension as 130/80 mm Hg or higher"
  },
  "med-g912.l11": {
    "s": "flag",
    "note": "claim contradicted: Current international guidance emphasizes that relying on a reliever alone is not enough for persistent asthma (albuterol framed as the reliever)"
  },
  "med-global-health.l03.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-global-health.l10": {
    "s": "flag",
    "note": "claim contradicted: Announced withdrawal of at least one major member (US); mpox PHEIC listed without end"
  },
  "med-global-health.l16": {
    "s": "flag",
    "note": "claim contradicted: Shortfall of roughly ten million health workers by 2030"
  },
  "med-micro.l07": {
    "s": "flag",
    "note": "claim contradicted: Meningococcal vaccines cover capsular groups A, C, W and Y, and a separate vaccine covers group B."
  },
  "med-micro.l10": {
    "s": "flag",
    "note": "claim contradicted: Lyme disease treatment is oral doxycycline in most adults and children above eight years."
  },
  "med-pharm-principles.l06.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-pharm-principles.l07.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-pharm-principles.l13": {
    "s": "flag",
    "note": "claim contradicted: Induction has little effect on high-extraction drugs because their clearance is limited by blood flow."
  },
  "med-pharm-systems.l01.q5": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-pharm-systems.l10.q4": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "med-pharm-systems.l15": {
    "s": "flag",
    "note": "claim contradicted: Tetracyclines including doxycycline are avoided in children under eight because of tooth staining."
  },
  "music-business.l04.q3": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "music-genres.l03.q4": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "music-theory-college.l21.q1": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "music-theory-early.l01.q5": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "music-theory-elementary.l17.q5": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "music-theory-secondary.l15.q1": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "music-theory.l12.q3": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  },
  "world-mythology.l25.q2": {
    "s": "flag",
    "note": "checkers disagreed with the key or were unsure"
  },
  "world-mythology.l25.q5": {
    "s": "fix",
    "note": "reworded after the first check; withheld until re-checked"
  }
};
