// CareFlagsPanel — pastoral "reach out" tasks generated by the Finance Hub. PRIVACY FIREWALL: these docs
// carry only who + why (lapsed / gave for the first time) — never an amount, fund or date of a gift.
// Mount in the pastor-facing care surface: <CareFlagsPanel orgId={org.id} />.
import React, { useEffect, useState } from 'react';
import { HeartHandshake, Loader2, UserPlus, UserMinus } from 'lucide-react';
import { fetchCareFlags, resolveCareFlag, type CareFlag } from '../../../../services/chmsFinance';
import { card, heading, Empty, Pill } from './shared';

const CareFlagsPanel: React.FC<{ orgId: string; onOpenPerson?: (personId: string) => void }> = ({ orgId, onOpenPerson }) => {
  const [flags, setFlags] = useState<CareFlag[] | null>(null);
  const load = () => fetchCareFlags(orgId).then(setFlags);
  useEffect(() => { load(); }, [orgId]); // eslint-disable-line react-hooks/exhaustive-deps
  if (!flags) return <div className="flex justify-center py-8"><Loader2 className="animate-spin text-white/30" size={18} /></div>;
  const open = flags.filter(f => f.status === 'OPEN');
  return (
    <div className={`${card} p-5`}>
      <h3 className={heading}><HeartHandshake size={12} className="inline mr-1.5" />Reach out ({open.length})</h3>
      {open.length === 0 ? <Empty>No one needs a check-in right now.</Empty> : (
        <div className="space-y-1.5">
          {open.map(f => (
            <div key={f.id} className="flex items-center gap-3 text-xs px-3 py-2 rounded-xl bg-white/[0.04]">
              <span className="text-white/50">{f.kind === 'FIRST_TIME' ? <UserPlus size={14} /> : <UserMinus size={14} />}</span>
              <button onClick={() => onOpenPerson?.(f.personId)} className="flex-1 text-left text-white font-bold hover:underline">{f.personName}</button>
              <Pill tone={f.kind === 'FIRST_TIME' ? 'ok' : 'warn'}>{f.kind === 'FIRST_TIME' ? 'gave for the first time — welcome them' : 'has been away a while — check in'}</Pill>
              <button onClick={async () => { await resolveCareFlag(f); load(); }} className="text-[9px] font-black uppercase tracking-widest text-small-orange">Done</button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default CareFlagsPanel;
