
export interface InteractiveZone {
  id: string;
  type: 'PHOTO' | 'TEXT' | 'VINYL' | 'GAME_SCREEN';
  x: number; // percentage 0-100
  y: number; // percentage 0-100
  width: number; // percentage 0-100
  height: number; // percentage 0-100
  rotation?: number; // degrees
}

export interface PostThemeBackground {
  id: string;
  theme: 'SCRAPBOOK' | 'PHOTO_ALBUM' | 'MUSIC_PLAYER' | 'NEWSPAPER' | 'ARCADE';
  imageUrl: string;
  zones: InteractiveZone[];
  name: string;
  createdAt: number;
}

export interface MovieSpecialFeature {
  id: string;
  title: string;
  url: string;
  type?: 'BEHIND_THE_SCENES' | 'DELETED_SCENE' | 'INTERVIEW' | 'TRAILER' | 'OTHER';
}

export interface MovieMetadata {
  trailerUrl?: string;
  tagline?: string;
  cast?: string[];
  crew?: string[];
  releaseYear?: number;
  specialFeatures?: MovieSpecialFeature[];
}

export interface TVSeason {
  id: string;
  number: number;
  episodes: Video[];
}

export interface Track {
  id: string;
  title: string;
  artist: string;
  artistId?: string; // Added artistId for radio/tips
  file?: File;
  url: string;
  duration?: number;
  videoUrl?: string;
  images?: string[]; 
  lyrics?: string; 
  timeCodedLyrics?: { time: number; text: string }[];
  price?: number; // Price for individual purchase, 0 or undefined means free
  isPaywalled?: boolean; // If true, requires purchase to play/view
  genre?: string;
  isRadioEligible?: boolean; // Artist can opt-in
  isSlideshowEligible?: boolean; // Artist can opt-in
  likes?: number; // For radio ranking
  isExclusive?: boolean; // Members only content
  albumId?: string; // For personal collection grouping
  albumTitle?: string;
  albumCover?: string;
  videoId?: string; // Linked music video ID
  playCount?: number;
  shareCount?: number;
  isGlobalArchive?: boolean; // Original work by artist
  isPersonalMedia?: boolean; // Uploaded by user for personal use
  isAdSupported?: boolean; // If true, plays ads at adMarkers
  rightsOwnerId?: string; // ID of the rights holder
  tags?: string[];
  adMarkers?: AdMarker[]; // Time codes for ad insertion
  podcastMetadata?: PodcastMetadata;
  artistNotes?: string[]; // Sticky notes from the artist for this specific track
}

export interface Photo {
  id: string;
  url: string;
  title?: string;
  description?: string;
  timestamp: number;
  ownerId: string;
  isPublic?: boolean;
  isGalleryEligible?: boolean;
  mediaType?: 'PHOTO' | 'VIDEO';
  albumId?: string;
  likesCount?: number;
  favorites?: string[]; // UIDs
  tags?: string[];
}

export interface PhotoAlbum {
  id: string;
  ownerId: string;
  title: string;
  description?: string;
  photoIds: string[];
  isPublic: boolean;
  timestamp: number;
  order?: string[]; // For slideshow arrangement
}

export interface EventPhotoPool {
  id: string;
  eventId: string;
  ownerId: string;
  title: string;
  description?: string;
  mediaIds: string[];
  qrCodeUrl?: string;
  inviteLink?: string;
  timestamp: number;
}

export interface TVChannel {
  id: string;
  ownerId: string;
  title: string;
  description?: string;
  isAutoGenerated: boolean;
  curatedVideoIds: string[];
  liveStreamUrl?: string;
}

export interface WebApp {
  id: string;
  ownerId: string;
  developerName: string;
  title: string;
  description: string;
  url: string; // The link to the web app
  thumbnailUrl: string;
  screenshots: string[];
  videoTrailerUrl?: string;
  category: string;
  version: string;
  size: string; // e.g. "12.5 MB"
  rating: number; // 0-5
  reviewCount: number;
  installCount: number;
  timestamp: number;
  tags?: string[];
  isGlobalArchive?: boolean;
  state?: 'PUBLISHED' | 'IDLE' | 'INSTALLING' | 'RUNNING';
}

export interface AppReview {
  id: string;
  appId: string;
  userId: string;
  userName: string;
  userPhoto: string;
  rating: number; // 1-5
  comment: string;
  timestamp: number;
}

export interface Game {
  id: string;
  ownerId: string;
  title: string;
  description: string;
  url: string; // Web-based game link
  thumbnailUrl: string;
  playCount: number;
  timestamp: number;
  tags?: string[];
}

export interface RadioAd {
  id: string;
  url: string;
  title: string;
  duration: number;
}

export interface BookPage {
  id: string;
  url: string; // Image URL for comic pages
  pageNumber: number;
}

export interface BookNote {
  id: string;
  bookId: string;
  userId: string;
  pageNumber?: number; // if undefined, it's a general note
  chapterId?: string;
  type: 'TEXT' | 'AUDIO' | 'LINK';
  content: string; // text, audio url, or link url
  timestamp: number;
}

export interface BookChapter {
  id: string;
  title: string;
  content?: string; // Text content
  url?: string; // PDF or EPUB URL
  audioUrl?: string; // For audiobook/narration
  pages?: BookPage[]; // For comics/graphic novels
  price?: number; // 0 or undefined means free
  isPaywalled?: boolean;
  description?: string;
  tags?: string[];
}

export interface Book {
  id: string;
  title: string;
  author: string;
  description: string;
  coverImage: string;
  chapters: BookChapter[];
  genre: string;
  price?: number; // Price for full book, 0 or undefined means free
  isPaywalled?: boolean;
  createdAt: number;
  tags?: string[];
  isGraphicNovel?: boolean;
}

export interface Album {
  id: string;
  ownerId?: string; // UID of the user who created it
  isDraft?: boolean;
  title: string;
  artist: string;
  artistBio?: string;
  artistImage?: string;
  artistFile?: File; // For direct upload
  coverImage: string;
  coverFile?: File; // For direct upload
  headerImage?: string;
  description: string;
  linerNotes?: string;
  tracks: Track[];
  slideshow?: string[]; 
  slideshowFiles?: File[]; // For direct upload
  createdAt: number;
  themeColor: string;
  isPublic?: boolean;
  isPrivate?: boolean; // If true, only accessible in chats/groups or to owner
  publishVideosToGallery?: boolean; // If true, album videos are mirrored to videos collection
  releaseDate?: number; // Timestamp for scheduled release
  isScheduled?: boolean; // Toggle for scheduling
  galleryUrl?: string; // Link to "Gallery Experience"
  genre?: string;
  price?: number; // Price for full album
  isPaywalled?: boolean;
  type?: 'MUSIC' | 'VIDEO' | 'BOOK' | 'PHOTO';
  subType?: 'MOVIE' | 'TV_SERIES' | 'GRAPHIC_NOVEL' | 'PODCAST' | 'NOVEL' | 'PLAYLIST';
  donationGoal?: number;
  donationCurrent?: number;
  socialLinks?: {
    twitter?: string;
    instagram?: string;
    spotify?: string;
    youtube?: string;
    website?: string;
  };
  musicVideos?: Video[];
  videoPlaylists?: VideoPlaylist[];
  seasons?: TVSeason[]; // For TV Series
  bookChapters?: BookChapter[];
  movieMetadata?: MovieMetadata; // Added for Movie Album type
  bookPreviewConfig?: {
    type: 'CHAPTERS' | 'PAGES';
    allowedChapterIds?: string[];
    allowedPageRange?: [number, number];
  };
  liveFeedUrl?: string; // Album-specific live feed
  isGlobalArchive?: boolean; // Original work by artist
  playCount?: number;
  shareCount?: number;
  isAdSupported?: boolean; 
  customVideoUrl?: string;
  rightsOwnerId?: string;
  tags?: string[];
  featuredMedia?: {
    url: string;
    type: 'IMAGE' | 'VIDEO';
  };
  relatedProjectIds?: string[]; // IDs of other albums/projects connected to the same IP
  worldId?: string;
  isSlideshowEnabled?: boolean; // Toggle for slideshow experience in player
}

export interface Universe {
  id: string;
  name: string;
  type: 'ON_PLATFORM' | 'ALLY';
  url?: string; // For ALLY
  coverImage?: string;
  description: string;
  createdAt: number;
}

export interface Episode {
  id: string;
  title: string;
  description: string;
  videoUrl?: string; // or content ID
  thumbnail?: string;
  duration: number; // in seconds
}

export interface Season {
  id: string;
  number: number;
  episodes: Episode[];
}

export interface TVSeries {
  id: string;
  title: string;
  description: string;
  coverImage?: string;
  genre: string;
  universeId: string; // Ref to Universe
  seasons: Season[];
}

export interface IPWorld {
  id: string;
  creatorId: string;
  name: string;
  description: string;
  coverImage: string;
  worldType: 'FICTION' | 'NON_FICTION';
  status?: 'DRAFT' | 'PUBLISHED';
  publishedAt?: number;
  parentWorldId?: string | null; // For nested worlds
  timelineConfig: {
    startYear: number;
    endYear: number;
    unitName: string; // e.g. "AY", "Years", "Eras"
  };
  themeConfig: {
    primaryColor: string;
    secondaryColor: string;
    backgroundId: string;
    customBackgroundImage?: string;
    useFrostedGlassDefault?: boolean;
  };
  assetIds: string[]; // Linked Album, Video, Book IDs
  characterIds: string[];
  loreIds: string[];
  timelineIds: string[];
  storyListIds: string[]; // Lists of multimedia content
  moduleIds: string[]; // Linked ClassroomModule IDs
  associatedClubIds: string[]; // Linked Club/FanPage IDs
  graphConnections: GraphNodeConnection[];
  createdAt: number;
}

export interface GraphNodeConnection {
  sourceId: string;
  sourceType: 'WORLD' | 'CHARACTER' | 'LORE' | 'TIMELINE' | 'ALBUM' | 'VIDEO' | 'BOOK';
  targetId: string;
  targetType: 'WORLD' | 'CHARACTER' | 'LORE' | 'TIMELINE' | 'ALBUM' | 'VIDEO' | 'BOOK';
  relationshipType: string; // e.g. "LOVER", "BIRTHPLACE", "INSPIRED_BY"
}

export interface StoryList {
  id: string;
  worldId: string;
  name: string;
  description: string;
  assetIds: string[]; // Linked assets (movies, books, etc.)
  tags: string[]; // For intelligent association
}

export interface Character {
  id: string;
  worldId: string;
  name: string;
  bio: string;
  imageUrl: string;
  role: string;
  stats?: Record<string, string | number>; // Added stats field
  tags: string[];
  appearanceAt: { projectId: string; timestamp: number }[]; // Connections to other projects
  isPublished?: boolean;
}

export interface LoreEntry {
  id: string;
  worldId: string;
  title: string;
  content: string;
  tags: string[];
  type: 'LOCATION' | 'ENVIRONMENT' | 'ITEM' | 'PLOT_POINT' | 'BACKSTORY';
  conflictsDetected: string[]; // Intelligent conflict warnings
  isPublished?: boolean;
}

export interface TimelineEvent {
  id: string;
  worldId: string;
  timelineId: string;
  title: string;
  description: string;
  year: number; // Linear timeline point in specified units
  isPublished?: boolean;
  linkedCharacterIds?: string[];
  linkedLoreIds?: string[];
  linkedAssetIds?: string[];
}


export interface Video {
  id: string;
  ownerId: string;
  title: string;
  url: string;
  embedUrl?: string; // Added for YouTube/Vimeo support
  file?: File;
  thumbnailUrl?: string;
  thumbnailFile?: File;
  coverImageUrl?: string;
  coverImageFile?: File;
  description?: string;
  duration?: number;
  playsCount?: number;
  price?: number; 
  isPaywalled?: boolean;
  genre?: string;
  artist?: string; 
  isPrivate?: boolean;
  worldId?: string;
  releaseDate?: number;
  isScheduled?: boolean;
  likesCount?: number;
  commentsCount?: number;
  timestamp: number;
  tags?: string[];
  isAdSupported?: boolean;
  isAdFreeLocked?: boolean; // If true, and purchased, no ads
  allowInFastChannel?: boolean;
  adMarkers?: AdMarker[]; // Time codes for ad insertion
  muxPlaybackId?: string; // Mux streaming support
  muxAssetId?: string;
  podcastMetadata?: PodcastMetadata;
  category?: 'MUSIC_VIDEO' | 'MOVIE' | 'TV_EPISODE' | 'TRAILER' | 'SHORT_FILM' | 'DOCUMENTARY';
  subType?: 'MOVIE' | 'TV_SERIES'; // Added subType to Video
  episodeNumber?: number; // Added for TV Series episodes
  seasonNumber?: number; // Added for TV Series episodes
  movieMetadata?: MovieMetadata;
  tvMetadata?: {
    seasonNumber?: number;
    episodeNumber?: number;
    seriesTitle?: string;
  };
}

export interface VideoLike {
  id: string;
  videoId: string;
  userId: string;
  timestamp: number;
}

export interface VideoComment {
  id: string;
  videoId: string;
  userId: string;
  userName: string;
  userPhoto: string;
  text: string;
  timestamp: number;
  parentId?: string; // For replies
}

export interface VideoPlaylist {
  id: string;
  ownerId: string;
  title: string;
  description?: string;
  videoIds: string[];
  videos?: Video[];
  thumbnailUrl?: string;
  isPrivate?: boolean;
  isDraft?: boolean;
  isPublic: boolean;
  timestamp: number;
}

export interface Comment {
  id: string;
  author: string;
  text: string;
  timestamp: number;
  trackId?: string; 
  videoId?: string;
  uid?: string | null;
  parentId?: string; // For replies
  mediaTimestamp?: number;
}

export interface Review {
  id: string;
  productId: string;
  userId: string;
  userName: string;
  userPhoto: string;
  rating: number; // 1-5
  comment: string;
  timestamp: number;
}

export interface MerchItem {
  id: string;
  ownerId: string; // Artist or Brand ID
  title: string;
  description: string;
  price: number;
  salePrice?: number;
  imageUrl: string;
  videoUrl?: string; // Video for product page
  category: 'APPAREL' | 'MUSIC' | 'ACCESSORY' | 'DIGITAL' | 'COLLECTIBLES' | 'MEDIA';
  stock: number;
  timestamp: number;
  rating?: number;
  reviewCount?: number;
  isDigitalAsset?: boolean;
  linkedAssetId?: string; // ID of Track or Video if it's a media asset
  worldId?: string; // ID of the specific World this item belongs to
}

export interface UserRevenue {
  donations: number;
  merch: number;
  adRevenue: number;
  subscriptions: number;
  cryptoWallet?: {
    bitcoin?: string;
    ethereum?: string;
    solana?: string;
  };
}

export interface StoreSettings {
  isEnabled: boolean;
  useExternalStore: boolean;
  externalStoreUrl?: string;
  showDemoContent?: boolean;
}

export interface Donation {
  id: string;
  fromId: string;
  fromName: string;
  toId: string;
  albumId?: string;
  amount: number;
  message?: string;
  timestamp: number;
}

export interface PrivateBoard {
  id: string;
  ownerId: string;
  name: string;
  createdAt: number;
  items: BoardItem[];
}

export interface BoardItem {
  id: string;
  type: string; // 'ALBUM', 'TRACK', 'POST', 'ARTICLE', 'BOOK', 'MOVIE', 'CUSTOM'
  contentId: string;
  x: number;
  y: number;
  width?: number;
  payload: any; // e.g. { title, imageUrl, snippet }
}

export interface SidebarItemConfig {
  id: string;
  order: number;
  isVisible: boolean;
}

export interface UserProfile {
  uid: string;
  displayName: string;
  photoURL: string;
  email: string;
  bio?: string;
  followerCount: number;
  followingCount: number;
  following?: string[];
  friendsCount?: number;
  joinedAt?: number;
  isArtist?: boolean; // True if they have uploaded content
  merch?: MerchItem[];
  acceptsTips?: boolean;
  tipGoal?: number;
  tipCurrent?: number;
  payItForwardOptIn?: boolean;
  payItForwardWinsMonth?: number;
  payItForwardWinsYear?: number;
  lastPayItForwardWinTimestamp?: number;
  photos?: Photo[];
  photoAlbums?: PhotoAlbum[];
  tvChannel?: TVChannel;
  games?: Game[];
  apps?: WebApp[];
  library?: string[]; // Track IDs of other people's music
  personalTracks?: Track[]; // Uploaded personal music
  personalPlaylists?: Playlist[]; // User created playlists
  activeEngagementScore?: number; // For radio ranking
  membershipConfig?: ArtistMembershipConfig;
  activeMemberships?: string[]; // Artist IDs where user is a member
  backgroundSlideshow?: {
    enabled: boolean;
    items: { id: string; url: string; type: 'PHOTO' | 'VIDEO' }[];
  };
  brandColor?: string;
  uiSettings?: {
    chatIconPosition?: { x: number; y: number };
    isChatIconPinned?: boolean;
    lastTheme?: ThemeType;
    isSpatialModeEnabled?: boolean;
    syncedFolders?: { id: string; name: string }[];
    backgroundSlideshow?: {
      enabled: boolean;
      items: { id: string; url: string; type: 'PHOTO' | 'VIDEO' }[];
    };
  };
  pinnedItems?: { id: string; refId: string; type: 'POST' | 'VIDEO' | 'AUDIO' }[];
  liveStreamConfig?: {
    streamUrl: string;
    fastChannelUrl?: string;
    activeStreamType?: 'LIVE' | 'FAST';
    title: string;
    isActive: boolean;
    source: string; // e.g., 'YouTube', 'Twitch', 'Custom'
  };
  interestsNotebook?: string;
  publicInterests?: string[];
  privateInterests?: string[];
  interestAlgorithmProfile?: string;
  coverArt?: string;
  customPhotoURL?: string;
  mailingListCount?: number;
  sidebarConfig?: SidebarItemConfig[];
  hiddenSections?: string[];
  savedThemePresets?: string[];
  activeThemePresetId?: string;
  videos?: Video[];
  videoPlaylists?: VideoPlaylist[];
  articles?: Article[];
  favoriteSportsTeams?: string[];
  favoriteScienceFields?: string[];
  favoriteCoins?: string[];
  favoriteStocks?: string[];
  radioSettings?: {
    enabled: boolean;
    stationName?: string;
    stingers: string[]; // URLs
    ads: string[];      // URLs
    stingerFrequency: number;
    adFrequency?: number; // Added for ad playback logic
    otherCreators?: string[]; // UIDs of other creators to play on this station
    exclusiveContentIds?: string[]; // IDs of Tracks/Videos for members
    scheduledEvents?: {
      id: string;
      title: string;
      startTime: number;
      type: 'LIVE_TALK' | 'LIVE_STREAM';
    }[];
  };
  accountType?: 'FAN' | 'ARTIST' | 'BRAND' | 'WRITER' | 'STUDENT' | 'TEACHER' | 'PARTNER' | 'ORGANIZATION';
  revenue?: UserRevenue;
  storeSettings?: StoreSettings;
  isWriter?: boolean;
  isBrandAdmin?: boolean;
  isFan?: boolean;
  isStudent?: boolean;
  isTeacher?: boolean;
  managedBrandIds?: string[];
  managedByBrandIds?: string[];
  role?: 'admin' | 'staff' | 'user';
  createdAt?: number;
  isPioneer?: boolean;
  pioneerRewardClaimed?: boolean;
  tier?: 'FREE' | 'PIONEER' | 'PRO' | 'ELITE';
  storageLimit: number; // 0 means unlimited
  storageUsage: {
    total: number;
    audio: number;
    video: number;
    photos: number;
  };
  isPartner?: boolean;
  isAdFree?: boolean;
  isFeatured?: boolean;
  featuredArtistPhoto?: string;
  masterEmail?: string;
  aliases?: UserAlias[];
  partnerConfig?: PartnerConfig;
  hasCompletedOnboarding?: boolean;
  onboardingStartTimestamp?: number;
  tooltipsEnabled?: boolean;
  frostedBackground?: string;
  themeBackgrounds?: { [theme: string]: string }; // theme -> backgroundId
  videoBackgroundUrl?: string;
  videoBackgroundFrosted?: boolean;
  videoBackgroundBlur?: boolean;
  defaultProfileTab?: 'FEED' | 'CONTENT' | 'ARTICLES' | 'PHOTOS' | 'VIDEOS' | 'TV' | 'GAMES' | 'LIVE_CHAT' | 'MERCH' | 'FOLLOWING' | 'FRIENDS' | 'INTERESTS' | 'LIBRARY' | 'MEMBERS';
  xHandle?: string;
  xUrl?: string;
  xEmbedHtml?: string;
  mastodonHandle?: string;
  mastodonInstance?: string; // e.g., mastodon.social
  blueskyHandle?: string; // e.g., username.bsky.social
  threadsHandle?: string; // e.g., username
}

export interface SystemStats {
  totalUsers: number;
  activeUsers24h: number;
  globalStorage: {
    total: number;
    audio: number;
    video: number;
    photos: number;
  };
  globalBandwidth: {
    daily: number;
    monthly: number;
  };
  sectionUsage: {
    music: number;
    video: number;
    books: number;
    photos: number;
  };
}

export interface AdConfig {
  id: string;
  title: string;
  imageUrl: string;
  linkUrl: string;
  placement: 'SIDEBAR' | 'FEED' | 'PLAYER' | 'BANNER';
  isActive: boolean;
  impressions: number;
  clicks: number;
  targetGenres?: string[];
}

export interface Newsletter {
  id: string;
  artistId: string;
  title: string;
  content: string;
  timestamp: number;
  sentCount: number;
}

export interface MailingListSubscriber {
  id: string;
  artistId: string;
  subscriberId: string;
  subscriberEmail: string;
  subscriberName: string;
  timestamp: number;
}

export interface Playlist {
  id: string;
  ownerId: string;
  authorName?: string;
  authorPhoto?: string;
  title: string;
  description?: string;
  coverUrl?: string;
  coverImage?: string; // Unified with coverUrl usage in MusiView
  trackIds: string[];
  tracks?: Track[];
  isDraft?: boolean;
  timestamp: number;
}

export interface MembershipTier {
  id: string;
  name: string;
  price: number;
  description: string;
  benefits: string[];
}

export interface ArtistMembershipConfig {
  isEnabled: boolean;
  fee: number;
  isWaitingListEnabled: boolean;
  description: string;
  tiers?: MembershipTier[];
}

export interface Membership {
  id: string;
  artistId: string;
  memberId: string;
  status: 'PENDING' | 'ACTIVE' | 'REVOKED';
  startDate: number;
  expiryDate?: number;
}

export interface FollowRelation {
  id: string;
  followerId: string;
  followingId: string;
  timestamp: number;
}

export interface Post {
  id: string;
  authorId: string;
  authorName: string;
  authorPhoto: string;
  text: string;
  media?: {
    type: 'PHOTO' | 'VIDEO' | 'AUDIO' | 'ALBUM' | 'LINK' | 'GIF' | 'STICKER';
    url?: string;
    id?: string; // For on-platform IDs
    title?: string;
    thumbnail?: string;
    linkPreview?: {
      title?: string;
      description?: string;
      image?: string;
      url: string;
    };
  }[];
  likesCount: number;
  commentsCount: number;
  timestamp: number;
  isPublic: boolean;
  sourceCollection?: 'feed' | 'posts';
  albumEmbed?: Album; // For the mini player
  autoPlayEmbed?: boolean;
  modifiedAt?: number;
  targetUserId?: string;
  targetUserName?: string;
}

export interface FeedPage {
  id: string;
  type: 'IMAGE' | 'VIDEO' | 'TEXT' | 'MUSIC';
  url?: string;
  content?: string;
  media?: { url: string; type: 'IMAGE' | 'VIDEO' }[]; // For Photo Album (up to 4)
}

export interface FeedItem {
  id: string;
  authorId: string;
  authorName: string;
  authorPhoto: string;
  type: 'PICTURE' | 'SONG' | 'COMMENT' | 'VIDEO' | 'BOOK' | 'NEWS' | 'GAME' | 'WATCH_ALONG' | 'LIVE_FEED' | 'RESEARCH_PAPER';
  theme?: 'SCRAPBOOK' | 'PHOTO_ALBUM' | 'MUSIC_PLAYER' | 'NEWSPAPER' | 'ARCADE' | 'WATCH_ALONG' | 'LIVE_FEED' | 'STANDARD';
  title?: string; // For news headlines
  content: string; // Text content or comment
  imageUrl?: string;
  songUrl?: string;
  songTitle?: string;
  albumId?: string;
  timestamp: number;
  source?: string; // For news
  url?: string; // For news links
  parentId?: string; // For threaded replies
  sourceCollection?: 'feed' | 'posts'; // Indicates which Firestore collection this item came from
  pages?: FeedPage[]; // For Scrapbook and Photo Album
  gameId?: string;
  shareCount: number;
  commentCount?: number;
  playCount?: number;
  backgroundId?: string;
  articleIds?: string[];
  deepLinkUrl?: string;
  aspectRatio?: 'VERTICAL' | 'HORIZONTAL' | 'SQUARE';
  autoCrop?: boolean;
  likesCount?: number;
  mediaTimestamp?: number;
}

export interface LiveFeed {
  id: string;
  ownerId: string;
  ownerName: string;
  ownerPhoto: string;
  title: string;
  url: string; // Embed URL (YouTube, Twitch, etc.)
  muxPlaybackId?: string; // For Mux live streams
  timestamp: number;
  status?: 'OFFLINE' | 'LIVE';
  isPublic?: boolean;
  price?: number;
  sanctuaryOnly?: boolean;
  genre?: string;
  subject?: string;
  brandId?: string;
  tags?: string[];
}

export interface FanPage {
  id: string;
  ownerId: string;
  name: string;
  description: string;
  members: string[];
  timestamp: number;
}

export interface BrandAccount {
  id: string;
  name: string;
  description: string;
  logoUrl?: string;
  coverUrl?: string;
  adminId: string;
  managers: string[];
  brandPages: string[];
  managedArtistIds: string[];
  timestamp: number;
}

export interface PPVEvent {
  id: string;
  ownerId: string;
  ownerName: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  streamUrl: string;
  price: number;
  isExclusive: boolean; // Members only
  startTime: number;
  duration: number; // in minutes
  status: 'UPCOMING' | 'LIVE' | 'ENDED';
  purchasedBy?: string[]; // UIDs
  photoPoolId?: string;
}

export interface Lesson {
  id: string;
  title: string;
  description: string;
  type: 'VIDEO' | 'AUDIO' | 'TEXT';
  contentUrl?: string;
  textContent?: string;
  order: number;
}

export interface Assignment {
  id: string;
  title: string;
  description: string;
  dueDate: number;
  maxPoints: number;
}

export interface Submission {
  id: string;
  assignmentId: string;
  studentId: string;
  studentName: string;
  contentUrl?: string;
  textContent?: string;
  grade?: number;
  feedback?: string;
  timestamp: number;
}

export interface Classroom {
  id: string;
  ownerId: string;
  ownerName: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  price: number; // 0 for free
  syllabus: string;
  lessons: Lesson[];
  assignments: Assignment[];
  enrolledStudents: string[]; // UIDs
  liveSessionUrl?: string;
  category: string;
}

export interface ClassroomModule {
  id: string;
  name: string;
  description: string;
  url: string; // The experience ID or route
  coverArt: string;
  createdAt: number;
  isActive: boolean;
}

export interface ProgressReport {
  id: string;
  classId: string;
  studentId: string;
  overallGrade: number;
  completedLessons: string[]; // Lesson IDs
  lastAccessed: number;
}

export interface VideoChatSession {
  id: string;
  roomId: string; // Linked to ChatRoom
  participants: { uid: string; displayName: string; photoURL: string; isMuted: boolean; isVideoOff: boolean }[];
  startTime: number;
  isActive: boolean;
}

export interface ArticleBlock {
  id: string;
  type: 'TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO' | 'QUOTE' | 'HEADING';
  content: string; // Text or URL
  layout?: 'FULL' | 'LEFT' | 'RIGHT' | 'CENTER'; // For text wrap
  caption?: string;
  assetId?: string; // Reference to backend asset
}

export interface Article {
  id: string;
  authorId: string;
  authorName: string;
  authorPhoto: string;
  title: string;
  subtitle?: string;
  coverImage?: string;
  blocks: ArticleBlock[];
  timestamp: number;
  isPublic: boolean;
  tags?: string[];
  likesCount: number;
  commentsCount: number;
  readTime?: number; // in minutes
  category?: string;
}

export interface Speaker {
  uid: string;
  name: string;
  photoURL: string;
  isMuted: boolean;
}

export interface LiveTalk {
  id: string;
  hostId: string;
  hostName: string;
  hostPhoto: string;
  title: string;
  description: string;
  topic: string;
  category: string;
  isActive: boolean;
  speakers: Speaker[]; // Changed from string[]
  listeners: string[]; // UIDs
  sharedAssets: SharedAsset[];
  timestamp: number;
}

export interface SharedAsset {
  id: string;
  type: 'MUSIC' | 'VIDEO' | 'ALBUM' | 'BOOK';
  title: string;
  url: string;
  sharedBy: string; // UID
  timestamp: number;
  mediaId?: string;
}

export type AppView = 'LANDING' | 'DASHBOARD' | 'CREATOR' | 'PLAYER' | 'PREVIEW' | 'SEARCH' | 'FEED' | 'USER_PROFILE' | 'LIVE_HUB' | 'RADIO' | 'LIVE_TV' | 'GAMES' | 'CHAT' | 'GAME_PLAYER' | 'CLASSROOMS' | 'CLASSROOM_DETAIL' | 'PPV_EVENTS' | 'VIDEOS' | 'BOOKS' | 'BOOK_READER' | 'MUSIC' | 'GLOBAL_PHOTOS' | 'ART_GALLERY' | 'EVENT_PHOTO_POOL' | 'ADMIN_DASHBOARD' | 'ARTICLES' | 'ARTICLE_EDITOR' | 'ARTICLE_VIEW' | 'BRAND_DASHBOARD' | 'VIDEO_MANAGER' | 'SANCTUARY' | 'STORE' | 'ADMIN_AD_DASHBOARD' | 'PARTNER_DASHBOARD' | 'HELP_CENTER' | 'MOVIE_UX' | 'CLUBS' | 'CHARITY' | 'MOVIES_TV' | 'APPS' | 'APP_DETAIL' | 'APP_PLAYER' | 'POSTMAN' | 'WORLDS' | 'WORLD_MANAGER' | 'LIVETALK_GALLERY' | 'TEAM_DETAIL' | 'PLAYER_DETAIL' | 'PRIVATE_BOARDS';

export type ThemeType = 'DARK' | 'LIGHT' | 'PASTEL' | 'PLAJAH' | 'BIG_SCREEN' | 'PHONE' | 'ETHEREAL' | 'NEBULA' | 'CITRUS';

export interface ProfileThemePreset {
  id: string;
  creatorId: string;
  title: string;
  description: string;
  mode: 'PHOTO_ONLY' | 'VIDEO_ONLY' | 'MIX';
  assets: { id: string; url: string; type: 'PHOTO' | 'VIDEO' }[];
  coverImage?: string;
  isPublic: boolean;
  downloads?: number;
  timestamp: number;
}

export interface AppNotification {
  id: string;
  userId: string;
  senderId: string;
  senderName: string;
  senderPhoto: string;
  type: 'MESSAGE' | 'COMMENT' | 'CONTENT' | 'SYSTEM' | 'LIKE' | 'FOLLOW';
  title: string;
  message: string;
  link?: string;
  targetId?: string;
  isRead: boolean;
  timestamp: number;
}

export interface ChatMessage {
  id: string;
  senderId: string;
  senderName: string;
  senderPhoto: string;
  text?: string;
  voiceUrl?: string;
  mediaId?: string;
  mediaType?: 'ALBUM' | 'TRACK' | 'VIDEO';
  timestamp: number;
  type: 'TEXT' | 'VOICE' | 'SYSTEM' | 'MEDIA' | 'ACTION';
  metadata?: {
    action?: string;
    time?: number;
    url?: string;
  };
  seenBy?: string[]; // Array of UIDs who have seen this message
}

export interface ChatRoom {
  id: string;
  participants: string[]; // UIDs
  lastMessage?: string;
  updatedAt: number;
  type: 'PRIVATE' | 'GROUP' | 'PUBLIC_LIVE';
  name?: string; // For groups/public
  ownerId?: string; // For groups/public
  isPublic?: boolean;
  typingUsers?: string[]; // Array of UIDs currently typing
}

export interface CollabProject {
  id: string;
  name: string;
  chatRoomId: string;
  whiteboardData?: string; // JSON string of Konva/Fabric state
  assets: { id: string; name: string; url: string; type: string }[];
  links: { title: string; url: string }[];
  updatedAt: number;
  ownerId: string;
}

export interface CallSession {
  id: string;
  callerId: string;
  receiverId: string;
  type: 'AUDIO' | 'VIDEO';
  status: 'RINGING' | 'CONNECTED' | 'ENDED' | 'MISSED';
  offer?: string; // WebRTC offer
  answer?: string; // WebRTC answer
  iceCandidates?: string[];
  timestamp: number;
}

export interface PayItForwardPool {
  status: 'ACTIVE' | 'PASSED';
  lastWinnerId: string;
  lastWinTimestamp: number;
  totalGivenOutMonth: number;
  totalGivenOutYear: number;
  resetMonthTimestamp: number;
  resetYearTimestamp: number;
}

export interface PayItForwardVault {
  currentPot: number;
}

export interface PayItForwardWinner {
  id?: string;
  uid: string;
  amount: number;
  timestamp: number;
  status: 'PENDING' | 'CLAIMED' | 'PASSED';
}

export interface PayItForwardDonation {
  id?: string;
  amount: number;
  donorId: string;
  timestamp: number;
}

export interface RSSFeed {
  id: string;
  url: string;
  title: string;
  ownerId: string;
  timestamp: number;
}

export interface PodcastSeries {
  id: string;
  title: string;
  description: string;
  coverImage?: string;
  creatorId: string;
  rssUrl?: string;
  episodeIds: string[]; // Refs to Video or Track
  timestamp: number;
}

export interface PodcastMetadata {
  episodeNumber: number;
  seasonNumber?: number;
  isExplicit?: boolean;
  showTitle: string;
  category?: string;
}

export interface AdMarker {
  id: string;
  time: number;
  label?: string;
}

export interface AdCampaign {
  id: string;
  ownerId: string;
  title: string;
  name?: string; // Alias for title
  type: 'USER_PROMOTION' | 'PARTNER' | 'THIRD_PARTY';
  targetType: 'POST' | 'ALBUM' | 'PROFILE' | 'EXTERNAL';
  targetId?: string;
  externalUrl?: string;
  imageUrl: string;
  budget: number;
  frequency: number; // times per hour/day
  probability: number; // 0-1 weight
  isActive: boolean;
  status?: 'ACTIVE' | 'PAUSED' | 'COMPLETED';
  targetInterests?: string[];
  timestamp: number;
}

export interface PartnerConfig {
  cloudProvider: 'AWS' | 'GCP' | 'AZURE' | 'ONEDRIVE';
  provider?: string; // Alias for cloudProvider
  bucketName: string;
  region?: string;
  accessKeyId?: string;
  secretAccessKey?: string;
  endpoint?: string;
  externalEndpoint?: string;
  importStatus: 'IDLE' | 'SYNCING' | 'COMPLETED';
}

export interface UserAlias {
  id: string;
  email: string;
  provider: string;
  isVerified: boolean;
}

export interface AdRatioConfig {
  userPromos: number; // e.g. 33
  partners: number;   // e.g. 33
  thirdParty: number; // e.g. 34
}

export interface StationIDStinger {
  id: string;
  name: string;
  url: string;
  duration: number;
}

export interface AutoFastChannelConfig {
  rulesEnabled: boolean;
  adInterval: number; // every N videos
  maxAdDuration: number; // seconds
}

export interface PlayerStats {
  id: string;
  name: string;
  position: string;
  number: string;
  photoUrl: string;
  stats: { [key: string]: string | number };
  recentNews?: any[];
}

export interface Team {
  id: string;
  name: string;
  location: string;
  abbreviation: string;
  logo: string;
  league: string;
  color?: string;
  roster: PlayerStats[];
  recentResults: any[];
  highlights: any[];
}

export interface SystemSettingsConfig {
  id: string;
  adRatios: AdRatioConfig;
  isLiveStreamAdsEnabledDefault: boolean;
  fastChannelAds: AutoFastChannelConfig;
  radioAdInterval: number; // every N songs
  stingers: StationIDStinger[];
  globalFreeStorageLimit: number;
  curatedMusicPlaylists?: string[]; // IDs of Playlists
  curatedVideoPlaylists?: string[]; // IDs of Video Playlists
  mustWatchMovies?: string[];       // IDs of Videos (Movies)
  externalSocialLinks: {
    xEnabled: boolean;
    mastodonEnabled: boolean;
    blueskyEnabled: boolean;
    threadsEnabled: boolean;
  };
  updatedAt: number;
}
