//! Oscillators: wavetable (mip-mapped), PolyBLEP analog shapes, sub, and noise.
//!
//! PolyBLEP is used for the classic saw/pulse/tri because a hard-edged waveform generated by
//! naive `2*t - 1` aliases badly, and correcting the discontinuity with a polynomial band-limited
//! step is far cheaper than a wavetable read for those specific shapes.

use crate::tables::WaveTable;

/// Polynomial band-limited step — subtracted at the discontinuity to remove most of the alias
/// energy. `t` is the phase 0..1, `dt` the phase increment.
#[inline]
fn poly_blep(t: f32, dt: f32) -> f32 {
    if t < dt {
        let x = t / dt;
        x + x - x * x - 1.0
    } else if t > 1.0 - dt {
        let x = (t - 1.0) / dt;
        x * x + x + x + 1.0
    } else {
        0.0
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum AnalogShape {
    Saw,
    Square,
    Triangle,
    Sine,
}

impl AnalogShape {
    pub fn from_index(i: u32) -> Self {
        match i {
            1 => AnalogShape::Square,
            2 => AnalogShape::Triangle,
            3 => AnalogShape::Sine,
            _ => AnalogShape::Saw,
        }
    }
}

/// One phase accumulator. Unison spawns several of these per oscillator.
#[derive(Clone, Copy, Default)]
pub struct Phasor {
    pub phase: f32,
    tri_state: f32, // leaky integrator state for the triangle
}

impl Phasor {
    #[inline]
    pub fn reset(&mut self, phase: f32) {
        self.phase = phase;
        self.tri_state = 0.0;
    }

    #[inline]
    pub fn advance(&mut self, inc: f32) {
        self.phase += inc;
        if self.phase >= 1.0 {
            self.phase -= 1.0;
        } else if self.phase < 0.0 {
            self.phase += 1.0;
        }
    }

    #[inline]
    pub fn wavetable(&mut self, table: &WaveTable, morph: f32, inc: f32) -> f32 {
        let s = table.sample(self.phase, morph, inc);
        self.advance(inc);
        s
    }

    #[inline]
    pub fn analog(&mut self, shape: AnalogShape, inc: f32, pulse_width: f32) -> f32 {
        let t = self.phase;
        let dt = inc.abs();
        let out = match shape {
            AnalogShape::Saw => 2.0 * t - 1.0 - poly_blep(t, dt),
            AnalogShape::Square => {
                let pw = pulse_width.clamp(0.02, 0.98);
                let raw = if t < pw { 1.0 } else { -1.0 };
                let mut o = raw + poly_blep(t, dt);
                let t2 = if t + (1.0 - pw) >= 1.0 { t - pw } else { t + (1.0 - pw) };
                o -= poly_blep(t2, dt);
                o
            }
            AnalogShape::Triangle => {
                // Integrated band-limited square — the standard way to get a clean triangle.
                let raw = if t < 0.5 { 1.0 } else { -1.0 };
                let mut sq = raw + poly_blep(t, dt);
                let t2 = if t + 0.5 >= 1.0 { t - 0.5 } else { t + 0.5 };
                sq -= poly_blep(t2, dt);
                self.tri_state = dt * 4.0 * sq + (1.0 - 0.0008) * self.tri_state;
                self.tri_state
            }
            AnalogShape::Sine => (core::f32::consts::TAU * t).sin(),
        };
        self.advance(inc);
        out
    }
}

/// Fast, well-distributed PRNG. Per-voice seeding keeps renders deterministic (the offline
/// bounce must be byte-identical run to run) while still sounding random.
#[derive(Clone, Copy)]
pub struct Rng(pub u32);

impl Rng {
    #[inline]
    pub fn next_u32(&mut self) -> u32 {
        // xorshift32
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;
        self.0 = x;
        x
    }
    #[inline]
    pub fn next_f32(&mut self) -> f32 {
        (self.next_u32() >> 8) as f32 * (1.0 / 16777216.0)
    }
    /// -1..1
    #[inline]
    pub fn bipolar(&mut self) -> f32 {
        self.next_f32() * 2.0 - 1.0
    }
}

/// Noise generator with a pink option — pink sits far better under a filter than white, and is
/// what most analog synths' noise sources actually sounded like.
#[derive(Clone, Copy, Default)]
pub struct Noise {
    b: [f32; 7],
}

impl Noise {
    #[inline]
    pub fn white(&mut self, rng: &mut Rng) -> f32 {
        rng.bipolar()
    }

    /// Paul Kellet's economy pink filter — cheap and accurate enough to ~-3dB/octave.
    #[inline]
    pub fn pink(&mut self, rng: &mut Rng) -> f32 {
        let w = rng.bipolar();
        self.b[0] = 0.99886 * self.b[0] + w * 0.0555179;
        self.b[1] = 0.99332 * self.b[1] + w * 0.0750759;
        self.b[2] = 0.96900 * self.b[2] + w * 0.1538520;
        self.b[3] = 0.86650 * self.b[3] + w * 0.3104856;
        self.b[4] = 0.55000 * self.b[4] + w * 0.5329522;
        self.b[5] = -0.7616 * self.b[5] - w * 0.0168980;
        let out = self.b[0] + self.b[1] + self.b[2] + self.b[3] + self.b[4] + self.b[5] + self.b[6] + w * 0.5362;
        self.b[6] = w * 0.115926;
        out * 0.11
    }
}

/// Unison detune spread. A linear spread sounds mechanical; real supersaws bunch voices toward
/// the centre and push the outliers further, which is what gives the shimmer without the beating
/// turning into a chord.
#[inline]
pub fn unison_detune_curve(index: usize, count: usize) -> f32 {
    if count <= 1 {
        return 0.0;
    }
    let x = index as f32 / (count - 1) as f32 * 2.0 - 1.0; // -1..1
    // Odd-symmetric ease: sign(x) * |x|^1.6
    let s = if x < 0.0 { -1.0 } else { 1.0 };
    s * x.abs().powf(1.6)
}

// NOTE: unison placement is deliberately NOT a stereo pan — it spreads in azimuth around the
// source position and is rendered by `spatial::pan_gains`, so a wide patch is wide in 7.1.4 and
// in ambisonics too, not just in stereo.
