// runMotionTemplateCouncil — the Motion Council directs the MOTION of every platform template: each lower third /
// full page (LOWER_THIRDS) and broadcast identity pack (FABULA_BROADCAST_PACKS) gets a lead cast from its own name,
// era, tags and premise, a counterpoint (the lead's standing rival), an editor (the lead's council seat), timing
// (fps, ones/twos/threes, ease, enter/hold) and notes — the brief a designer builds or revises the template against.
// Deterministic (no model calls): the same registries always produce the same direction, so diffs are reviewable.
//
// Run: npx tsx scripts/council/runMotionTemplateCouncil.ts
// Out: docs/motion/template-direction.json  +  docs/motion/TEMPLATE_DIRECTION.md
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { platformTemplateDirections, councilRecipeTemplates } from '../../services/motion/council/motionTemplates';
import { rosterMember } from '../../services/motion/council/motionRoster';
import { MOTION_PERSONAS } from '../../services/motion/council/motionCouncilPersonas';
import { LOWER_THIRDS } from '../../services/fabula/lowerThirdRegistry';
import { FABULA_BROADCAST_PACKS } from '../../services/fabula/broadcastPacks';

const out = path.resolve('docs/motion');
mkdirSync(out, { recursive: true });
const directions = platformTemplateDirections(LOWER_THIRDS as any, FABULA_BROADCAST_PACKS as any);
const name = (id?: string) => (id ? rosterMember(id)?.name || (MOTION_PERSONAS as any)[id]?.name || id : '—');

writeFileSync(path.join(out, 'template-direction.json'), JSON.stringify({
  generatedBy: 'scripts/council/runMotionTemplateCouncil.ts',
  note: 'Motion direction from the Motion Council for every platform template. Deterministic; regenerate after adding templates.',
  count: directions.length,
  recipes: councilRecipeTemplates().length,
  directions,
}, null, 1));

const leads = new Map<string, number>();
directions.forEach(d => leads.set(d.lead, (leads.get(d.lead) || 0) + 1));
const md = [
  '# Motion Council — platform template direction',
  '',
  `Generated by \`scripts/council/runMotionTemplateCouncil.ts\` — ${directions.length} templates (lower thirds, full pages, broadcast packs).`,
  'Each template has a **lead** (cast from its own name, era, tags and premise), a **counterpoint** (the lead\'s standing rival, used once) and an **editor** (the lead\'s council seat). Art Council attribution (`councilStyle`) is unchanged — this is the motion layer beside it.',
  '',
  `**Leads across the roster:** ${[...leads.entries()].sort((a, b) => b[1] - a[1]).map(([id, n]) => `${name(id).replace(/^The /, '')} ${n}`).join(' · ')}`,
  '',
  '| Template | Family | Lead | Counterpoint | Editor | Timing |',
  '|---|---|---|---|---|---|',
  ...directions.map(d => `| ${d.templateName} (\`${d.templateId}\`) | ${d.family} | ${name(d.lead)} | ${name(d.counterpoint)} | ${name(d.editor)} | ${d.timing.fps} fps · ${d.timing.on === 'mixed' ? 'ones+twos' : `on ${['', 'ones', 'twos', 'threes'][d.timing.on as number]}`} · ${d.timing.ease} · in ${d.timing.enterSec}s / hold ${d.timing.holdSec}s |`),
  '',
].join('\n');
writeFileSync(path.join(out, 'TEMPLATE_DIRECTION.md'), md);
console.log(`Motion Council directed ${directions.length} platform templates across ${leads.size} leads → docs/motion/`);
