import assert from 'node:assert/strict';
import test from 'node:test';
import type { FastChannelSchedule, FastChannelSlot } from '../types';
import {
  backfillScheduleDurationsByUrl,
  dayAnchoredPosition,
  localMidnightMs,
  unresolvedDurationUrls,
} from '../services/fastChannelTimeline';

const programme = (id: string, url: string, duration: number): FastChannelSlot => ({
  id,
  type: 'VIDEO',
  order: 0,
  videoId: id,
  videoUrl: url,
  videoTitle: id,
  videoDurationSeconds: duration,
});

test('Mux URL probes repair placeholder durations in default and weekly schedules', () => {
  const muxA = 'https://stream.mux.com/a.m3u8';
  const muxB = 'https://stream.mux.com/b.m3u8';
  const schedule: FastChannelSchedule = {
    userId: 'owner',
    slots: [programme('a', muxA, 1800)],
    weeklySlots: { 1: [programme('b', muxB, 1)] },
    adFrequencyMinutes: 20,
    adDurationSeconds: 60,
    commercialFree: false,
    loopSchedule: true,
    autoGenerated: true,
    includePublicDomain: false,
  };

  assert.deepEqual(unresolvedDurationUrls(schedule).sort(), [muxA, muxB]);
  const healed = backfillScheduleDurationsByUrl(schedule, new Map([[muxA, 102], [muxB, 313]]));
  assert.equal(healed.slots[0].videoDurationSeconds, 102);
  assert.equal(healed.weeklySlots?.[1]?.[0].videoDurationSeconds, 313);
  assert.deepEqual(unresolvedDurationUrls(healed), []);
});

test('a corrected programme window advances into the following break', () => {
  const slots: FastChannelSlot[] = [
    programme('program', 'https://stream.mux.com/program.m3u8', 102),
    { id: 'break', type: 'AD_BREAK', order: 1, adDurationSeconds: 60 },
  ];
  const midnight = localMidnightMs(Date.now());
  assert.deepEqual(dayAnchoredPosition(slots, midnight + 101_000), { index: 0, offsetSec: 101 });
  assert.deepEqual(dayAnchoredPosition(slots, midnight + 102_000), { index: 1, offsetSec: 0 });
});
