/**
 * lightShowEngine.ts — The core show document model for LD (Lighting Designer).
 *
 * A show is a tree: Show → CueList → Cue → FixtureState.
 * The engine interpolates between cues over time, supports snapping to beat
 * markers, and outputs a unified fixture bus that feeds all output adapters
 * (smart lights, DMX, screen sync, Pixels visualizer).
 *
 * Design philosophy: "Magic not math." DMX addresses auto-assign, fixture
 * profiles auto-detect, channel groups auto-label. The LD can always dig
 * deeper, but the default is delight.
 */

// ── Types ───────────────────────────────────────────────────────────────────

/** A color in HSL space — the natural space for lighting design (hue wheel, saturation, luminance). */
export interface LDColor {
  h: number; // 0-360
  s: number; // 0-100
  l: number; // 0-100
}

/** Fixture categories the engine knows about. */
export type FixtureKind =
  | 'SMART_BULB'     // Hue, Nanoleaf, Govee, generic Wi-Fi
  | 'SMART_STRIP'    // LED strips (Hue, Govee, WLED)
  | 'SCREEN'         // Any logged-in Plajah device (screen-as-fixture)
  | 'DMX_DIMMER'     // Single-channel dimmer
  | 'DMX_RGB'        // 3/4 channel RGB/RGBW par
  | 'DMX_MOVING'     // Moving head / scanner (pan/tilt/color/gobo)
  | 'DMX_LED_BAR'    // Multi-cell LED bar
  | 'DMX_STROBE'     // Strobe/blinder
  | 'DMX_LASER'      // Laser fixture
  | 'DMX_FOG'        // Fog/haze machine
  | 'RAZER_CHROMA'   // Razer Chroma peripherals
  | 'CUSTOM';        // User-defined

/** How a fixture transitions between states. */
export type TransitionType =
  | 'SNAP'      // Instant change (blackout, strobe)
  | 'FADE'      // Linear crossfade
  | 'EASE_IN'   // Smooth acceleration
  | 'EASE_OUT'  // Smooth deceleration
  | 'EASE'      // Smooth both directions
  | 'CHASE'     // Sequential through fixtures in the group
  | 'RAINBOW'   // Hue rotation through group
  | 'PULSE'     // Beat-synced pulse
  | 'BREATHE';  // Slow organic pulse

/** The state of a single fixture at a point in time. */
export interface FixtureState {
  /** Fixture or fixture-group ID this state applies to. */
  fixtureId: string;
  color: LDColor;
  /** 0-1, overall brightness. */
  intensity: number;
  /** For moving heads: 0-540 degrees. */
  pan?: number;
  /** For moving heads: 0-270 degrees. */
  tilt?: number;
  /** Strobe rate: 0 = off, 1 = slow, 10 = full. */
  strobe?: number;
  /** Gobo wheel position (DMX moving heads). */
  gobo?: number;
  /** Effect applied to this fixture. */
  effect?: TransitionType;
  /** Effect speed multiplier (1 = 1x tempo). */
  effectSpeed?: number;
}

/** A cue is a time-stamped lighting state for one or more fixtures. */
export interface Cue {
  id: string;
  /** Seconds from the start of the track (or show). */
  time: number;
  /** Duration of the transition into this cue, in seconds. */
  fadeDuration: number;
  /** How to transition into this cue. */
  transition: TransitionType;
  /** Fixture states at this cue point. */
  states: FixtureState[];
  /** Optional: which song section this cue is for (verse, chorus, bridge, etc.). */
  section?: string;
  /** Optional: label for the cue timeline ("Chorus burst", "Fade to blue", etc.). */
  label?: string;
  /** Whether this cue was auto-generated by the AI. */
  aiGenerated?: boolean;
  /** AI annotation / "Teach Me" explanation. */
  aiAnnotation?: string;
}

/** A scene is a saved preset — a named collection of fixture states. */
export interface Scene {
  id: string;
  name: string;
  /** Colors extracted from album art, or manually chosen. */
  palette: LDColor[];
  states: FixtureState[];
  /** Optional: the mood/energy this scene targets. */
  mood?: 'intimate' | 'energetic' | 'dramatic' | 'calm' | 'celebratory';
  thumbnail?: string;
}

/** A fixture in the user's rig (physical or virtual). */
export interface Fixture {
  id: string;
  kind: FixtureKind;
  name: string;
  /** Adapter-specific device ID (Hue light ID, DMX address, screen device ID, etc.). */
  adapterId: string;
  /** Which adapter manages this fixture. */
  adapter: 'HUE' | 'NANOLEAF' | 'GOVEE' | 'RAZER' | 'DMX_SERIAL' | 'ARTNET' | 'SACN' | 'SCREEN' | 'WLED';
  /** Position in the spatial fixture map. */
  position: { x: number; y: number };
  /** DMX start address (for DMX fixtures). */
  dmxAddress?: number;
  /** DMX channel count (for DMX fixtures). */
  dmxChannels?: number;
  /** Fixture profile ID from the Open Fixture Library. */
  profileId?: string;
  /** Group ID for fixture grouping (e.g., "front wash", "stage left"). */
  groupId?: string;
  /** Whether this fixture is online / reachable. */
  online: boolean;
  /** Capabilities this fixture supports. */
  capabilities: Array<'COLOR' | 'DIMMER' | 'PAN' | 'TILT' | 'STROBE' | 'GOBO' | 'FOG'>;
}

/** A fixture group — logical grouping for batch control. */
export interface FixtureGroup {
  id: string;
  name: string;
  fixtureIds: string[];
  /** Auto-assigned color for visual identification in the fixture map. */
  color: string;
}

/** A complete show document. */
export interface LightShow {
  id: string;
  name: string;
  /** The track or album this show is designed for. */
  trackId?: string;
  albumId?: string;
  /** All fixtures in the rig. */
  fixtures: Fixture[];
  /** Fixture groups. */
  groups: FixtureGroup[];
  /** Saved scene presets. */
  scenes: Scene[];
  /** The cue list — the "program" of the show. */
  cues: Cue[];
  /** BPM of the associated track (from audio analysis). */
  bpm?: number;
  /** Master intensity (0-1). */
  masterIntensity: number;
  /** Master speed multiplier. */
  masterSpeed: number;
  /** Whether the show is in Party Mode (auto-reactive, no cue list). */
  partyMode: boolean;
  createdAt: number;
  updatedAt: number;
}

// ── Default Show ────────────────────────────────────────────────────────────

export function createDefaultShow(): LightShow {
  return {
    id: `show_${Date.now()}`,
    name: 'New Show',
    fixtures: [],
    groups: [],
    scenes: createDefaultScenes(),
    cues: [],
    masterIntensity: 0.85,
    masterSpeed: 1.0,
    partyMode: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}

/** Built-in scene presets that every new show starts with. */
function createDefaultScenes(): Scene[] {
  return [
    {
      id: 'scene_warm',
      name: 'Warm Glow',
      palette: [{ h: 30, s: 90, l: 55 }, { h: 15, s: 85, l: 45 }],
      states: [],
      mood: 'intimate',
    },
    {
      id: 'scene_cool',
      name: 'Cool Wash',
      palette: [{ h: 220, s: 80, l: 50 }, { h: 240, s: 70, l: 40 }],
      states: [],
      mood: 'calm',
    },
    {
      id: 'scene_energy',
      name: 'Energy Burst',
      palette: [{ h: 330, s: 100, l: 50 }, { h: 30, s: 100, l: 55 }],
      states: [],
      mood: 'energetic',
    },
    {
      id: 'scene_deep',
      name: 'Deep Purple',
      palette: [{ h: 280, s: 85, l: 35 }, { h: 310, s: 90, l: 45 }],
      states: [],
      mood: 'dramatic',
    },
    {
      id: 'scene_party',
      name: 'Party',
      palette: [
        { h: 0, s: 100, l: 50 }, { h: 60, s: 100, l: 50 },
        { h: 120, s: 100, l: 50 }, { h: 240, s: 100, l: 50 },
      ],
      states: [],
      mood: 'celebratory',
    },
    {
      id: 'scene_blackout',
      name: 'Blackout',
      palette: [{ h: 0, s: 0, l: 0 }],
      states: [],
    },
  ];
}

// ── Interpolation Engine ────────────────────────────────────────────────────

/** Convert HSL to CSS string. */
export function hslToCSS(c: LDColor): string {
  return `hsl(${c.h}, ${c.s}%, ${c.l}%)`;
}

/** Convert HSL to RGB hex string. */
export function hslToHex(c: LDColor): string {
  const s = c.s / 100;
  const l = c.l / 100;
  const a = s * Math.min(l, 1 - l);
  const f = (n: number) => {
    const k = (n + c.h / 30) % 12;
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
    return Math.round(255 * color).toString(16).padStart(2, '0');
  };
  return `#${f(0)}${f(8)}${f(4)}`;
}

/** Linearly interpolate between two colors. */
export function lerpColor(a: LDColor, b: LDColor, t: number): LDColor {
  // Handle hue wrapping (shortest path around the wheel).
  let dh = b.h - a.h;
  if (dh > 180) dh -= 360;
  if (dh < -180) dh += 360;
  return {
    h: ((a.h + dh * t) % 360 + 360) % 360,
    s: a.s + (b.s - a.s) * t,
    l: a.l + (b.l - a.l) * t,
  };
}

/** Get eased t value based on transition type. */
function easeT(t: number, transition: TransitionType): number {
  switch (transition) {
    case 'SNAP': return t >= 1 ? 1 : 0;
    case 'EASE_IN': return t * t;
    case 'EASE_OUT': return 1 - (1 - t) * (1 - t);
    case 'EASE': return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
    case 'FADE':
    default: return t;
  }
}

/** Interpolate between two fixture states. */
export function lerpFixtureState(a: FixtureState, b: FixtureState, rawT: number, transition: TransitionType): FixtureState {
  const t = easeT(Math.max(0, Math.min(1, rawT)), transition);
  return {
    fixtureId: b.fixtureId,
    color: lerpColor(a.color, b.color, t),
    intensity: a.intensity + (b.intensity - a.intensity) * t,
    pan: a.pan != null && b.pan != null ? a.pan + (b.pan - a.pan) * t : b.pan,
    tilt: a.tilt != null && b.tilt != null ? a.tilt + (b.tilt - a.tilt) * t : b.tilt,
    strobe: b.strobe,
    gobo: b.gobo,
    effect: b.effect,
    effectSpeed: b.effectSpeed,
  };
}

/**
 * Evaluate the cue list at a given time and return the current state for all fixtures.
 *
 * This is the hot loop — called every animation frame during playback.
 */
export function evaluateShow(
  show: LightShow,
  timeSec: number,
): Map<string, FixtureState> {
  const result = new Map<string, FixtureState>();
  if (show.cues.length === 0) return result;

  // Sort cues by time (should already be sorted, but defensive).
  const sorted = [...show.cues].sort((a, b) => a.time - b.time);

  // For each fixture, find the surrounding cues and interpolate.
  const fixtureIds = new Set(sorted.flatMap(c => c.states.map(s => s.fixtureId)));

  for (const fixtureId of fixtureIds) {
    // Find the cues that have a state for this fixture.
    const fixtureTimeline: Array<{ time: number; fadeDuration: number; transition: TransitionType; state: FixtureState }> = [];
    for (const cue of sorted) {
      const state = cue.states.find(s => s.fixtureId === fixtureId);
      if (state) {
        fixtureTimeline.push({
          time: cue.time,
          fadeDuration: cue.fadeDuration,
          transition: cue.transition,
          state,
        });
      }
    }

    if (fixtureTimeline.length === 0) continue;

    // Find where we are in the timeline.
    let prevIdx = -1;
    for (let i = fixtureTimeline.length - 1; i >= 0; i--) {
      if (fixtureTimeline[i].time <= timeSec) {
        prevIdx = i;
        break;
      }
    }

    if (prevIdx === -1) {
      // Before the first cue — use the first cue's state at zero intensity.
      const first = fixtureTimeline[0].state;
      result.set(fixtureId, { ...first, intensity: 0 });
    } else if (prevIdx === fixtureTimeline.length - 1) {
      // After the last cue — hold the last state.
      const state = { ...fixtureTimeline[prevIdx].state };
      state.intensity *= show.masterIntensity;
      result.set(fixtureId, state);
    } else {
      // Between two cues — interpolate.
      const prev = fixtureTimeline[prevIdx];
      const next = fixtureTimeline[prevIdx + 1];
      const fadeStart = next.time - next.fadeDuration;
      if (timeSec < fadeStart) {
        // Still holding the previous cue.
        const state = { ...prev.state };
        state.intensity *= show.masterIntensity;
        result.set(fixtureId, state);
      } else {
        // In the fade zone.
        const rawT = next.fadeDuration > 0
          ? (timeSec - fadeStart) / next.fadeDuration
          : 1;
        const interpolated = lerpFixtureState(prev.state, next.state, rawT, next.transition);
        interpolated.intensity *= show.masterIntensity;
        result.set(fixtureId, interpolated);
      }
    }
  }

  return result;
}

// ── Party Mode Engine ───────────────────────────────────────────────────────

/**
 * Generate a reactive fixture state from audio analysis data.
 * Used in Party Mode — no cue list, just pure audio reactivity.
 */
export function partyModeState(
  audioData: { bass: number; mid: number; treble: number; level: number },
  palette: LDColor[],
  timeSec: number,
  masterIntensity: number,
): FixtureState {
  if (palette.length === 0) palette = [{ h: 280, s: 85, l: 45 }];

  // Rotate through palette colors based on time + bass energy.
  const colorIndex = Math.floor((timeSec * 0.5 + audioData.bass * 3) % palette.length);
  const nextIndex = (colorIndex + 1) % palette.length;
  const colorT = (timeSec * 0.5 + audioData.bass * 3) % 1;
  const color = lerpColor(palette[colorIndex], palette[nextIndex], colorT);

  // Bass pumps the brightness, treble adds strobe.
  const intensity = Math.min(1, (0.4 + audioData.level * 0.6)) * masterIntensity;
  const strobe = audioData.treble > 0.8 ? Math.min(5, audioData.treble * 6) : 0;

  return {
    fixtureId: '*', // Applies to all fixtures.
    color,
    intensity,
    strobe: strobe > 0.5 ? strobe : 0,
    effect: audioData.bass > 0.7 ? 'PULSE' : undefined,
    effectSpeed: 1 + audioData.bass * 0.5,
  };
}

// ── Album Art Color Extraction ──────────────────────────────────────────────

/** Extract a palette of dominant colors from album art (simplified k-means-ish). */
export function extractPaletteFromImage(
  imageData: ImageData,
  count: number = 5,
): LDColor[] {
  const pixels = imageData.data;
  const buckets: Map<string, { h: number; s: number; l: number; count: number }> = new Map();

  // Sample every 4th pixel for performance.
  for (let i = 0; i < pixels.length; i += 16) {
    const r = pixels[i] / 255;
    const g = pixels[i + 1] / 255;
    const b = pixels[i + 2] / 255;

    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    const l = (max + min) / 2;

    // Skip very dark and very light pixels.
    if (l < 0.08 || l > 0.92) continue;

    const d = max - min;
    const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
    let h = 0;
    if (d !== 0) {
      switch (max) {
        case r: h = ((g - b) / d + (g < b ? 6 : 0)) * 60; break;
        case g: h = ((b - r) / d + 2) * 60; break;
        case b: h = ((r - g) / d + 4) * 60; break;
      }
    }

    // Quantize to 15° hue buckets for clustering.
    const key = `${Math.round(h / 15) * 15}-${Math.round(s * 4) * 25}-${Math.round(l * 4) * 25}`;
    const existing = buckets.get(key);
    if (existing) {
      existing.h += h;
      existing.s += s * 100;
      existing.l += l * 100;
      existing.count++;
    } else {
      buckets.set(key, { h, s: s * 100, l: l * 100, count: 1 });
    }
  }

  // Sort by frequency and take the top N.
  const sorted = [...buckets.values()].sort((a, b) => b.count - a.count);
  return sorted.slice(0, count).map(b => ({
    h: Math.round(b.h / b.count) % 360,
    s: Math.round(b.s / b.count),
    l: Math.round(b.l / b.count),
  }));
}
