import type { TelaVectorObject } from '../types';
import { PUBLICATION_DESIGNS } from './tela/designs/publications';
import { MAGAZINE_PRINT } from './tela/designs/publications/magazines';
import { frame } from './tela/templateKit';

export type TelaPublicationCategory='EMAIL BLAST'|'NEWSLETTER'|'MAGAZINE'|'CHILDREN’S BOOK'|'PHOTO BOOK'|'COMIC & MANGA'|'ARTICLE'|'CATALOG';
export type TelaPublicationPageType='EMAIL HERO'|'EMAIL STORY'|'COVER'|'CONTENTS'|'EDITOR’S NOTE'|'SECTION OPENER'|'FEATURE OPENER'|'ARTICLE'|'INTERVIEW'|'PHOTO ESSAY'|'STORY SPREAD'|'QUIET SPREAD'|'ACTIVITY'|'FULL BLEED'|'PHOTO GRID'|'CAPTIONED PHOTO'|'TIMELINE'|'COMIC COVER'|'COMIC PAGE'|'MANGA PAGE'|'SPLASH PAGE'|'CHARACTER SHEET'|'WEBTOON EPISODE'|'BACK COVER'|'ARTICLE HEADER'|'BODY PAGE'|'PULL QUOTE'|'SIDEBAR'|'LONG-FORM OPENER'|'DATA CHART'|'PHOTO GALLERY'|'END PAGE'|'PRODUCT GRID'|'PRODUCT DETAIL'|'ORDER FORM'|'PRICE LIST'|'SPEC TABLE'|'LOOKBOOK SPREAD'|'INDEX'|'DEPARTMENT'|'AD PAGE'|'COLOPHON'|'BOARD PAGE'|'COUNT PAGE'|'PEEK PAGE'|'COLOURING PAGE'|'MAZE PAGE'|'DOT-TO-DOT PAGE'|'FIND & CIRCLE PAGE'|'MIRROR PAGE'|'TRACE PAGE'|'WORD PUZZLE PAGE'|'DESIGN PAGE'|'CERTIFICATE';
/** Print-correct metadata for periodicals: trim, 0.125in bleed, safe area, binding, facing-page spreads and the grid constants (px at 96/in). */
export interface TelaPublicationPrint{trimIn:[number,number];bleedIn:number;safeIn:number;binding:'PERFECT'|'SADDLE'|'STAPLED'|'SPIRAL';pxPerIn:number;facing:boolean;spreads:Array<[number,number]>;grid:{columns:number;gutterPx:number;baselinePx:number;marginPx:{top:number;bottom:number;inner:number;outer:number}}}
export interface TelaPublicationTemplate {id:string;name:string;category:TelaPublicationCategory;description:string;audience:string;palette:[string,string,string,string];fontMood:'SERIF'|'SANS'|'PLAYFUL'|'DISPLAY';width:number;height:number;pages:TelaPublicationPageType[];print?:TelaPublicationPrint;}

const p=(id:string,name:string,category:TelaPublicationCategory,description:string,audience:string,palette:[string,string,string,string],fontMood:TelaPublicationTemplate['fontMood'],width:number,height:number,pages:TelaPublicationPageType[]):TelaPublicationTemplate=>({id,name,category,description,audience,palette,fontMood,width,height,pages});
const MAG:TelaPublicationPageType[]=['COVER','CONTENTS','EDITOR’S NOTE','SECTION OPENER','FEATURE OPENER','ARTICLE','ARTICLE','INTERVIEW','PHOTO ESSAY','BACK COVER'];
const STORY:TelaPublicationPageType[]=['COVER','STORY SPREAD','STORY SPREAD','QUIET SPREAD','STORY SPREAD','ACTIVITY','BACK COVER'];
const STORY_B9:TelaPublicationPageType[]=['COVER','STORY SPREAD','STORY SPREAD','STORY SPREAD','QUIET SPREAD','FULL BLEED','STORY SPREAD','ACTIVITY','BACK COVER'];
const PHOTO:TelaPublicationPageType[]=['COVER','FULL BLEED','PHOTO GRID','CAPTIONED PHOTO','FULL BLEED','TIMELINE','PHOTO GRID','BACK COVER'];
const COMIC:TelaPublicationPageType[]=['COMIC COVER','CHARACTER SHEET','SPLASH PAGE','COMIC PAGE','COMIC PAGE','COMIC PAGE','BACK COVER'];
const MANGA:TelaPublicationPageType[]=['COMIC COVER','CHARACTER SHEET','MANGA PAGE','MANGA PAGE','SPLASH PAGE','MANGA PAGE','BACK COVER'];
// ── MAGAZINE SYSTEMS (12-page issues, print metadata in designs/publications/magazines.ts) ──
const MAG12:TelaPublicationPageType[]=['COVER','CONTENTS','EDITOR’S NOTE','DEPARTMENT','AD PAGE','FEATURE OPENER','ARTICLE','ARTICLE','INTERVIEW','PHOTO ESSAY','COLOPHON','BACK COVER'];
const mag=(id:string,name:string,description:string,audience:string,palette:[string,string,string,string],fontMood:TelaPublicationTemplate['fontMood'],width:number,height:number):TelaPublicationTemplate=>({...p(id,name,'MAGAZINE',description,audience,palette,fontMood,width,height,MAG12),print:MAGAZINE_PRINT[id]});
// ── END MAGAZINE SYSTEMS helpers ──
export const TELA_PUBLICATION_TEMPLATES:TelaPublicationTemplate[]=[
  p('email-product','Product Drop','EMAIL BLAST','A focused launch email with a bold product hero, proof, and one decisive action.','Products, releases, and merch',['#0E0A14','#FFFFFF','#D40055','#FF8A00'],'SANS',800,1400,['EMAIL HERO']),
  p('email-event','Event Invitation','EMAIL BLAST','A cinematic invitation with date hierarchy, atmosphere, and RSVP.','Shows, premieres, and gatherings',['#150C23','#F7EEDC','#8C2CB7','#E2B45A'],'DISPLAY',800,1400,['EMAIL HERO']),
  p('email-editorial','Editorial Dispatch','EMAIL BLAST','A thoughtful letter-led campaign that reads like a small publication.','Essays, announcements, and community',['#F5F0E6','#211B2A','#7A3157','#B78B4A'],'SERIF',800,1400,['EMAIL STORY']),
  p('email-course','Course Launch','EMAIL BLAST','Curriculum, outcomes, teacher presence, and enrollment action.','Classes and workshops',['#F2FBFF','#173C54','#00A8BC','#FF8A00'],'SANS',800,1400,['EMAIL HERO']),
  p('email-nonprofit','Impact Appeal','EMAIL BLAST','Human story, evidence, impact figures, and a respectful contribution ask.','Causes and community organizations',['#F7F2E8','#243B33','#C9533F','#D4A94E'],'SERIF',800,1400,['EMAIL STORY']),
  p('email-digest','Weekly Digest','EMAIL BLAST','A scan-friendly collection of stories, links, and recommendations.','Recurring creator updates',['#10151D','#F7FAFC','#3667D6','#5ED3C6'],'SANS',800,1400,['EMAIL STORY']),
  p('news-community','Community Current','NEWSLETTER','Warm local reporting with recurring departments and practical notices.','Clubs, neighborhoods, and organizations',['#FFF4E4','#372447','#D85268','#1A8B88'],'SERIF',816,1056,['COVER','CONTENTS','EDITOR’S NOTE','ARTICLE','ARTICLE','BACK COVER']),
  p('news-creator','Creator Notes','NEWSLETTER','A personal editorial voice balanced with projects, links, and studio process.','Artists and independent creators',['#110B18','#F8F1FF','#B548C8','#FF8A00'],'DISPLAY',816,1056,['COVER','EDITOR’S NOTE','FEATURE OPENER','ARTICLE','PHOTO ESSAY','BACK COVER']),
  p('news-school','School Chronicle','NEWSLETTER','Clear sections for learning, student work, dates, and recognition.','Schools and learning communities',['#F5FAFF','#1D3557','#3977C9','#E6A92C'],'SANS',816,1056,['COVER','CONTENTS','ARTICLE','PHOTO GRID','ARTICLE','BACK COVER']),
  p('news-culture','Culture Letter','NEWSLETTER','An elegant reading experience for criticism, recommendations, and cultural notes.','Museums, books, film, and music',['#F0E8D9','#261D22','#8D2E3D','#A88952'],'SERIF',816,1056,['COVER','CONTENTS','FEATURE OPENER','ARTICLE','INTERVIEW','BACK COVER']),
  p('news-business','Field Report','NEWSLETTER','A confident professional briefing with signals, charts, and analysis.','Teams and professional communities',['#0D1B2A','#F4F7FA','#2E6EA6','#E07836'],'SANS',816,1056,['COVER','CONTENTS','EDITOR’S NOTE','ARTICLE','ARTICLE','BACK COVER']),
  p('news-faith','Gathered','NEWSLETTER','A contemplative community rhythm for reflection, service, and upcoming life together.','Faith communities',['#F4EEE2','#373047','#765A9B','#C08C4A'],'SERIF',816,1056,['COVER','EDITOR’S NOTE','ARTICLE','PHOTO ESSAY','ARTICLE','BACK COVER']),
  p('mag-culture','New Culture Review','MAGAZINE','Expressive culture journalism with large type, interviews, and visual essays.','Culture and criticism',['#121015','#F6F0E8','#D40055','#00A8BC'],'DISPLAY',816,1056,MAG),
  p('mag-fashion','Atelier Quarterly','MAGAZINE','High-fashion pacing with restraint, full-bleed imagery, and refined captions.','Fashion and beauty',['#F5F1E9','#19171A','#9A294A','#B9A46C'],'SERIF',816,1056,MAG),
  p('mag-music','Frequency','MAGAZINE','Energetic music editorial with sharp departments and poster-scale feature pages.','Music and nightlife',['#080A10','#F5F7FF','#7547FF','#FF4B3E'],'DISPLAY',816,1056,MAG),
  p('mag-travel','Elsewhere','MAGAZINE','Immersive travel narratives, maps, field notes, and generous photography.','Travel and place',['#EDE4D1','#213F43','#D1683E','#D7A93A'],'SERIF',816,1056,MAG),
  p('mag-science','Observable','MAGAZINE','Precise but inviting science features with diagrams, evidence, and explanatory pacing.','Science and discovery',['#071B29','#EAFBFF','#00A8BC','#F2B544'],'SANS',816,1056,MAG),
  p('mag-independent','Small Press','MAGAZINE','A tactile independent magazine with collage, essays, and artist portfolios.','Independent publishing',['#E9DDC6','#171717','#C62D39','#386B63'],'DISPLAY',816,1056,MAG),
  p('story-forest','Little Fox, Big Trees','CHILDREN’S BOOK','A woodblock-print forest picture book for ages 5–7, drawn from the real story of Tam the little fox, Dot the lost fawn and the Big Trees: off-register vermilion, gold and pine, a triangle fox, towering trunks and a low sun, with every word carved into signs and flags across 11 pages: a hero page, a counting-trunks page, a hush page, a crunch-rustle-peek strip, a giant fawn face, a golden path, the den, a find-the-lights activity and a back-cover blurb.','Ages 5–7',['#0B3C1A','#FFF3D6','#FF4500','#FFD700'],'PLAYFUL',1024,768,['COVER','STORY SPREAD','STORY SPREAD','QUIET SPREAD','PHOTO GRID','FULL BLEED','CAPTIONED PHOTO','FULL BLEED','STORY SPREAD','ACTIVITY','BACK COVER']),
  p('story-space','Orbit Party!','CHILDREN’S BOOK','A torn cut-paper picture book for ages 4–6, drawn from the real story of Zib the round astronaut, Nova the comet pup and shy Mars: every planet a circle, every word lettered into the art, across 11 pages: a parade of planets, a hush page, three failed attempts in round windows, a giant blushing face, a sit-down, a small dance, a good-night page and a back-cover blurb.','Ages 4–6',['#0D0015','#FFFFFF','#FF0055','#FFF200'],'PLAYFUL',1024,768,['COVER','STORY SPREAD','STORY SPREAD','FULL BLEED','QUIET SPREAD','PHOTO GRID','FULL BLEED','CAPTIONED PHOTO','STORY SPREAD','QUIET SPREAD','BACK COVER']),
  {...p('story-ocean','Below the Blue','CHILDREN’S BOOK','A watercolour picture book for ages 6–8, laid out from the story of Below the Blue (Coral the round coral-red reef fish with three golden stripes, Lumi the tiny silver lanternfish with a row of glowing dots along her belly, Mabel the humpback whale, and the glowing jellies). Transparent ultramarine, cerulean, turquoise and rose washes with wet edges, blooms, salt and loose pencil lines, handwritten and serif story text on warm paper. Thirteen pages: cover, a bright reef page, a porthole vignette, a three-band descent, a quiet dark page, a Lumi close-up, a jelly panorama, rising ribbons, a bright return, Mabel’s giant eye, a dawn closing page, an activity page and a back cover with blurb and barcode.','Ages 6–8',['#FBF6EC','#26386E','#2E4FD0','#E5517C'],'PLAYFUL',816,816,['COVER','STORY SPREAD','STORY SPREAD','PHOTO GRID','QUIET SPREAD','FULL BLEED','FULL BLEED','STORY SPREAD','STORY SPREAD','FULL BLEED','END PAGE','ACTIVITY','BACK COVER']),print:{trimIn:[8.5,8.5],bleedIn:.125,safeIn:.25,binding:'SADDLE',pxPerIn:96,facing:false,spreads:[],grid:{columns:6,gutterPx:16,baselinePx:28,marginPx:{top:72,bottom:72,inner:64,outer:64}}}},
  {...p('story-bedtime','Moon Blanket','CHILDREN’S BOOK','A felt-and-stitch picture book for ages 2–4, laid out from the story of Moon Blanket (Bramble the honey-brown bear with a mustard-patched ear, Flit the tiny ember-orange moth, and a sleepy moon). Indigo, burgundy, mustard, teal and moon-cream felt with fuzzy edges, running stitches, button eyes and satin-stitch lettering on quilted linen. Eleven pages: cover, two hero pages, a hole close-up, a three-panel guessing strip, a near-empty quiet page, a giant moth with a stitched tear, a lifted-blanket page, a snug closing and a quiet Goodnight, and a back cover with blurb and barcode.','Ages 2–4',['#241F70','#F8EACB','#E8A91C','#972250'],'PLAYFUL',768,960,['COVER','STORY SPREAD','STORY SPREAD','FULL BLEED','PHOTO GRID','QUIET SPREAD','FULL BLEED','STORY SPREAD','STORY SPREAD','QUIET SPREAD','BACK COVER']),print:{trimIn:[8,10],bleedIn:.125,safeIn:.25,binding:'SADDLE',pxPerIn:96,facing:false,spreads:[],grid:{columns:4,gutterPx:18,baselinePx:32,marginPx:{top:72,bottom:72,inner:60,outer:60}}}},
  p('story-city','Beep Block Street','CHILDREN’S BOOK','A loud, bright screen-print picture book told in ten spreads: Bo the square red bus loses his beep, Tilly the taxi and Gus the dump truck jam the street, and Pip the small emerald pigeon finds it. Voxel-grid towers, sound words and a find-Pip activity after the ending.','Ages 3–5',['#FFF6E5','#1A1A1D','#E5173F','#FFC300'],'DISPLAY',1024,768,['COVER','STORY SPREAD','STORY SPREAD','QUIET SPREAD','FULL BLEED','STORY SPREAD','FULL BLEED','END PAGE','ACTIVITY','BACK COVER']),
  p('story-folktale','The Golden Thread','CHILDREN’S BOOK','A folk-papercut tale in fourteen spreads, in wine, crimson, saffron and gold: Mira the weaver, Glint the thread spirit, the Grey Wolf and the Moon, three kind tasks, mirrored triangle hills and one gold thread that runs unbroken through every page, with long story panels sized for confident readers.','Ages 7–9',['#F1E6CF','#5A1230','#D4262B','#F5B800'],'DISPLAY',1024,768,['COVER','STORY SPREAD','STORY SPREAD','FULL BLEED','STORY SPREAD','FULL BLEED','STORY SPREAD','QUIET SPREAD','FULL BLEED','STORY SPREAD','END PAGE','QUIET SPREAD','ACTIVITY','BACK COVER']),
  p('story-anime','Sakura and the Sky Whale','CHILDREN’S BOOK','An anime-inspired picture book with a Plajah-original look: cel-shaded Sakura with huge glossy eyes, a giant friendly sky whale, pastel gradient skies, drifting cherry petals, speed lines, reaction panels and a diagonal-cut manga spread, all read left to right.','Ages 4–8',['#FFF1F6','#1E1B4B','#FF8FB8','#7FD8FF'],'PLAYFUL',960,768,['COVER','STORY SPREAD','FULL BLEED','STORY SPREAD','FULL BLEED','QUIET SPREAD','STORY SPREAD','FULL BLEED','ACTIVITY','BACK COVER']),
  p('story-pixel','Pixel Quest','CHILDREN’S BOOK','A true 8-bit adventure and activity book on a real pixel grid: a 16-colour palette, a pixel knight with a face, slimes, hearts and coins, a level-map spread, a side-scroller panorama, dialogue boxes, a dungeon maze, an inventory grid and a boss-fight scale shock.','Ages 6–12',['#14102A','#FFFFFF','#2FB8E8','#F2E94E'],'DISPLAY',960,720,['COVER','SECTION OPENER','FULL BLEED','STORY SPREAD','QUIET SPREAD','ACTIVITY','PHOTO GRID','FULL BLEED','TIMELINE','END PAGE','BACK COVER']),
  p('story-board','Hello, Colors!','CHILDREN’S BOOK','A bold-shape board book for the very youngest: one giant primary-colour object per page inside a rounded cut-edge frame, one huge word, point-to-it cues, a counting trio, a black-and-white page, a mirror face and a peek-a-boo window.','Ages 0–2',['#FFFFFF','#111111','#E4141C','#FFD200'],'PLAYFUL',576,576,['COVER','BOARD PAGE','BOARD PAGE','BOARD PAGE','COUNT PAGE','COUNT PAGE','COUNT PAGE','BOARD PAGE','BOARD PAGE','PEEK PAGE','BOARD PAGE','BOARD PAGE','BOARD PAGE','END PAGE','BACK COVER']),
  p('story-doodle','Doodle Day','CHILDREN’S BOOK','A print-friendly activity and colouring book in pure black line art: colour-me scenes, two solvable mazes, dot-to-dots, find-and-circle, draw-the-other-half, trace-the-path, a word search, a design-your-own frame and a certificate.','All ages',['#FFFFFF','#111111','#FF5A5F','#FFC93C'],'PLAYFUL',816,1056,['COVER','CONTENTS','COLOURING PAGE','MAZE PAGE','DOT-TO-DOT PAGE','FIND & CIRCLE PAGE','COLOURING PAGE','MIRROR PAGE','MAZE PAGE','TRACE PAGE','COLOURING PAGE','DOT-TO-DOT PAGE','WORD PUZZLE PAGE','DESIGN PAGE','CERTIFICATE','BACK COVER']),
  p('photo-family','Family Archive','PHOTO BOOK','A warm chronological album mixing full images, small moments, and written memory.','Families and personal archives',['#F2E9D8','#332B28','#9B5B45','#BDA16B'],'SERIF',1024,768,PHOTO),
  p('photo-travel','Road & Horizon','PHOTO BOOK','Wide cinematic landscapes, field-note captions, and a journey timeline.','Travel photography',['#E9E1CF','#263B43','#C7673F','#D1A948'],'SANS',1024,768,PHOTO),
  p('photo-portfolio','Photographer’s Edit','PHOTO BOOK','Gallery-like sequencing with restrained typography and image-first pacing.','Photography portfolios',['#F7F7F4','#161616','#767676','#C1273D'],'SANS',1024,768,PHOTO),
  p('photo-wedding','Vows & Light','PHOTO BOOK','Elegant event storytelling with quiet details, portraits, and generous spreads.','Weddings and celebrations',['#F7F0EA','#47363D','#B77A83','#C4A56B'],'SERIF',1024,768,PHOTO),
  p('photo-yearbook','The Year We Made','PHOTO BOOK','A spirited year-in-review album with grids, milestones, and candid energy.','Teams, classes, and communities',['#F6EAD1','#27345B','#E34D59','#2FA89A'],'PLAYFUL',1024,768,PHOTO),
  p('photo-minimal','Quiet Frames','PHOTO BOOK','Minimal fine-art sequencing that gives every photograph its own atmosphere.','Fine-art and monochrome work',['#F4F3EF','#171717','#A6A29A','#6B6B6B'],'SERIF',1024,768,PHOTO),
  p('comic-superhero','Velocity Comics','COMIC & MANGA','Dynamic hero pacing with splash reveals, diagonal action panels, captions, and impact lettering.','Superhero and action comics',['#F6E33B','#10152B','#E32935','#2F67C7'],'DISPLAY',816,1056,COMIC),
  p('comic-noir','Midnight Casefiles','COMIC & MANGA','High-contrast noir pages with cinematic wides, inset clues, and restrained narration.','Mystery, crime, and noir',['#EEE9DC','#111111','#8A1F2D','#58616A'],'SERIF',816,1056,COMIC),
  p('comic-kids','Bright Side Comics','COMIC & MANGA','Open friendly grids, rounded panels, expressive balloons, and generous visual clarity.','Children and all-ages comics',['#FFF4C7','#27345F','#F05A5A','#28AFA1'],'PLAYFUL',816,1056,COMIC),
  p('comic-anthology','Panel Stories','COMIC & MANGA','An editorial anthology system for short comics, creator notes, and varied page rhythms.','Anthologies and literary comics',['#F2E9DA','#282129','#A73C4A','#39756D'],'SERIF',816,1056,['COMIC COVER','CONTENTS','COMIC PAGE','SPLASH PAGE','COMIC PAGE','EDITOR’S NOTE','BACK COVER']),
  p('manga-shonen','Rising Impact','COMIC & MANGA','Right-to-left action pacing with speed-line splashes and compressed reaction panels.','Action and adventure manga',['#FFFFFF','#090909','#E2232E','#808080'],'DISPLAY',816,1152,MANGA),
  p('manga-shojo','Petals & Promises','COMIC & MANGA','Airy emotional pacing, borderless moments, portrait insets, and delicate transitions.','Romance and character drama manga',['#FFF9FC','#241D2A','#D85E9D','#9B86C7'],'SERIF',816,1152,MANGA),
  p('manga-seinen','Afterimage','COMIC & MANGA','Measured cinematic layouts with silence, environmental wides, and psychological close-ups.','Mature drama and suspense manga',['#F5F5F2','#111111','#535353','#9B1E28'],'SANS',816,1152,MANGA),
  p('comic-webtoon','Infinite Scroll','COMIC & MANGA','Vertical episode pacing with breath between beats, reveal spacing, and mobile-first dialogue.','Webtoons and vertical comics',['#11131B','#F8F8FC','#7A55FF','#FF5C7A'],'SANS',800,2400,['COMIC COVER','WEBTOON EPISODE','WEBTOON EPISODE','BACK COVER']),
  // ── BEGIN articles + catalogs block (services/tela/designs/publications/articles.ts, catalogs.ts) ──
  p('art-longform','The Long Read','ARTICLE','A magazine feature opener with a hushed headline, standfirst, drop-cap body, pull-quote page and endnote.','Longform journalism and essays',['#FBF9F4','#151515','#C4161C','#8A7F6C'],'SERIF',816,1056,['LONG-FORM OPENER','BODY PAGE','PULL QUOTE','SIDEBAR','END PAGE']),
  p('art-breaking','Wire Desk','ARTICLE','A compact wire-service story page with dateline, key-points box and a live updates rail.','Breaking news and bulletins',['#FFFFFF','#111111','#D90429','#F2B705'],'SANS',1080,1500,['ARTICLE HEADER','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-dossier','Case File','ARTICLE','An investigative dossier with exhibit tabs, redaction bars, source panels and a chain-of-custody log.','Investigations and document-led reporting',['#E8E1CE','#1A1A1A','#B3261E','#4A5568'],'DISPLAY',794,1123,['ARTICLE HEADER','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-oped','The Column','ARTICLE','An opinion page with a portrait rail, a ruled argument column and a bold pull quote.','Opinion, editorials and commentary',['#FFFDF8','#0B1F3A','#E4572E','#A8B5C7'],'SERIF',816,1056,['ARTICLE HEADER','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-interview','In Conversation','ARTICLE','A question-and-answer feature with hanging Q markers, a speaker card and margin notes.','Interviews and conversations',['#F1ECE4','#2B1B17','#0F766E','#D9A441'],'SERIF',794,1123,['ARTICLE HEADER','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-explainer','How It Works','ARTICLE','A web explainer with numbered steps, a glossary sidebar and a recap checklist.','Explainers and guides',['#F7FAFF','#0F172A','#2563EB','#FBBF24'],'SANS',1080,1400,['ARTICLE HEADER','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-data','Numbers Desk','ARTICLE','A data story with chart frames drawn from the numbers, oversized figures and source notes.','Data journalism and reports',['#0B132B','#F1F5F9','#5BC0BE','#FFD166'],'SANS',1080,1350,['ARTICLE HEADER','DATA CHART','DATA CHART','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-photoessay','Frame by Frame','ARTICLE','A landscape photo essay with a quiet opener, numbered plates and long captions.','Photo essays and documentary work',['#121212','#F2EFE9','#E0B04C','#8A8A85'],'SERIF',1056,816,['LONG-FORM OPENER','PHOTO GALLERY','PHOTO GALLERY','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-review','The Verdict','ARTICLE','A review page with a score block, pros and cons, a spec strip and a clear recommendation.','Reviews and recommendations',['#FFFFFF','#1B1B1F','#FFC300','#D62839'],'SANS',816,1056,['ARTICLE HEADER','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-profile','Portrait','ARTICLE','A profile with a tall portrait hero, fact box, timeline and a closing quote.','Profiles and people stories',['#F3EDE7','#241A1A','#B5446E','#6D597A'],'SERIF',794,1123,['LONG-FORM OPENER','BODY PAGE','SIDEBAR','END PAGE']),
  p('art-newsletter','Sunday Letter','ARTICLE','A single-column newsletter essay built for email widths, with one image, one quote and one link.','Newsletter essays and Substack-style letters',['#FBF8F1','#2A2522','#3E6B5A','#D7C7A5'],'SERIF',680,1500,['ARTICLE HEADER','BODY PAGE','PULL QUOTE','END PAGE']),
  p('art-research','Research Brief','ARTICLE','A two-column brief with abstract, numbered figures, a methods sidebar and hanging references.','Academic and research briefs',['#FFFFFF','#1C1C1C','#7A1F2B','#5B6B7A'],'SERIF',794,1123,['ARTICLE HEADER','BODY PAGE','SIDEBAR','END PAGE']),
  p('cat-product','Supply Catalog','CATALOG','A product catalog with 2x3 and 3x4 grids, spec tables, order codes and an order form.','Product lines and retail',['#F5F5F2','#14171A','#FF5A1F','#1D4E89'],'SANS',816,1056,['COVER','CONTENTS','SECTION OPENER','PRODUCT GRID','PRODUCT GRID','PRODUCT DETAIL','SPEC TABLE','ORDER FORM','INDEX','BACK COVER']),
  p('cat-lookbook','Lookbook','CATALOG','A fashion lookbook with full-bleed plates, look numbers, a line sheet and stockist details.','Fashion and apparel',['#F3EFE9','#1A1A1A','#A68A64','#7C8E7E'],'SERIF',1056,816,['COVER','CONTENTS','LOOKBOOK SPREAD','LOOKBOOK SPREAD','LOOKBOOK SPREAD','PRODUCT GRID','PRODUCT DETAIL','PRICE LIST','BACK COVER']),
  p('cat-books','Publisher Catalog','CATALOG','A publisher season catalog with cover grids, ISBN and price lines, author storefront links and a rights page.','Publishers and author storefronts',['#FBF7EE','#1E2A3A','#9C2F2F','#C8A24A'],'SERIF',816,1056,['COVER','CONTENTS','SECTION OPENER','PRODUCT GRID','PRODUCT GRID','PRODUCT DETAIL','PRICE LIST','ORDER FORM','INDEX','BACK COVER']),
  p('cat-parts','Parts and Hardware','CATALOG','A dense parts catalog with order-code tables, exploded-view pages and a quick-order sheet.','Hardware, supplies and trade counters',['#EDEDE6','#1A1F1C','#F2A900','#2F5D50'],'SANS',816,1056,['COVER','CONTENTS','SPEC TABLE','SPEC TABLE','PRODUCT GRID','PRODUCT DETAIL','PRICE LIST','ORDER FORM','INDEX','BACK COVER']),
  p('cat-auction','Auction Catalog','CATALOG','An auction catalog with lot pages, estimates, provenance lines, conditions of sale and a bid form.','Auction houses and gallery sales',['#FAF8F3','#101010','#7A0019','#B08D57'],'SERIF',794,1123,['COVER','CONTENTS','SECTION OPENER','PRODUCT DETAIL','PRODUCT GRID','PRODUCT DETAIL','PRICE LIST','ORDER FORM','INDEX','BACK COVER']),
  p('cat-events','Course Catalog','CATALOG','A course and event catalog with schedule tiles, fees, instructor cards and a registration form.','Schools, workshops and festivals',['#FFF8EC','#1F2937','#0EA5A4','#F97316'],'SANS',816,1056,['COVER','CONTENTS','SECTION OPENER','PRODUCT GRID','PRODUCT DETAIL','PRICE LIST','ORDER FORM','INDEX','BACK COVER']),
  // ── END articles + catalogs block ──
  // ── MAGAZINE SYSTEMS block (12 titles) ──
  mag('mag-fashion-monthly','Vesper — Fashion Monthly','A fashion monthly built on a hairline Didone masthead, enormous crops, tight captions and a quiet three-column text system.','Fashion, beauty and style publishers',['#F3EFE8','#0B0A0B','#B3202A','#B8A47E'],'SERIF',804,1044),
  mag('mag-tech-review','Vector — Technology & Science Review','A grotesk-and-mono review of technology and science: numbered figures, labelled diagrams, data callouts and a twelve-column grid on a 12 px baseline.','Technology, science and engineering readers',['#F2F4F6','#0A1622','#FF4F1A','#1E63E9'],'SANS',816,1056),
  mag('mag-culture-quarterly','Lyceum — Culture & Arts Quarterly','A literary quarterly set in Cardo and Cormorant: generous margins, a marginal-notes column, framed plates, contents with leaders and review ratings.','Literary, arts and humanities readers',['#EFE8D8','#241B15','#7B2C2C','#5F705B'],'SERIF',720,960),
  mag('mag-sports-weekly','Overtime — Sports Weekly','A weekly sports title in condensed type: a tilted masthead, scoreboard contents, stat boxes, standings, recap tiles and angled action crops.','Sports fans and league media',['#F5F5F0','#0B1020','#F23A1B','#1747E8'],'DISPLAY',816,1056),
  mag('mag-food-travel','Table & Trail — Food & Travel','A warm food-and-travel title: arch cover, route-map contents, recipe card, itinerary spread, postcard colophon and handwritten notes.','Food writers, travellers and slow-living readers',['#F6EAD4','#2A1C12','#C4501F','#5C7A38'],'SERIF',804,1044),
  mag('mag-business-weekly','The Ledger — Business & Finance Weekly','A tabloid business weekly: italic Playfair masthead, ticker strip, newspaper front page, dense columns, charts, index tables and a back-page long view.','Business, finance and policy readers',['#FFF4E6','#16181B','#0F4C8A','#9B1239'],'SERIF',1056,1632),
  mag('mag-nightlife-zine','Basement Static — Music & Nightlife Zine','A zine-magazine for the live scene: stacked Anton masthead with pink overprint, tape, torn paper, ransom-note headlines, halftone, contact sheets and a gig-poster back cover.','Music, club and DIY-scene readers',['#E8E3D6','#0A0A0A','#FF2D8F','#C8FF00'],'DISPLAY',816,1056),
  mag('mag-home-design','Atrium — Home, Design & Architecture','An airy architecture and interiors magazine: small tracked masthead, caption-led pages, floor plans, material swatches and wide white margins.','Architecture, interiors and design readers',['#F1EEE8','#1E2220','#B07A5B','#7D8C84'],'SERIF',864,1056),
  mag('mag-literary-journal','Quire — Indie Literary Journal','A small-trim literary journal with no photographs: Gloock and Lora, poems laid out by line, fiction with a drop cap, a typographic broadside and a sewn-signature cover.','Poets, fiction writers and small presses',['#F5EFE2','#1D1A17','#8A3B2D','#6A6A55'],'SERIF',576,864),
  mag('mag-community-digest','Porch Light — Community, Faith & Local Digest','A friendly neighbourhood digest: rounded Baloo type, a lamp motif, month calendar, classifieds and business cards, speech-bubble Q&A and a tear-off notice board.','Neighbourhoods, congregations, schools and local groups',['#FFF5E2','#2B2745','#E0523F','#2A9A8E'],'PLAYFUL',816,1056),
  mag('mag-kids-family','Tumble — Kids & Family','A playful kids-and-family magazine: alphabet-block masthead, stepping-stone contents, big read-aloud type, word search, spot-the-difference and a cut-out paper hat.','Children aged 4–10 and the grown-ups who read with them',['#FFF7DC','#222A66','#FF5A5F','#00B2A3'],'PLAYFUL',816,1056),
  mag('mag-photojournal','Witness — Photojournalism & Documentary','A documentary photography quarterly: full-bleed pictures, a quiet Archivo masthead, dateline captions, a caption index and an ethics colophon on a dark ground.','Photojournalists, agencies and documentary readers',['#0F0F0E','#F1EEE7','#E23B24','#BDB6A6'],'SANS',912,1152),
  // ── END MAGAZINE SYSTEMS block ──
];

const uid=(p:string)=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`; const obj=(kind:TelaVectorObject['kind'],x:number,y:number,w:number,h:number,fill:string,label:string,extra:Partial<TelaVectorObject>={}):TelaVectorObject=>({id:uid(kind.toLowerCase()),kind,x,y,w,h,fill,stroke:'none',strokeWidth:0,rotation:0,opacity:1,objectLabel:label,...extra});
const txt=(x:number,y:number,w:number,h:number,text:string,size:number,color:string,weight=700,family='var(--font-sans,Inter),system-ui,sans-serif',label='Editable text')=>obj('TEXT',x,y,w,h,color,label,{text,fontSize:size,fontWeight:weight,fontFamily:family});
const photo=(x:number,y:number,w:number,h:number,ink:string,accent:string,label='Replace with photo'):TelaVectorObject[]=>[obj('RECT',x,y,w,h,ink,'Image well',{opacity:.12,stroke:accent,strokeWidth:2}),txt(x+18,y+h/2-12,w-36,28,label.toUpperCase(),12,ink,800,undefined,'Image instruction')];
function legacyPublicationPage(template:TelaPublicationTemplate,pageType:TelaPublicationPageType,pageIndex:number):TelaVectorObject[]{const {width:w,height:h}=template;const [paper,ink,accent,secondary]=template.palette;const margin=Math.round(Math.min(w,h)*.065);const serif=template.fontMood==='SERIF'?'Georgia,serif':template.fontMood==='PLAYFUL'?'Trebuchet MS,system-ui,sans-serif':'var(--font-display,Outfit),system-ui,sans-serif';const base=[obj('RECT',0,0,w,h,pageType==='COVER'||pageType==='FEATURE OPENER'||pageType==='FULL BLEED'?ink:paper,`${pageType} background`)];const fg=(pageType==='COVER'||pageType==='FEATURE OPENER'||pageType==='FULL BLEED')?'#FFFFFF':ink;
  if(pageType==='COMIC COVER')return [obj('RECT',0,0,w,h,ink,'Comic cover background'),...photo(0,0,w,h,fg,accent,'Cover art'),obj('RECT',0,0,w,h,'none','Comic cover trim',{stroke:accent,strokeWidth:18}),txt(margin,margin,w-margin*2,h*.2,template.name.toUpperCase(),Math.round(w*.105),'#FFFFFF',950,'Impact,Arial Black,sans-serif','Comic masthead'),txt(margin,h-margin-64,w*.55,46,'ISSUE 01  ·  $4.99',18,'#FFFFFF',900),obj('ELLIPSE',w-margin-105,h-margin-105,92,92,accent,'Issue badge'),txt(w-margin-94,h-margin-76,70,32,'#01',22,'#FFFFFF',950)];
  if(pageType==='CHARACTER SHEET')return [...base,txt(margin,margin,w-margin*2,60,'Character sheet',44,ink,900,serif),...Array.from({length:3},(_,i)=>[...photo(margin+i*(w-margin*2)/3,margin+100,(w-margin*2)/3-18,h*.42,ink,i%2?accent:secondary,'Character art'),txt(margin+i*(w-margin*2)/3,margin+h*.57,(w-margin*2)/3-18,36,['HERO','RIVAL','ALLY'][i],20,ink,900),txt(margin+i*(w-margin*2)/3,margin+h*.63,(w-margin*2)/3-18,100,'Want · fear · contradiction · visual signature',14,ink,500)]).flat()];
  if(pageType==='SPLASH PAGE')return [obj('RECT',0,0,w,h,ink,'Splash background'),...photo(0,0,w,h,'#FFFFFF',accent,'Full-page comic art'),txt(margin,margin,w*.45,56,'CHAPTER '+String(pageIndex).padStart(2,'0'),18,'#FFFFFF',900),txt(margin,h*.7,w*.75,150,'THE MOMENT EVERYTHING CHANGED',58,'#FFFFFF',950,'Impact,Arial Black,sans-serif','Splash title'),txt(margin,h-margin-70,w*.55,52,'Narration sets the stakes without stealing the image.',16,'#FFFFFF',650,'Georgia,serif','Narration caption')];
  if(pageType==='COMIC PAGE'||pageType==='MANGA PAGE'){const manga=pageType==='MANGA PAGE';const sets=pageIndex%3===0?[[0,0,100,34],[0,34,48,33],[48,34,52,33],[0,67,100,33]]:pageIndex%3===1?[[0,0,60,48],[60,0,40,28],[60,28,40,20],[0,48,42,52],[42,48,58,52]]:[[0,0,33,45],[33,0,67,45],[0,45,55,55],[55,45,45,55]];return [obj('RECT',0,0,w,h,manga?'#FFFFFF':paper,'Comic page ground'),...sets.flatMap((s,i)=>{const [px,py,pw,ph]=s;const x=margin+px/100*(w-margin*2),y=margin+py/100*(h-margin*2),ww=pw/100*(w-margin*2)-8,hh=ph/100*(h-margin*2)-8;return [...photo(x,y,ww,hh,ink,accent,`Panel ${i+1}`),...(i<2?[obj('ELLIPSE',x+ww*.42,y+18,ww*.48,Math.min(90,hh*.25),'#FFFFFF','Speech balloon',{stroke:ink,strokeWidth:2}),txt(x+ww*.47,y+34,ww*.38,45,'Dialogue goes here.',13,'#111111',650,'Arial,sans-serif','Balloon text')]:[]),...(i===sets.length-1?[txt(x+14,y+hh-48,ww*.7,34,manga?'ザッ  ·  SFX':'KRAK!',manga?30:34,manga?ink:accent,950,'Impact,Arial Black,sans-serif','Sound effect')]:[])]}),...(manga?[txt(w-margin-120,h-margin+6,120,20,'← READ RTL',11,ink,800)]:[])];}
  if(pageType==='WEBTOON EPISODE'){const gap=h*.055;return [obj('RECT',0,0,w,h,ink,'Webtoon episode ground'),...Array.from({length:5},(_,i)=>{const y=margin+i*(h-margin*2)/5+gap*.35;return [...photo(margin,y,w-margin*2,(h-margin*2)/5-gap,'#FFFFFF',i%2?accent:secondary,`Scroll panel ${i+1}`),...(i===2?[obj('ELLIPSE',w*.28,y-gap*.65,w*.44,70,'#FFFFFF','Webtoon dialogue',{stroke:'#111111',strokeWidth:2}),txt(w*.33,y-gap*.55,w*.34,38,'Wait… did you hear that?',14,'#111111',650)]:[])]}).flat()];}
  if(pageType==='COVER')return [...base,obj('RECT',margin,margin,10,h-margin*2,accent,'Cover spine'),txt(margin+38,margin,w-margin*2-38,36,template.category,14,fg,800),txt(margin+38,h*.28,w-margin*2-38,h*.28,template.name,Math.round(Math.min(w,h)*.09),fg,900,serif,'Publication title'),...photo(w*.58,h*.58,w*.34,h*.26,fg,accent,'Cover artwork'),txt(margin+38,h-margin-30,w*.45,28,'ISSUE 01 · A PLAJAH PUBLICATION',12,fg,700)];
  if(pageType==='CONTENTS')return [...base,txt(margin,margin,w-margin*2,60,'Contents',46,ink,850,serif),obj('RECT',margin,margin+76,w-margin*2,4,accent,'Contents rule'),...['Opening note','The feature','Conversation','Photo essay','Closing frame'].flatMap((name,i)=>[txt(margin,margin+130+i*92,80,42,String(i+1).padStart(2,'0'),28,accent,900),txt(margin+96,margin+130+i*92,w-margin*2-96,42,name,24,ink,700,serif),obj('RECT',margin+96,margin+178+i*92,w-margin*2-96,1,ink,'Contents divider',{opacity:.16})])];
  if(pageType==='EDITOR’S NOTE')return [...base,txt(margin,margin,w*.55,80,'From the editor',48,ink,850,serif),...photo(w*.68,margin,w*.22,h*.24,ink,accent,'Portrait'),txt(margin,margin+130,w*.55,h*.52,'Begin with a human note. Tell the reader why this issue exists, what you noticed while making it, and what you hope they carry away.',22,ink,450,'Georgia,serif'),txt(margin,h-margin-36,w*.5,30,'— Your name',17,accent,750,serif)];
  if(pageType==='SECTION OPENER'||pageType==='FEATURE OPENER')return [...base,txt(margin,margin,w-margin*2,30,'FEATURE  /  01',13,accent,850),txt(margin,h*.2,w*.62,h*.3,'A title with enough gravity to open the story',Math.round(Math.min(w,h)*.075),fg,900,serif),...photo(w*.66,h*.12,w*.28,h*.68,fg,accent,'Feature image'),txt(margin,h*.72,w*.52,90,'A precise deck that creates curiosity without giving the whole piece away.',21,fg,500,'Georgia,serif')];
  if(pageType==='INTERVIEW')return [...base,txt(margin,margin,w-margin*2,80,'In conversation',48,ink,850,serif),...photo(margin,margin+110,w*.42,h*.36,ink,accent,'Portrait'),txt(w*.52,margin+110,w*.4,h*.14,'“A pull quote gives the conversation a pulse.”',27,accent,750,serif),txt(margin,margin+h*.52,w-margin*2,h*.34,'Q  Start with the question that opens the subject.\n\nA  Let the answer breathe. Preserve voice and cadence.\n\nQ  Follow the interesting turn, not merely the prepared order.',19,ink,500,'Georgia,serif')];
  if(pageType==='PHOTO ESSAY'||pageType==='PHOTO GRID')return [...base,txt(margin,margin,w-margin*2,50,pageType==='PHOTO GRID'?'A constellation of moments':'Photo essay',40,ink,850,serif),...photo(margin,margin+88,w*.54,h*.48,ink,accent,'Primary photo'),...photo(w*.64,margin+88,w*.28,h*.22,ink,secondary,'Detail'),...photo(w*.64,margin+h*.34,w*.28,h*.29,ink,accent,'Detail'),txt(margin,h-margin-70,w*.82,55,'Caption · place · date · what deserves remembering',15,ink,500,'Georgia,serif')];
  if(pageType==='STORY SPREAD'||pageType==='QUIET SPREAD')return [...base,...photo(pageType==='QUIET SPREAD'?w*.26:margin,margin,pageType==='QUIET SPREAD'?w*.48:w-margin*2,pageType==='QUIET SPREAD'?h*.58:h*.68,ink,accent,'Illustration'),txt(pageType==='QUIET SPREAD'?w*.22:margin,h*.78,pageType==='QUIET SPREAD'?w*.56:w-margin*2,h*.14,pageType==='QUIET SPREAD'?'And for one small moment, everything became quiet.':'The story continues here, with language shaped for reading aloud.',pageType==='QUIET SPREAD'?28:31,ink,650,serif)];
  if(pageType==='ACTIVITY')return [...base,txt(margin,margin,w-margin*2,70,'A little invitation',44,ink,850,serif),txt(margin,margin+100,w*.55,80,'Draw, notice, imagine, or tell what happens next.',24,ink,550,serif),obj('RECT',margin,margin+230,w-margin*2,h-margin*2-230,'none','Activity space',{stroke:accent,strokeWidth:4}),...Array.from({length:7},(_,i)=>obj('ELLIPSE',margin+25+i*110,h-margin-55,22,22,i%2?accent:secondary,'Playful activity dot'))];
  if(pageType==='FULL BLEED')return [...base,...photo(0,0,w,h,fg,accent,'Full-bleed photograph'),txt(margin,h-margin-90,w*.62,70,'A place, a feeling, a frame.',28,'#FFFFFF',750,serif)];
  if(pageType==='CAPTIONED PHOTO')return [...base,...photo(margin,margin,w*.62,h-margin*2,ink,accent,'Primary photograph'),txt(w*.72,margin,w*.2,100,'Frame 03',14,accent,850),txt(w*.72,margin+130,w*.2,h*.45,'Give the photograph context without explaining away its mystery.',20,ink,500,serif),txt(w*.72,h-margin-50,w*.2,35,'Place · year',13,ink,700)];
  if(pageType==='TIMELINE')return [...base,txt(margin,margin,w-margin*2,60,'The journey',46,ink,850,serif),obj('RECT',margin,margin+160,w-margin*2,4,accent,'Timeline'),...Array.from({length:4},(_,i)=>[obj('ELLIPSE',margin+i*(w-margin*2)/3-9,margin+151,22,22,accent,'Milestone'),...photo(margin+i*(w-margin*2)/4,margin+220,(w-margin*2)/4-18,h*.35,ink,secondary,'Moment'),txt(margin+i*(w-margin*2)/4,margin+h*.62,(w-margin*2)/4-18,60,`0${i+1} · Milestone`,15,ink,750)]).flat()];
  if(pageType==='EMAIL HERO'||pageType==='EMAIL STORY')return [...base,txt(margin,margin,w-margin*2,24,'VIEW IN BROWSER  ·  PLAJAH',11,fg,700),txt(margin,margin+88,w-margin*2,190,template.name,66,fg,900,serif),...photo(margin,margin+320,w-margin*2,360,fg,accent,'Campaign image'),txt(margin,720,w-margin*2,100,template.description,23,fg,500,'Georgia,serif'),obj('RECT',margin,860,250,64,accent,'Call to action'),txt(margin+24,878,202,30,'TAKE THE NEXT STEP →',15,'#FFFFFF',850),txt(margin,1010,w-margin*2,170,'Add the supporting story, details, proof, or schedule here. Keep the invitation clear and the number of competing actions low.',19,fg,450,'Georgia,serif')];
  if(pageType==='BACK COVER')return [...base,txt(margin,h*.3,w-margin*2,120,template.name,54,fg,900,serif),obj('RECT',margin,h*.52,w-margin*2,3,accent,'Closing rule'),txt(margin,h*.58,w*.55,90,'Thank you for spending time with this story.',22,fg,500,'Georgia,serif'),txt(margin,h-margin-30,w-margin*2,24,'PLAJAH · MADE WITH TELA',11,fg,700)];
  return [...base,txt(margin,margin,w-margin*2,65,pageType,42,ink,850,serif),txt(margin,margin+105,w*.42,h*.7,'Begin the article with the strongest idea. Build a clear hierarchy with subheads, captions, evidence, and breathing room.',19,ink,450,'Georgia,serif'),...photo(w*.52,margin+105,w*.4,h*.42,ink,accent,'Article image'),txt(w*.52,h*.63,w*.4,h*.2,'A supporting passage or pull quote can change the rhythm of the page.',24,accent,750,serif)];
}

/** Hand-designed page when a designer exists for the template; legacy composer otherwise. */
export function instantiatePublicationPage(template:TelaPublicationTemplate,pageType:TelaPublicationPageType,pageIndex:number):TelaVectorObject[]{
  const designer=PUBLICATION_DESIGNS[template.id];
  if(!designer) return legacyPublicationPage(template,pageType,pageIndex);
  const [paper,ink,accent,secondary]=template.palette; const {width:W,height:H}=template;
  return designer({template,pageType,pageIndex,pageCount:template.pages.length,W,H,fr:frame(W,H,Math.round(Math.min(W,H)*.07)),paper,ink,accent,secondary,seed:[...template.id].reduce((a,c)=>a+c.charCodeAt(0),pageIndex*31+3)});
}
export const hasPublicationDesign=(id:string)=>!!PUBLICATION_DESIGNS[id];
