import type { TelaVectorObject } from '../types';
import { PUBLICATION_DESIGNS } from './tela/designs/publications';
import { frame } from './tela/templateKit';

export type TelaPublicationCategory='EMAIL BLAST'|'NEWSLETTER'|'MAGAZINE'|'CHILDREN’S BOOK'|'PHOTO BOOK'|'COMIC & MANGA';
export type TelaPublicationPageType='EMAIL HERO'|'EMAIL STORY'|'COVER'|'CONTENTS'|'EDITOR’S NOTE'|'SECTION OPENER'|'FEATURE OPENER'|'ARTICLE'|'INTERVIEW'|'PHOTO ESSAY'|'STORY SPREAD'|'QUIET SPREAD'|'ACTIVITY'|'FULL BLEED'|'PHOTO GRID'|'CAPTIONED PHOTO'|'TIMELINE'|'COMIC COVER'|'COMIC PAGE'|'MANGA PAGE'|'SPLASH PAGE'|'CHARACTER SHEET'|'WEBTOON EPISODE'|'BACK COVER';
export interface TelaPublicationTemplate {id:string;name:string;category:TelaPublicationCategory;description:string;audience:string;palette:[string,string,string,string];fontMood:'SERIF'|'SANS'|'PLAYFUL'|'DISPLAY';width:number;height:number;pages:TelaPublicationPageType[];}

const p=(id:string,name:string,category:TelaPublicationCategory,description:string,audience:string,palette:[string,string,string,string],fontMood:TelaPublicationTemplate['fontMood'],width:number,height:number,pages:TelaPublicationPageType[]):TelaPublicationTemplate=>({id,name,category,description,audience,palette,fontMood,width,height,pages});
const MAG:TelaPublicationPageType[]=['COVER','CONTENTS','EDITOR’S NOTE','SECTION OPENER','FEATURE OPENER','ARTICLE','ARTICLE','INTERVIEW','PHOTO ESSAY','BACK COVER'];
const STORY:TelaPublicationPageType[]=['COVER','STORY SPREAD','STORY SPREAD','QUIET SPREAD','STORY SPREAD','ACTIVITY','BACK COVER'];
const PHOTO:TelaPublicationPageType[]=['COVER','FULL BLEED','PHOTO GRID','CAPTIONED PHOTO','FULL BLEED','TIMELINE','PHOTO GRID','BACK COVER'];
const COMIC:TelaPublicationPageType[]=['COMIC COVER','CHARACTER SHEET','SPLASH PAGE','COMIC PAGE','COMIC PAGE','COMIC PAGE','BACK COVER'];
const MANGA:TelaPublicationPageType[]=['COMIC COVER','CHARACTER SHEET','MANGA PAGE','MANGA PAGE','SPLASH PAGE','MANGA PAGE','BACK COVER'];
export const TELA_PUBLICATION_TEMPLATES:TelaPublicationTemplate[]=[
  p('email-product','Product Drop','EMAIL BLAST','A focused launch email with a bold product hero, proof, and one decisive action.','Products, releases, and merch',['#0E0A14','#FFFFFF','#D40055','#FF8A00'],'SANS',800,1400,['EMAIL HERO']),
  p('email-event','Event Invitation','EMAIL BLAST','A cinematic invitation with date hierarchy, atmosphere, and RSVP.','Shows, premieres, and gatherings',['#150C23','#F7EEDC','#8C2CB7','#E2B45A'],'DISPLAY',800,1400,['EMAIL HERO']),
  p('email-editorial','Editorial Dispatch','EMAIL BLAST','A thoughtful letter-led campaign that reads like a small publication.','Essays, announcements, and community',['#F5F0E6','#211B2A','#7A3157','#B78B4A'],'SERIF',800,1400,['EMAIL STORY']),
  p('email-course','Course Launch','EMAIL BLAST','Curriculum, outcomes, teacher presence, and enrollment action.','Classes and workshops',['#F2FBFF','#173C54','#00A8BC','#FF8A00'],'SANS',800,1400,['EMAIL HERO']),
  p('email-nonprofit','Impact Appeal','EMAIL BLAST','Human story, evidence, impact figures, and a respectful contribution ask.','Causes and community organizations',['#F7F2E8','#243B33','#C9533F','#D4A94E'],'SERIF',800,1400,['EMAIL STORY']),
  p('email-digest','Weekly Digest','EMAIL BLAST','A scan-friendly collection of stories, links, and recommendations.','Recurring creator updates',['#10151D','#F7FAFC','#3667D6','#5ED3C6'],'SANS',800,1400,['EMAIL STORY']),
  p('news-community','Community Current','NEWSLETTER','Warm local reporting with recurring departments and practical notices.','Clubs, neighborhoods, and organizations',['#FFF4E4','#372447','#D85268','#1A8B88'],'SERIF',816,1056,['COVER','CONTENTS','EDITOR’S NOTE','ARTICLE','ARTICLE','BACK COVER']),
  p('news-creator','Creator Notes','NEWSLETTER','A personal editorial voice balanced with projects, links, and studio process.','Artists and independent creators',['#110B18','#F8F1FF','#B548C8','#FF8A00'],'DISPLAY',816,1056,['COVER','EDITOR’S NOTE','FEATURE OPENER','ARTICLE','PHOTO ESSAY','BACK COVER']),
  p('news-school','School Chronicle','NEWSLETTER','Clear sections for learning, student work, dates, and recognition.','Schools and learning communities',['#F5FAFF','#1D3557','#3977C9','#E6A92C'],'SANS',816,1056,['COVER','CONTENTS','ARTICLE','PHOTO GRID','ARTICLE','BACK COVER']),
  p('news-culture','Culture Letter','NEWSLETTER','An elegant reading experience for criticism, recommendations, and cultural notes.','Museums, books, film, and music',['#F0E8D9','#261D22','#8D2E3D','#A88952'],'SERIF',816,1056,['COVER','CONTENTS','FEATURE OPENER','ARTICLE','INTERVIEW','BACK COVER']),
  p('news-business','Field Report','NEWSLETTER','A confident professional briefing with signals, charts, and analysis.','Teams and professional communities',['#0D1B2A','#F4F7FA','#2E6EA6','#E07836'],'SANS',816,1056,['COVER','CONTENTS','EDITOR’S NOTE','ARTICLE','ARTICLE','BACK COVER']),
  p('news-faith','Gathered','NEWSLETTER','A contemplative community rhythm for reflection, service, and upcoming life together.','Faith communities',['#F4EEE2','#373047','#765A9B','#C08C4A'],'SERIF',816,1056,['COVER','EDITOR’S NOTE','ARTICLE','PHOTO ESSAY','ARTICLE','BACK COVER']),
  p('mag-culture','New Culture Review','MAGAZINE','Expressive culture journalism with large type, interviews, and visual essays.','Culture and criticism',['#121015','#F6F0E8','#D40055','#00A8BC'],'DISPLAY',816,1056,MAG),
  p('mag-fashion','Atelier Quarterly','MAGAZINE','High-fashion pacing with restraint, full-bleed imagery, and refined captions.','Fashion and beauty',['#F5F1E9','#19171A','#9A294A','#B9A46C'],'SERIF',816,1056,MAG),
  p('mag-music','Frequency','MAGAZINE','Energetic music editorial with sharp departments and poster-scale feature pages.','Music and nightlife',['#080A10','#F5F7FF','#7547FF','#FF4B3E'],'DISPLAY',816,1056,MAG),
  p('mag-travel','Elsewhere','MAGAZINE','Immersive travel narratives, maps, field notes, and generous photography.','Travel and place',['#EDE4D1','#213F43','#D1683E','#D7A93A'],'SERIF',816,1056,MAG),
  p('mag-science','Observable','MAGAZINE','Precise but inviting science features with diagrams, evidence, and explanatory pacing.','Science and discovery',['#071B29','#EAFBFF','#00A8BC','#F2B544'],'SANS',816,1056,MAG),
  p('mag-independent','Small Press','MAGAZINE','A tactile independent magazine with collage, essays, and artist portfolios.','Independent publishing',['#E9DDC6','#171717','#C62D39','#386B63'],'DISPLAY',816,1056,MAG),
  p('story-forest','The Lantern Forest','CHILDREN’S BOOK','A warm woodland story with roomy narration, gentle suspense, and luminous picture wells.','Ages 4–8',['#F3E8C8','#284B3C','#D96C43','#E2B94F'],'PLAYFUL',1024,768,STORY),
  p('story-space','Little Orbit','CHILDREN’S BOOK','A friendly space adventure with big shapes, wonder, and clear read-aloud rhythm.','Ages 3–7',['#111A46','#F7F2E8','#676BFF','#FFCE4A'],'PLAYFUL',1024,768,STORY),
  p('story-ocean','Below the Blue','CHILDREN’S BOOK','Layered underwater spreads with calm pacing and curious marine encounters.','Ages 4–8',['#DDF6F3','#145A6A','#00A8BC','#FF8A5B'],'PLAYFUL',1024,768,STORY),
  p('story-bedtime','The Moon’s Pocket','CHILDREN’S BOOK','A quiet bedtime book with soft night fields and intimate text placement.','Ages 2–6',['#171A3B','#F3EBD8','#8D72D8','#E7BC68'],'SERIF',1024,768,STORY),
  p('story-city','My Block Sings','CHILDREN’S BOOK','A lively neighborhood story with collage energy, signs, windows, and community voices.','Ages 4–9',['#FFF0D4','#303A72','#E34E5E','#1AA39A'],'PLAYFUL',1024,768,STORY),
  p('story-folktale','The Golden Thread','CHILDREN’S BOOK','A timeless folktale structure with ornamental frames and dramatic scene changes.','Ages 5–10',['#F0DFC0','#452C52','#A83C35','#D1A43D'],'SERIF',1024,768,STORY),
  p('photo-family','Family Archive','PHOTO BOOK','A warm chronological album mixing full images, small moments, and written memory.','Families and personal archives',['#F2E9D8','#332B28','#9B5B45','#BDA16B'],'SERIF',1024,768,PHOTO),
  p('photo-travel','Road & Horizon','PHOTO BOOK','Wide cinematic landscapes, field-note captions, and a journey timeline.','Travel photography',['#E9E1CF','#263B43','#C7673F','#D1A948'],'SANS',1024,768,PHOTO),
  p('photo-portfolio','Photographer’s Edit','PHOTO BOOK','Gallery-like sequencing with restrained typography and image-first pacing.','Photography portfolios',['#F7F7F4','#161616','#767676','#C1273D'],'SANS',1024,768,PHOTO),
  p('photo-wedding','Vows & Light','PHOTO BOOK','Elegant event storytelling with quiet details, portraits, and generous spreads.','Weddings and celebrations',['#F7F0EA','#47363D','#B77A83','#C4A56B'],'SERIF',1024,768,PHOTO),
  p('photo-yearbook','The Year We Made','PHOTO BOOK','A spirited year-in-review album with grids, milestones, and candid energy.','Teams, classes, and communities',['#F6EAD1','#27345B','#E34D59','#2FA89A'],'PLAYFUL',1024,768,PHOTO),
  p('photo-minimal','Quiet Frames','PHOTO BOOK','Minimal fine-art sequencing that gives every photograph its own atmosphere.','Fine-art and monochrome work',['#F4F3EF','#171717','#A6A29A','#6B6B6B'],'SERIF',1024,768,PHOTO),
  p('comic-superhero','Velocity Comics','COMIC & MANGA','Dynamic hero pacing with splash reveals, diagonal action panels, captions, and impact lettering.','Superhero and action comics',['#F6E33B','#10152B','#E32935','#2F67C7'],'DISPLAY',816,1056,COMIC),
  p('comic-noir','Midnight Casefiles','COMIC & MANGA','High-contrast noir pages with cinematic wides, inset clues, and restrained narration.','Mystery, crime, and noir',['#EEE9DC','#111111','#8A1F2D','#58616A'],'SERIF',816,1056,COMIC),
  p('comic-kids','Bright Side Comics','COMIC & MANGA','Open friendly grids, rounded panels, expressive balloons, and generous visual clarity.','Children and all-ages comics',['#FFF4C7','#27345F','#F05A5A','#28AFA1'],'PLAYFUL',816,1056,COMIC),
  p('comic-anthology','Panel Stories','COMIC & MANGA','An editorial anthology system for short comics, creator notes, and varied page rhythms.','Anthologies and literary comics',['#F2E9DA','#282129','#A73C4A','#39756D'],'SERIF',816,1056,['COMIC COVER','CONTENTS','COMIC PAGE','SPLASH PAGE','COMIC PAGE','EDITOR’S NOTE','BACK COVER']),
  p('manga-shonen','Rising Impact','COMIC & MANGA','Right-to-left action pacing with speed-line splashes and compressed reaction panels.','Action and adventure manga',['#FFFFFF','#090909','#E2232E','#808080'],'DISPLAY',816,1152,MANGA),
  p('manga-shojo','Petals & Promises','COMIC & MANGA','Airy emotional pacing, borderless moments, portrait insets, and delicate transitions.','Romance and character drama manga',['#FFF9FC','#241D2A','#D85E9D','#9B86C7'],'SERIF',816,1152,MANGA),
  p('manga-seinen','Afterimage','COMIC & MANGA','Measured cinematic layouts with silence, environmental wides, and psychological close-ups.','Mature drama and suspense manga',['#F5F5F2','#111111','#535353','#9B1E28'],'SANS',816,1152,MANGA),
  p('comic-webtoon','Infinite Scroll','COMIC & MANGA','Vertical episode pacing with breath between beats, reveal spacing, and mobile-first dialogue.','Webtoons and vertical comics',['#11131B','#F8F8FC','#7A55FF','#FF5C7A'],'SANS',800,2400,['COMIC COVER','WEBTOON EPISODE','WEBTOON EPISODE','BACK COVER']),
];

const uid=(p:string)=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`; const obj=(kind:TelaVectorObject['kind'],x:number,y:number,w:number,h:number,fill:string,label:string,extra:Partial<TelaVectorObject>={}):TelaVectorObject=>({id:uid(kind.toLowerCase()),kind,x,y,w,h,fill,stroke:'none',strokeWidth:0,rotation:0,opacity:1,objectLabel:label,...extra});
const txt=(x:number,y:number,w:number,h:number,text:string,size:number,color:string,weight=700,family='var(--font-sans,Inter),system-ui,sans-serif',label='Editable text')=>obj('TEXT',x,y,w,h,color,label,{text,fontSize:size,fontWeight:weight,fontFamily:family});
const photo=(x:number,y:number,w:number,h:number,ink:string,accent:string,label='Replace with photo'):TelaVectorObject[]=>[obj('RECT',x,y,w,h,ink,'Image well',{opacity:.12,stroke:accent,strokeWidth:2}),txt(x+18,y+h/2-12,w-36,28,label.toUpperCase(),12,ink,800,undefined,'Image instruction')];
function legacyPublicationPage(template:TelaPublicationTemplate,pageType:TelaPublicationPageType,pageIndex:number):TelaVectorObject[]{const {width:w,height:h}=template;const [paper,ink,accent,secondary]=template.palette;const margin=Math.round(Math.min(w,h)*.065);const serif=template.fontMood==='SERIF'?'Georgia,serif':template.fontMood==='PLAYFUL'?'Trebuchet MS,system-ui,sans-serif':'var(--font-display,Outfit),system-ui,sans-serif';const base=[obj('RECT',0,0,w,h,pageType==='COVER'||pageType==='FEATURE OPENER'||pageType==='FULL BLEED'?ink:paper,`${pageType} background`)];const fg=(pageType==='COVER'||pageType==='FEATURE OPENER'||pageType==='FULL BLEED')?'#FFFFFF':ink;
  if(pageType==='COMIC COVER')return [obj('RECT',0,0,w,h,ink,'Comic cover background'),...photo(0,0,w,h,fg,accent,'Cover art'),obj('RECT',0,0,w,h,'none','Comic cover trim',{stroke:accent,strokeWidth:18}),txt(margin,margin,w-margin*2,h*.2,template.name.toUpperCase(),Math.round(w*.105),'#FFFFFF',950,'Impact,Arial Black,sans-serif','Comic masthead'),txt(margin,h-margin-64,w*.55,46,'ISSUE 01  ·  $4.99',18,'#FFFFFF',900),obj('ELLIPSE',w-margin-105,h-margin-105,92,92,accent,'Issue badge'),txt(w-margin-94,h-margin-76,70,32,'#01',22,'#FFFFFF',950)];
  if(pageType==='CHARACTER SHEET')return [...base,txt(margin,margin,w-margin*2,60,'Character sheet',44,ink,900,serif),...Array.from({length:3},(_,i)=>[...photo(margin+i*(w-margin*2)/3,margin+100,(w-margin*2)/3-18,h*.42,ink,i%2?accent:secondary,'Character art'),txt(margin+i*(w-margin*2)/3,margin+h*.57,(w-margin*2)/3-18,36,['HERO','RIVAL','ALLY'][i],20,ink,900),txt(margin+i*(w-margin*2)/3,margin+h*.63,(w-margin*2)/3-18,100,'Want · fear · contradiction · visual signature',14,ink,500)]).flat()];
  if(pageType==='SPLASH PAGE')return [obj('RECT',0,0,w,h,ink,'Splash background'),...photo(0,0,w,h,'#FFFFFF',accent,'Full-page comic art'),txt(margin,margin,w*.45,56,'CHAPTER '+String(pageIndex).padStart(2,'0'),18,'#FFFFFF',900),txt(margin,h*.7,w*.75,150,'THE MOMENT EVERYTHING CHANGED',58,'#FFFFFF',950,'Impact,Arial Black,sans-serif','Splash title'),txt(margin,h-margin-70,w*.55,52,'Narration sets the stakes without stealing the image.',16,'#FFFFFF',650,'Georgia,serif','Narration caption')];
  if(pageType==='COMIC PAGE'||pageType==='MANGA PAGE'){const manga=pageType==='MANGA PAGE';const sets=pageIndex%3===0?[[0,0,100,34],[0,34,48,33],[48,34,52,33],[0,67,100,33]]:pageIndex%3===1?[[0,0,60,48],[60,0,40,28],[60,28,40,20],[0,48,42,52],[42,48,58,52]]:[[0,0,33,45],[33,0,67,45],[0,45,55,55],[55,45,45,55]];return [obj('RECT',0,0,w,h,manga?'#FFFFFF':paper,'Comic page ground'),...sets.flatMap((s,i)=>{const [px,py,pw,ph]=s;const x=margin+px/100*(w-margin*2),y=margin+py/100*(h-margin*2),ww=pw/100*(w-margin*2)-8,hh=ph/100*(h-margin*2)-8;return [...photo(x,y,ww,hh,ink,accent,`Panel ${i+1}`),...(i<2?[obj('ELLIPSE',x+ww*.42,y+18,ww*.48,Math.min(90,hh*.25),'#FFFFFF','Speech balloon',{stroke:ink,strokeWidth:2}),txt(x+ww*.47,y+34,ww*.38,45,'Dialogue goes here.',13,'#111111',650,'Arial,sans-serif','Balloon text')]:[]),...(i===sets.length-1?[txt(x+14,y+hh-48,ww*.7,34,manga?'ザッ  ·  SFX':'KRAK!',manga?30:34,manga?ink:accent,950,'Impact,Arial Black,sans-serif','Sound effect')]:[])]}),...(manga?[txt(w-margin-120,h-margin+6,120,20,'← READ RTL',11,ink,800)]:[])];}
  if(pageType==='WEBTOON EPISODE'){const gap=h*.055;return [obj('RECT',0,0,w,h,ink,'Webtoon episode ground'),...Array.from({length:5},(_,i)=>{const y=margin+i*(h-margin*2)/5+gap*.35;return [...photo(margin,y,w-margin*2,(h-margin*2)/5-gap,'#FFFFFF',i%2?accent:secondary,`Scroll panel ${i+1}`),...(i===2?[obj('ELLIPSE',w*.28,y-gap*.65,w*.44,70,'#FFFFFF','Webtoon dialogue',{stroke:'#111111',strokeWidth:2}),txt(w*.33,y-gap*.55,w*.34,38,'Wait… did you hear that?',14,'#111111',650)]:[])]}).flat()];}
  if(pageType==='COVER')return [...base,obj('RECT',margin,margin,10,h-margin*2,accent,'Cover spine'),txt(margin+38,margin,w-margin*2-38,36,template.category,14,fg,800),txt(margin+38,h*.28,w-margin*2-38,h*.28,template.name,Math.round(Math.min(w,h)*.09),fg,900,serif,'Publication title'),...photo(w*.58,h*.58,w*.34,h*.26,fg,accent,'Cover artwork'),txt(margin+38,h-margin-30,w*.45,28,'ISSUE 01 · A PLAJAH PUBLICATION',12,fg,700)];
  if(pageType==='CONTENTS')return [...base,txt(margin,margin,w-margin*2,60,'Contents',46,ink,850,serif),obj('RECT',margin,margin+76,w-margin*2,4,accent,'Contents rule'),...['Opening note','The feature','Conversation','Photo essay','Closing frame'].flatMap((name,i)=>[txt(margin,margin+130+i*92,80,42,String(i+1).padStart(2,'0'),28,accent,900),txt(margin+96,margin+130+i*92,w-margin*2-96,42,name,24,ink,700,serif),obj('RECT',margin+96,margin+178+i*92,w-margin*2-96,1,ink,'Contents divider',{opacity:.16})])];
  if(pageType==='EDITOR’S NOTE')return [...base,txt(margin,margin,w*.55,80,'From the editor',48,ink,850,serif),...photo(w*.68,margin,w*.22,h*.24,ink,accent,'Portrait'),txt(margin,margin+130,w*.55,h*.52,'Begin with a human note. Tell the reader why this issue exists, what you noticed while making it, and what you hope they carry away.',22,ink,450,'Georgia,serif'),txt(margin,h-margin-36,w*.5,30,'— Your name',17,accent,750,serif)];
  if(pageType==='SECTION OPENER'||pageType==='FEATURE OPENER')return [...base,txt(margin,margin,w-margin*2,30,'FEATURE  /  01',13,accent,850),txt(margin,h*.2,w*.62,h*.3,'A title with enough gravity to open the story',Math.round(Math.min(w,h)*.075),fg,900,serif),...photo(w*.66,h*.12,w*.28,h*.68,fg,accent,'Feature image'),txt(margin,h*.72,w*.52,90,'A precise deck that creates curiosity without giving the whole piece away.',21,fg,500,'Georgia,serif')];
  if(pageType==='INTERVIEW')return [...base,txt(margin,margin,w-margin*2,80,'In conversation',48,ink,850,serif),...photo(margin,margin+110,w*.42,h*.36,ink,accent,'Portrait'),txt(w*.52,margin+110,w*.4,h*.14,'“A pull quote gives the conversation a pulse.”',27,accent,750,serif),txt(margin,margin+h*.52,w-margin*2,h*.34,'Q  Start with the question that opens the subject.\n\nA  Let the answer breathe. Preserve voice and cadence.\n\nQ  Follow the interesting turn, not merely the prepared order.',19,ink,500,'Georgia,serif')];
  if(pageType==='PHOTO ESSAY'||pageType==='PHOTO GRID')return [...base,txt(margin,margin,w-margin*2,50,pageType==='PHOTO GRID'?'A constellation of moments':'Photo essay',40,ink,850,serif),...photo(margin,margin+88,w*.54,h*.48,ink,accent,'Primary photo'),...photo(w*.64,margin+88,w*.28,h*.22,ink,secondary,'Detail'),...photo(w*.64,margin+h*.34,w*.28,h*.29,ink,accent,'Detail'),txt(margin,h-margin-70,w*.82,55,'Caption · place · date · what deserves remembering',15,ink,500,'Georgia,serif')];
  if(pageType==='STORY SPREAD'||pageType==='QUIET SPREAD')return [...base,...photo(pageType==='QUIET SPREAD'?w*.26:margin,margin,pageType==='QUIET SPREAD'?w*.48:w-margin*2,pageType==='QUIET SPREAD'?h*.58:h*.68,ink,accent,'Illustration'),txt(pageType==='QUIET SPREAD'?w*.22:margin,h*.78,pageType==='QUIET SPREAD'?w*.56:w-margin*2,h*.14,pageType==='QUIET SPREAD'?'And for one small moment, everything became quiet.':'The story continues here, with language shaped for reading aloud.',pageType==='QUIET SPREAD'?28:31,ink,650,serif)];
  if(pageType==='ACTIVITY')return [...base,txt(margin,margin,w-margin*2,70,'A little invitation',44,ink,850,serif),txt(margin,margin+100,w*.55,80,'Draw, notice, imagine, or tell what happens next.',24,ink,550,serif),obj('RECT',margin,margin+230,w-margin*2,h-margin*2-230,'none','Activity space',{stroke:accent,strokeWidth:4}),...Array.from({length:7},(_,i)=>obj('ELLIPSE',margin+25+i*110,h-margin-55,22,22,i%2?accent:secondary,'Playful activity dot'))];
  if(pageType==='FULL BLEED')return [...base,...photo(0,0,w,h,fg,accent,'Full-bleed photograph'),txt(margin,h-margin-90,w*.62,70,'A place, a feeling, a frame.',28,'#FFFFFF',750,serif)];
  if(pageType==='CAPTIONED PHOTO')return [...base,...photo(margin,margin,w*.62,h-margin*2,ink,accent,'Primary photograph'),txt(w*.72,margin,w*.2,100,'Frame 03',14,accent,850),txt(w*.72,margin+130,w*.2,h*.45,'Give the photograph context without explaining away its mystery.',20,ink,500,serif),txt(w*.72,h-margin-50,w*.2,35,'Place · year',13,ink,700)];
  if(pageType==='TIMELINE')return [...base,txt(margin,margin,w-margin*2,60,'The journey',46,ink,850,serif),obj('RECT',margin,margin+160,w-margin*2,4,accent,'Timeline'),...Array.from({length:4},(_,i)=>[obj('ELLIPSE',margin+i*(w-margin*2)/3-9,margin+151,22,22,accent,'Milestone'),...photo(margin+i*(w-margin*2)/4,margin+220,(w-margin*2)/4-18,h*.35,ink,secondary,'Moment'),txt(margin+i*(w-margin*2)/4,margin+h*.62,(w-margin*2)/4-18,60,`0${i+1} · Milestone`,15,ink,750)]).flat()];
  if(pageType==='EMAIL HERO'||pageType==='EMAIL STORY')return [...base,txt(margin,margin,w-margin*2,24,'VIEW IN BROWSER  ·  PLAJAH',11,fg,700),txt(margin,margin+88,w-margin*2,190,template.name,66,fg,900,serif),...photo(margin,margin+320,w-margin*2,360,fg,accent,'Campaign image'),txt(margin,720,w-margin*2,100,template.description,23,fg,500,'Georgia,serif'),obj('RECT',margin,860,250,64,accent,'Call to action'),txt(margin+24,878,202,30,'TAKE THE NEXT STEP →',15,'#FFFFFF',850),txt(margin,1010,w-margin*2,170,'Add the supporting story, details, proof, or schedule here. Keep the invitation clear and the number of competing actions low.',19,fg,450,'Georgia,serif')];
  if(pageType==='BACK COVER')return [...base,txt(margin,h*.3,w-margin*2,120,template.name,54,fg,900,serif),obj('RECT',margin,h*.52,w-margin*2,3,accent,'Closing rule'),txt(margin,h*.58,w*.55,90,'Thank you for spending time with this story.',22,fg,500,'Georgia,serif'),txt(margin,h-margin-30,w-margin*2,24,'PLAJAH · MADE WITH TELA',11,fg,700)];
  return [...base,txt(margin,margin,w-margin*2,65,pageType,42,ink,850,serif),txt(margin,margin+105,w*.42,h*.7,'Begin the article with the strongest idea. Build a clear hierarchy with subheads, captions, evidence, and breathing room.',19,ink,450,'Georgia,serif'),...photo(w*.52,margin+105,w*.4,h*.42,ink,accent,'Article image'),txt(w*.52,h*.63,w*.4,h*.2,'A supporting passage or pull quote can change the rhythm of the page.',24,accent,750,serif)];
}

/** Hand-designed page when a designer exists for the template; legacy composer otherwise. */
export function instantiatePublicationPage(template:TelaPublicationTemplate,pageType:TelaPublicationPageType,pageIndex:number):TelaVectorObject[]{
  const designer=PUBLICATION_DESIGNS[template.id];
  if(!designer) return legacyPublicationPage(template,pageType,pageIndex);
  const [paper,ink,accent,secondary]=template.palette; const {width:W,height:H}=template;
  return designer({template,pageType,pageIndex,pageCount:template.pages.length,W,H,fr:frame(W,H,Math.round(Math.min(W,H)*.07)),paper,ink,accent,secondary,seed:[...template.id].reduce((a,c)=>a+c.charCodeAt(0),pageIndex*31+3)});
}
export const hasPublicationDesign=(id:string)=>!!PUBLICATION_DESIGNS[id];
