// Phase 1 geometric, optical and procedural distortion tools.
export const PHASE1_DISTORT_EFFECTS: any[] = [
  {
    id: 'turbulentdisplace', name: 'Turbulent Displace', category: 'distort', version: 1,
    summary: 'Layered procedural displacement with independent scale, evolution, complexity and directional bias.',
    params: [{ key: 'amount', label: 'Amount', min: 0, max: 120, default: 18, step: .5 }, { key: 'scale', label: 'Scale', min: .2, max: 15, default: 3, step: .05 }, { key: 'complexity', label: 'Complexity', min: 0, max: 1, default: .58, step: .01 }, { key: 'evolution', label: 'Evolution', min: -3, max: 3, default: .3, step: .02 }, { key: 'direction', label: 'Direction', min: -180, max: 180, default: 0, step: 1 }, { key: 'bias', label: 'Directional Bias', min: 0, max: 1, default: .1, step: .01 }],
    presets: [{ id: 'organic', name: 'Organic Surface', description: 'Slow natural material deformation.', params: { amount: 16, scale: 2.4, complexity: .68, evolution: .18, direction: 0, bias: .08 } }, { id: 'flag', name: 'Fabric Wave', description: 'Directional flowing cloth-like motion.', params: { amount: 24, scale: 4.2, complexity: .48, evolution: .65, direction: 0, bias: .76 } }, { id: 'dream', name: 'Dream Melt', description: 'Broad surreal evolving displacement.', params: { amount: 52, scale: 1.2, complexity: .82, evolution: .4, direction: -30, bias: .28 } }],
    glsl: `float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5);} float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+1.0),f.x),f.y);} vec4 fx(vec2 uv){vec2 p=uv*P1+uTime*P3;float a=n(p)*6.283+n(p*2.03)*P2*3.14;vec2 organic=vec2(cos(a),sin(a));float da=radians(P4);vec2 dir=vec2(cos(da),sin(da));vec2 d=mix(organic,dir,P5)*P0/uResolution;return inp(uv+d);}`,
  },
  {
    id: 'ripplewave', name: 'Ripple & Wave', category: 'distort', version: 1,
    summary: 'Radial ripples, directional waves and expanding shockwaves with damping.',
    params: [{ key: 'amount', label: 'Amount', min: 0, max: 80, default: 14, step: .5 }, { key: 'frequency', label: 'Frequency', min: 1, max: 40, default: 12, step: .1 }, { key: 'phase', label: 'Phase', min: -6.28, max: 6.28, default: 0, step: .02 }, { key: 'centerX', label: 'Center X', min: 0, max: 1, default: .5, step: .005 }, { key: 'centerY', label: 'Center Y', min: 0, max: 1, default: .5, step: .005 }, { key: 'radial', label: 'Radial', min: 0, max: 1, default: 1, step: 1 }, { key: 'damping', label: 'Damping', min: 0, max: 1, default: .38, step: .01 }],
    presets: [{ id: 'water-drop', name: 'Water Drop', description: 'Gentle expanding circular water ripple.', params: { amount: 10, frequency: 16, phase: 0, centerX: .5, centerY: .5, radial: 1, damping: .62 } }, { id: 'shockwave', name: 'Shockwave', description: 'Strong cinematic impact ring.', params: { amount: 48, frequency: 8, phase: -1.2, centerX: .5, centerY: .5, radial: 1, damping: .28 } }, { id: 'heat-wave', name: 'Wave Band', description: 'Directional rolling refraction.', params: { amount: 18, frequency: 22, phase: 0, centerX: .5, centerY: .5, radial: 0, damping: .12 } }],
    glsl: `vec4 fx(vec2 uv){vec2 c=vec2(P3,P4),v=uv-c;float r=length(v);float coord=mix(uv.y,r,step(.5,P5));float wave=sin(coord*P1*6.283+P2+uTime*2.0);float damp=mix(1.0,exp(-r*5.0),P6);vec2 dir=mix(vec2(1,0),normalize(v+1e-5),step(.5,P5));return inp(uv+dir*wave*damp*P0/uResolution);}`,
  },
  {
    id: 'cornerpin', name: 'Corner Pin', category: 'distort', version: 1,
    summary: 'Four-corner perspective placement for screen inserts, signs and planar composites.',
    params: [{ key: 'tlX', label: 'Top Left X', min: -.5, max: .5, default: 0, step: .005 }, { key: 'tlY', label: 'Top Left Y', min: -.5, max: .5, default: 0, step: .005 }, { key: 'trX', label: 'Top Right X', min: -.5, max: .5, default: 0, step: .005 }, { key: 'trY', label: 'Top Right Y', min: -.5, max: .5, default: 0, step: .005 }, { key: 'blX', label: 'Bottom Left X', min: -.5, max: .5, default: 0, step: .005 }, { key: 'blY', label: 'Bottom Left Y', min: -.5, max: .5, default: 0, step: .005 }, { key: 'brX', label: 'Bottom Right X', min: -.5, max: .5, default: 0, step: .005 }, { key: 'brY', label: 'Bottom Right Y', min: -.5, max: .5, default: 0, step: .005 }],
    presets: [{ id: 'left-wall', name: 'Left Wall', description: 'Perspective placement on a receding left wall.', params: { tlX: .08, tlY: .08, trX: -.16, trY: -.02, blX: .08, blY: -.08, brX: -.16, brY: .02 } }, { id: 'right-wall', name: 'Right Wall', description: 'Perspective placement on a receding right wall.', params: { tlX: .16, tlY: -.02, trX: -.08, trY: .08, blX: .16, blY: .02, brX: -.08, brY: -.08 } }, { id: 'floor', name: 'Floor Plane', description: 'Trapezoidal floor/surface placement.', params: { tlX: .18, tlY: .18, trX: -.18, trY: .18, blX: -.08, blY: -.08, brX: .08, brY: -.08 } }],
    glsl: `vec4 fx(vec2 uv){vec2 top=mix(vec2(P0,P1),vec2(P2,P3),uv.x);vec2 bot=mix(vec2(P4,P5),vec2(P6,P7),uv.x);vec2 offset=mix(top,bot,uv.y);return inp(uv-offset);}`,
  },
  {
    id: 'meshwarp', name: 'Mesh Warp', category: 'distort', version: 1,
    summary: 'Smooth localized deformation with center, radius, pull, twist and falloff controls.',
    params: [{ key: 'centerX', label: 'Center X', min: 0, max: 1, default: .5, step: .005 }, { key: 'centerY', label: 'Center Y', min: 0, max: 1, default: .5, step: .005 }, { key: 'radius', label: 'Radius', min: .01, max: 1, default: .32, step: .01 }, { key: 'pullX', label: 'Pull X', min: -.5, max: .5, default: 0, step: .005 }, { key: 'pullY', label: 'Pull Y', min: -.5, max: .5, default: 0, step: .005 }, { key: 'twist', label: 'Twist', min: -3.14, max: 3.14, default: 0, step: .01 }, { key: 'falloff', label: 'Falloff', min: .2, max: 4, default: 1.5, step: .02 }],
    presets: [{ id: 'gentle-pull', name: 'Gentle Pull', description: 'Localized natural feature adjustment.', params: { centerX: .5, centerY: .5, radius: .28, pullX: .08, pullY: 0, twist: 0, falloff: 1.8 } }, { id: 'swirl', name: 'Soft Swirl', description: 'Smooth central spiral deformation.', params: { centerX: .5, centerY: .5, radius: .48, pullX: 0, pullY: 0, twist: 1.4, falloff: 1.3 } }, { id: 'stretch', name: 'Elastic Stretch', description: 'Broad directional elastic warp.', params: { centerX: .45, centerY: .5, radius: .62, pullX: .28, pullY: -.04, twist: .12, falloff: .8 } }],
    glsl: `vec4 fx(vec2 uv){vec2 c=vec2(P0,P1),d=uv-c;float r=length(d);float w=pow(max(0.0,1.0-r/P2),P6);float a=-P5*w,cs=cos(a),sn=sin(a);vec2 q=mat2(cs,-sn,sn,cs)*d-vec2(P3,P4)*w;return inp(c+q);}`,
  },
  {
    id: 'bulgepinch', name: 'Bulge & Pinch', category: 'distort', version: 1,
    summary: 'High-quality radial bulge, pinch and fisheye with protected outer geometry.',
    params: [{ key: 'amount', label: 'Amount', min: -1, max: 1, default: .25, step: .01 }, { key: 'radius', label: 'Radius', min: .01, max: 1, default: .42, step: .01 }, { key: 'centerX', label: 'Center X', min: 0, max: 1, default: .5, step: .005 }, { key: 'centerY', label: 'Center Y', min: 0, max: 1, default: .5, step: .005 }, { key: 'falloff', label: 'Falloff', min: .2, max: 4, default: 1.4, step: .02 }],
    presets: [{ id: 'subtle-bulge', name: 'Subtle Bulge', description: 'Gentle optical center emphasis.', params: { amount: .18, radius: .52, centerX: .5, centerY: .5, falloff: 1.8 } }, { id: 'fisheye', name: 'Fisheye', description: 'Strong wide-angle barrel character.', params: { amount: .72, radius: .78, centerX: .5, centerY: .5, falloff: .72 } }, { id: 'pinch', name: 'Pinch Tunnel', description: 'Centered inward tunnel deformation.', params: { amount: -.68, radius: .58, centerX: .5, centerY: .5, falloff: 1.1 } }],
    glsl: `vec4 fx(vec2 uv){vec2 c=vec2(P2,P3),d=uv-c;float r=length(d);float w=pow(max(0.0,1.0-r/P1),P4);float scale=1.0-P0*w*.72;return inp(c+d*scale);}`,
  },
  {
    id: 'polarwarp', name: 'Polar Warp', category: 'distort', version: 1,
    summary: 'Rectangular-to-polar conversion, tunnel wrapping and seamless panorama transformations.',
    params: [{ key: 'amount', label: 'Polar Amount', min: 0, max: 1, default: 1, step: .01 }, { key: 'rotation', label: 'Rotation', min: -180, max: 180, default: 0, step: 1 }, { key: 'radius', label: 'Radius', min: .1, max: 2, default: 1, step: .01 }, { key: 'centerX', label: 'Center X', min: 0, max: 1, default: .5, step: .005 }, { key: 'centerY', label: 'Center Y', min: 0, max: 1, default: .5, step: .005 }, { key: 'invert', label: 'Invert', min: 0, max: 1, default: 0, step: 1 }],
    presets: [{ id: 'tiny-planet', name: 'Tiny Planet', description: 'Wraps a panorama into a circular planet.', params: { amount: 1, rotation: 0, radius: 1, centerX: .5, centerY: .5, invert: 0 } }, { id: 'tunnel', name: 'Infinite Tunnel', description: 'Inverted polar tunnel mapping.', params: { amount: 1, rotation: 90, radius: .72, centerX: .5, centerY: .5, invert: 1 } }, { id: 'polar-blend', name: 'Polar Blend', description: 'Half-polar surreal geometry.', params: { amount: .5, rotation: 30, radius: 1.2, centerX: .5, centerY: .5, invert: 0 } }],
    glsl: `vec4 fx(vec2 uv){vec2 p=uv-vec2(P3,P4);float r=length(p)/P2,a=atan(p.y,p.x)/6.283185+.5+P1/360.0;vec2 polar=vec2(a,mix(r,1.0-r,step(.5,P5)));return inp(mix(uv,polar,P0));}`,
  },
  {
    id: 'rollingrepair', name: 'Rolling Shutter Repair', category: 'distort', version: 1,
    summary: 'Corrects skew and wobble caused by rolling-shutter readout.',
    params: [{ key: 'skew', label: 'Skew', min: -.25, max: .25, default: 0, step: .001 }, { key: 'wobble', label: 'Wobble', min: 0, max: .1, default: 0, step: .001 }, { key: 'frequency', label: 'Frequency', min: .2, max: 12, default: 2, step: .05 }, { key: 'phase', label: 'Phase', min: -3.14, max: 3.14, default: 0, step: .01 }, { key: 'vertical', label: 'Vertical Readout', min: 0, max: 1, default: 1, step: 1 }],
    presets: [{ id: 'phone-pan', name: 'Phone Pan Repair', description: 'Corrects common horizontal pan skew.', params: { skew: -.045, wobble: .004, frequency: 2, phase: 0, vertical: 1 } }, { id: 'drone-jello', name: 'Drone Jello Repair', description: 'Counteracts repeating vibration wobble.', params: { skew: 0, wobble: .018, frequency: 7.5, phase: 0, vertical: 1 } }, { id: 'vertical-scan', name: 'Vertical Scan Repair', description: 'Correction for horizontal sensor readout.', params: { skew: .028, wobble: .006, frequency: 3, phase: .4, vertical: 0 } }],
    glsl: `vec4 fx(vec2 uv){float scan=mix(uv.x,uv.y,step(.5,P4));float off=P0*(scan-.5)+sin(scan*P2*6.283+P3+uTime)*P1;vec2 d=mix(vec2(0,off),vec2(off,0),step(.5,P4));return inp(uv+d);}`,
  },
  {
    id: 'perspectivewarp', name: 'Perspective Warp', category: 'distort', version: 1,
    summary: 'Interactive yaw, pitch, roll and depth perspective for screen and graphic placement.',
    params: [{ key: 'yaw', label: 'Yaw', min: -75, max: 75, default: 0, step: .5 }, { key: 'pitch', label: 'Pitch', min: -75, max: 75, default: 0, step: .5 }, { key: 'roll', label: 'Roll', min: -180, max: 180, default: 0, step: 1 }, { key: 'depth', label: 'Depth', min: .2, max: 3, default: 1, step: .01 }, { key: 'centerX', label: 'Center X', min: 0, max: 1, default: .5, step: .005 }, { key: 'centerY', label: 'Center Y', min: 0, max: 1, default: .5, step: .005 }],
    presets: [{ id: 'left-plane', name: 'Left Plane', description: 'Rotates the image onto a left-facing plane.', params: { yaw: -42, pitch: 0, roll: 0, depth: 1.1, centerX: .5, centerY: .5 } }, { id: 'floor-plane', name: 'Floor Plane', description: 'Tilts the image into floor perspective.', params: { yaw: 0, pitch: 58, roll: 0, depth: .85, centerX: .5, centerY: .52 } }, { id: 'dynamic-card', name: 'Dynamic Card', description: 'Combined presentation-card perspective.', params: { yaw: 24, pitch: -16, roll: 6, depth: 1.15, centerX: .5, centerY: .5 } }],
    glsl: `vec4 fx(vec2 uv){vec2 p=uv-vec2(P4,P5);float r=radians(P2),cs=cos(r),sn=sin(r);p=mat2(cs,-sn,sn,cs)*p;float y=radians(P0),x=radians(P1);float z=P3+p.x*sin(y)+p.y*sin(x);vec2 q=vec2(p.x*cos(y),p.y*cos(x))/max(.15,z)+vec2(P4,P5);return inp(q);}`,
  },
];
