import React from 'react';
import { AppWindow, BookOpen, Camera, Film, Gamepad2, Globe, MessageCircle, Mic, Music, Newspaper, Play, Radio, User } from 'lucide-react';
import { useUniversalPlatformSearch, type UniversalPlatformResult, type UniversalResultType } from '../hooks/useUniversalPlatformSearch';

const ICONS: Record<UniversalResultType, React.ComponentType<any>> = { USER: User, MUSIC: Music, PODCAST: Mic, BOOK: BookOpen, VIDEO: Play, MOVIE: Film, TV: Film, ARTICLE: Newspaper, GAME: Gamepad2, WORLD: Globe, LIVE: Radio, DISCUSSION: MessageCircle, PHOTO: Camera, APP: AppWindow, POST: MessageCircle };
export interface UniversalCommandResultsProps {
  query: string; onNavigate: (view: string) => void; onClose: () => void;
  onVisitUser?: (uid: string) => void; onSelectItem?: (item: any) => void; onSelectArticle?: (article: any) => void; onSelectGame?: (game: any) => void; onSelectLiveFeed?: (feed: any) => void;
}
const UniversalCommandResults: React.FC<UniversalCommandResultsProps> = ({ query, onNavigate, onClose, onVisitUser, onSelectItem, onSelectArticle, onSelectGame, onSelectLiveFeed }) => {
  const { results, loading } = useUniversalPlatformSearch(query);
  const choose = (result: UniversalPlatformResult) => { onClose(); switch (result.type) { case 'USER': return onVisitUser ? onVisitUser(result.id) : onNavigate('SEARCH'); case 'ARTICLE': return onSelectArticle ? onSelectArticle(result.raw) : onNavigate('ARTICLES'); case 'GAME': return onSelectGame ? onSelectGame(result.raw) : onNavigate('GAMES'); case 'LIVE': return onSelectLiveFeed ? onSelectLiveFeed(result.raw) : onNavigate('LIVE_HUB'); case 'WORLD': return onNavigate('WORLDS'); case 'DISCUSSION': return onNavigate('DISCUSSION'); case 'POST': return onNavigate('FEED'); case 'PHOTO': return onNavigate('GLOBAL_PHOTOS'); case 'APP': return onNavigate('APPS'); default: return onSelectItem ? onSelectItem(result.raw) : onNavigate(result.type === 'BOOK' ? 'BOOKS' : result.type === 'MOVIE' || result.type === 'TV' ? 'MOVIES_TV' : result.type === 'VIDEO' ? 'VIDEOS' : 'MUSIC'); } };
  if (query.trim().length < 2) return null;
  return <section><div className="text-[.6rem] font-black uppercase tracking-[0.2em] text-white/40 mt-5 mb-2.5">Public on Plajah</div>{loading && !results.length ? <p className="py-5 text-center text-xs text-white/40">Searching the platform…</p> : results.length ? <div className="grid sm:grid-cols-2 gap-2">{results.map(result => { const Icon = ICONS[result.type]; return <button key={`${result.type}:${result.id}`} onClick={() => choose(result)} className="flex items-center gap-3 text-left p-2.5 rounded-2xl border border-white/[0.08] bg-white/[0.045] hover:bg-white/[0.1] transition-colors"><span className="w-11 h-11 rounded-xl overflow-hidden grid place-items-center bg-[#1B1329] shrink-0">{result.thumbnail ? <img src={result.thumbnail} alt="" className="w-full h-full object-cover" /> : <Icon size={19} className="text-[#00DAF3]" />}</span><span className="min-w-0 flex-1"><span className="block text-[.72rem] font-bold text-white truncate">{result.title}</span><span className="block text-[.62rem] text-white/45 truncate">{result.subtitle || result.type.toLowerCase()}</span></span><span className="text-[.52rem] font-black uppercase tracking-wider text-[#FF8C00]">{result.type}</span></button>; })}</div> : <p className="py-5 text-center text-xs text-white/35">No public people or creations match “{query.trim()}”.</p>}</section>;
};
export default UniversalCommandResults;
