// Loudness calibration tables, generated by `npx tsx tests/support/livingAudioSurvey.ts calibrate --write` from offline renders (see docs/LIVING_AUDIO.md).
// The recipes in sfxCatalog.ts / instruments.ts / ambience.ts are written at natural synthesis levels; these multipliers bring every sound to a
// comparable, safe loudness (sfx ~ -20 dBFS active RMS, instruments ~ -23, beds ~ -28 at gain 0.5; startle sounds lower). Regenerate after changing a recipe.

export const SFX_GAIN: Record<string, number> = {
  'beep': 0.34, 'beep-low': 0.34, 'beep-high': 0.33, 'beep-double': 0.36, 'beep-car': 0.33, 'honk': 0.32, 'toot': 0.42, 'kazoo-toot': 0.95, 'pop': 0.77, 'boing': 0.91, 'whoosh': 2.13, 'swoosh': 4.42, 'zip': 1.95, 'jelly-squish': 0.95, 'squeak': 0.73, 'boop': 0.86, 'tick': 1.74, 'button-click': 1.25, 'pop-balloon': 0.74, 'confetti': 1.51, 'sparkle': 1.79, 'twinkle': 1.42, 'magic-appear': 1.17, 'success-jingle': 1.21, 'gentle-no': 0.56, 'chime': 0.76, 'glass-chime': 0.7, 'bell': 0.47, 'ding': 0.89, 'harp-gliss': 0.97, 'stitch': 1.43, 'thread-pluck': 1.01, 'thread-tug': 0.57, 'unravel': 2.23, 'knock': 0.92, 'thud': 0.69, 'crunch': 2.89, 'rustle': 3.55, 'splash': 2.15, 'bubble': 1.01, 'drip': 1.26, 'cricket': 2.15, 'owl-hoo': 0.57, 'wings': 3.34, 'whale-call': 0.41, 'hum': 0.6, 'snore': 1.18, 'yawn': 1.31, 'footstep-left': 1.03, 'footstep-right': 1.12, 'heartbeat': 0.77, 'candle-flicker': 3.53, 'candle-blow': 4.31, 'page-flip': 3.8, 'rumble': 0.34,
};
export const INSTRUMENT_LEVEL: Record<string, number> = {
  'musicbox': 1.02, 'marimba': 0.86, 'felt-piano': 0.88, 'harp': 1.25, 'pluck': 1.73, 'kalimba': 0.96, 'bell': 0.77, 'glass': 1.08, 'bass': 0.23, 'flute': 0.36, 'whistle': 0.42, 'kazoo': 1.32, 'pad': 1.21, 'choir': 1.3, 'whale': 1.15, 'hum': 0.6, 'kick': 0.6, 'snare': 1.79, 'hat': 2.04, 'ohat': 2.29, 'shaker': 1.5, 'click': 1.19, 'clap': 2.5, 'tom': 0.73, 'drum': 0.6,
};
export const BED_LEVEL: Record<string, number> = {
  'night-crickets': 1.21, 'forest-wind': 0.73, 'ocean-hum': 0.36, 'city-murmur': 0.54, 'room-tone': 0.83, 'space-drone': 0.65, 'wind': 0.86, 'rain-soft': 1.14, 'forest-night': 0.69,
};
