"""buildFaceAtlas — turn a green-screen decal sheet (generated by Magnific) into a clean RGBA atlas.

    python scripts/decals/buildFaceAtlas.py <sheet.png> <out_prefix> --cols 3 --rows 4 [--pair] [--names a,b,c,...] [--cell 384]

For each grid cell: chroma-key the green (soft alpha + despill), crop to the content, scale so every state keeps
its true relative size inside a square cell (the biggest state of the sheet fills ~92% of the cell; the cell keeps
the content's centre of mass as its anchor), and pack the cells into an atlas. `--pair` = each source cell holds a
LEFT and a RIGHT eye side by side: two atlases are written (<prefix>_L.png / <prefix>_R.png).

Outputs: <prefix>.png (RGBA atlas), <prefix>.json ({cols, rows, cell, states:[{name,col,row,anchor:[x,y],size:[w,h]}]}),
<prefix>_preview.jpg (atlas on a checker, for eyeballing).
"""
import argparse, json, os
import cv2
import numpy as np


def key_green(bgr):
    f = bgr.astype(np.float32)
    b, g, r = f[..., 0], f[..., 1], f[..., 2]
    d = g - np.maximum(r, b)                       # how much greener than the rest (pure screen ≈ 200+)
    alpha = np.clip(1.0 - (d - 38.0) / (118.0 - 38.0), 0.0, 1.0)
    alpha = np.where(d < 38.0, 1.0, alpha)
    # despill: pull green back toward the other channels where we kept partial alpha
    g2 = np.minimum(g, np.maximum(r, b) + 6.0)
    out = np.stack([b, g2, r], -1)
    return np.clip(out, 0, 255).astype(np.uint8), (alpha * 255).astype(np.uint8)


def trim(rgb, a, pad=6):
    ys, xs = np.where(a > 24)
    if len(xs) == 0:
        return None
    x0, x1, y0, y1 = max(0, xs.min() - pad), min(a.shape[1], xs.max() + pad + 1), max(0, ys.min() - pad), min(a.shape[0], ys.max() + pad + 1)
    return rgb[y0:y1, x0:x1], a[y0:y1, x0:x1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('sheet'); ap.add_argument('out')
    ap.add_argument('--cols', type=int, required=True); ap.add_argument('--rows', type=int, required=True)
    ap.add_argument('--pair', action='store_true'); ap.add_argument('--names', default=''); ap.add_argument('--cell', type=int, default=384)
    o = ap.parse_args()
    im = cv2.imread(o.sheet)
    H, W = im.shape[:2]
    cw, ch = W / o.cols, H / o.rows
    names = [n.strip() for n in o.names.split(',')] if o.names else []
    sides = ['L', 'R'] if o.pair else ['']
    result = {}
    for si, side in enumerate(sides):
        cells = []
        for r in range(o.rows):
            for c in range(o.cols):
                x0, x1, y0, y1 = int(c * cw), int((c + 1) * cw), int(r * ch), int((r + 1) * ch)
                crop = im[y0 + 4:y1 - 4, x0 + 4:x1 - 4]
                if o.pair:
                    half = crop.shape[1] // 2
                    crop = crop[:, :half] if si == 0 else crop[:, half:]
                rgb, a = key_green(crop)
                t = trim(rgb, a)
                cells.append(t)
        # common scale: the largest state fills 92% of the cell
        mx = max(max(t[0].shape[0], t[0].shape[1]) for t in cells if t is not None)
        sc = (o.cell * 0.92) / mx
        atlas = np.zeros((o.rows * o.cell, o.cols * o.cell, 4), np.uint8)
        states = []
        for i, t in enumerate(cells):
            r, c = divmod(i, o.cols)
            name = names[i] if i < len(names) else f'state{i}'
            if t is None:
                states.append({'name': name, 'col': c, 'row': r, 'anchor': [0.5, 0.5], 'size': [0, 0]}); continue
            rgb, a = t
            h, w = a.shape
            nw, nh = max(1, int(round(w * sc))), max(1, int(round(h * sc)))
            rgb = cv2.resize(rgb, (nw, nh), interpolation=cv2.INTER_AREA); a = cv2.resize(a, (nw, nh), interpolation=cv2.INTER_AREA)
            # premultiplied-safe edge: erode alpha a hair to kill the last green fringe
            a = cv2.erode(a, np.ones((2, 2), np.uint8)) if nw > 24 else a
            ox, oy = (o.cell - nw) // 2, (o.cell - nh) // 2
            tile = np.dstack([rgb, a])
            atlas[r * o.cell + oy:r * o.cell + oy + nh, c * o.cell + ox:c * o.cell + ox + nw] = tile
            states.append({'name': name, 'col': c, 'row': r, 'anchor': [0.5, 0.5], 'size': [round(nw / o.cell, 4), round(nh / o.cell, 4)]})
        key = o.out + (('_' + side) if side else '')
        os.makedirs(os.path.dirname(key) or '.', exist_ok=True)
        cv2.imwrite(key + '.png', atlas)
        with open(key + '.json', 'w', encoding='utf8') as f:
            json.dump({'cols': o.cols, 'rows': o.rows, 'cell': o.cell, 'source': os.path.basename(o.sheet), 'side': side or None, 'states': states}, f, indent=1)
        # preview on a light checker
        chk = np.indices(atlas.shape[:2]).sum(0) // 24 % 2
        bg = np.where(chk[..., None] == 0, 236, 255).astype(np.float32).repeat(3, -1)
        al = atlas[..., 3:4].astype(np.float32) / 255.0
        prev = (atlas[..., :3].astype(np.float32) * al + bg * (1 - al)).astype(np.uint8)
        s = 1400 / max(prev.shape[:2])
        cv2.imwrite(key + '_preview.jpg', cv2.resize(prev, (int(prev.shape[1] * s), int(prev.shape[0] * s)), interpolation=cv2.INTER_AREA), [cv2.IMWRITE_JPEG_QUALITY, 90])
        result[side or 'all'] = key
    print(json.dumps(result))


if __name__ == '__main__':
    main()
