// Survey / calibration tool for the Living Books audio engine (run from the repo root):
//   npx tsx tests/support/livingAudioSurvey.ts sfx|inst|bed|score     print measurements (peak, RMS, duration, centroid) per sound
//   npx tsx tests/support/livingAudioSurvey.ts calibrate              print new tables for services/living/audio/calibration.ts
import { openRenderPage } from './livingAudioBrowser';
import { SFX_CATALOG } from '../../services/living/audio/sfxCatalog';
import { INSTRUMENTS } from '../../services/living/audio/instruments';
import { AMBIENCE_BEDS } from '../../services/living/audio/ambience';

const T_SFX = -20, T_SFX_LOUD = -24, CAP = 0.5, CAP_LOUD = 0.4, T_INST = -23, T_BED = -28;
const round = (x: number) => Math.round(x * 100) / 100;

(async () => {
  const rp = await openRenderPage();
  if (!rp) { console.log('no chromium'); return; }
  const which = process.argv[2] || 'sfx';
  const row = (k: string, s: any) => console.log(k.padEnd(26), 'pk', s.peakLR.toFixed(2), 'rmsA', s.rmsActiveDb.toFixed(1).padStart(6), 'dur', s.durationSec.toFixed(2), 'cent', String(Math.round(s.centroidHz)).padStart(5), s.hasNaN ? 'NaN!' : '', s.silent ? 'SILENT' : '');
  const noteFor = (i: any) => (i.family === 'drum' ? (i.id === 'drum' ? 'kick' : 'x') : 'C4');
  if (which === 'sfx') for (const d of SFX_CATALOG) { const r = await rp.call(`LA.sfx(${JSON.stringify(d.id)}, {raw:true, wav:false})`); row(d.id, r.stats); }
  if (which === 'inst') for (const i of INSTRUMENTS) { const r = await rp.call(`LA.note(${JSON.stringify(i.id)}, ${JSON.stringify(noteFor(i))}, {raw:true})`); row(i.id, r.stats); }
  if (which === 'bed') for (const b of AMBIENCE_BEDS) { const r = await rp.call(`LA.bed(${JSON.stringify(b.id)}, {})`); row(b.id, r.stats); }
  if (which === 'score') for (const id of ['lullaby', 'city', 'folk']) { const r = await rp.call(`LA.score(${JSON.stringify(id)}, {seconds: 12})`); row(id, r.stats); console.log('events', r.events); }
  if (which === 'calibrate') {
    const sfx: string[] = [], inst: string[] = [], bed: string[] = [];
    for (const d of SFX_CATALOG) {
      const r = await rp.call(`LA.sfx(${JSON.stringify(d.id)}, {raw:true, wav:false, gain:${1 / d.defaultGain}})`);
      const t = d.loud ? T_SFX_LOUD : T_SFX, cap = d.loud ? CAP_LOUD : CAP;
      const g = Math.min(Math.pow(10, (t - r.stats.rmsActiveDb) / 20), cap / r.stats.peakLR, 6);
      sfx.push(`'${d.id}': ${round(g)}`);
    }
    for (const i of INSTRUMENTS) {
      const r = await rp.call(`LA.note(${JSON.stringify(i.id)}, ${JSON.stringify(noteFor(i))}, {raw:true, gain:${1 / i.level}})`);
      if (r.stats.silent) { console.log('SILENT', i.id); continue; }
      const g = Math.min(Math.pow(10, (T_INST - r.stats.rmsActiveDb) / 20), 0.55 / r.stats.peakLR, 2.5);
      inst.push(`'${i.id}': ${round(g)}`);
    }
    for (const b of AMBIENCE_BEDS) {
      const r = await rp.call(`LA.bed(${JSON.stringify(b.id)}, {gain:${0.5 / b.level}})`);
      bed.push(`'${b.id}': ${round(Math.pow(10, (T_BED - r.stats.rmsActiveDb) / 20))}`);
    }
    const text = `// Loudness calibration tables, generated by \`npx tsx tests/support/livingAudioSurvey.ts calibrate --write\` from offline renders (see docs/LIVING_AUDIO.md).
// The recipes in sfxCatalog.ts / instruments.ts / ambience.ts are written at natural synthesis levels; these multipliers bring every sound to a
// comparable, safe loudness (sfx ~ -20 dBFS active RMS, instruments ~ -23, beds ~ -28 at gain 0.5; startle sounds lower). Regenerate after changing a recipe.

export const SFX_GAIN: Record<string, number> = {
  ${sfx.join(', ')},
};
export const INSTRUMENT_LEVEL: Record<string, number> = {
  ${inst.join(', ')},
};
export const BED_LEVEL: Record<string, number> = {
  ${bed.join(', ')},
};
`;
    if (process.argv.includes('--write')) { (await import('node:fs')).writeFileSync('services/living/audio/calibration.ts', text); console.log('wrote calibration.ts'); }
    else console.log(text);
    if (false) console.log(`export const SFX_GAIN: Record<string, number> = {\n  ${sfx.join(', ')},\n};\nexport const INSTRUMENT_LEVEL: Record<string, number> = {\n  ${inst.join(', ')},\n};\nexport const BED_LEVEL: Record<string, number> = {\n  ${bed.join(', ')},\n};`);
  }
  if (rp.consoleErrors.length) console.log('errors', rp.consoleErrors);
  await rp.close();
})();
