// sports — eighteen genuinely different competition identities.
//
// Each one owns its clock, its numerals and its impact timing. The score strip is where these
// identities earn their keep, so most author it explicitly instead of taking the derived one.
import * as orn from '../../tela/ornaments';
import { type Ctx, C, D, E, L, P, PolyG, R, T, checker, dots, drift, enter, gradient, mix, alpha, perspectiveGrid, pulse, radial, rings, rotateLoop, slot, stripes, specks, twoLines, halftone, filters } from './kit';
import type { BroadcastDesign } from './types';

const lt = (k: Ctx, inner: string, type: Parameters<typeof enter>[1], o: Parameters<typeof enter>[2] = {}) => enter(inner, type, { dur: k.beat, ease: 'expo', loop: k.total, outDur: k.beat * .6, ...o });
const score = (k: Ctx, x: number, y: number, size: number, font: Parameters<typeof T>[3]['font'], fill: string, weight = 900) => `${T(x, y, k.scoreHome, { font, size, weight, fill, anchor: 'end' })}${T(x + size * 1.1, y, k.scoreAway, { font, size, weight, fill })}`;

export const SPORTS_DESIGNS: Record<string, BroadcastDesign> = {

  /* ── Arena Carbon — plates slam on along Z; four-frame impact holds ── */
  'arena-carbon': {
    type: { display: 'archivoBlack', text: 'archivo', utility: 'oswald' }, idea: 'Bevelled carbon plates slam in from depth with a hot edge light; every element is a machined part.', ground: 'a', surface: 'CLEAN', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${PolyG([[cx - s * .5, cy - s * .3], [cx + s * .3, cy - s * .3], [cx + s * .5, cy + s * .3], [cx - s * .3, cy + s * .3]], k.b)}${PolyG([[cx - s * .4, cy - s * .2], [cx + s * .2, cy - s * .2], [cx + s * .38, cy + s * .2], [cx - s * .22, cy + s * .2]], k.a)}${L(cx - s * .5, cy - s * .3, cx + s * .3, cy - s * .3, k.c, s * .05)}`,
    field: (k, x, y, w, h, i = 1) => `${checker(x, y, w, h, 18, alpha(k.b, .06 * i))}${[0, 1, 2].map(n => PolyG([[x + w * (.1 + n * .3), y], [x + w * (.2 + n * .3), y], [x + w * (.12 + n * .3), y + h], [x + w * (.02 + n * .3), y + h]], alpha(k.d, .18 * i))).join('')}`,
    opener: k => { const { w, h } = k; const carbon = k.uid('cb'); k.defs.push(`<pattern id="${carbon}" width="12" height="12" patternUnits="userSpaceOnUse"><rect width="6" height="6" fill="${mix(k.a, .08)}"/><rect x="6" y="6" width="6" height="6" fill="${mix(k.a, .08)}"/></pattern>`);
      const plate = (x: number, y: number, pw: number, ph: number, fill: string) => `${PolyG([[x, y], [x + pw, y], [x + pw - 40, y + ph], [x - 40, y + ph]], fill)}${L(x, y, x + pw, y, k.c, 6)}`;
      return `${R(0, 0, w, h, k.a)}${R(0, 0, w, h, `url(#${carbon})`)}${R(0, h * .84, w, h * .16, mix(k.a, -.4))}
        ${enter(plate(w * .1, h * .22, w * .8, h * .18, mix(k.a, .14)), 'pop', { dur: k.beat * .35, ease: 'expo', amount: .5, origin: [w / 2, h * .3] })}
        ${enter(plate(w * .16, h * .44, w * .68, h * .26, k.b), 'pop', { dur: k.beat * .35, delay: k.beat * .3, ease: 'expo', amount: .5, origin: [w / 2, h * .57] })}
        ${enter(`${T(w / 2, h * .34, k.eyebrow, { font: 'oswald', size: h * .05, weight: 700, fill: k.c, anchor: 'middle', tracking: .3, upper: true })}${T(w / 2, h * .63, k.title, { font: 'archivoBlack', size: h * .13, fill: k.a, anchor: 'middle', upper: true, fitW: w * .6 })}`, 'fade', { dur: k.beat * .4, delay: k.beat * .6 })}
        ${enter(`${R(w * .3, h * .74, w * .4, h * .06, k.d)}${T(w / 2, h * .785, k.subtitle, { font: 'archivo', size: h * .028, weight: 800, fill: k.b, anchor: 'middle', upper: true, tracking: .12, fitW: w * .36 })}`, 'slideU', { dur: k.beat * .5, delay: k.beat * 1, ease: 'expo' })}
        ${drift(R(0, h * .21, w, 4, alpha(k.c, .9), { blend: 'screen' }), 0, h * .5, k.beat * 7)}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${PolyG([[w * .05, h * .76], [w * .52, h * .76], [w * .5, h * .9], [w * .03, h * .9]], k.b)}${PolyG([[w * .05, h * .76], [w * .14, h * .76], [w * .12, h * .9], [w * .03, h * .9]], k.c)}${L(w * .05, h * .76, w * .52, h * .76, k.d, 5)}
        ${T(w * .16, h * .835, k.title, { font: 'archivoBlack', size: h * .052, fill: k.a, upper: true, fitW: w * .33 })}${T(w * .16, h * .88, k.subtitle, { font: 'oswald', size: h * .022, weight: 600, fill: k.a, tracking: .16, upper: true, fitW: w * .33 })}`, 'pop', { amount: .4, origin: [w * .28, h * .83] }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['arena-carbon'].field(k, 0, 0, w, h, 1)}${slot(k, w * .06, h * .1, w * .5, h * .8, { tone: 'dark', filter: undefined })}${L(w * .06, h * .1, w * .56, h * .1, k.c, 8)}
        ${enter(`${PolyG([[w * .6, h * .2], [w * .96, h * .2], [w * .94, h * .82], [w * .58, h * .82]], k.b)}${T(w * .63, h * .32, k.eyebrow, { font: 'oswald', size: h * .036, weight: 700, fill: k.c, tracking: .24, upper: true })}${T(w * .63, h * .5, twoLines(k.title)[0], { font: 'archivoBlack', size: h * .09, fill: k.a, upper: true, lines: twoLines(k.title), leading: .95, fitW: w * .3 })}${T(w * .63, h * .7, k.subtitle, { font: 'archivo', size: h * .024, weight: 700, fill: k.a, upper: true, tracking: .06, fitW: w * .3 })}`, 'pop', { dur: k.beat * .4, ease: 'expo', amount: .4, origin: [w * .77, h * .5] })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${L(0, 0, w, 0, k.c, 8)}${PolyG([[0, 0], [w * .4, 0], [w * .38, h], [0, h]], k.b)}${enter(T(w * .04, h * .68, k.title, { font: 'archivoBlack', size: h * .42, fill: k.a, upper: true, fitW: w * .3 }), 'slideL', { dur: k.beat * .4, amount: .5 })}
        ${enter(`${score(k, w * .62, h * .74, h * .6, 'oswald', k.b)}${T(w * .94, h * .66, k.subtitle, { font: 'oswald', size: h * .22, weight: 600, fill: k.c, anchor: 'end', tracking: .1, upper: true, fitW: w * .16 })}`, 'pop', { dur: k.beat * .3, delay: k.beat * .3, amount: .3, origin: [w * .7, h / 2] })}`; },
  },

  /* ── Varsity Letterpress — scoreboard slats flip; ink layers land a few frames apart ── */
  'varsity-letterpress': {
    type: { display: 'robotoSlab', text: 'bitter', utility: 'oswald' }, idea: 'Felt-and-ink campus sport: a chunky slab on paper with the colour plate landing a beat late, out of register.', ground: 'a', surface: 'PAPER', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${C(cx, cy, s * .5, k.b)}${C(cx, cy, s * .4, 'none', { stroke: k.a, sw: s * .04, dash: `${s * .06} ${s * .04}` })}${T(cx, cy + s * .14, 'V', { font: 'robotoSlab', size: s * .48, weight: 900, fill: k.a, anchor: 'middle' })}`,
    field: (k, x, y, w, h, i = 1) => `${halftone(x, y, w, h, 16, alpha(k.b, .5 * i), { direction: 'y' })}${stripes(x, y, w, h, 3, 6, alpha(k.c, .6 * i))}`,
    opener: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${halftone(0, h * .5, w, h * .5, 18, alpha(k.b, .35), { direction: 'y' })}${R(0, h * .12, w, 10, k.b)}${R(0, h * .88, w, 10, k.b)}
        ${enter(`${T(w / 2 + 8, h * .5 + 8, k.title, { font: 'robotoSlab', size: h * .19, weight: 900, fill: k.c, anchor: 'middle', upper: true, fitW: w * .8 })}`, 'slideD', { dur: k.beat * .5, delay: k.beat * .4, amount: .6 })}
        ${enter(`${T(w / 2, h * .5, k.title, { font: 'robotoSlab', size: h * .19, weight: 900, fill: k.b, anchor: 'middle', upper: true, fitW: w * .8 })}`, 'slideD', { dur: k.beat * .5, amount: .6 })}
        ${enter(`${R(w * .28, h * .58, w * .44, h * .09, k.d)}${T(w / 2, h * .645, k.subtitle, { font: 'oswald', size: h * .036, weight: 600, fill: k.a, anchor: 'middle', tracking: .18, upper: true, fitW: w * .4 })}`, 'growX', { dur: k.beat * .6, delay: k.beat * .9, ease: 'expo', origin: [w / 2, h * .62] })}
        ${enter(`${T(w / 2, h * .27, k.eyebrow, { font: 'bitter', size: h * .03, weight: 700, fill: k.b, anchor: 'middle', tracking: .3, upper: true })}${[0, 1, 2, 3, 4].map(n => C(w * (.3 + n * .1), h * .78, 10, n % 2 ? k.c : k.d)).join('')}`, 'fade', { dur: k.beat, delay: k.beat * 1.3 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05 + 6, h * .75 + 6, w * .48, h * .15, k.c)}${R(w * .05, h * .75, w * .48, h * .15, k.a, { stroke: k.b, sw: 6 })}${R(w * .05 + 14, h * .75 + 14, w * .48 - 28, h * .15 - 28, 'none', { stroke: k.b, sw: 2, dash: '8 6' })}${C(w * .1, h * .825, h * .045, k.b)}${T(w * .1, h * .84, 'V', { font: 'robotoSlab', size: h * .05, weight: 900, fill: k.a, anchor: 'middle' })}
        ${T(w * .16, h * .82, k.title, { font: 'robotoSlab', size: h * .052, weight: 900, fill: k.b, upper: true, fitW: w * .34 })}${T(w * .16, h * .865, k.subtitle, { font: 'oswald', size: h * .021, weight: 600, fill: k.d, tracking: .16, upper: true, fitW: w * .34 })}`, 'drop', { dur: k.beat * .7, ease: 'back' }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${halftone(0, 0, w, h, 18, alpha(k.b, .2), { direction: 'x' })}${R(w * .05, h * .07, w * .9, h * .86, 'none', { stroke: k.b, sw: 10 })}${R(w * .05 + 18, h * .07 + 18, w * .9 - 36, h * .86 - 36, 'none', { stroke: k.c, sw: 3, dash: '12 8' })}
        ${slot(k, w * .1, h * .14, w * .42, h * .72, { tone: 'light', filter: k.uid('dt') })}
        ${enter(`${T(w * .56 + 6, h * .4 + 6, twoLines(k.title)[0], { font: 'robotoSlab', size: h * .1, weight: 900, fill: k.c, upper: true, lines: twoLines(k.title), leading: .95, fitW: w * .34 })}${T(w * .56, h * .4, twoLines(k.title)[0], { font: 'robotoSlab', size: h * .1, weight: 900, fill: k.b, upper: true, lines: twoLines(k.title), leading: .95, fitW: w * .34 })}${R(w * .56, h * .64, w * .3, h * .07, k.d)}${T(w * .575, h * .69, k.subtitle, { font: 'oswald', size: h * .03, weight: 600, fill: k.a, tracking: .16, upper: true, fitW: w * .27 })}${T(w * .56, h * .8, 'EST. · REPLACEABLE', { font: 'bitter', size: h * .022, weight: 700, fill: k.b, tracking: .2 })}`, 'slideD', { dur: k.beat * .6, delay: k.beat * .5, amount: .6 })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${halftone(0, 0, w, h, 14, alpha(k.b, .22), { direction: 'x' })}${R(0, 0, w, 8, k.b)}${R(0, h - 8, w, 8, k.b)}${T(w * .04, h * .7, k.title, { font: 'robotoSlab', size: h * .42, weight: 900, fill: k.b, upper: true, fitW: w * .36 })}
        ${[0, 1].map(n => `${R(w * (.6 + n * .14), h * .18, w * .11, h * .64, k.b)}${R(w * (.6 + n * .14), h * .18, w * .11, h * .64, 'none', { stroke: k.c, sw: 4 })}${T(w * (.655 + n * .14), h * .68, n ? k.scoreAway : k.scoreHome, { font: 'robotoSlab', size: h * .5, weight: 900, fill: k.a, anchor: 'middle' })}`).join('')}${T(w * .94, h * .64, k.subtitle, { font: 'oswald', size: h * .2, weight: 600, fill: k.d, anchor: 'end', tracking: .14, upper: true, fitW: w * .1 })}`; },
  },

  /* ── Continental Football — passing lanes draw into modular fields; possession glides ── */
  'continental-football': {
    type: { display: 'dmSans', text: 'dmSans', utility: 'jetbrains' }, idea: 'Pitch geometry as a Swiss grid: the centre circle, the D, and hairline passing lanes; data glides, never punches.', ground: 'a', surface: 'CLEAN',
    mark: (k, cx, cy, s) => `${R(cx - s * .5, cy - s * .32, s, s * .64, 'none', { stroke: k.c, sw: s * .03 })}${C(cx, cy, s * .14, 'none', { stroke: k.c, sw: s * .03 })}${L(cx, cy - s * .32, cx, cy + s * .32, k.c, s * .03)}`,
    field: (k, x, y, w, h, i = 1) => `${R(x + w * .06, y + h * .1, w * .88, h * .8, 'none', { stroke: alpha(k.b, .35 * i), sw: 3 })}${C(x + w / 2, y + h / 2, h * .2, 'none', { stroke: alpha(k.b, .35 * i), sw: 3 })}${L(x + w / 2, y + h * .1, x + w / 2, y + h * .9, alpha(k.b, .35 * i), 3)}${[0, 1].map(n => R(x + w * (n ? .78 : .06), y + h * .3, w * .16, h * .4, 'none', { stroke: alpha(k.b, .35 * i), sw: 3 })).join('')}`,
    opener: k => { const { w, h } = k;
      const lanes: Array<[number, number, number, number]> = [[w * .12, h * .7, w * .34, h * .42], [w * .34, h * .42, w * .58, h * .56], [w * .58, h * .56, w * .82, h * .3]];
      return `${R(0, 0, w, h, k.a)}${stripes(0, 0, w, h, 8, h / 16, alpha(k.b, .03))}${enter(SPORTS_DESIGNS['continental-football'].field(k, 0, 0, w, h, 1), 'fade', { dur: k.beat * 1.4 })}
        ${lanes.map(([x1, y1, x2, y2], n) => enter(`${L(x1, y1, x2, y2, k.c, 4)}${C(x2, y2, 12, k.c)}`, 'draw', { dur: k.beat * .8, delay: k.beat * (.8 + n * .5), ease: 'inOut' })).join('')}${C(lanes[0][0], lanes[0][1], 12, k.d)}
        ${enter(`${R(w * .06, h * .08, w * .4, h * .2, k.b)}${T(w * .08, h * .17, k.title, { font: 'dmSans', size: h * .06, weight: 800, fill: k.a, fitW: w * .36 })}${T(w * .08, h * .23, k.subtitle, { font: 'jetbrains', size: h * .02, weight: 500, fill: k.a, tracking: .1, upper: true, fitW: w * .36 })}`, 'slideL', { dur: k.beat * 1.2, delay: k.beat * .3, ease: 'expo', amount: 1.2 })}
        ${enter(`${R(w * .72, h * .8, w * .22, h * .12, k.c)}${T(w * .74, h * .85, 'POSSESSION', { font: 'jetbrains', size: h * .018, weight: 700, fill: k.a, tracking: .18 })}${T(w * .74, h * .895, '58 %', { font: 'dmSans', size: h * .04, weight: 800, fill: k.a })}`, 'slideU', { dur: k.beat, delay: k.beat * 2.4, ease: 'expo' })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .76, w * .46, h * .13, k.b)}${R(w * .05, h * .76, w * .46, 6, k.c)}${C(w * .09, h * .825, h * .035, 'none', { stroke: k.a, sw: 3 })}${L(w * .09, h * .79, w * .09, h * .86, k.a, 3)}
        ${T(w * .14, h * .815, k.title, { font: 'dmSans', size: h * .048, weight: 800, fill: k.a, fitW: w * .35 })}${T(w * .14, h * .86, k.subtitle, { font: 'jetbrains', size: h * .019, weight: 500, fill: k.a, tracking: .1, upper: true, fitW: w * .35 })}`, 'wipeR', { dur: k.beat * .9 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['continental-football'].field(k, 0, 0, w, h, .7)}${slot(k, w * .06, h * .1, w * .48, h * .8, { tone: 'dark' })}
        ${enter(`${R(w * .58, h * .1, w * .36, h * .8, k.b)}${R(w * .58, h * .1, w * .36, 8, k.c)}${T(w * .61, h * .3, twoLines(k.title)[0], { font: 'dmSans', size: h * .07, weight: 800, fill: k.a, lines: twoLines(k.title), fitW: w * .3 })}${T(w * .61, h * .5, k.subtitle, { font: 'dmSans', size: h * .024, weight: 500, fill: k.a, fitW: w * .3 })}${[['xG', '1.84'], ['SHOTS', '14'], ['PASSES', '612'], ['POSS.', '58 %']].map(([l, v], n) => `${T(w * .61, h * (.62 + n * .06), l, { font: 'jetbrains', size: h * .018, weight: 500, fill: k.a, tracking: .14 })}${T(w * .9, h * (.62 + n * .06), v, { font: 'dmSans', size: h * .03, weight: 800, fill: k.c, anchor: 'end' })}${L(w * .61, h * (.635 + n * .06), w * .9, h * (.635 + n * .06), alpha(k.a, .3), 1.5)}`).join('')}`, 'slideR', { dur: k.beat * 1.2, ease: 'expo', amount: 1.5 })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.b)}${R(0, 0, w, 8, k.c)}${T(w * .03, h * .66, k.title, { font: 'dmSans', size: h * .38, weight: 800, fill: k.a, fitW: w * .38 })}${R(w * .5, h * .2, w * .28, h * .6, k.a)}${score(k, w * .625, h * .7, h * .5, 'dmSans', k.b, 800)}${T(w * .96, h * .64, k.subtitle, { font: 'jetbrains', size: h * .18, weight: 500, fill: k.a, anchor: 'end', tracking: .1, upper: true, fitW: w * .16 })}`; },
  },

  /* ── Neon Hardwood — lacquered court reflections; stats bounce once, then lock ── */
  'neon-hardwood': {
    type: { display: 'sixCaps', text: 'exo2', utility: 'chakra' }, idea: 'A reflective court floor under coloured haze; ultra-compressed clock numerals pivot on the 90° angles of the key.', ground: 'a', surface: 'GLOW', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${R(cx - s * .5, cy - s * .5, s, s * .7, 'none', { stroke: k.c, sw: s * .05, rx: s * .06 })}${D(`M${cx - s * .35} ${cy + s * .2}A${s * .35} ${s * .35} 0 0 1 ${cx + s * .35} ${cy + s * .2}`, 'none', { stroke: k.d, sw: s * .05 })}${C(cx, cy - s * .15, s * .07, k.b)}`,
    field: (k, x, y, w, h, i = 1) => `${stripes(x, y, w, h, 24, 3, alpha(k.b, .12 * i), { vertical: true })}${D(`M${x + w * .2} ${y + h}A${w * .3} ${h * .5} 0 0 1 ${x + w * .8} ${y + h}`, 'none', { stroke: alpha(k.c, .7 * i), sw: 6 })}`,
    opener: k => { const { w, h } = k; const haze = k.uid('hz'), floor = k.uid('fl'); k.defs.push(gradient(haze, [[0, k.c, .55], [1, k.c, 0]], { radial: true, cx: .3, cy: .3, r: .6 }), gradient(floor, [[0, k.d, .35], [1, k.d, 0]], { angle: 180 }));
      return `${R(0, 0, w, h, k.a)}${R(0, 0, w, h, `url(#${haze})`)}${stripes(0, h * .6, w, h * .4, 26, 4, alpha(k.b, .1), { vertical: true })}${R(0, h * .6, w, h * .4, `url(#${floor})`)}
        ${enter(`${D(`M${w * .25} ${h * .6}A${w * .25} ${h * .32} 0 0 1 ${w * .75} ${h * .6}`, 'none', { stroke: k.c, sw: 8 })}${R(w * .38, h * .6, w * .24, h * .34, 'none', { stroke: k.d, sw: 6 })}`, 'draw', { dur: k.beat * 1.4, ease: 'inOut' })}
        ${enter(`${T(w / 2, h * .5, k.title, { font: 'sixCaps', size: h * .34, fill: k.b, anchor: 'middle', upper: true, tracking: .04, fitW: w * .8, stroke: k.c, strokeWidth: 3 })}`, 'drop', { dur: k.beat * .6, delay: k.beat * .6, ease: 'back', amount: .8 })}
        ${enter(`${T(w / 2, h * .74, k.subtitle, { font: 'chakra', size: h * .03, weight: 700, fill: k.d, anchor: 'middle', tracking: .24, upper: true, fitW: w * .5 })}`, 'fade', { dur: k.beat, delay: k.beat * 1.4 })}
        ${enter(`<g transform="scale(1 -1) translate(0 ${-h * 1.2})" opacity=".18">${T(w / 2, h * .5, k.title, { font: 'sixCaps', size: h * .34, fill: k.b, anchor: 'middle', upper: true, tracking: .04, fitW: w * .8 })}</g>`, 'fade', { dur: k.beat, delay: k.beat * 1.2 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .74, w * .44, h * .16, alpha(k.a, .85), { stroke: k.c, sw: 3 })}${R(w * .05, h * .74, h * .16, h * .16, k.c)}${T(w * .05 + h * .08, h * .87, '24', { font: 'sixCaps', size: h * .14, fill: k.a, anchor: 'middle' })}
        ${T(w * .05 + h * .19, h * .82, k.title, { font: 'sixCaps', size: h * .09, fill: k.b, upper: true, tracking: .04, fitW: w * .28 })}${T(w * .05 + h * .19, h * .87, k.subtitle, { font: 'chakra', size: h * .021, weight: 700, fill: k.d, tracking: .2, upper: true, fitW: w * .28 })}`, 'drop', { dur: k.beat * .5, ease: 'back', amount: .5 }); },
    fullPage: k => { const { w, h } = k; const haze = k.uid('hz'); k.defs.push(gradient(haze, [[0, k.c, .5], [1, k.c, 0]], { radial: true, cx: .7, cy: .2, r: .6 }));
      return `${R(0, 0, w, h, k.a)}${R(0, 0, w, h, `url(#${haze})`)}${SPORTS_DESIGNS['neon-hardwood'].field(k, 0, h * .5, w, h * .5, 1)}${slot(k, w * .08, h * .1, w * .4, h * .8, { tone: 'dark', filter: undefined, frame: k.c, frameWidth: 3 })}
        ${enter(`${T(w * .54, h * .45, twoLines(k.title)[0], { font: 'sixCaps', size: h * .22, fill: k.b, upper: true, lines: twoLines(k.title), leading: .86, fitW: w * .4, stroke: k.c, strokeWidth: 2 })}${T(w * .54, h * .68, k.subtitle, { font: 'exo2', size: h * .026, weight: 600, fill: k.d, tracking: .12, upper: true, fitW: w * .4 })}${[['PTS', '31'], ['REB', '12'], ['AST', '9']].map(([l, v], n) => `${R(w * (.54 + n * .14), h * .74, w * .12, h * .14, alpha(k.b, .08), { stroke: k.c, sw: 2 })}${T(w * (.6 + n * .14), h * .8, l, { font: 'chakra', size: h * .02, weight: 700, fill: k.d, anchor: 'middle', tracking: .2 })}${T(w * (.6 + n * .14), h * .86, v, { font: 'sixCaps', size: h * .07, fill: k.b, anchor: 'middle' })}`).join('')}`, 'drop', { dur: k.beat * .6, delay: k.beat * .4, ease: 'back', amount: .5 })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${stripes(0, 0, w, h, 40, 3, alpha(k.b, .08), { vertical: true })}${R(0, 0, w, 6, k.c)}${T(w * .03, h * .8, k.title, { font: 'sixCaps', size: h * .86, fill: k.b, upper: true, fitW: w * .34 })}${R(w * .5, h * .1, w * .26, h * .8, k.c)}${T(w * .61, h * .82, k.scoreHome, { font: 'sixCaps', size: h * .8, fill: k.a, anchor: 'end' })}${R(w * .625, h * .3, 6, h * .4, k.a)}${T(w * .65, h * .82, k.scoreAway, { font: 'sixCaps', size: h * .8, fill: k.a })}${pulse(T(w * .96, h * .74, k.subtitle, { font: 'sixCaps', size: h * .6, fill: k.d, anchor: 'end', fitW: w * .16 }), 1.2, .6, 1)}`; },
  },

  /* ── Scorebook Classic — penciled notation; inning cells flip with tactile easing ── */
  'scorebook-classic': {
    type: { display: 'playfair', text: 'lora', utility: 'courierPrime' }, idea: 'The scorekeeper\'s ruled page: a diamond traced in pencil, inning cells in a hairline grid, a news-serif masthead.', ground: 'a', surface: 'PAPER',
    mark: (k, cx, cy, s) => `${PolyG([[cx, cy - s * .48], [cx + s * .48, cy], [cx, cy + s * .48], [cx - s * .48, cy]], 'none', { stroke: k.b, sw: s * .05 })}${C(cx, cy + s * .48, s * .07, k.c)}${C(cx + s * .48, cy, s * .05, k.b)}`,
    field: (k, x, y, w, h, i = 1) => { const out: string[] = []; const cell = 90; for (let n = 0; n * cell <= w; n++) out.push(L(x + n * cell, y, x + n * cell, y + h, alpha(k.b, .35 * i), 1.5)); for (let j = 0; j * cell <= h; j++) out.push(L(x, y + j * cell, x + w, y + j * cell, alpha(k.b, .35 * i), 1.5)); return out.join(''); },
    opener: k => { const { w, h } = k; const cell = 96;
      const grid = SPORTS_DESIGNS['scorebook-classic'].field(k, w * .06, h * .3, w * .88, cell * 5, 1);
      const diamond = (x: number, y: number) => PolyG([[x + cell / 2, y + 12], [x + cell - 12, y + cell / 2], [x + cell / 2, y + cell - 12], [x + 12, y + cell / 2]], 'none', { stroke: k.c, sw: 3 });
      return `${R(0, 0, w, h, k.a)}${stripes(0, 0, w, h, 30, 1, alpha(k.b, .12))}${R(w * .06, h * .08, w * .88, 3, k.b)}${R(w * .06, h * .1, w * .88, 1.5, k.b)}
        ${enter(`${T(w * .06, h * .22, k.title, { font: 'playfair', size: h * .1, weight: 900, fill: k.b, fitW: w * .7 })}${T(w * .94, h * .22, 'No. 7', { font: 'playfair', size: h * .06, weight: 400, fill: k.c, anchor: 'end', italic: true })}`, 'fade', { dur: k.beat })}
        ${enter(grid, 'fade', { dur: k.beat, delay: k.beat * .4 })}
        ${['1', '2', '3', '4', '5', '6', '7', '8', '9'].map((inn, n) => enter(`${T(w * .06 + (n + 1) * cell + cell / 2, h * .3 - 12, inn, { font: 'courierPrime', size: 22, fill: k.b, anchor: 'middle' })}${n < 4 ? diamond(w * .06 + (n + 1) * cell, h * .3 + cell) : ''}`, 'fade', { dur: k.beat * .4, delay: k.beat * (.8 + n * .18) })).join('')}
        ${enter(`${R(w * .06, h * .3, cell, cell * 5, k.d, { opacity: .12 })}${['LEADOFF', 'CATCHER', 'FIRST', 'SHORT', 'CENTRE'].map((p, n) => T(w * .06 + 10, h * .3 + n * cell + cell * .6, p, { font: 'courierPrime', size: 18, fill: k.b, tracking: .06 })).join('')}`, 'fade', { dur: k.beat, delay: k.beat * 1.2 })}
        ${enter(`${T(w * .06, h * .9, k.subtitle, { font: 'lora', size: h * .026, weight: 400, fill: k.c, italic: true, fitW: w * .6 })}`, 'fade', { dur: k.beat, delay: k.beat * 2.4 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .75, w * .48, h * .14, k.a, { stroke: k.b, sw: 2 })}${[1, 2, 3].map(n => L(w * .05 + n * 60, h * .75, w * .05 + n * 60, h * .89, alpha(k.b, .5), 1.5)).join('')}${L(w * .05, h * .82, w * .05 + 180, h * .82, alpha(k.b, .5), 1.5)}${PolyG([[w * .05 + 30, h * .77], [w * .05 + 52, h * .785], [w * .05 + 30, h * .8], [w * .05 + 8, h * .785]], 'none', { stroke: k.c, sw: 2 })}
        ${T(w * .05 + 200, h * .815, k.title, { font: 'playfair', size: h * .05, weight: 900, fill: k.b, fitW: w * .3 })}${T(w * .05 + 200, h * .86, k.subtitle, { font: 'courierPrime', size: h * .02, fill: k.c, tracking: .04, fitW: w * .3 })}`, 'fade', { dur: k.beat }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${stripes(0, 0, w, h, 34, 1, alpha(k.b, .12))}${R(w * .06, h * .07, w * .88, 3, k.b)}${R(w * .06, h * .09, w * .88, 1.5, k.b)}${slot(k, w * .06, h * .14, w * .44, h * .6, { tone: 'light', frame: k.b, frameWidth: 2, filter: undefined })}${SPORTS_DESIGNS['scorebook-classic'].field(k, w * .06, h * .76, w * .44, h * .16, .8)}
        ${enter(`${T(w * .54, h * .3, twoLines(k.title)[0], { font: 'playfair', size: h * .08, weight: 900, fill: k.b, lines: twoLines(k.title), fitW: w * .4 })}${T(w * .54, h * .5, k.subtitle, { font: 'lora', size: h * .024, weight: 400, fill: k.c, italic: true, fitW: w * .4 })}${[['AVG', '.318'], ['HR', '27'], ['RBI', '84'], ['OPS', '.912']].map(([l, v], n) => `${T(w * .54, h * (.6 + n * .07), l, { font: 'courierPrime', size: h * .022, fill: k.b, tracking: .1 })}${T(w * .92, h * (.6 + n * .07), v, { font: 'courierPrime', size: h * .03, fill: k.c, anchor: 'end' })}${L(w * .54, h * (.615 + n * .07), w * .92, h * (.615 + n * .07), alpha(k.b, .4), 1.5, { dash: '3 4' })}`).join('')}`, 'fade', { dur: k.beat * 1.4, delay: k.beat * .6 })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${R(0, 0, w, 3, k.b)}${R(0, h - 3, w, 3, k.b)}${T(w * .03, h * .66, k.title, { font: 'playfair', size: h * .36, weight: 900, fill: k.b, fitW: w * .3 })}${Array.from({ length: 9 }, (_, n) => `${L(w * (.4 + n * .045), h * .15, w * (.4 + n * .045), h * .85, alpha(k.b, .5), 1.5)}${T(w * (.4225 + n * .045), h * .42, String(n + 1), { font: 'courierPrime', size: h * .14, fill: k.c, anchor: 'middle' })}${T(w * (.4225 + n * .045), h * .76, n < 5 ? String((n * 7) % 3) : '', { font: 'courierPrime', size: h * .2, fill: k.b, anchor: 'middle' })}`).join('')}${L(w * .4, h * .5, w * .805, h * .5, alpha(k.b, .5), 1.5)}${score(k, w * .87, h * .7, h * .5, 'courierPrime', k.b, 700)}`; },
  },

  /* ── Telemetry Redline — timing towers; elements accelerate, overshoot minimally, brake into alignment ── */
  'telemetry-redline': {
    type: { display: 'chakra', text: 'exo2', utility: 'jetbrains' }, idea: 'A timing tower and a velocity trace: everything moves at racing speed and brakes hard into tabular alignment.', ground: 'a', surface: 'SCAN', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${PolyG([[cx - s * .5, cy + s * .2], [cx - s * .2, cy - s * .3], [cx + s * .5, cy - s * .3], [cx + s * .2, cy + s * .2]], k.c)}${L(cx - s * .5, cy + s * .35, cx + s * .5, cy + s * .35, k.b, s * .06)}`,
    field: (k, x, y, w, h, i = 1) => `${checker(x, y, w, h, 14, alpha(k.b, .05 * i))}${D(`M${x} ${y + h * .8}L${x + w * .2} ${y + h * .3}L${x + w * .35} ${y + h * .6}L${x + w * .55} ${y + h * .15}L${x + w * .7} ${y + h * .5}L${x + w} ${y + h * .25}`, 'none', { stroke: k.c, sw: 4 * i })}`,
    opener: k => { const { w, h } = k;
      const rows = ['01', '02', '03', '04', '05'];
      return `${R(0, 0, w, h, k.a)}${checker(0, 0, w, h, 14, alpha(k.b, .04))}${stripes(0, 0, w, h, 6, 1, alpha(k.b, .15))}
        ${enter(D(`M0 ${h * .82}L${w * .18} ${h * .5}L${w * .3} ${h * .66}L${w * .48} ${h * .22}L${w * .62} ${h * .52}L${w} ${h * .3}`, 'none', { stroke: k.c, sw: 5 }), 'draw', { dur: k.beat * 1.2, ease: 'in' })}
        ${rows.map((r, n) => enter(`${R(w * .06, h * .12 + n * h * .075, w * .3, h * .062, n === 0 ? k.c : alpha(k.b, .1))}${T(w * .075, h * .165 + n * h * .075, r, { font: 'jetbrains', size: h * .034, weight: 700, fill: n === 0 ? k.a : k.b })}${T(w * .13, h * .165 + n * h * .075, ['REPLACEABLE', 'DRIVER TWO', 'DRIVER THREE', 'DRIVER FOUR', 'DRIVER FIVE'][n], { font: 'chakra', size: h * .03, weight: 700, fill: n === 0 ? k.a : k.b, tracking: .06 })}${T(w * .35, h * .165 + n * h * .075, ['LEADER', '+0.412', '+1.087', '+3.550', '+7.201'][n], { font: 'jetbrains', size: h * .028, weight: 500, fill: n === 0 ? k.a : k.d, anchor: 'end' })}`, 'slideL', { dur: k.beat * .35, delay: k.beat * .12 * n, ease: 'expo', amount: 2 })).join('')}
        ${enter(`${T(w * .94, h * .82, k.title, { font: 'chakra', size: h * .11, weight: 700, fill: k.b, anchor: 'end', upper: true, fitW: w * .5 })}${R(w * .44, h * .845, w * .5, 6, k.c)}${T(w * .94, h * .9, k.subtitle, { font: 'jetbrains', size: h * .022, weight: 500, fill: k.d, anchor: 'end', tracking: .18, upper: true, fitW: w * .5 })}`, 'slideR', { dur: k.beat * .5, delay: k.beat * .8, ease: 'expo', amount: 2 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .77, w * .46, h * .12, alpha(k.a, .9))}${R(w * .05, h * .77, w * .07, h * .12, k.c)}${T(w * .085, h * .855, '01', { font: 'jetbrains', size: h * .06, weight: 700, fill: k.a, anchor: 'middle' })}${R(w * .05, h * .89, w * .46, 4, k.c)}
        ${T(w * .14, h * .82, k.title, { font: 'chakra', size: h * .046, weight: 700, fill: k.b, upper: true, tracking: .04, fitW: w * .3 })}${T(w * .14, h * .865, k.subtitle, { font: 'jetbrains', size: h * .02, weight: 500, fill: k.d, tracking: .16, upper: true, fitW: w * .3 })}`, 'slideL', { dur: k.beat * .4, amount: 2.5 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['telemetry-redline'].field(k, 0, h * .5, w, h * .5, .7)}${slot(k, w * .06, h * .1, w * .5, h * .56, { tone: 'dark', frame: k.c, frameWidth: 2 })}
        ${enter(`${R(w * .6, h * .1, w * .34, h * .8, alpha(k.b, .06), { stroke: k.b, sw: 1.5 })}${T(w * .63, h * .25, twoLines(k.title)[0], { font: 'chakra', size: h * .07, weight: 700, fill: k.b, upper: true, lines: twoLines(k.title), fitW: w * .28 })}${T(w * .63, h * .42, k.subtitle, { font: 'exo2', size: h * .022, weight: 500, fill: k.d, fitW: w * .28 })}${[['SPEED TRAP', '318 km/h'], ['SECTOR 2', '28.114'], ['TYRE', 'MEDIUM · L14'], ['GAP', '+0.412']].map(([l, v], n) => `${T(w * .63, h * (.54 + n * .08), l, { font: 'jetbrains', size: h * .017, weight: 500, fill: k.d, tracking: .18 })}${T(w * .63, h * (.585 + n * .08), v, { font: 'chakra', size: h * .036, weight: 700, fill: n === 3 ? k.c : k.b })}`).join('')}`, 'slideR', { dur: k.beat * .5, ease: 'expo', amount: 2 })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${checker(0, 0, w, h, 12, alpha(k.b, .05))}${R(0, 0, w * .04, h, k.c)}${T(w * .06, h * .68, k.title, { font: 'chakra', size: h * .42, weight: 700, fill: k.b, upper: true, fitW: w * .34 })}${['01', '02', '03'].map((p, n) => `${R(w * (.46 + n * .17), h * .2, w * .16, h * .6, n ? alpha(k.b, .08) : k.c)}${T(w * (.47 + n * .17), h * .64, p, { font: 'jetbrains', size: h * .34, weight: 700, fill: n ? k.b : k.a })}${T(w * (.61 + n * .17), h * .64, n ? `+${(n * .87).toFixed(3)}` : k.scoreHome, { font: 'jetbrains', size: h * .26, weight: 500, fill: n ? k.d : k.a, anchor: 'end' })}`).join('')}`; },
  },

  /* ── Tale of the Tape — opposing columns approach centre; the final stat lands like a bell ── */
  'tale-of-tape': {
    type: { display: 'anton', text: 'oswald', utility: 'ibmPlexMono' }, idea: 'Two fighters as two columns of measurements closing on a centre line; the last stat strikes and the plate holds.', ground: 'a', surface: 'CLEAN', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${R(cx - s * .5, cy - s * .04, s, s * .08, k.b)}${R(cx - s * .04, cy - s * .5, s * .08, s, k.c)}${C(cx, cy, s * .12, k.a, { stroke: k.d, sw: s * .04 })}`,
    field: (k, x, y, w, h, i = 1) => `${L(x + w / 2, y, x + w / 2, y + h, alpha(k.b, .5 * i), 3)}${[0, 1, 2, 3].map(n => `${R(x + w * .1, y + h * (.15 + n * .2), w * .3, 10, alpha(k.c, .6 * i))}${R(x + w * .6, y + h * (.15 + n * .2), w * .3, 10, alpha(k.d, .6 * i))}`).join('')}`,
    opener: k => { const { w, h } = k;
      const rows = [['REACH', '76"', '74"'], ['HEIGHT', '6\'1"', '5\'11"'], ['WEIGHT', '160', '159'], ['RECORD', '24–1', '22–0']];
      return `${R(0, 0, w, h, k.a)}${L(w / 2, 0, w / 2, h, k.b, 3)}${R(w / 2 - 2, 0, 4, h, alpha(k.b, .5))}
        ${enter(`${R(0, h * .12, w * .48, h * .14, k.c)}${T(w * .46, h * .22, 'RED CORNER', { font: 'anton', size: h * .07, fill: k.a, anchor: 'end', upper: true, tracking: .02 })}`, 'slideL', { dur: k.beat * .5, ease: 'expo', amount: 3 })}
        ${enter(`${R(w * .52, h * .12, w * .48, h * .14, k.d)}${T(w * .54, h * .22, 'BLUE CORNER', { font: 'anton', size: h * .07, fill: k.a, upper: true, tracking: .02 })}`, 'slideR', { dur: k.beat * .5, ease: 'expo', amount: 3 })}
        ${rows.map(([l, a, b], n) => enter(`${T(w / 2, h * (.38 + n * .11), l, { font: 'ibmPlexMono', size: h * .022, weight: 500, fill: k.b, anchor: 'middle', tracking: .24 })}${T(w * .44, h * (.39 + n * .11), a, { font: 'anton', size: h * .075, fill: k.b, anchor: 'end' })}${T(w * .56, h * (.39 + n * .11), b, { font: 'anton', size: h * .075, fill: k.b })}${L(w * .3, h * (.41 + n * .11), w * .7, h * (.41 + n * .11), alpha(k.b, .25), 1.5)}`, n === rows.length - 1 ? 'pop' : 'fade', { dur: k.beat * .4, delay: k.beat * (.7 + n * .32), ease: n === rows.length - 1 ? 'back' : 'out', origin: [w / 2, h * (.39 + n * .11)] })).join('')}
        ${enter(`${R(w * .3, h * .86, w * .4, h * .08, k.b)}${T(w / 2, h * .92, k.title, { font: 'anton', size: h * .05, fill: k.a, anchor: 'middle', upper: true, tracking: .06, fitW: w * .36 })}`, 'growX', { dur: k.beat * .5, delay: k.beat * 2, ease: 'expo', origin: [w / 2, h * .9] })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${PolyG([[w * .05, h * .76], [w * .3, h * .76], [w * .28, h * .9], [w * .05, h * .9]], k.c)}${PolyG([[w * .3, h * .76], [w * .55, h * .76], [w * .55, h * .9], [w * .28, h * .9]], k.d)}${R(w * .29, h * .74, 4, h * .18, k.b)}
        ${T(w * .27, h * .83, k.title, { font: 'anton', size: h * .058, fill: k.a, anchor: 'end', upper: true, fitW: w * .2 })}${T(w * .27, h * .875, 'RED CORNER', { font: 'ibmPlexMono', size: h * .018, weight: 500, fill: k.a, anchor: 'end', tracking: .2 })}${T(w * .32, h * .83, k.subtitle, { font: 'anton', size: h * .058, fill: k.a, upper: true, fitW: w * .2 })}${T(w * .32, h * .875, 'BLUE CORNER', { font: 'ibmPlexMono', size: h * .018, weight: 500, fill: k.a, tracking: .2 })}`, 'pop', { dur: k.beat * .4, ease: 'back', amount: .4, origin: [w * .3, h * .83] }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${L(w / 2, 0, w / 2, h, k.b, 3)}${slot(k, w * .06, h * .1, w * .4, h * .56, { tone: 'dark', frame: k.c, frameWidth: 6 })}${slot(k, w * .54, h * .1, w * .4, h * .56, { tone: 'dark', frame: k.d, frameWidth: 6 })}
        ${enter(`${R(0, h * .7, w * .5, h * .14, k.c)}${R(w * .5, h * .7, w * .5, h * .14, k.d)}${T(w * .46, h * .8, k.title, { font: 'anton', size: h * .07, fill: k.a, anchor: 'end', upper: true, fitW: w * .38 })}${T(w * .54, h * .8, k.subtitle, { font: 'anton', size: h * .07, fill: k.a, upper: true, fitW: w * .38 })}${T(w / 2, h * .92, 'TALE OF THE TAPE', { font: 'ibmPlexMono', size: h * .024, weight: 500, fill: k.b, anchor: 'middle', tracking: .3 })}`, 'pop', { dur: k.beat * .5, delay: k.beat * .4, ease: 'back', amount: .4, origin: [w / 2, h * .77] })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${PolyG([[0, 0], [w * .5, 0], [w * .48, h], [0, h]], k.c)}${PolyG([[w * .5, 0], [w, 0], [w, h], [w * .48, h]], k.d)}${R(w * .49, 0, 8, h, k.b)}${T(w * .44, h * .68, k.title, { font: 'anton', size: h * .46, fill: k.a, anchor: 'end', upper: true, fitW: w * .3 })}${T(w * .56, h * .68, k.subtitle, { font: 'anton', size: h * .46, fill: k.a, upper: true, fitW: w * .3 })}${T(w * .06, h * .68, k.scoreHome, { font: 'anton', size: h * .5, fill: k.a })}${T(w * .94, h * .68, k.scoreAway, { font: 'anton', size: h * .5, fill: k.a, anchor: 'end' })}`; },
  },

  /* ── Velocity Lanes — staggered lane delays; a photo-finish freeze ── */
  'velocity-lanes': {
    type: { display: 'syne', text: 'dmSans', utility: 'spaceMono' }, idea: 'Eight lanes sweep left to right at staggered delays and freeze on a finish line; split times read like a photo finish.', ground: 'a', surface: 'SCAN', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${[0, 1, 2, 3].map(n => R(cx - s * .5, cy - s * .4 + n * s * .24, s * (.6 + n * .12), s * .1, n % 2 ? k.c : k.d)).join('')}${L(cx + s * .45, cy - s * .5, cx + s * .45, cy + s * .5, k.b, s * .05)}`,
    field: (k, x, y, w, h, i = 1) => `${stripes(x, y, w, h, 8, 3, alpha(k.b, .35 * i))}${[0, 1, 2, 3, 4, 5, 6, 7].map(n => R(x, y + n * h / 8 + h / 32, w * (.3 + ((n * 7) % 5) * .12) * i, h / 24, n % 2 ? alpha(k.c, .7) : alpha(k.d, .7))).join('')}`,
    opener: k => { const { w, h } = k; const laneH = h * .085;
      return `${R(0, 0, w, h, k.a)}${stripes(0, h * .16, w, laneH * 8, 9, 3, alpha(k.b, .35))}${enter(L(w * .86, h * .14, w * .86, h * .84, k.b, 6), 'growY', { dur: k.beat * .8, ease: 'expo', origin: [w * .86, h * .5] })}
        ${[0, 1, 2, 3, 4, 5, 6, 7].map(n => enter(`${R(0, h * .16 + n * laneH + laneH * .3, w * .86, laneH * .4, n % 2 ? k.c : k.d)}${T(w * .84, h * .16 + n * laneH + laneH * .68, ['9.87', '9.91', '9.94', '10.02', '10.05', '10.11', '10.19', '10.24'][n], { font: 'spaceMono', size: laneH * .5, weight: 700, fill: k.a, anchor: 'end' })}${T(w * .02, h * .16 + n * laneH + laneH * .68, String(n + 1), { font: 'spaceMono', size: laneH * .5, weight: 700, fill: k.a })}`, 'wipeR', { dur: k.beat * (1.2 + n * .12), delay: k.beat * .1 * n, ease: 'expo' })).join('')}
        ${enter(`${R(w * .88, h * .16, w * .12, laneH * 8, k.b)}${T(w * .94, h * .55, 'FIN', { font: 'syne', size: h * .05, weight: 800, fill: k.a, anchor: 'middle', rotate: -90 })}`, 'fade', { dur: k.beat * .4, delay: k.beat * 1.4 })}
        ${enter(`${T(w * .02, h * .1, k.title, { font: 'syne', size: h * .07, weight: 800, fill: k.b, upper: true, fitW: w * .6 })}${T(w * .02, h * .93, k.subtitle, { font: 'dmSans', size: h * .024, weight: 500, fill: k.d, tracking: .16, upper: true, fitW: w * .6 })}`, 'fade', { dur: k.beat, delay: k.beat * 2 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${[0, 1, 2].map(n => R(w * .05, h * (.74 + n * .05), w * (.44 - n * .06), h * .028, n % 2 ? k.d : k.c)).join('')}${R(w * .05, h * .74, w * .012, h * .16, k.b)}
        ${T(w * .07, h * .905, k.title, { font: 'syne', size: h * .05, weight: 800, fill: k.b, upper: true, fitW: w * .42 })}${T(w * .07, h * .945, k.subtitle, { font: 'spaceMono', size: h * .02, weight: 700, fill: k.d, tracking: .1, fitW: w * .42 })}`, 'wipeR', { dur: k.beat * .7 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['velocity-lanes'].field(k, 0, h * .55, w, h * .45, .7)}${slot(k, w * .06, h * .08, w * .52, h * .44, { tone: 'dark' })}${L(w * .58, h * .08, w * .58, h * .52, k.b, 6)}
        ${enter(`${T(w * .62, h * .24, twoLines(k.title)[0], { font: 'syne', size: h * .07, weight: 800, fill: k.b, upper: true, lines: twoLines(k.title), fitW: w * .32 })}${T(w * .62, h * .4, k.subtitle, { font: 'dmSans', size: h * .022, weight: 500, fill: k.d, fitW: w * .32 })}${[['REACTION', '0.142'], ['60 m', '6.38'], ['FINISH', '9.87']].map(([l, v], n) => `${T(w * .62, h * (.47 + n * .045), l, { font: 'spaceMono', size: h * .017, weight: 700, fill: k.c, tracking: .12 })}${T(w * .94, h * (.47 + n * .045), v, { font: 'spaceMono', size: h * .028, weight: 700, fill: k.b, anchor: 'end' })}`).join('')}`, 'slideR', { dur: k.beat * .8, ease: 'expo', amount: 1.5 })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${[0, 1, 2].map(n => R(0, h * (.15 + n * .3), w * (.3 - n * .04), h * .1, n % 2 ? k.d : k.c)).join('')}${T(w * .33, h * .68, k.title, { font: 'syne', size: h * .4, weight: 800, fill: k.b, upper: true, fitW: w * .3 })}${score(k, w * .82, h * .7, h * .52, 'spaceMono', k.b, 700)}${R(w * .97, 0, 6, h, k.b)}`; },
  },

  /* ── Ice Prism — facets refract; scores settle with low-friction glide ── */
  'ice-prism': {
    type: { display: 'outfit', text: 'karla', utility: 'dmMono' }, idea: 'Cold spectrum facets refract across the frame; the type glides in on a frictionless line and settles.', ground: 'a', surface: 'GLASS',
    mark: (k, cx, cy, s) => `${PolyG([[cx, cy - s * .5], [cx + s * .45, cy - s * .1], [cx + s * .25, cy + s * .5], [cx - s * .25, cy + s * .5], [cx - s * .45, cy - s * .1]], alpha(k.c, .5), { stroke: k.c, sw: s * .03 })}${PolyG([[cx, cy - s * .5], [cx + s * .45, cy - s * .1], [cx, cy + s * .1]], alpha(k.d, .6))}`,
    field: (k, x, y, w, h, i = 1) => `${[0, 1, 2, 3, 4].map(n => PolyG([[x + w * (.1 + n * .18), y], [x + w * (.28 + n * .18), y], [x + w * (.2 + n * .18), y + h], [x + w * (.02 + n * .18), y + h]], n % 2 ? alpha(k.c, .16 * i) : alpha(k.d, .16 * i))).join('')}`,
    opener: k => { const { w, h } = k; const cold = k.uid('ic'); k.defs.push(gradient(cold, [[0, k.d, .35], [.5, k.c, .12], [1, k.a, 0]], { angle: 135 }));
      const facets = [[.05, 0, .35, .15, .28, 1, .0, 1], [.3, 0, .62, 0, .5, 1, .22, 1], [.58, 0, .95, 0, .78, 1, .5, 1]].map((f, n) => enter(PolyG([[w * f[0], h * f[1]], [w * f[2], h * f[3]], [w * f[4], h * f[5]], [w * f[6], h * f[7]]], n % 2 ? alpha(k.c, .18) : alpha(k.d, .14), { stroke: alpha(k.b, .5), sw: 2 }), 'slideR', { dur: k.beat * 1.6, delay: k.beat * .2 * n, ease: 'expo', amount: 1.5 + n })).join('');
      return `${R(0, 0, w, h, k.a)}${R(0, 0, w, h, `url(#${cold})`)}${facets}
        ${enter(`${T(w * .08, h * .58, k.title, { font: 'outfit', size: h * .12, weight: 700, fill: k.b, fitW: w * .6 })}${L(w * .08, h * .63, w * .08 + 220, h * .63, k.c, 3)}${T(w * .08, h * .69, k.subtitle, { font: 'karla', size: h * .026, weight: 400, fill: k.d, tracking: .1, upper: true, fitW: w * .6 })}`, 'slideL', { dur: k.beat * 1.6, delay: k.beat * .8, ease: 'expo', amount: .8 })}
        ${drift(PolyG([[w * .7, 0], [w * .78, 0], [w * .6, h], [w * .52, h]], alpha(k.b, .12), { blend: 'screen' }), w * .3, 0, k.beat * 8)}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${PolyG([[w * .05, h * .76], [w * .52, h * .76], [w * .49, h * .9], [w * .05, h * .9]], alpha(k.a, .8), { stroke: alpha(k.c, .7), sw: 2 })}${PolyG([[w * .05, h * .76], [w * .12, h * .76], [w * .09, h * .9], [w * .05, h * .9]], alpha(k.c, .5))}
        ${T(w * .14, h * .82, k.title, { font: 'outfit', size: h * .05, weight: 700, fill: k.b, fitW: w * .32 })}${T(w * .14, h * .865, k.subtitle, { font: 'dmMono', size: h * .02, weight: 500, fill: k.d, tracking: .12, upper: true, fitW: w * .32 })}`, 'slideL', { dur: k.beat * 1.3, amount: 1.4 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['ice-prism'].field(k, 0, 0, w, h, .8)}${slot(k, w * .08, h * .12, w * .44, h * .76, { tone: 'dark', shape: 'path', d: 'M12 0L100 0L88 100L0 100Z', frame: k.c, frameWidth: 2 })}
        ${enter(`${T(w * .58, h * .36, twoLines(k.title)[0], { font: 'outfit', size: h * .08, weight: 700, fill: k.b, lines: twoLines(k.title), fitW: w * .36 })}${T(w * .58, h * .54, k.subtitle, { font: 'karla', size: h * .024, weight: 400, fill: k.d, fitW: w * .36 })}${[['TIME', '1:47.22'], ['SPLIT', '+0.31'], ['RUN', '2 / 2']].map(([l, v], n) => `${T(w * .58, h * (.64 + n * .06), l, { font: 'dmMono', size: h * .017, weight: 500, fill: k.c, tracking: .16 })}${T(w * .92, h * (.64 + n * .06), v, { font: 'outfit', size: h * .032, weight: 700, fill: k.b, anchor: 'end' })}`).join('')}`, 'slideR', { dur: k.beat * 1.2, ease: 'expo', amount: 1.4 })}`; },
  },

  /* ── Tidal Tour — swell, tide, sun angle; cards rise and recede on long curves ── */
  'tidal-tour': {
    type: { display: 'fredoka', text: 'nunito', utility: 'dmMono' }, idea: 'A rounded score card rises on a long easing curve over a rolling swell; the sun angle sets the palette.', ground: 'a', surface: 'TOPO',
    mark: (k, cx, cy, s) => `${C(cx + s * .15, cy - s * .2, s * .22, k.d)}${P(cx - s * .5, cy - s * .1, s, s * .6, orn.wavePath(2, 26, 30), k.c)}`,
    field: (k, x, y, w, h, i = 1) => `${[0, 1, 2].map(n => P(x - w * .1, y + h * (.3 + n * .22), w * 1.2, h * .3, orn.wavePath(3, 20, 28 - n * 6, n * .8), n % 2 ? alpha(k.c, .7 * i) : alpha(k.b, .5 * i))).join('')}`,
    opener: k => { const { w, h } = k; const sun = k.uid('sn'); k.defs.push(gradient(sun, [[0, k.d, .9], [1, k.d, 0]], { radial: true, cx: .78, cy: .22, r: .3 }));
      return `${R(0, 0, w, h, k.a)}${R(0, 0, w, h, `url(#${sun})`)}${C(w * .78, h * .22, h * .09, k.d)}
        ${[0, 1, 2, 3].map(n => drift(P(-w * .2, h * (.5 + n * .12), w * 1.4, h * .3, orn.wavePath(3, 22, 30 - n * 5, n * .9), n % 2 ? k.c : mix(k.c, -.25), { opacity: .9 }), -w * .12 * (n + 1), 0, k.beat * (9 + n * 2))).join('')}
        ${enter(`${R(w * .08, h * .18, w * .38, h * .44, k.b, { rx: 36 })}${T(w * .12, h * .3, k.eyebrow, { font: 'dmMono', size: h * .02, weight: 500, fill: k.c, tracking: .18, upper: true })}${T(w * .12, h * .42, k.title, { font: 'fredoka', size: h * .08, weight: 700, fill: k.a, fitW: w * .3 })}${T(w * .12, h * .48, k.subtitle, { font: 'nunito', size: h * .024, weight: 600, fill: k.a, fitW: w * .3 })}${T(w * .12, h * .58, '8.73', { font: 'fredoka', size: h * .06, weight: 700, fill: k.c })}${T(w * .24, h * .58, 'HEAT SCORE', { font: 'dmMono', size: h * .017, weight: 500, fill: k.a, tracking: .18 })}`, 'slideU', { dur: k.beat * 2.4, ease: 'expo', amount: 2 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .74, w * .44, h * .16, k.b, { rx: 28 })}${C(w * .11, h * .82, h * .05, k.c)}${P(w * .07, h * .8, 100, 40, orn.wavePath(2, 24, 30), k.d)}
        ${T(w * .17, h * .815, k.title, { font: 'fredoka', size: h * .05, weight: 700, fill: k.a, fitW: w * .3 })}${T(w * .17, h * .86, k.subtitle, { font: 'nunito', size: h * .022, weight: 600, fill: k.a, fitW: w * .3 })}`, 'slideU', { dur: k.beat * 1.8, amount: 1.4 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['tidal-tour'].field(k, 0, h * .4, w, h * .6, 1)}${slot(k, w * .06, h * .08, w * .5, h * .58, { tone: 'dark', shape: 'soft', rx: 40 })}
        ${enter(`${R(w * .6, h * .12, w * .34, h * .76, k.b, { rx: 36 })}${T(w * .64, h * .3, twoLines(k.title)[0], { font: 'fredoka', size: h * .07, weight: 700, fill: k.a, lines: twoLines(k.title), fitW: w * .27 })}${T(w * .64, h * .48, k.subtitle, { font: 'nunito', size: h * .024, weight: 600, fill: k.a, fitW: w * .27 })}${[['SWELL', '6–8 ft'], ['TIDE', 'Rising'], ['WIND', 'Offshore 9 kn']].map(([l, v], n) => `${T(w * .64, h * (.58 + n * .08), l, { font: 'dmMono', size: h * .017, weight: 500, fill: k.c, tracking: .18 })}${T(w * .64, h * (.625 + n * .08), v, { font: 'fredoka', size: h * .036, weight: 700, fill: k.a })}`).join('')}`, 'slideU', { dur: k.beat * 2, ease: 'expo', amount: 1.5 })}`; },
  },

  /* ── Hologrid Esports — panels rotate in real 3D hierarchy; state travels as light ── */
  'hologrid-esports': {
    type: { display: 'delaGothic', text: 'sora', utility: 'jetbrains' }, idea: 'A lucid bracket in glass volumes: team panels, hairline connections, and state that travels as light along the lines.', ground: 'a', surface: 'GLOW', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${R(cx - s * .5, cy - s * .3, s * .4, s * .22, alpha(k.c, .5), { stroke: k.c, sw: s * .03 })}${R(cx - s * .5, cy + s * .08, s * .4, s * .22, alpha(k.d, .5), { stroke: k.d, sw: s * .03 })}${D(`M${cx - s * .1} ${cy - s * .19}H${cx + s * .1}V${cy + s * .19}H${cx - s * .1}M${cx + s * .1} ${cy}H${cx + s * .5}`, 'none', { stroke: k.b, sw: s * .03 })}`,
    field: (k, x, y, w, h, i = 1) => `${dots(x, y, w, h, 40, alpha(k.c, .5 * i), { r: 1.2 })}${[0, 1, 2].map(n => R(x + w * .1, y + h * (.2 + n * .25), w * .22, h * .12, alpha(k.c, .12 * i), { stroke: alpha(k.c, .6 * i), sw: 2 })).join('')}${D(`M${x + w * .32} ${y + h * .26}H${x + w * .45}V${y + h * .76}H${x + w * .32}M${x + w * .45} ${y + h * .5}H${x + w * .7}`, 'none', { stroke: alpha(k.b, .7 * i), sw: 2 })}`,
    opener: k => { const { w, h } = k; const panel = (x: number, y: number, name: string, win: boolean, delay: number) => enter(`${R(x, y, w * .2, h * .09, alpha(win ? k.c : k.b, win ? .22 : .06), { stroke: win ? k.c : alpha(k.b, .5), sw: 2 })}${T(x + 20, y + h * .058, name, { font: 'sora', size: h * .03, weight: 700, fill: k.b, tracking: .04, upper: true })}${T(x + w * .19, y + h * .058, win ? '2' : '1', { font: 'jetbrains', size: h * .034, weight: 700, fill: win ? k.c : k.d, anchor: 'end' })}`, 'slideL', { dur: k.beat * .5, delay, ease: 'expo', amount: 1.2 });
      const link = (d: string, delay: number) => enter(D(d, 'none', { stroke: k.d, sw: 2 }), 'draw', { dur: k.beat * .6, delay, ease: 'inOut' });
      const spark = (d: string) => `<circle r="6" fill="${k.c}"><animateMotion dur="${k.beat * 2.5}s" repeatCount="indefinite" path="${d}"/></circle>`;
      const l1 = `M${w * .27} ${h * .215}H${w * .32}V${h * .4}H${w * .38}`, l2 = `M${w * .27} ${h * .585}H${w * .32}V${h * .4}H${w * .38}`, l3 = `M${w * .58} ${h * .4}H${w * .64}`;
      return `${R(0, 0, w, h, k.a)}${dots(0, 0, w, h, 40, alpha(k.c, .35), { r: 1.2 })}
        ${panel(w * .07, h * .12, 'TEAM ALPHA', true, 0)}${panel(w * .07, h * .26, 'TEAM BRAVO', false, k.beat * .1)}${panel(w * .07, h * .49, 'TEAM CHARLIE', false, k.beat * .2)}${panel(w * .07, h * .63, 'TEAM DELTA', true, k.beat * .3)}
        ${link(l1, k.beat * .6)}${link(l2, k.beat * .7)}${panel(w * .38, h * .355, 'ALPHA', true, k.beat * 1)}${panel(w * .38, h * .5, 'DELTA', false, k.beat * 1.1)}${link(l3, k.beat * 1.4)}
        ${enter(`${R(w * .64, h * .3, w * .3, h * .2, alpha(k.c, .16), { stroke: k.c, sw: 3 })}${T(w * .79, h * .38, 'GRAND FINAL', { font: 'jetbrains', size: h * .02, weight: 700, fill: k.d, anchor: 'middle', tracking: .24 })}${T(w * .79, h * .46, k.title, { font: 'delaGothic', size: h * .05, fill: k.b, anchor: 'middle', upper: true, fitW: w * .26 })}`, 'pop', { dur: k.beat * .6, delay: k.beat * 1.7, ease: 'back', origin: [w * .79, h * .4] })}
        ${spark(l1)}${spark(l3)}
        ${enter(T(w * .07, h * .9, k.subtitle, { font: 'sora', size: h * .024, weight: 400, fill: k.d, tracking: .12, upper: true, fitW: w * .6 }), 'fade', { dur: k.beat, delay: k.beat * 2.2 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .75, w * .44, h * .14, alpha(k.a, .8), { stroke: k.c, sw: 2 })}${R(w * .05, h * .75, w * .012, h * .14, k.c)}${D(`M${w * .49} ${h * .82}H${w * .53}V${h * .7}`, 'none', { stroke: k.d, sw: 2 })}
        ${T(w * .08, h * .81, k.title, { font: 'delaGothic', size: h * .042, fill: k.b, upper: true, fitW: w * .34 })}${T(w * .08, h * .86, k.subtitle, { font: 'jetbrains', size: h * .019, weight: 500, fill: k.d, tracking: .16, upper: true, fitW: w * .34 })}`, 'slideL', { dur: k.beat * .6, amount: 1.2 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['hologrid-esports'].field(k, 0, 0, w, h, .6)}${slot(k, w * .06, h * .1, w * .46, h * .8, { tone: 'dark', frame: k.c, frameWidth: 2 })}
        ${enter(`${R(w * .56, h * .1, w * .38, h * .8, alpha(k.c, .08), { stroke: k.c, sw: 2 })}${T(w * .59, h * .28, twoLines(k.title)[0], { font: 'delaGothic', size: h * .06, fill: k.b, upper: true, lines: twoLines(k.title), fitW: w * .32 })}${T(w * .59, h * .46, k.subtitle, { font: 'sora', size: h * .022, weight: 400, fill: k.d, fitW: w * .32 })}${[['K / D', '2.41'], ['ADR', '108.7'], ['HS %', '61'], ['RATING', '1.38']].map(([l, v], n) => `${T(w * .59, h * (.56 + n * .07), l, { font: 'jetbrains', size: h * .017, weight: 700, fill: k.d, tracking: .18 })}${T(w * .91, h * (.56 + n * .07), v, { font: 'delaGothic', size: h * .034, fill: k.c, anchor: 'end' })}${L(w * .59, h * (.58 + n * .07), w * .91, h * (.58 + n * .07), alpha(k.c, .3), 1.5)}`).join('')}`, 'slideR', { dur: k.beat * .7, ease: 'expo', amount: 1.5 })}`; },
  },

  /* ── Global Games Ceremony — rings and routes converge slowly; one decisive kinetic signature ── */
  'global-games-ceremony': {
    type: { display: 'raleway', text: 'workSans', utility: 'tenor' }, idea: 'Five interlaced rings and mapped routes converge at ceremonial pace under a thin, dignified display face.', ground: 'a', surface: 'GRAIN',
    mark: (k, cx, cy, s) => `${[[-.3, -.12], [0, -.12], [.3, -.12], [-.15, .14], [.15, .14]].map(([ox, oy], n) => C(cx + ox * s, cy + oy * s, s * .18, 'none', { stroke: [k.c, k.d, k.b, k.c, k.d][n], sw: s * .04 })).join('')}`,
    field: (k, x, y, w, h, i = 1) => `${rings(x + w / 2, y + h / 2, [h * .2, h * .3, h * .4], alpha(k.b, .4 * i), 3)}${D(`M${x} ${y + h * .8}Q${x + w * .3} ${y + h * .2} ${x + w * .55} ${y + h * .5}T${x + w} ${y + h * .3}`, 'none', { stroke: alpha(k.c, .6 * i), sw: 2, dash: '10 8' })}`,
    opener: k => { const { w, h } = k;
      const ringsG = [[-.3, -.12, k.c], [0, -.12, k.d], [.3, -.12, k.b], [-.15, .14, k.c], [.15, .14, k.d]].map(([ox, oy, col], n) => enter(C(w / 2 + (ox as number) * h * .6, h * .42 + (oy as number) * h * .6, h * .11, 'none', { stroke: col as string, sw: 10 }), 'pop', { dur: k.beat * 1.6, delay: k.beat * .3 * n, ease: 'expo', origin: [w / 2, h * .42] })).join('');
      return `${R(0, 0, w, h, k.a)}${enter(D(`M0 ${h * .9}Q${w * .25} ${h * .3} ${w * .5} ${h * .62}T${w} ${h * .38}`, 'none', { stroke: alpha(k.b, .5), sw: 2, dash: '12 10' }), 'draw', { dur: k.beat * 3, ease: 'inOut' })}${ringsG}
        ${enter(`${T(w / 2, h * .74, k.title, { font: 'raleway', size: h * .09, weight: 200, fill: k.b, anchor: 'middle', tracking: .16, upper: true, fitW: w * .8 })}${L(w * .4, h * .78, w * .6, h * .78, k.d, 2)}${T(w / 2, h * .84, k.subtitle, { font: 'tenor', size: h * .024, weight: 400, fill: k.c, anchor: 'middle', tracking: .28, upper: true, fitW: w * .6 })}`, 'fade', { dur: k.beat * 2.4, delay: k.beat * 1.8 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .76, w * .5, h * .13, alpha(k.a, .85))}${L(w * .05, h * .89, w * .55, h * .89, k.d, 2)}${[k.c, k.d, k.b].map((col, n) => C(w * .08 + n * 34, h * .825, 16, 'none', { stroke: col, sw: 4 })).join('')}
        ${T(w * .16, h * .815, k.title, { font: 'raleway', size: h * .046, weight: 300, fill: k.b, tracking: .1, upper: true, fitW: w * .36 })}${T(w * .16, h * .86, k.subtitle, { font: 'tenor', size: h * .02, weight: 400, fill: k.c, tracking: .22, upper: true, fitW: w * .36 })}`, 'fade', { dur: k.beat * 1.8 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['global-games-ceremony'].field(k, 0, 0, w, h, .6)}${slot(k, w * .08, h * .12, w * .4, h * .76, { tone: 'dark', shape: 'circle', frame: k.d, frameWidth: 3 })}
        ${enter(`${T(w * .54, h * .34, twoLines(k.title)[0], { font: 'raleway', size: h * .07, weight: 200, fill: k.b, tracking: .12, upper: true, lines: twoLines(k.title), fitW: w * .4 })}${L(w * .54, h * .52, w * .66, h * .52, k.d, 2)}${T(w * .54, h * .58, k.subtitle, { font: 'workSans', size: h * .024, weight: 400, fill: k.c, fitW: w * .4 })}${['Nation', 'Discipline', 'Session', 'Venue'].map((f, n) => `${T(w * .54, h * (.66 + n * .055), f, { font: 'tenor', size: h * .017, fill: k.d, tracking: .24, upper: true })}${L(w * .66, h * (.655 + n * .055), w * .92, h * (.655 + n * .055), alpha(k.b, .35), 1.5)}`).join('')}`, 'fade', { dur: k.beat * 2, delay: k.beat })}`; },
  },

  /* ── Olympian Measure — divisions accumulate like a score before the record locks ── */
  'olympian-measure': {
    type: { display: 'forum', text: 'marcellus', utility: 'dmMono' }, idea: 'Measured divisions — a stone rule marked in tenths — accumulate beneath the athlete until the record locks into a bronze plate.', ground: 'a', surface: 'PAPER',
    mark: (k, cx, cy, s) => `${L(cx - s * .5, cy, cx + s * .5, cy, k.b, s * .05)}${[0, 1, 2, 3, 4].map(n => L(cx - s * .5 + n * s * .25, cy - (n % 2 ? s * .12 : s * .22), cx - s * .5 + n * s * .25, cy, k.b, s * .04)).join('')}${C(cx, cy - s * .35, s * .1, k.c)}`,
    field: (k, x, y, w, h, i = 1) => { const out: string[] = []; for (let n = 0; n * 40 <= w; n++) out.push(L(x + n * 40, y + h * .5, x + n * 40, y + h * .5 - (n % 5 ? 14 : 30), alpha(k.b, .5 * i), 2)); return out.join('') + L(x, y + h * .5, x + w, y + h * .5, alpha(k.b, .5 * i), 3); },
    opener: k => { const { w, h } = k;
      const ticks = Array.from({ length: 41 }, (_, n) => enter(L(w * .1 + n * w * .02, h * .7, w * .1 + n * w * .02, h * .7 - (n % 10 === 0 ? 44 : n % 5 === 0 ? 28 : 14), k.b, n % 10 === 0 ? 4 : 2), 'growY', { dur: k.beat * .3, delay: k.beat * .05 * n, ease: 'expo', origin: [0, h * .7] })).join('');
      return `${R(0, 0, w, h, k.a)}${R(w * .08, h * .06, w * .84, 2, k.b)}${R(w * .08, h * .94, w * .84, 4, k.b)}
        ${enter(L(w * .1, h * .7, w * .9, h * .7, k.b, 4), 'growX', { dur: k.beat * 2, ease: 'inOut', origin: [w * .1, h * .7] })}${ticks}
        ${enter(`${R(w * .3, h * .76, w * .4, h * .12, k.c)}${T(w / 2, h * .845, '9.58', { font: 'forum', size: h * .08, fill: k.a, anchor: 'middle' })}${T(w * .32, h * .845, 'RECORD', { font: 'dmMono', size: h * .02, fill: k.a, tracking: .3 })}`, 'pop', { dur: k.beat * .6, delay: k.beat * 2.4, ease: 'back', origin: [w / 2, h * .82] })}
        ${enter(`${T(w / 2, h * .34, k.title, { font: 'forum', size: h * .11, fill: k.b, anchor: 'middle', tracking: .08, upper: true, fitW: w * .8 })}${T(w / 2, h * .42, k.subtitle, { font: 'marcellus', size: h * .026, fill: k.d, anchor: 'middle', tracking: .2, upper: true, fitW: w * .6 })}`, 'fade', { dur: k.beat * 2, delay: k.beat * .6 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .76, w * .48, h * .13, k.a)}${L(w * .05, h * .89, w * .53, h * .89, k.b, 3)}${[0, 1, 2, 3, 4, 5, 6].map(n => L(w * .05 + n * 24, h * .89, w * .05 + n * 24, h * .89 - (n % 3 ? 8 : 16), k.b, 2)).join('')}${R(w * .05, h * .76, 10, h * .13, k.c)}
        ${T(w * .08, h * .82, k.title, { font: 'forum', size: h * .05, fill: k.b, tracking: .06, upper: true, fitW: w * .4 })}${T(w * .08, h * .865, k.subtitle, { font: 'marcellus', size: h * .02, fill: k.d, tracking: .16, upper: true, fitW: w * .4 })}`, 'fade', { dur: k.beat * 1.4 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${R(w * .06, h * .06, w * .88, 2, k.b)}${R(w * .06, h * .94, w * .88, 4, k.b)}${slot(k, w * .08, h * .12, w * .42, h * .76, { tone: 'light', frame: k.c, frameWidth: 3 })}${SPORTS_DESIGNS['olympian-measure'].field(k, w * .54, h * .68, w * .38, h * .1, 1)}
        ${enter(`${T(w * .54, h * .3, twoLines(k.title)[0], { font: 'forum', size: h * .08, fill: k.b, tracking: .06, upper: true, lines: twoLines(k.title), fitW: w * .38 })}${T(w * .54, h * .48, k.subtitle, { font: 'marcellus', size: h * .024, fill: k.d, fitW: w * .38 })}${[['PERSONAL BEST', '9.58'], ['SEASON BEST', '9.77']].map(([l, v], n) => `${T(w * .54, h * (.56 + n * .055), l, { font: 'dmMono', size: h * .017, fill: k.d, tracking: .2 })}${T(w * .92, h * (.56 + n * .055), v, { font: 'forum', size: h * .036, fill: k.c, anchor: 'end' })}`).join('')}${T(w * .54, h * .86, 'MEASURED IN TENTHS · REPLACEABLE', { font: 'dmMono', size: h * .016, fill: k.d, tracking: .2 })}`, 'fade', { dur: k.beat * 1.8, delay: k.beat })}`; },
  },

  /* ── Street Court Uprising — fresh tags; paint trails follow the drives ── */
  'street-court-uprising': {
    type: { display: 'bangers', text: 'oswald', utility: 'kalam' }, idea: 'Asphalt, overspray and a hand-marked bracket: the score snaps on like a fresh tag and a paint trail follows the drive.', ground: 'a', surface: 'INK', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${P(cx - s * .5, cy - s * .5, s, s, orn.burstPath(10, k.seed % 5), k.c)}${T(cx, cy + s * .16, '#1', { font: 'bangers', size: s * .5, fill: k.b, anchor: 'middle', rotate: -8 })}`,
    field: (k, x, y, w, h, i = 1) => `${specks(x, y, w, h, 260 * i, alpha(k.b, .5), k.seed, .5)}${D(`M${x + w * .1} ${y + h * .8}C${x + w * .3} ${y + h * .1} ${x + w * .5} ${y + h * .9} ${x + w * .9} ${y + h * .2}`, 'none', { stroke: alpha(k.c, .8 * i), sw: 14 })}${R(x + w * .55, y + h * .3, w * .3, h * .2, 'none', { stroke: alpha(k.d, .8 * i), sw: 5, rotate: -4 })}`,
    opener: k => { const { w, h } = k; const spray = k.uid('sp'); k.defs.push(`<filter id="${spray}" x="-20%" y="-20%" width="140%" height="140%"><feTurbulence type="fractalNoise" baseFrequency=".09" numOctaves="2" seed="${k.seed % 30}" result="n"/><feDisplacementMap in="SourceGraphic" in2="n" scale="18"/><feGaussianBlur stdDeviation="1.5"/></filter>`);
      return `${R(0, 0, w, h, k.a)}${specks(0, 0, w, h, 700, alpha(k.b, .35), k.seed, .5)}${R(w * .14, h * .14, w * .72, h * .72, 'none', { stroke: alpha(k.b, .4), sw: 5, dash: '26 14' })}${D(`M${w * .5} ${h * .14}V${h * .86}`, 'none', { stroke: alpha(k.b, .4), sw: 5 })}
        ${enter(D(`M${w * .1} ${h * .78}C${w * .3} ${h * .2} ${w * .5} ${h * .9} ${w * .92} ${h * .3}`, 'none', { stroke: k.c, sw: 22, filter: spray }), 'draw', { dur: k.beat * .8, ease: 'in' })}
        ${enter(`${R(w * .16, h * .34, w * .68, h * .26, k.b, { rotate: -3 })}${T(w * .5, h * .53, k.title, { font: 'bangers', size: h * .17, fill: k.a, anchor: 'middle', upper: true, rotate: -3, fitW: w * .62 })}`, 'pop', { dur: k.beat * .35, delay: k.beat * .7, ease: 'back', origin: [w / 2, h * .47] })}
        ${enter(`${T(w * .5, h * .7, k.subtitle, { font: 'kalam', size: h * .04, weight: 700, fill: k.d, anchor: 'middle', rotate: 2, fitW: w * .5 })}${D(`M${w * .32} ${h * .73}Q${w * .5} ${h * .77} ${w * .68} ${h * .72}`, 'none', { stroke: k.d, sw: 6 })}`, 'fade', { dur: k.beat * .5, delay: k.beat * 1.2 })}
        ${[[.2, .2], [.78, .76], [.82, .2]].map(([px, py], n) => enter(`${C(w * px, h * py, 26 + n * 6, 'none', { stroke: k.c, sw: 6, filter: spray })}${T(w * px, h * py + 12, String(n + 1), { font: 'kalam', size: 34, weight: 700, fill: k.c, anchor: 'middle' })}`, 'pop', { dur: k.beat * .3, delay: k.beat * (1.5 + n * .2), ease: 'back', origin: [w * px, h * py] })).join('')}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .76, w * .46, h * .14, k.b, { rotate: -2 })}${D(`M${w * .02} ${h * .9}C${w * .15} ${h * .72} ${w * .3} ${h * .95} ${w * .55} ${h * .74}`, 'none', { stroke: k.c, sw: 10, opacity: .9 })}
        ${T(w * .08, h * .855, k.title, { font: 'bangers', size: h * .072, fill: k.a, upper: true, rotate: -2, fitW: w * .3 })}${T(w * .36, h * .85, k.subtitle, { font: 'kalam', size: h * .026, weight: 700, fill: k.a, rotate: -2, fitW: w * .14 })}`, 'pop', { dur: k.beat * .35, ease: 'back', amount: .5, origin: [w * .28, h * .83] }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['street-court-uprising'].field(k, 0, 0, w, h, .8)}${slot(k, w * .06, h * .1, w * .46, h * .76, { tone: 'dark', rotate: -2, frame: k.b, frameWidth: 8 })}
        ${enter(`${R(w * .56, h * .3, w * .38, h * .2, k.b, { rotate: 2 })}${T(w * .58, h * .45, k.title, { font: 'bangers', size: h * .11, fill: k.a, upper: true, rotate: 2, fitW: w * .34 })}${T(w * .57, h * .58, k.subtitle, { font: 'kalam', size: h * .034, weight: 700, fill: k.d, fitW: w * .36 })}${[['PTS', '31'], ['AST', '9'], ['STL', '4']].map(([l, v], n) => `${C(w * (.6 + n * .12), h * .74, 46, 'none', { stroke: k.c, sw: 5 })}${T(w * (.6 + n * .12), h * .76, v, { font: 'bangers', size: h * .05, fill: k.b, anchor: 'middle' })}${T(w * (.6 + n * .12), h * .84, l, { font: 'kalam', size: h * .024, weight: 700, fill: k.c, anchor: 'middle' })}`).join('')}`, 'pop', { dur: k.beat * .4, delay: k.beat * .5, ease: 'back', origin: [w * .75, h * .5] })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${specks(0, 0, w, h, 300, alpha(k.b, .35), k.seed, .5)}${R(w * .02, h * .1, w * .36, h * .8, k.b, { rotate: -1.5 })}${T(w * .05, h * .72, k.title, { font: 'bangers', size: h * .58, fill: k.a, upper: true, fitW: w * .3 })}${D(`M${w * .42} ${h * .8}C${w * .5} ${h * .1} ${w * .6} ${h * .95} ${w * .7} ${h * .3}`, 'none', { stroke: k.c, sw: 10 })}${score(k, w * .8, h * .74, h * .62, 'bangers', k.b, 400)}`; },
  },

  /* ── Quantum League — forecast paths branch ahead and collapse at decisions ── */
  'quantum-league': {
    type: { display: 'audiowide', text: 'exo2', utility: 'ibmPlexMono' }, idea: 'Probability rendered as branching forecast paths that collapse to one line when the play decides; numerals scale with confidence.', ground: 'a', surface: 'GLOW', titleCase: 'upper',
    mark: (k, cx, cy, s) => `${D(`M${cx - s * .5} ${cy}Q${cx - s * .1} ${cy} ${cx} ${cy - s * .3}T${cx + s * .5} ${cy - s * .4}M${cx - s * .5} ${cy}Q${cx - s * .1} ${cy} ${cx} ${cy + s * .3}T${cx + s * .5} ${cy + s * .4}`, 'none', { stroke: k.c, sw: s * .04 })}${C(cx - s * .5, cy, s * .08, k.d)}`,
    field: (k, x, y, w, h, i = 1) => `${[0, 1, 2, 3, 4].map(n => D(`M${x} ${y + h * .5}C${x + w * .3} ${y + h * .5} ${x + w * .5} ${y + h * (.1 + n * .2)} ${x + w} ${y + h * (.15 + n * .18)}`, 'none', { stroke: alpha(n === 2 ? k.d : k.c, (n === 2 ? .9 : .35) * i), sw: n === 2 ? 4 : 2 })).join('')}${dots(x, y, w, h, 56, alpha(k.c, .3 * i), { r: 1 })}`,
    opener: k => { const { w, h } = k;
      const branches = [0, 1, 2, 3, 4, 5, 6].map(n => enter(D(`M${w * .12} ${h * .55}C${w * .35} ${h * .55} ${w * .5} ${h * (.15 + n * .12)} ${w * .9} ${h * (.12 + n * .12)}`, 'none', { stroke: n === 3 ? k.d : k.c, sw: n === 3 ? 6 : 2, opacity: n === 3 ? 1 : .4 }), 'draw', { dur: k.beat * 1.2, delay: k.beat * .12 * n, ease: 'inOut' })).join('');
      return `${R(0, 0, w, h, k.a)}${dots(0, 0, w, h, 56, alpha(k.c, .3), { r: 1 })}${branches}${pulse(C(w * .12, h * .55, 14, k.d), 1.4, .5, 1)}
        ${[[.4, .3, '31 %'], [.62, .5, '47 %'], [.9, .48, '88 %']].map(([px, py, v], n) => enter(`${R(w * (px as number) - 60, h * (py as number) - 24, 120, 48, alpha(k.a, .9), { stroke: k.c, sw: 1.5 })}${T(w * (px as number), h * (py as number) + 10, v as string, { font: 'ibmPlexMono', size: 26, weight: 700, fill: n === 2 ? k.d : k.c, anchor: 'middle' })}`, 'pop', { dur: k.beat * .5, delay: k.beat * (1.2 + n * .4), ease: 'back', origin: [w * (px as number), h * (py as number)] })).join('')}
        ${enter(`${T(w * .06, h * .84, k.title, { font: 'audiowide', size: h * .08, fill: k.b, upper: true, fitW: w * .6 })}${T(w * .06, h * .9, k.subtitle, { font: 'exo2', size: h * .024, weight: 500, fill: k.c, tracking: .16, upper: true, fitW: w * .6 })}`, 'slideU', { dur: k.beat, delay: k.beat * 2, ease: 'expo' })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .76, w * .46, h * .13, alpha(k.a, .85), { stroke: k.c, sw: 1.5 })}${D(`M${w * .05} ${h * .825}C${w * .09} ${h * .825} ${w * .1} ${h * .78} ${w * .13} ${h * .78}M${w * .05} ${h * .825}C${w * .09} ${h * .825} ${w * .1} ${h * .87} ${w * .13} ${h * .87}`, 'none', { stroke: k.d, sw: 3 })}
        ${T(w * .15, h * .815, k.title, { font: 'audiowide', size: h * .042, fill: k.b, upper: true, fitW: w * .28 })}${T(w * .15, h * .86, k.subtitle, { font: 'ibmPlexMono', size: h * .019, weight: 500, fill: k.c, tracking: .12, upper: true, fitW: w * .28 })}${T(w * .49, h * .845, '88 %', { font: 'ibmPlexMono', size: h * .05, weight: 700, fill: k.d, anchor: 'end' })}`, 'fade', { dur: k.beat }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['quantum-league'].field(k, 0, 0, w, h, .7)}${slot(k, w * .06, h * .1, w * .46, h * .8, { tone: 'dark', frame: k.c, frameWidth: 1.5 })}
        ${enter(`${R(w * .56, h * .1, w * .38, h * .8, alpha(k.a, .9), { stroke: k.c, sw: 1.5 })}${T(w * .59, h * .27, twoLines(k.title)[0], { font: 'audiowide', size: h * .06, fill: k.b, upper: true, lines: twoLines(k.title), fitW: w * .32 })}${T(w * .59, h * .44, k.subtitle, { font: 'exo2', size: h * .022, weight: 500, fill: k.c, fitW: w * .32 })}${[['WIN PROB.', '88 %', 1], ['xPTS', '2.4', .7], ['MOMENTUM', '+14', .5]].map(([l, v, s], n) => `${T(w * .59, h * (.56 + n * .09), l as string, { font: 'ibmPlexMono', size: h * .017, weight: 500, fill: k.c, tracking: .18 })}${T(w * .59, h * (.61 + n * .09), v as string, { font: 'audiowide', size: h * (.02 + .04 * (s as number)), fill: k.d })}${R(w * .74, h * (.585 + n * .09), w * .18 * (s as number), 6, k.d)}`).join('')}`, 'slideR', { dur: k.beat * .8, ease: 'expo', amount: 1.4 })}`; },
  },

  /* ── Nomad Games Atlas — terrain traces reveal the course; conditions arrive as field observations ── */
  'nomad-games-atlas': {
    type: { display: 'epilogue', text: 'lexend', utility: 'spaceMono' }, idea: 'A course traced over terrain contours, with conditions, place and participant credit written as field observations.', ground: 'a', surface: 'TOPO',
    mark: (k, cx, cy, s) => `${rings(cx, cy, [s * .46, s * .32, s * .18], k.b, s * .03)}${D(`M${cx - s * .5} ${cy + s * .3}L${cx - s * .1} ${cy - s * .1}L${cx + s * .15} ${cy + s * .15}L${cx + s * .5} ${cy - s * .35}`, 'none', { stroke: k.c, sw: s * .05 })}`,
    field: (k, x, y, w, h, i = 1) => `${[0, 1, 2, 3].map(n => D(`M${x} ${y + h * (.2 + n * .2)}C${x + w * .2} ${y + h * (.1 + n * .2)} ${x + w * .4} ${y + h * (.35 + n * .2)} ${x + w * .6} ${y + h * (.2 + n * .2)}S${x + w * .9} ${y + h * (.05 + n * .2)} ${x + w} ${y + h * (.25 + n * .2)}`, 'none', { stroke: alpha(k.b, .35 * i), sw: 2 })).join('')}`,
    opener: k => { const { w, h } = k;
      const contours = [0, 1, 2, 3, 4, 5].map(n => D(`M0 ${h * (.15 + n * .15)}C${w * .2} ${h * (.05 + n * .15)} ${w * .4} ${h * (.3 + n * .15)} ${w * .6} ${h * (.15 + n * .15)}S${w * .9} ${h * (.02 + n * .15)} ${w} ${h * (.2 + n * .15)}`, 'none', { stroke: alpha(k.b, .35), sw: 2 })).join('');
      const course = `M${w * .1} ${h * .8}C${w * .25} ${h * .5} ${w * .35} ${h * .75} ${w * .5} ${h * .45}S${w * .75} ${h * .35} ${w * .88} ${h * .25}`;
      return `${R(0, 0, w, h, k.a)}${contours}${enter(D(course, 'none', { stroke: k.c, sw: 6, dash: '18 12' }), 'draw', { dur: k.beat * 3, ease: 'inOut' })}
        ${[[.1, .8, 'START · replaceable'], [.5, .45, 'CHECKPOINT · 14 km'], [.88, .25, 'FINISH · 32 km']].map(([px, py, l], n) => enter(`${C(w * (px as number), h * (py as number), 12, k.c)}${C(w * (px as number), h * (py as number), 24, 'none', { stroke: k.c, sw: 2 })}${T(w * (px as number) + (n === 2 ? -40 : 40), h * (py as number) + 8, l as string, { font: 'spaceMono', size: 20, weight: 700, fill: k.b, anchor: n === 2 ? 'end' : 'start', tracking: .06 })}`, 'pop', { dur: k.beat * .6, delay: k.beat * (.6 + n * 1.1), ease: 'back', origin: [w * (px as number), h * (py as number)] })).join('')}
        ${enter(`${R(w * .06, h * .08, w * .38, h * .2, alpha(k.a, .92), { stroke: k.b, sw: 2 })}${T(w * .08, h * .17, k.title, { font: 'epilogue', size: h * .058, weight: 800, fill: k.b, fitW: w * .34 })}${T(w * .08, h * .23, k.subtitle, { font: 'lexend', size: h * .021, weight: 400, fill: k.c, fitW: w * .34 })}`, 'fade', { dur: k.beat * 1.4, delay: k.beat * .4 })}
        ${enter(`${T(w * .94, h * .92, 'CONDITIONS · 4 °C · WIND NW 22 · replaceable', { font: 'spaceMono', size: h * .018, weight: 700, fill: k.d, anchor: 'end', tracking: .06 })}`, 'fade', { dur: k.beat, delay: k.beat * 3.4 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .75, w * .48, h * .14, alpha(k.a, .92), { stroke: k.b, sw: 2 })}${SPORTS_DESIGNS['nomad-games-atlas'].field(k, w * .05, h * .75, w * .48, h * .14, .8)}${C(w * .09, h * .82, 10, k.c)}
        ${T(w * .12, h * .815, k.title, { font: 'epilogue', size: h * .046, weight: 800, fill: k.b, fitW: w * .38 })}${T(w * .12, h * .86, k.subtitle, { font: 'spaceMono', size: h * .019, weight: 700, fill: k.d, tracking: .06, upper: true, fitW: w * .38 })}`, 'fade', { dur: k.beat * 1.4 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['nomad-games-atlas'].field(k, 0, 0, w, h, 1)}${slot(k, w * .06, h * .1, w * .48, h * .8, { tone: 'dark', frame: k.b, frameWidth: 3 })}
        ${enter(`${R(w * .58, h * .1, w * .36, h * .8, alpha(k.a, .92), { stroke: k.b, sw: 2 })}${T(w * .61, h * .26, twoLines(k.title)[0], { font: 'epilogue', size: h * .06, weight: 800, fill: k.b, lines: twoLines(k.title), fitW: w * .3 })}${T(w * .61, h * .42, k.subtitle, { font: 'lexend', size: h * .022, weight: 400, fill: k.c, fitW: w * .3 })}${['Place', 'Participant', 'Community review', 'Conditions'].map((f, n) => `${T(w * .61, h * (.52 + n * .08), f, { font: 'spaceMono', size: h * .017, weight: 700, fill: k.d, tracking: .1, upper: true })}${L(w * .61, h * (.555 + n * .08), w * .9, h * (.555 + n * .08), alpha(k.b, .4), 1.5)}`).join('')}`, 'fade', { dur: k.beat * 1.6, delay: k.beat })}`; },
  },

  /* ── Baroque Victory — data unfurls like fabric; results arrive on a fanfare ── */
  'baroque-victory': {
    type: { display: 'abril', text: 'libreBaskerville', utility: 'cinzel' }, idea: 'A gilded fanfare: scroll-work unfurls from the corners, a chiaroscuro shaft crosses, and the result lands in engraved numerals.', ground: 'a', surface: 'GLASS',
    mark: (k, cx, cy, s) => `${P(cx - s * .5, cy - s * .5, s * .5, s, orn.cScrollPath(), k.c)}${P(cx, cy - s * .5, s * .5, s, orn.cScrollPath(), k.c, { rotate: 180 })}${P(cx - s * .15, cy - s * .15, s * .3, s * .3, orn.starPath(8, .5), k.d)}`,
    field: (k, x, y, w, h, i = 1) => `${[0, 1, 2, 3].map(n => P(x + w * (.05 + n * .24), y + h * .2, w * .18, h * .6, orn.cScrollPath(), alpha(k.c, .45 * i), { rotate: n % 2 ? 180 : 0 })).join('')}`,
    opener: k => { const { w, h } = k; const shaft = k.uid('sh'); k.defs.push(gradient(shaft, [[0, k.c, 0], [.5, k.c, .5], [1, k.c, 0]], { angle: 60 }));
      const corner = (x: number, y: number, rot: number, delay: number) => enter(P(x, y, 420, 560, orn.cScrollPath(), k.c, { rotate: rot }), 'pop', { dur: k.beat * 1.6, delay, ease: 'expo', origin: [x + 210, y + 280] });
      return `${R(0, 0, w, h, k.a)}${drift(R(-w * .1, -h * .3, w * .4, h * 1.6, `url(#${shaft})`, { rotate: 24, blend: 'screen' }), w * 1.2, 0, k.beat * 8)}
        ${corner(-40, -60, 0, 0)}${corner(w - 380, -60, 90, k.beat * .3)}${corner(-40, h - 500, -90, k.beat * .6)}${corner(w - 380, h - 500, 180, k.beat * .9)}
        ${enter(`${T(w / 2, h * .46, k.title, { font: 'abril', size: h * .15, fill: k.b, anchor: 'middle', fitW: w * .64 })}${L(w * .3, h * .52, w * .7, h * .52, k.c, 2)}`, 'fade', { dur: k.beat * 2, delay: k.beat * 1.4 })}
        ${enter(`${R(w * .36, h * .58, w * .28, h * .14, k.d)}${T(w / 2, h * .68, `${k.scoreHome} – ${k.scoreAway}`, { font: 'cinzel', size: h * .08, weight: 700, fill: k.a, anchor: 'middle' })}`, 'pop', { dur: k.beat * .6, delay: k.beat * 2.6, ease: 'back', origin: [w / 2, h * .65] })}
        ${enter(T(w / 2, h * .8, k.subtitle, { font: 'cinzel', size: h * .026, weight: 500, fill: k.c, anchor: 'middle', tracking: .24, upper: true, fitW: w * .5 }), 'fade', { dur: k.beat * 1.4, delay: k.beat * 3 })}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .75, w * .5, h * .14, alpha(k.a, .85))}${P(w * .03, h * .7, 110, 160, orn.cScrollPath(), k.c)}${P(w * .5, h * .7, 110, 160, orn.cScrollPath(), k.c, { rotate: 180 })}${L(w * .05, h * .89, w * .55, h * .89, k.c, 2)}
        ${T(w * .13, h * .82, k.title, { font: 'abril', size: h * .058, fill: k.b, fitW: w * .34 })}${T(w * .13, h * .865, k.subtitle, { font: 'cinzel', size: h * .02, weight: 500, fill: k.c, tracking: .2, upper: true, fitW: w * .34 })}`, 'fade', { dur: k.beat * 1.8 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${SPORTS_DESIGNS['baroque-victory'].field(k, 0, 0, w, h, .6)}${slot(k, w * .08, h * .1, w * .4, h * .8, { tone: 'dark', shape: 'circle', frame: k.c, frameWidth: 4 })}
        ${enter(`${T(w * .54, h * .36, twoLines(k.title)[0], { font: 'abril', size: h * .09, fill: k.b, lines: twoLines(k.title), fitW: w * .4 })}${L(w * .54, h * .54, w * .74, h * .54, k.c, 2)}${T(w * .54, h * .6, k.subtitle, { font: 'libreBaskerville', size: h * .024, weight: 400, fill: k.c, fitW: w * .4 })}${R(w * .54, h * .68, w * .2, h * .1, k.d)}${T(w * .64, h * .755, `${k.scoreHome} – ${k.scoreAway}`, { font: 'cinzel', size: h * .06, weight: 700, fill: k.a, anchor: 'middle' })}`, 'fade', { dur: k.beat * 2, delay: k.beat })}`; },
  },

  /* ── Essential Score — only the score, the clock, possession, and one team signal ── */
  'essential-score': {
    type: { display: 'manrope', text: 'manrope', utility: 'ibmPlexMono' }, idea: 'Nothing but the numbers: two tabular figures, a clock, a possession dot, and one team colour. State changes cut.', ground: 'a', surface: 'CLEAN',
    mark: (k, cx, cy, s) => `${R(cx - s * .5, cy - s * .5, s, s, k.b)}${C(cx + s * .32, cy - s * .32, s * .08, k.d)}`,
    field: (k, x, y, w, h, i = 1) => `${L(x, y + h * .5, x + w, y + h * .5, alpha(k.b, .5 * i), 2)}`,
    opener: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${enter(`${T(w * .5, h * .56, `${k.scoreHome}  ${k.scoreAway}`, { font: 'manrope', size: h * .3, weight: 300, fill: k.b, anchor: 'middle' })}`, 'fade', { dur: k.beat * .2 })}
        ${enter(C(w * .3, h * .3, 12, k.d), 'fade', { dur: k.beat * .1, delay: k.beat * .4 })}
        ${enter(`${T(w * .5, h * .7, k.title, { font: 'manrope', size: h * .04, weight: 800, fill: k.b, anchor: 'middle', fitW: w * .6 })}${T(w * .5, h * .76, k.subtitle, { font: 'ibmPlexMono', size: h * .022, weight: 500, fill: k.c, anchor: 'middle', tracking: .1, fitW: w * .5 })}`, 'fade', { dur: k.beat * .2, delay: k.beat * .8 })}${R(w * .5 - 4, h * .14, 8, h * .06, k.d)}`; },
    lowerThird: k => { const { w, h } = k;
      return lt(k, `${R(w * .05, h * .8, w * .3, h * .1, k.a)}${C(w * .07, h * .85, 7, k.d)}${T(w * .09, h * .865, k.title, { font: 'manrope', size: h * .04, weight: 800, fill: k.b, fitW: w * .16 })}${T(w * .34, h * .865, k.subtitle, { font: 'ibmPlexMono', size: h * .03, weight: 500, fill: k.c, anchor: 'end', fitW: w * .08 })}`, 'fade', { dur: k.beat * .2, outDur: .15 }); },
    fullPage: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${slot(k, w * .5, 0, w * .5, h, { tone: 'light', silent: true })}${enter(`${T(w * .06, h * .5, `${k.scoreHome}`, { font: 'manrope', size: h * .28, weight: 300, fill: k.b })}${T(w * .06, h * .78, `${k.scoreAway}`, { font: 'manrope', size: h * .28, weight: 300, fill: k.c })}${C(w * .38, h * .42, 10, k.d)}${T(w * .06, h * .88, k.title, { font: 'manrope', size: h * .03, weight: 800, fill: k.b, fitW: w * .4 })}${T(w * .06, h * .92, k.subtitle, { font: 'ibmPlexMono', size: h * .02, weight: 500, fill: k.c, tracking: .1, fitW: w * .4 })}`, 'fade', { dur: k.beat * .2 })}`; },
    scoreStrip: k => { const { w, h } = k;
      return `${R(0, 0, w, h, k.a)}${T(w * .03, h * .66, k.title, { font: 'manrope', size: h * .3, weight: 800, fill: k.b, fitW: w * .3 })}${C(w * .5, h * .5, 9, k.d)}${score(k, w * .47, h * .7, h * .56, 'manrope', k.b, 300)}${T(w * .97, h * .66, k.subtitle, { font: 'ibmPlexMono', size: h * .26, weight: 500, fill: k.c, anchor: 'end', fitW: w * .14 })}`; },
  },
};
