// articlesB — ARTICLE templates 5–8: Interview Q&A, Explainer, Data Story, Photo Essay.
//
// Same contract as articlesA: one designer per template id, pages switch on ctx.pageType, copy is
// poured with typeset/pour so it never overflows, and every text object carries a templateRole.
import type { TelaVectorObject } from '../../../../types';
import type { DesignLesson } from '../types';
import type { PublicationDesigner } from './types';
import { rect, circle, hr, vr, path, text, below, imageSlot, mix, alpha } from '../../templateKit';
import * as orn from '../../ornaments';
import { typeset, pour, figure, pullQuote, table, pill, button, meter, checkbox, runningFoot, label, verso, type Block } from './pubKit';

const obj = (...parts: Array<TelaVectorObject | TelaVectorObject[]>): TelaVectorObject[] => parts.flat();

// ═════════════════════════════════════════════════════════════════════════════
// 5 · art-interview — In Conversation (A4; hanging Q/A markers, margin notes, speaker card)
// ═════════════════════════════════════════════════════════════════════════════
const IV = {
  head: 'Nobody told me a song could be a room you live in.',
  deck: 'The composer Marisol Quint on writing for choirs of strangers, failing in public and the long afterlife of a lullaby.',
  qa: [
    ['You wrote your first piece for a choir that had never sung together. What did you learn that night?', 'That a room full of strangers will forgive almost anything except a lack of nerve. I had written something very careful, and it died on the first page. Then a woman in the back row, a retired bus driver, started improvising a drone under the second verse and the whole thing woke up. I have been trying to write for her ever since.'],
    ['Is that why your scores leave so much space?', 'Space is the point. A score that tells everyone exactly what to do is a set of instructions, and nobody sings instructions. If I leave a bar open, somebody will fill it with something I would never have thought of, and sometimes it is wrong, and sometimes the wrong thing is the best moment in the piece.'],
    ['You have said you distrust the word “inclusive.”', 'I distrust it as a decoration. Inclusion is not a poster in the foyer; it is whether the person with the weakest voice can find a part that is actually necessary. If their line can be cut without anyone noticing, you have not included them. You have tolerated them.'],
    ['What does failing in public teach you that failing in private does not?', 'Private failure is a draft. Public failure is a rehearsal for being forgiven. The first time a piece of mine fell apart in front of four hundred people, the audience laughed, and then they sang louder to carry us through. I have never forgotten that. It rearranged my idea of what an audience is for.'],
    ['How do you teach a choir a part by ear?', 'Slowly, and with food. I give them the shape before the notes: a hill, a staircase, a sigh. Then the notes arrive as details of a thing they already feel. People remember what a phrase does long before they remember what it is.'],
    ['Your lullaby “Small Weather” has been sung at weddings, funerals, once at a football match. How does it feel to lose control of a song?', 'Like watching a child leave home and become better at things than you are. I get letters. A man sang it to his dying father in a language I do not speak. I would be a fool to want that back.'],
    ['What are you afraid of now?', 'Tidiness. Success makes you tidy: better venues, better microphones, better-behaved audiences. I keep a list of things I am not allowed to fix.'],
    ['And what is on that list?', 'The cough in the second movement. The key change that nobody likes. The bar where the altos always come in early. They are all, I think, where the piece is alive.'],
    ['Do you ever write alone anymore?', 'Rarely, and I resent it. The best ideas arrive when someone says “I can’t reach that note.” Then you have to decide whether to move the note or move the person, and I always, eventually, move the note.'],
    ['What do you listen to when you are not working?', 'Silence, mostly, and the radio on the wrong station. I like the moment when two broadcasts bleed into each other and make a chord nobody intended. I have stolen half my harmony from interference.'],
    ['You teach as well. What do students get wrong?', 'They treat nerves as a problem to be solved. Nerves are information. They tell you that something is at stake. A choir with no nerves is a choir that has stopped listening to itself.'],
    ['How do you know when a piece is finished?', 'When someone I love has stopped asking me to change it, and I have stopped wanting to. Those two events rarely coincide. Usually I run out of time, and the performance decides for me.'],
    ['What would you tell the composer you were at twenty-five?', 'Write the dull parts first. Everyone waits to write the climax and then discovers the climax needs a road. Also, buy a better coat. You will be standing in a lot of cold church halls.'],
    ['Last question. What is a good song for?', 'To hold the door open. Somebody has to carry the weight of what we cannot say at the dinner table, and a three-minute song with a decent tune will do it without making a speech.'],
  ] as Array<[string, string]>,
  quick: [['Last book finished', 'A field guide to British lichens'], ['Song you wish you had written', '“Wayfaring Stranger”'], ['Warm-up you swear by', 'Humming into a cup of tea'], ['Instrument you cannot play', 'Anything with a reed'], ['Best advice you ignored', '“Write what you know.”'], ['Hidden talent', 'Parallel parking, any vehicle']],
  pull: '“A score that tells everyone exactly what to do is a set of instructions, and nobody sings instructions.”',
};

const interview: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex } = ctx;
  const M = 56, TX = 112, TW = 430, NX = 584, NW = W - M - NX, soft = mix(ink, .45), hair = alpha(ink, .22), gold = mix(secondary, -.25);
  const G = rect(0, 0, W, H, paper, { role: 'GROUND', label: 'Page ground' });
  const qa: Block[] = IV.qa.flatMap(([q, a], i) => [
    { t: q, font: 'dmSans' as const, weight: 700, size: 13, color: accent, leading: 1.45, after: 6, before: i ? 16 : 0, keepNext: true, label: 'Question', marker: { t: 'Q', dx: -56, dy: -4, size: 20, font: 'dmSerif' as const, color: accent, weight: 400 } },
    { t: a, font: 'ebGaramond' as const, weight: 400, size: 15, color: ink, leading: 1.5, after: 4, label: 'Answer', marker: { t: 'A', dx: -56, dy: -3, size: 20, font: 'dmSerif' as const, color: gold, weight: 400 } },
  ]);
  const pages = pour(qa, [[{ x: TX, y: 486, w: TW, h: 540 }], [{ x: TX, y: 96, w: TW, h: 560 }], [{ x: TX, y: 352, w: TW, h: 650 }], [{ x: TX, y: 96, w: TW, h: 210 }]], { size: 15, font: 'ebGaramond', color: ink });
  const head = (n: number): TelaVectorObject[] => obj(label(M, 34, 300, 'In Conversation', { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .22 }), label(W - M - 300, 34, 300, 'Nº 38  ·  Autumn 2026', { size: 8.5, font: 'dmSans', color: soft, align: 'right', tracking: .16 }), hr(M, 54, W - 2 * M, ink, 1, { label: 'Head rule' }), ...(n > 1 ? [] : []));
  const foot = (): TelaVectorObject[] => runningFoot(ctx, { left: M, right: W - M, y: H - 42, font: 'dmSans', size: 8.5, color: soft, head: 'In Conversation  ·  Marisol Quint', rule: hair });
  const note = (x: number, y: number, w: number, t: string, rot = -2): TelaVectorObject[] => [text(x, y, w, t, { size: 17, font: 'caveat', weight: 600, color: accent, leading: 1.15, rotation: rot, label: 'Margin note', role: 'SIDEBAR' }), hr(x - 2, y - 6, 34, accent, 1.5, { label: 'Note tick' })];

  switch (pageType) {
    case 'ARTICLE HEADER': {
      const bar = rect(M, 84, 56, 6, gold, { label: 'Kicker bar', role: 'RULE' });
      const hed = text(M, 108, 464, IV.head, { size: 54, font: 'dmSerif', color: ink, leading: 1.04, tracking: -.01, label: 'Headline', role: 'HEADLINE' });
      const deck = text(M, below(hed, 18), 448, IV.deck, { size: 19, font: 'ebGaramond', italic: true, color: mix(ink, .2), leading: 1.35, label: 'Standfirst', role: 'DECK' });
      const by = text(M, below(deck, 16), 440, 'INTERVIEW BY TEO BRANDT  ·  PHOTOGRAPHS BY ADA NJOKU', { size: 8.5, font: 'dmSans', weight: 700, color: soft, tracking: .14, wrap: false, label: 'Byline', role: 'BYLINE' });
      const px = 556, pw = W - M - px;
      const portrait = obj(rect(px + 12, 112, pw, 276, accent, { label: 'Portrait offset block', role: 'ORNAMENT' }), figure(px, 100, pw, 276, { tone: 'dark', shade: mix(ink, .3), hint: 'Portrait · 3:4', hero: true, label: 'Hero portrait' }).objs);
      const card = obj(label(px, 400, pw, 'Marisol Quint', { size: 11, font: 'dmSans', color: ink, weight: 800, tracking: .12, role: 'BYLINE', label: 'Subject name' }), text(px, 418, pw, 'Composer and choir director. Recorded 12 September in her studio in Leith.', { size: 10.5, font: 'dmSans', color: soft, leading: 1.45, label: 'Speaker card', role: 'DATELINE' }));
      return obj(G, head(1), bar, hed, deck, by, portrait, card, hr(M, 470, W - 2 * M, hair, .75), pages[0].objs, foot());
    }
    case 'BODY PAGE': {
      const fig = figure(TX, 690, TW, 214, { tone: 'dark', shade: mix(ink, .28), hint: 'Rehearsal photograph · 2:1', caption: 'Quint rehearsing “Small Weather” with the Leith Community Choir, forty-three voices and one radiator.', credit: 'Ada Njoku', capFont: 'ebGaramond', capSize: 12, capItalic: true, capColor: soft, label: 'Inline figure' });
      const rail = obj(text(NX - 4, 94, 60, '“', { size: 92, font: 'dmSerif', color: accent, wrap: false, leading: 1, label: 'Quotation mark', role: 'ORNAMENT' }), text(NX, 154, NW, IV.pull.replace(/[“”]/g, ''), { size: 19, font: 'dmSerif', color: accent, leading: 1.2, label: 'Pull quote', role: 'PULLQUOTE' }), hr(NX, 420, NW, accent, 2, { label: 'Pull quote rule' }), ...note(NX, 452, NW, 'the bus driver is on the recording, 2:14', -3), ...note(NX, 560, NW, 'ask again about the cough!', 2));
      return obj(G, head(2), pages[1].objs, fig.objs, rail, foot());
    }
    case 'SIDEBAR': {
      const cw = (W - 2 * M - 2 * 14) / 3, ch = 84;
      const cards = IV.quick.flatMap(([k, v], i) => { const x = M + (i % 3) * (cw + 14), y = 128 + Math.floor(i / 3) * (ch + 14); return [rect(x, y, cw, ch, i % 2 ? mix(paper, -.05) : mix(secondary, .72), { label: 'Quick-fire card', role: 'SIDEBAR' }), rect(x, y, 4, ch, i % 2 ? accent : gold, { label: 'Card edge', role: 'RULE' }), label(x + 16, y + 12, cw - 28, k, { size: 7.5, font: 'dmSans', color: soft, weight: 700, tracking: .16, wrap: true, role: 'SIDEBAR', label: 'Quick-fire question' }), text(x + 16, y + 34, cw - 28, v, { size: 14, font: 'ebGaramond', italic: true, color: ink, leading: 1.25, role: 'SIDEBAR', label: 'Quick-fire answer' })]; });
      const title = obj(label(M, 96, 300, 'Quick-fire round', { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .22, role: 'SIDEBAR' }), hr(M, 114, W - 2 * M, ink, 1.25));
      return obj(G, head(3), title, cards, pages[2].objs, ...note(NX, 420, NW, 'she hums when she thinks. you can hear it on the tape', -2), ...note(NX, 700, NW, 'cut? no. keep the lichens.', 3), foot());
    }
    default: {
      const bars = orn.rng(ctx.seed); const wf: TelaVectorObject[] = [];
      for (let i = 0; i < 54; i++) { const h = 8 + Math.round(Math.abs(Math.sin(i * .35) * .6 + bars() * .5) * 34); wf.push(rect(M + 96 + i * 8.6, 372 - h / 2, 4, h, i < 22 ? accent : mix(ink, .6), { rx: 2, label: 'Waveform bar', role: 'ORNAMENT' })); }
      const player = obj(rect(M, 330, W - 2 * M, 84, mix(paper, -.05), { rx: 8, label: 'Audio player', role: 'SIDEBAR' }), circle(M + 44, 372, 24, accent, { label: 'Play button' }), path(M + 37, 360, 20, 24, 'M20 0 L100 50 L20 100 Z', paper, { label: 'Play icon' }), wf, text(W - M - 110, 392, 96, '10:42 / 48:12', { size: 10, font: 'dmMono', color: soft, wrap: false, align: 'right', label: 'Timecode', role: 'CAPTION' }), label(M + 96, 338, 300, 'Listen to the full conversation', { size: 8, font: 'dmSans', color: accent, weight: 800, tracking: .16, role: 'SIDEBAR' }));
      const aboutX = M, aboutW = 330;
      const about = obj(hr(M, 452, aboutW, ink, 1.25), label(M, 462, aboutW, 'About Marisol Quint', { size: 8.5, font: 'dmSans', color: accent, weight: 800, tracking: .22 }), text(M, 484, aboutW, 'Marisol Quint has written for more than two hundred community choirs. Her song cycle Small Weather has been recorded eleven times. She teaches at the Leith Conservatoire and lives with a cello she describes as “a very tall lodger.”', { size: 14, font: 'ebGaramond', color: ink, leading: 1.5, label: 'Subject biography', role: 'SIDEBAR' }));
      const cr = table(M + aboutW + 40, 462, [{ w: 110, font: 'dmSans', size: 8, weight: 700, color: soft, tracking: .12 }, { w: W - 2 * M - aboutW - 40 - 110, font: 'dmSerif', size: 13 }], [['Interview', 'Teo Brandt'], ['Photographs', 'Ada Njoku'], ['Transcription', 'Lena Okafor'], ['Edited by', 'Priya Natarajan'], ['Recorded', '12 September 2026']], { size: 12, font: 'dmSans', color: ink, rule: hair, pad: 7, head: ['Credits', ''], headSize: 8, headColor: accent, headRule: ink, label: 'Credits' });
      const next = obj(rect(M, 750, W - 2 * M, 200, ink, { label: 'Next card', role: 'SIDEBAR' }), ...imageSlot(M, 750, 250, 200, { tone: 'dark', shade: mix(ink, .15), caption: 'Next portrait', label: 'Next portrait' }), label(M + 280, 780, 300, 'Next in conversation', { size: 8.5, font: 'dmSans', color: gold, weight: 800, tracking: .22, role: 'SIDEBAR' }), text(M + 280, 804, 400, '“I built the shop around the one chair that wobbles.”', { size: 28, font: 'dmSerif', color: paper, leading: 1.12, label: 'Next headline', role: 'HEADLINE' }), text(M + 280, 900, 400, 'The furniture maker Anselm Ode on repair, regret and the sound of a plane.', { size: 13, font: 'ebGaramond', italic: true, color: alpha(paper, .8), leading: 1.4, role: 'SIDEBAR', label: 'Next deck' }));
      const colo = text(M, 980, 420, 'This interview has been edited for length and clarity. Quotations were checked with Marisol Quint before publication. Set in DM Serif Display, EB Garamond and DM Sans.', { size: 9.5, font: 'dmSans', color: soft, leading: 1.5, label: 'Colophon', role: 'FOOTNOTE' });
      const A4 = pages[3].ends[0] + 40, sh = 330 - A4; const up = (arr: TelaVectorObject[]) => { arr.forEach(o => { o.y -= sh; if (o.points) o.points = o.points.map((v, i) => (i % 2 ? v - sh : v)); }); return arr; };
      return obj(G, head(4), pages[3].objs, up(obj(player, about, cr.objs, next, colo)), foot());
    }
  }
};

// ═════════════════════════════════════════════════════════════════════════════
// 6 · art-explainer — How It Works (web 1080 × 1600; numbered steps + glossary sidebar)
// ═════════════════════════════════════════════════════════════════════════════
const EX = {
  head: 'How a heat pump moves heat uphill',
  deck: 'It does not make heat. It moves it, the way a pump moves water, and that single trick lets one unit of electricity deliver three or four units of warmth.',
  intro: 'A heat pump sounds like a trick: it warms your house using air that feels cold. But it is the same principle that keeps your fridge cold, run in reverse. Here is the whole cycle in five steps, with the vocabulary you need to follow any installer’s quote.',
  steps: [
    ['Liquid refrigerant picks up heat outside', 'Even on a cold day, outdoor air contains heat. A fluid called a refrigerant circulates through the outdoor coil at a temperature far below the air’s, so heat flows into it the way warmth flows into a cold hand. The refrigerant boils at around minus 25 degrees Celsius and turns into a gas.'],
    ['The compressor squeezes the gas', 'The compressor is the only part that uses much electricity. It squeezes the gas, which raises both its pressure and its temperature. This is the step that turns low-grade outdoor warmth into something hot enough to heat a home, often 45 to 55 degrees Celsius.'],
    ['The hot gas gives up its heat indoors', 'Inside, the gas flows through a second coil. Air or water passing over it absorbs the heat, and the refrigerant cools back into a liquid. Because the refrigerant carried heat from outside plus the energy of compression, you get several units of heat for every unit of electricity.'],
    ['The expansion valve resets the cycle', 'The liquid passes through a valve that suddenly lets it expand. Pressure and temperature plunge, and it is cold enough to start the loop again. The whole cycle repeats continuously, and the refrigerant never leaves its sealed circuit.'],
    ['Controls decide how hard to work', 'A modern unit varies its compressor speed to match demand, which is why it hums quietly instead of cycling on and off. A good controller also learns your house: it heats earlier when the cold is coming and rests when the sun is doing the job.'],
  ] as Array<[string, string]>,
  rule: 'A well-installed heat pump delivers three to four units of heat for every unit of electricity it uses. That ratio is called the coefficient of performance, or COP.',
  mistakes: [['Oversizing the unit', 'A bigger unit short-cycles, wastes power and wears out faster.'], ['Ignoring the radiators', 'Old, small radiators may need water hotter than a heat pump likes.'], ['Skipping insulation', 'The cheapest kilowatt hour is the one you never need.'], ['Setting it and forgetting it', 'Clean the filters and clear the outdoor coil twice a year.']] as Array<[string, string]>,
  gloss: [['Refrigerant', 'The fluid that carries heat around the loop.'], ['Compressor', 'The pump that raises the gas’s pressure and temperature.'], ['Evaporator', 'The coil where refrigerant absorbs heat and boils.'], ['Condenser', 'The coil where it releases heat and turns back to liquid.'], ['COP', 'Coefficient of performance: heat delivered per unit of electricity.'], ['SCOP', 'Seasonal COP, averaged across a whole year.'], ['Defrost cycle', 'A short reversal that melts frost from the outdoor coil.'], ['Flow temperature', 'The temperature of water sent to your radiators.']] as Array<[string, string]>,
  recap: ['Heat is moved, not made.', 'The compressor does the work; everything else is plumbing.', 'Expect three to four units of heat per unit of electricity.', 'Size the unit to the house, never the other way round.', 'Insulate first, then choose the pump.'],
};

const explainer: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex } = ctx;
  const M = 64, CW = 640, RX = M + CW + 48, RW = W - M - RX, soft = mix(ink, .45), hair = alpha(ink, .14), tint = mix(accent, .93), amber = mix(secondary, .8);
  const G = rect(0, 0, W, H, paper, { role: 'GROUND', label: 'Page ground' });
  const body = { size: 18, font: 'workSans' as const, color: mix(ink, .12), leading: 1.6, after: 14 };
  const nav = (): TelaVectorObject[] => obj(rect(0, 0, W, 64, '#FFFFFF', { label: 'Nav bar', role: 'ORNAMENT' }), hr(0, 64, W, hair, 1, { label: 'Nav rule' }), circle(M + 12, 32, 12, accent, { label: 'Logo mark' }), text(M + 34, 21, 200, 'Explainer', { size: 20, font: 'manrope', weight: 800, color: ink, wrap: false, label: 'Wordmark', role: 'LOGO' }), ...['Guides', 'Energy', 'Home', 'Newsletter'].map((t, i) => label(W - M - 360 + i * 94, 26, 90, t, { size: 11, font: 'manrope', color: i === 1 ? accent : soft, weight: 700, tracking: .1, transform: 'none' })));
  const foot = (): TelaVectorObject[] => obj(hr(M, H - 52, W - 2 * M, hair, 1, { label: 'Foot rule' }), text(M, H - 38, 500, 'Explainer  ·  How a heat pump moves heat uphill', { size: 11, font: 'dmMono', color: soft, wrap: false, label: 'Page footer', role: 'FOLIO' }), text(W - M - 200, H - 38, 200, `${pageIndex + 1} / 4`, { size: 11, font: 'dmMono', color: soft, align: 'right', wrap: false, label: 'Folio', role: 'FOLIO' }));
  const stepBlock = (i: number, y: number, withFig: boolean): { objs: TelaVectorObject[]; bottom: number } => {
    const [h, b] = EX.steps[i]; const o: TelaVectorObject[] = [];
    o.push(text(M, y - 6, 100, String(i + 1), { size: 76, font: 'spaceGrotesk', weight: 700, color: accent, wrap: false, leading: 1, label: 'Step number', role: 'LABEL' }));
    const hh = text(M + 108, y, CW - 108, h, { size: 28, font: 'manrope', weight: 800, color: ink, leading: 1.15, label: 'Step heading', role: 'HEADLINE' });
    const t = typeset([b], [{ x: M + 108, y: below(hh, 12), w: CW - 108, h: 320 }], body);
    o.push(hh, ...t.objs); let bt = t.ends[0];
    if (withFig) { const f = figure(M + 108, bt + 6, CW - 108, 170, { tone: 'light', shade: mix(accent, .86), hint: 'Diagram · outdoor coil', caption: 'Figure 1. Warm air passes over the cold outdoor coil; refrigerant absorbs the heat and boils.', capFont: 'dmMono', capSize: 11, capColor: soft, label: 'Step diagram' }); o.push(...f.objs); bt = f.bottom; }
    return { objs: o, bottom: bt + 30 };
  };

  switch (pageType) {
    case 'ARTICLE HEADER': {
      const chip = pill(M, 96, 'Explainer  ·  6 min read', { fill: tint, color: accent, size: 11, h: 28, font: 'manrope', tracking: .1 });
      const hed = text(M, 144, CW + 20, EX.head, { size: 62, font: 'manrope', weight: 800, color: ink, leading: 1.04, tracking: -.02, label: 'Headline', role: 'HEADLINE' });
      const deck = text(M, below(hed, 20), CW, EX.deck, { size: 22, font: 'workSans', color: mix(ink, .3), leading: 1.45, label: 'Deck', role: 'DECK' });
      const by = below(deck, 24);
      const byrow = obj(circle(M + 18, by + 22, 18, mix(accent, .6), { label: 'Author avatar' }), circle(M + 44, by + 22, 18, mix(secondary, .2), { stroke: paper, strokeWidth: 3, label: 'Author avatar' }), text(M + 76, by + 6, 380, 'By Imani Wright and Joel Adeyemi', { size: 14, font: 'manrope', weight: 700, color: ink, wrap: false, label: 'Byline', role: 'BYLINE' }), text(M + 76, by + 26, 400, 'Updated 8 October 2026  ·  Reviewed by an energy engineer', { size: 12, font: 'workSans', color: soft, wrap: false, label: 'Dateline', role: 'DATELINE' }));
      const hero = figure(M, by + 64, CW, 340, { tone: 'light', shade: mix(accent, .88), hint: 'Hero diagram · refrigerant loop · 16:9', hero: true, label: 'Hero diagram', caption: 'The refrigerant loop: outdoor coil, compressor, indoor coil and expansion valve.', capFont: 'dmMono', capSize: 11, capColor: soft });
      const tl = hero.bottom + 30;
      const box = obj(rect(M, tl, CW, 190, amber, { rx: 14, label: 'TL;DR box', role: 'SIDEBAR' }), rect(M, tl, 6, 190, secondary, { label: 'TL;DR bar', role: 'RULE' }), label(M + 30, tl + 22, 200, 'The short version', { size: 11, font: 'manrope', color: mix(secondary, -.5), weight: 800, tracking: .18, role: 'SIDEBAR' }), typeset(['It moves heat from outside to inside using a refrigerant loop.', 'The compressor is the one part that uses real electricity.', 'You get three to four units of heat per unit of power.'].map(t => ({ t, marker: { t: '→', dx: -22, size: 16, color: mix(secondary, -.4), font: 'manrope' as const, weight: 800, dy: 1 }, after: 8 })), [{ x: M + 54, y: tl + 52, w: CW - 84, h: 130 }], { size: 17, font: 'workSans', color: ink, leading: 1.45 }).objs);
      const intro = typeset([EX.intro], [{ x: M, y: tl + 222, w: CW, h: 200 }], { ...body, size: 19 });
      const toc = obj(rect(RX, 96, RW, 340, '#FFFFFF', { rx: 14, stroke: hair, strokeWidth: 1, label: 'Table of contents card', role: 'SIDEBAR' }), label(RX + 22, 120, RW - 44, 'In this guide', { size: 11, font: 'manrope', color: accent, weight: 800, tracking: .18, role: 'SIDEBAR' }), vr(RX + 30, 162, 246, hair, 2, { label: 'Progress rail' }), vr(RX + 30, 162, 50, accent, 3, { label: 'Progress value' }), ...EX.steps.flatMap(([h], i) => [circle(RX + 30, 168 + i * 56, 6, i === 0 ? accent : '#FFFFFF', { stroke: i === 0 ? accent : mix(ink, .6), strokeWidth: 2, label: 'Step dot' }), text(RX + 50, 158 + i * 56, RW - 72, h, { size: 13, font: 'workSans', weight: i === 0 ? 700 : 500, color: i === 0 ? ink : soft, leading: 1.25, role: 'SIDEBAR', label: 'Step title' })]));
      const share = obj(label(RX, 466, RW, 'Share this guide', { size: 10, font: 'manrope', color: soft, weight: 800, tracking: .16, role: 'SIDEBAR' }), ...['Copy link', 'Email', 'Print'].flatMap((t, i) => pill(RX + i * 92, 490, t, { fill: 'none', stroke: mix(ink, .7), color: ink, size: 10, h: 30, font: 'manrope', tracking: .04, padX: 14 }).objs));
      return obj(G, nav(), chip.objs, hed, deck, byrow, hero.objs, box, intro.objs, toc, share, foot());
    }
    case 'BODY PAGE': {
      let y = 108; const o: TelaVectorObject[] = [];
      for (let i = 0; i < 3; i++) { const s = stepBlock(i, y, i === 0); o.push(...s.objs); y = s.bottom; if (i < 2) { o.push(hr(M, y - 14, CW, hair, 1, { label: 'Step divider' })); y += 10; } }
      const call = pullQuote(M + 108, y + 8, CW - 108, EX.rule, { size: 24, font: 'manrope', weight: 700, color: ink, rule: 'left', ruleColor: secondary, ruleW: 8, attrib: 'Rule of thumb', attribColor: mix(secondary, -.4), pad: 26, leading: 1.3 });
      const rail = obj(rect(RX, 108, RW, 300, tint, { rx: 14, label: 'Key number card', role: 'SIDEBAR' }), label(RX + 22, 130, RW - 44, 'The number to remember', { size: 10, font: 'manrope', color: accent, weight: 800, tracking: .16, role: 'SIDEBAR' }), text(RX + 22, 160, RW - 44, '3–4×', { size: 74, font: 'spaceGrotesk', weight: 700, color: accent, wrap: false, leading: 1, role: 'SIDEBAR', label: 'Key figure' }), text(RX + 22, 252, RW - 44, 'units of heat delivered for every unit of electricity, in a well-installed system.', { size: 15, font: 'workSans', color: ink, leading: 1.45, role: 'SIDEBAR', label: 'Key figure caption' }), ...meter(RX + 22, 360, RW - 44, 10, 1, 4, mix(ink, .6), '#FFFFFF'), ...meter(RX + 22, 378, RW - 44, 10, 3.5, 4, accent, '#FFFFFF'), label(RX + 22, 396, RW - 44, 'Gas boiler  ·  heat pump', { size: 9, font: 'dmMono', color: soft, transform: 'none', tracking: .02, role: 'CAPTION' }));
      return obj(G, nav(), o, call.objs, rail, foot());
    }
    case 'SIDEBAR': {
      let y = 108; const o: TelaVectorObject[] = [];
      for (let i = 3; i < 5; i++) { const s = stepBlock(i, y, false); o.push(...s.objs); y = s.bottom; o.push(hr(M, y - 14, CW, hair, 1, { label: 'Step divider' })); y += 10; }
      const mt = obj(label(M, y + 10, 300, 'Common mistakes', { size: 12, font: 'manrope', color: accent, weight: 800, tracking: .18 }), ...EX.mistakes.flatMap(([h, b], i) => { const cw = (CW - 20) / 2, x = M + (i % 2) * (cw + 20), yy = y + 44 + Math.floor(i / 2) * 176; return [rect(x, yy, cw, 156, '#FFFFFF', { rx: 14, stroke: hair, strokeWidth: 1, label: 'Mistake card', role: 'SIDEBAR' }), circle(x + 34, yy + 38, 16, mix(secondary, .3), { label: 'Warning badge' }), text(x + 28, yy + 26, 14, '!', { size: 20, font: 'manrope', weight: 800, color: ink, align: 'center', wrap: false, label: 'Warning mark', role: 'ORNAMENT' }), text(x + 62, yy + 24, cw - 82, h, { size: 17, font: 'manrope', weight: 800, color: ink, leading: 1.2, role: 'SIDEBAR', label: 'Mistake title' }), text(x + 24, yy + 78, cw - 48, b, { size: 15, font: 'workSans', color: soft, leading: 1.45, role: 'SIDEBAR', label: 'Mistake detail' })]; }));
      const gl = obj(rect(RX, 108, RW, 1050, '#FFFFFF', { rx: 14, stroke: hair, strokeWidth: 1, label: 'Glossary card', role: 'SIDEBAR' }), label(RX + 22, 132, RW - 44, 'Glossary', { size: 11, font: 'manrope', color: accent, weight: 800, tracking: .18, role: 'SIDEBAR' }), hr(RX + 22, 156, RW - 44, ink, 2), ...EX.gloss.flatMap(([t, d], i) => { const yy = 176 + i * 116; const dd = text(RX + 22, yy + 22, RW - 44, d, { size: 14, font: 'workSans', color: mix(ink, .15), leading: 1.45, role: 'SIDEBAR', label: 'Glossary definition' }); return [text(RX + 22, yy, RW - 44, t, { size: 13, font: 'dmMono', weight: 500, color: accent, wrap: false, role: 'SIDEBAR', label: 'Glossary term' }), dd, hr(RX + 22, below(dd, 12), RW - 44, hair, 1, { label: 'Glossary rule' })]; }));
      return obj(G, nav(), o, mt, gl, foot());
    }
    default: {
      const rc = obj(label(M, 112, 400, 'Recap checklist', { size: 12, font: 'manrope', color: accent, weight: 800, tracking: .18 }), hr(M, 138, CW, ink, 2), ...EX.recap.flatMap((t, i) => checkbox(M, 160 + i * 48, t, { color: accent, font: 'workSans', textSize: 18, w: CW - 40, size: 22, checked: true, accent })));
      const cta = obj(rect(M, 440, CW, 190, accent, { rx: 18, label: 'Next steps card', role: 'SIDEBAR' }), text(M + 34, 466, CW - 68, 'Ready to get a quote?', { size: 32, font: 'manrope', weight: 800, color: '#FFFFFF', wrap: false, label: 'CTA headline', role: 'HEADLINE' }), text(M + 34, 512, CW - 68, 'Use our checklist to compare three installers like for like.', { size: 17, font: 'workSans', color: alpha('#FFFFFF', .88), leading: 1.45, role: 'SIDEBAR', label: 'CTA text' }), ...button(M + 34, 566, 230, 48, 'Download the checklist', { fill: secondary, color: ink, font: 'manrope', size: 14, rx: 24 }));
      const src = obj(label(M, 680, 300, 'Sources', { size: 12, font: 'manrope', color: accent, weight: 800, tracking: .18 }), hr(M, 706, CW, ink, 2), typeset(['International Energy Agency, The Future of Heat Pumps, 2022 edition, chapter 2.', 'Heat Pump Association, Seasonal performance in cold climates: field trial summary, 2025.', 'National Renewable Energy Laboratory, Cold-climate air-source heat pump performance, technical report.'].map((t, i) => ({ t, marker: { t: String(i + 1), dx: -32, size: 13, font: 'dmMono' as const, color: accent, weight: 500 }, after: 10 })), [{ x: M + 36, y: 724, w: CW - 36, h: 220 }], { size: 14, font: 'workSans', color: soft, leading: 1.5 }).objs);
      const help = obj(rect(M, 880, CW, 96, mix(accent, .94), { rx: 14, label: 'Feedback card', role: 'SIDEBAR' }), text(M + 28, 906, 300, 'Was this guide helpful?', { size: 17, font: 'manrope', weight: 800, color: ink, wrap: false, label: 'Feedback prompt', role: 'SIDEBAR' }), ...pill(M + CW - 220, 912, 'Yes, thanks', { fill: '#FFFFFF', stroke: accent, color: accent, size: 11, h: 34, font: 'manrope', padX: 16 }).objs, ...pill(M + CW - 104, 912, 'Not quite', { fill: '#FFFFFF', stroke: mix(ink, .6), color: ink, size: 11, h: 34, font: 'manrope', padX: 16 }).objs);
      const rail = obj(rect(RX, 112, RW, 330, '#FFFFFF', { rx: 14, stroke: hair, strokeWidth: 1, label: 'Newsletter card', role: 'SIDEBAR' }), label(RX + 22, 134, RW - 44, 'Get one explainer a week', { size: 11, font: 'manrope', color: accent, weight: 800, tracking: .12, transform: 'none', role: 'SIDEBAR' }), text(RX + 22, 166, RW - 44, 'Plain-language guides to the things your house, car and bank account are doing.', { size: 15, font: 'workSans', color: ink, leading: 1.45, role: 'SIDEBAR', label: 'Newsletter pitch' }), rect(RX + 22, 262, RW - 44, 46, paper, { rx: 8, stroke: hair, strokeWidth: 1, label: 'Email field', role: 'ORNAMENT' }), text(RX + 36, 276, RW - 70, 'you@example.com', { size: 14, font: 'workSans', color: soft, wrap: false, label: 'Email placeholder', role: 'LABEL' }), ...button(RX + 22, 324, RW - 44, 46, 'Subscribe', { fill: ink, color: '#FFFFFF', font: 'manrope', size: 14, rx: 8 }));
      const credits = obj(label(RX, 480, RW, 'Credits', { size: 11, font: 'manrope', color: accent, weight: 800, tracking: .18, role: 'SIDEBAR' }), hr(RX, 502, RW, ink, 2), ...[['Writing', 'Imani Wright'], ['Reporting', 'Joel Adeyemi'], ['Diagrams', 'Marlon Fitch'], ['Review', 'Dr. Aino Laine']].flatMap(([a, b], i) => [text(RX, 518 + i * 34, 90, a, { size: 12, font: 'dmMono', color: soft, wrap: false, role: 'CREDIT', label: 'Credit role' }), text(RX + 96, 518 + i * 34, RW - 96, b, { size: 14, font: 'workSans', weight: 500, color: ink, wrap: false, role: 'CREDIT', label: 'Credit name' })]));
      return obj(G, nav(), rc, cta, src, help, rail, credits, foot());
    }
  }
};

// ═════════════════════════════════════════════════════════════════════════════
// 7 · art-data — Numbers Desk (web 1080 × 1350; dark data story with drawn charts)
// ═════════════════════════════════════════════════════════════════════════════
const DT = {
  head: 'Rents outran paychecks in 41 of 50 cities',
  deck: 'Between 2019 and 2025 the median rent rose 39 percent while wages rose 19. The gap opened in two bursts, and in nine cities it is now wider than a month of pay.',
  paras: [
    'Between 2019 and 2025 the median asking rent across 50 mid-sized cities rose 39 percent. Median hourly wages rose 19 percent. In 41 of those cities, rents grew faster than pay, and in nine of them the gap exceeded 25 percentage points.',
    'The pattern is not simply a story of a few expensive coasts. Brenmouth and Calder Falls, neither of which appears on a typical list of unaffordable places, saw rents climb by more than half. In both, the largest local employer cut headcount over the same period.',
    'Most of the increase arrived in two bursts. The first, in 2021 and 2022, followed the reopening of offices and a shortage of new construction. The second, in 2024, tracked a rise in borrowing costs that discouraged builders from starting projects they had already planned.',
    'Wages did not stand still. They rose faster than at any point since the early 2000s. But they started from a lower base, and rent is a bill that arrives on the first of every month regardless of when a pay rise lands.',
    'The bottom of the table is just as instructive. In the nine cities where wages beat rents, the common feature was supply: each permitted more than twice as many homes per thousand residents as the national median over the period.',
    'None of this proves that building causes affordability on its own. Cities that build more also tend to be growing faster, and growth lifts wages. But the association held after we adjusted for population change, and it was the strongest single relationship in the data.',
    'What does a 12-point gap mean for a household? For a worker earning the median wage and renting the median apartment, it means roughly 110 more hours of work a year to cover rent than in 2019, about three extra weeks.',
    'Rents are not the whole story. Utilities, childcare and transport also rose. But housing is the largest line in almost every household budget, and the one that is hardest to substitute away from in the short run.',
    'Local governments have levers, and some are using them. Two cities in our sample legalised small apartment buildings on single-family lots in 2021; permits for new homes there doubled within two years, and rent growth slowed by seven points relative to their neighbours.',
    'Tenants have levers too, though weaker ones. Surveys of renters show that roughly one in four moved in the past two years because of a price increase, and one in ten moved in with family or friends to cope. Those choices do not appear in the rent index, but they are the other half of the story.',
    'We have published the full dataset and the code that produced every chart on this page. If you find an error, tell us. We would rather correct a number than defend one.',
  ],
  years: ['2019', '2020', '2021', '2022', '2023', '2024', '2025'],
  rent: [100, 104, 111, 124, 131, 135, 139],
  wage: [100, 102, 105, 110, 114, 117, 119],
  cities: [['Brenmouth', 58, 24], ['Calder Falls', 54, 22], ['Dunmore', 49, 21], ['Eastvale', 46, 20], ['Fenwick', 44, 24], ['Garrow', 41, 19], ['Halsey', 39, 23], ['Ironbridge', 37, 18], ['Juniper', 35, 22], ['Ashford', 33, 21]] as Array<[string, number, number]>,
  notes: ['Asking rents for one- and two-bedroom units from listings in each metro area, nominal dollars, median of monthly medians.', 'Median hourly wages from the national employment survey, nominal, all occupations, full-year average.', 'Cities are the 50 largest metros with continuous data across 2019–2025. Index values set to 100 in 2019.', 'Housing permits per 1,000 residents, cumulative 2019–2025, from municipal permit records.', 'All figures on this page are illustrative sample data for the template preview.'],
};

const dataStory: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex } = ctx;
  const M = 72, CW = W - 2 * M, soft = mix(ink, -.35), hair = alpha(ink, .14), panel = mix(paper, .06), grid = alpha(ink, .12);
  const G = rect(0, 0, W, H, paper, { role: 'GROUND', label: 'Page ground' });
  const bar = (): TelaVectorObject[] => obj(rect(M, 34, 14, 14, accent, { label: 'Logo mark', role: 'LOGO' }), text(M + 24, 30, 260, 'NUMBERS DESK', { size: 14, font: 'spaceGrotesk', weight: 700, color: ink, tracking: .16, wrap: false, label: 'Wordmark', role: 'LOGO' }), text(W - M - 420, 32, 420, 'Rent report 2026  ·  Data story', { size: 12, font: 'dmMono', color: soft, align: 'right', wrap: false, label: 'Section label', role: 'DATELINE' }), hr(M, 64, CW, hair, 1, { label: 'Top rule' }));
  const foot = (src = 'Illustrative sample data for the template preview.'): TelaVectorObject[] => obj(hr(M, H - 56, CW, hair, 1, { label: 'Foot rule' }), text(M, H - 42, 700, 'Source: ' + src, { size: 11, font: 'dmMono', color: soft, wrap: false, label: 'Source line', role: 'FOOTNOTE' }), text(W - M - 120, H - 42, 120, `${pageIndex + 1} / 6`, { size: 11, font: 'dmMono', color: soft, align: 'right', wrap: false, label: 'Folio', role: 'FOLIO' }));
  const frameBox = (x: number, y: number, w: number, h: number, title: string, sub: string): TelaVectorObject[] => obj(rect(x, y, w, h, panel, { rx: 16, stroke: hair, strokeWidth: 1, label: 'Chart frame', role: 'SIDEBAR' }), text(x + 28, y + 24, w - 56, title, { size: 22, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, label: 'Chart title', role: 'HEADLINE' }), text(x + 28, y + 56, w - 56, sub, { size: 14, font: 'dmSans', color: soft, label: 'Chart subtitle', role: 'CAPTION' }));
  /** Line through points in a box; returns a PATH with an absolute-pixel origin box. */
  const polyline = (pts: Array<[number, number]>, color: string, w = 3): TelaVectorObject => { const xs = pts.map(p => p[0]), ys = pts.map(p => p[1]); const x0 = Math.min(...xs), y0 = Math.min(...ys), x1 = Math.max(...xs), y1 = Math.max(...ys); const d = pts.map(([x, y], i) => `${i ? 'L' : 'M'}${x.toFixed(1)} ${y.toFixed(1)}`).join(' '); return path(x0, y0, Math.max(1, x1 - x0), Math.max(1, y1 - y0), d, 'none', { stroke: color, strokeWidth: w, open: true, origin: { x: x0, y: y0, w: Math.max(1, x1 - x0), h: Math.max(1, y1 - y0) }, label: 'Chart line', role: 'ORNAMENT' }); };
  const legend = (x: number, y: number): TelaVectorObject[] => obj(rect(x, y + 3, 14, 14, accent, { rx: 3, label: 'Legend swatch' }), text(x + 22, y, 140, 'Median rent', { size: 13, font: 'dmSans', color: ink, wrap: false, role: 'CAPTION', label: 'Legend' }), rect(x + 150, y + 3, 14, 14, secondary, { rx: 3, label: 'Legend swatch' }), text(x + 172, y, 140, 'Median wage', { size: 13, font: 'dmSans', color: ink, wrap: false, role: 'CAPTION', label: 'Legend' }));
  const body = { size: 17, font: 'dmSans' as const, color: mix(ink, -.12), leading: 1.6, after: 12 };
  const flow = pour(DT.paras.map(t => ({ t })), [
    [{ x: M, y: 140, w: 440, h: 440 }, { x: M + 496, y: 140, w: 440, h: 440 }, { x: M, y: 966, w: 440, h: 214 }, { x: M + 496, y: 966, w: 440, h: 214 }],
    [{ x: M, y: 140, w: 420, h: 640 }],
  ], body);

  switch (pageType) {
    case 'ARTICLE HEADER': {
      const kick = text(M, 100, 500, 'DATA STORY  ·  HOUSING', { size: 13, font: 'dmMono', weight: 500, color: accent, tracking: .1, wrap: false, label: 'Kicker', role: 'KICKER' });
      const hed = text(M, 128, 880, DT.head, { size: 64, font: 'spaceGrotesk', weight: 700, color: ink, leading: 1.04, tracking: -.02, label: 'Headline', role: 'HEADLINE' });
      const deck = text(M, below(hed, 18), 760, DT.deck, { size: 20, font: 'dmSans', color: mix(ink, -.1), leading: 1.5, label: 'Deck', role: 'DECK' });
      const ny = below(deck, 34);
      const big = text(M - 8, ny - 24, 520, '41', { size: 400, font: 'bigShoulders', weight: 800, color: accent, wrap: false, leading: 1, tracking: -.02, label: 'Hero figure', role: 'HERO' });
      const of = obj(text(M + 440, ny + 40, 160, '/ 50', { size: 110, font: 'bigShoulders', weight: 700, color: secondary, wrap: false, leading: 1, label: 'Figure denominator', role: 'HERO' }), text(M + 440, ny + 168, 440, 'cities where rent grew faster than wages between 2019 and 2025', { size: 24, font: 'dmSans', weight: 500, color: ink, leading: 1.3, label: 'Figure caption', role: 'CAPTION' }));
      const sy = ny + 346;
      const tiles = [['+39%', 'median rent growth', accent], ['+19%', 'median wage growth', secondary], ['20 pts', 'the gap between them', ink]] as Array<[string, string, string]>;
      const tw = (CW - 40) / 3;
      const tl = tiles.flatMap(([v, l, c], i) => { const x = M + i * (tw + 20); return [rect(x, sy, tw, 132, panel, { rx: 14, stroke: hair, strokeWidth: 1, label: 'Stat tile', role: 'SIDEBAR' }), text(x + 24, sy + 18, tw - 48, v, { size: 56, font: 'spaceGrotesk', weight: 700, color: c, wrap: false, leading: 1, label: 'Stat value', role: 'SIDEBAR' }), text(x + 24, sy + 92, tw - 48, l, { size: 14, font: 'dmMono', color: soft, wrap: false, role: 'SIDEBAR', label: 'Stat label' })]; });
      const cy = sy + 168, ch = H - cy - 150;
      const pts = (arr: number[]): Array<[number, number]> => arr.map((v, i) => [M + 40 + i * ((CW - 120) / 6), cy + ch - 34 - (v - 95) / 50 * (ch - 80)]);
      const chart = obj(frameBox(M, cy, CW, ch + 40, 'Rent pulled away in 2022', 'Index, 2019 = 100'), [100, 120, 140].flatMap(v => [hr(M + 28, cy + ch - 34 - (v - 95) / 50 * (ch - 80), CW - 56, grid, 1, { label: 'Gridline' })]), polyline(pts(DT.rent), accent, 4), polyline(pts(DT.wage), secondary, 4), ...pts(DT.rent).map(([x, y], i) => i === 6 ? circle(x, y, 7, accent, { label: 'End point' }) : circle(x, y, 4, accent, { label: 'Point' })), ...pts(DT.wage).map(([x, y], i) => i === 6 ? circle(x, y, 7, secondary, { label: 'End point' }) : circle(x, y, 4, secondary, { label: 'Point' })), text(pts(DT.rent)[6][0] - 70, pts(DT.rent)[6][1] - 34, 90, '139', { size: 22, font: 'spaceGrotesk', weight: 700, color: accent, align: 'right', wrap: false, role: 'CAPTION', label: 'End value' }), text(pts(DT.wage)[6][0] - 70, pts(DT.wage)[6][1] + 12, 90, '119', { size: 22, font: 'spaceGrotesk', weight: 700, color: secondary, align: 'right', wrap: false, role: 'CAPTION', label: 'End value' }), ...DT.years.map((y, i) => text(pts(DT.rent)[i][0] - 24, cy + ch + 8, 48, y, { size: 11, font: 'dmMono', color: soft, align: 'center', wrap: false, role: 'CAPTION', label: 'Axis year' })), legend(M + CW - 340, cy + 24));
      const by = text(M, H - 100, 700, 'By Joel Adeyemi and Marlon Fitch  ·  Data and graphics: the Numbers Desk  ·  8 October 2026', { size: 12, font: 'dmMono', color: soft, label: 'Byline', role: 'BYLINE' });
      return obj(G, bar(), kick, hed, deck, big, of, tl, chart, by, foot());
    }
    case 'DATA CHART': {
      if (pageIndex === 1) {
        const cx = M, cy = 110, cw = CW, chh = 700;
        const x0 = cx + 76, y0 = cy + chh - 70, plotW = cw - 120, plotH = chh - 210, minV = 90, maxV = 150;
        const yOf = (v: number) => y0 - (v - minV) / (maxV - minV) * plotH;
        const gl = [90, 100, 110, 120, 130, 140, 150].flatMap(v => [hr(x0, yOf(v), plotW, v === 100 ? alpha(ink, .35) : grid, v === 100 ? 1.5 : 1, { label: 'Gridline' }), text(cx + 20, yOf(v) - 8, 48, String(v), { size: 12, font: 'dmMono', color: soft, align: 'right', wrap: false, role: 'CAPTION', label: 'Axis value' })]);
        const gw = plotW / 7;
        const bars = DT.years.flatMap((yr, i) => { const bw = gw * .32, gx = x0 + i * gw + gw * .16; const hr1 = y0 - yOf(Math.max(minV, DT.rent[i])), hw = y0 - yOf(Math.max(minV, DT.wage[i])); const o: TelaVectorObject[] = [rect(gx, yOf(DT.rent[i]), bw, y0 - yOf(DT.rent[i]), accent, { rx: 3, label: 'Rent bar', role: 'ORNAMENT' }), rect(gx + bw + 5, yOf(DT.wage[i]), bw, y0 - yOf(DT.wage[i]), secondary, { rx: 3, label: 'Wage bar', role: 'ORNAMENT' }), text(gx - 12, y0 + 12, bw * 2 + 30, yr, { size: 13, font: 'dmMono', color: soft, align: 'center', wrap: false, role: 'CAPTION', label: 'Axis year' })]; void hr1; void hw; if (i === 6) o.push(text(gx - 10, yOf(DT.rent[i]) - 28, bw + 20, String(DT.rent[i]), { size: 20, font: 'spaceGrotesk', weight: 700, color: accent, align: 'center', wrap: false, role: 'CAPTION', label: 'Bar value' }), text(gx + bw - 5, yOf(DT.wage[i]) - 28, bw + 20, String(DT.wage[i]), { size: 20, font: 'spaceGrotesk', weight: 700, color: secondary, align: 'center', wrap: false, role: 'CAPTION', label: 'Bar value' })); return o; });
        const ax = x0 + gw * 3.5, ay = yOf(124);
        const ann = obj(vr(ax, cy + 130, ay - cy - 130 - 18, ink, 1.5, { dash: [4, 4], label: 'Annotation leader' }), rect(ax - 148, cy + 98, 296, 36, ink, { rx: 18, label: 'Annotation pill' }), text(ax - 148, cy + 108, 296, 'The gap doubled after 2021', { size: 14, font: 'dmSans', weight: 700, color: paper, align: 'center', wrap: false, role: 'CAPTION', label: 'Annotation' }));
        const read = obj(label(M, 836, 400, 'How to read this chart', { size: 12, font: 'dmMono', color: accent, weight: 500, tracking: .12, transform: 'none' }), hr(M, 858, CW, hair, 1), text(M, 876, 440, 'Each pair of columns shows the cost of renting and the median wage for one year, both indexed to 100 in 2019. A taller teal column than yellow means rents have outrun pay since the starting line.', { size: 16, font: 'dmSans', color: mix(ink, -.1), leading: 1.55, label: 'Chart guidance', role: 'BODY' }), text(M + 496, 876, 440, 'The dark line at 100 marks 2019. Everything above it is growth. By 2025 the average rent column sits 20 points above the wage column, a difference larger than the whole rise in wages across 2019 to 2021.', { size: 16, font: 'dmSans', color: mix(ink, -.1), leading: 1.55, label: 'Chart guidance', role: 'BODY' }));
        const take = obj(rect(M, 1060, CW, 130, panel, { rx: 14, stroke: hair, strokeWidth: 1, label: 'Takeaway panel', role: 'SIDEBAR' }), text(M + 32, 1078, 280, '+39 vs +19', { size: 48, font: 'bigShoulders', weight: 800, color: accent, wrap: false, leading: 1, role: 'SIDEBAR', label: 'Takeaway figure' }), text(M + 330, 1084, CW - 360, 'Over six years the typical renter saw their housing cost grow at twice the pace of their paycheck. The next chart shows where it happened fastest.', { size: 17, font: 'dmSans', color: ink, leading: 1.5, role: 'SIDEBAR', label: 'Takeaway text' }));
        return obj(G, bar(), frameBox(cx, cy, cw, chh, 'Rents rose twice as fast as wages', 'Median rent and median hourly wage, index, 2019 = 100'), gl, bars, ann, legend(cx + cw - 340, cy + 26), read, take, foot('Illustrative sample data. Notes 1 and 2.'));
      }
      // ranking page
      const cx = M, cy = 110, cw = CW;
      const rx0 = cx + 190, rw = cw - 190 - 110, rowH = 46, maxV = 60;
      const rows = DT.cities.flatMap(([c, r, w], i) => { const y = cy + 130 + i * rowH; return [text(cx + 28, y + 4, 150, c, { size: 15, font: 'dmSans', weight: i < 3 ? 700 : 500, color: ink, wrap: false, role: 'CAPTION', label: 'City' }), rect(rx0, y, rw, 26, grid, { rx: 5, label: 'Track', role: 'ORNAMENT' }), rect(rx0, y, rw * r / maxV, 26, i < 3 ? accent : mix(accent, -.3), { rx: 5, label: 'Rent growth bar', role: 'ORNAMENT' }), rect(rx0 + rw * w / maxV - 2, y - 4, 5, 34, secondary, { label: 'Wage marker', role: 'ORNAMENT' }), text(rx0 + rw + 14, y + 2, 80, '+' + r + '%', { size: 18, font: 'spaceGrotesk', weight: 700, color: i < 3 ? accent : ink, wrap: false, role: 'CAPTION', label: 'Value' })]; });
      const rank = obj(frameBox(cx, cy, cw, 130 + 10 * rowH + 56, 'Where rents grew fastest', 'Change in median rent, 2019 to 2025. Yellow tick = wage growth in the same city'), rows, hr(rx0, cy + 114, rw, grid, 1, { label: 'Axis rule' }), ...[0, 20, 40, 60].map(v => text(rx0 + rw * v / maxV - 20, cy + 94, 40, v + '%', { size: 11, font: 'dmMono', color: soft, align: 'center', wrap: false, role: 'CAPTION', label: 'Axis value' })));
      const my = cy + 130 + 10 * rowH + 90;
      const names = ['Ashford', 'Brenmouth', 'Calder Falls', 'Dunmore', 'Eastvale', 'Fenwick']; const mw = (CW - 40) / 3, mh = 190;
      const small = names.flatMap((n, i) => { const x = M + (i % 3) * (mw + 20), y = my + 54 + Math.floor(i / 3) * (mh + 20); const r = orn.rng(ctx.seed + i * 7); const seriesR = Array.from({ length: 7 }, (_, k) => 100 + k * (4 + r() * 8)); const seriesW = Array.from({ length: 7 }, (_, k) => 100 + k * (2 + r() * 4)); const px = (k: number) => x + 24 + k * ((mw - 48) / 6); const py = (v: number) => y + mh - 44 - (v - 100) / 60 * (mh - 100); return [rect(x, y, mw, mh, panel, { rx: 14, stroke: hair, strokeWidth: 1, label: 'Small multiple frame', role: 'SIDEBAR' }), text(x + 24, y + 16, mw - 48, n, { size: 16, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'CAPTION', label: 'Small multiple title' }), polyline(seriesR.map((v, k) => [px(k), py(v)] as [number, number]), accent, 3), polyline(seriesW.map((v, k) => [px(k), py(v)] as [number, number]), secondary, 3), text(x + mw - 90, y + 16, 66, '+' + Math.round(seriesR[6] - 100) + '%', { size: 16, font: 'spaceGrotesk', weight: 700, color: accent, align: 'right', wrap: false, role: 'CAPTION', label: 'Final value' }), text(x + 24, y + mh - 28, mw - 48, '2019' + '                    ' + '2025', { size: 11, font: 'dmMono', color: soft, wrap: false, role: 'CAPTION', label: 'Axis labels' })]; });
      const st = obj(text(M, my, 600, 'Six cities, same trend', { size: 22, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'HEADLINE', label: 'Section heading' }), ...legend(M + CW - 340, my + 4));
      return obj(G, bar(), rank, st, small, foot('Illustrative sample data. Notes 1, 2 and 3.'));
    }
    case 'BODY PAGE': {
      const big = obj(rect(M, 614, CW, 316, panel, { rx: 16, stroke: hair, strokeWidth: 1, label: 'Feature stat band', role: 'SIDEBAR' }), text(M + 36, 590, 520, '3 in 5', { size: 214, font: 'bigShoulders', weight: 800, color: secondary, wrap: false, leading: 1, label: 'Feature stat', role: 'HERO' }), text(M + 560, 664, 340, 'renters in the 50 cities now spend more than 30 percent of their pay on housing, up from two in five in 2019.', { size: 24, font: 'dmSans', weight: 500, color: ink, leading: 1.35, label: 'Feature stat caption', role: 'CAPTION' }), ...[0, 1, 2, 3, 4].map(i => rect(M + 560 + i * 62, 840, 52, 22, i < 3 ? secondary : grid, { rx: 5, label: 'Share pip', role: 'ORNAMENT' })));
      const sub = obj(text(M, 104, 500, 'What changed', { size: 15, font: 'dmMono', weight: 500, color: accent, tracking: .1, wrap: false, role: 'LABEL', label: 'Subhead' }), text(M, 930, 500, 'What it means', { size: 15, font: 'dmMono', weight: 500, color: accent, tracking: .1, wrap: false, role: 'LABEL', label: 'Subhead' }));
      return obj(G, bar(), sub, flow[0].objs, big, foot('Illustrative sample data. Notes 1 to 4.'));
    }
    case 'SIDEBAR': {
      const tx = M + 480, tw = W - M - tx;
      const rows = DT.cities.slice(0, 6).map(([c, r, w]) => [c, '+' + r + '%', '+' + w + '%', '+' + (r - w)]);
      const tbl = table(tx + 20, 168, [{ w: 150, font: 'dmSans', weight: 600 }, { w: 90, font: 'dmMono', align: 'right', color: accent }, { w: 90, font: 'dmMono', align: 'right', color: secondary }, { w: 78, font: 'dmMono', align: 'right', weight: 500 }], rows, { size: 15, font: 'dmSans', color: ink, rule: hair, ruleW: 1, pad: 10, head: ['City', 'Rent', 'Wage', 'Gap'], headFont: 'dmMono', headSize: 11, headColor: soft, headRule: ink, label: 'Data table' });
      const panelBox = obj(rect(tx, 110, tw, 610, panel, { rx: 16, stroke: hair, strokeWidth: 1, label: 'Table panel', role: 'SIDEBAR' }), text(tx + 24, 128, tw - 48, 'The six biggest gaps', { size: 20, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'HEADLINE', label: 'Table title' }), tbl.objs);
      const dy0 = tbl.bottom + 44; const gapBars: TelaVectorObject[] = [text(tx + 24, dy0 - 6, tw - 48, 'Each dot is a city', { size: 15, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'CAPTION', label: 'Unit chart title' }), ...Array.from({ length: 50 }, (_, i) => circle(tx + 38 + (i % 10) * ((tw - 76) / 9), dy0 + 38 + Math.floor(i / 10) * 30, 9, i < 41 ? accent : 'none', { stroke: i < 41 ? 'none' : secondary, strokeWidth: 2, label: i < 41 ? 'City: rent beat wages' : 'City: wages beat rent' })), text(tx + 24, dy0 + 188, tw - 48, 'Teal: rent grew faster (41). Outline: wages grew faster (9).', { size: 12, font: 'dmMono', color: soft, leading: 1.5, role: 'CAPTION', label: 'Unit chart key' })];
      const method = obj(rect(M, 780, CW, 300, panel, { rx: 16, stroke: hair, strokeWidth: 1, label: 'Method panel', role: 'SIDEBAR' }), text(M + 32, 804, 400, 'How we did this', { size: 22, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'HEADLINE', label: 'Method title' }), ...typeset(DT.notes.slice(0, 4).map((t, i) => ({ t, marker: { t: String(i + 1), dx: -32, size: 13, font: 'dmMono' as const, color: accent, weight: 500 }, after: 8 })), [{ x: M + 68, y: 852, w: 380, h: 220 }, { x: M + 508, y: 852, w: 380, h: 220 }], { size: 14, font: 'dmSans', color: mix(ink, -.1), leading: 1.5 }).objs);
      return obj(G, bar(), flow[1].objs, panelBox, gapBars, method, foot('Illustrative sample data. Notes 1 to 4.'));
    }
    default: {
      const nts = typeset(DT.notes.map((t, i) => ({ t, marker: { t: String(i + 1), dx: -40, size: 14, font: 'dmMono' as const, color: accent, weight: 500 }, after: 14 })), [{ x: M + 48, y: 170, w: 640, h: 520 }], { size: 16, font: 'dmSans', color: mix(ink, -.1), leading: 1.55 });
      const notes = obj(text(M, 112, 400, 'Notes and sources', { size: 28, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'HEADLINE', label: 'Notes heading' }), hr(M, 152, 700, ink, 2, { label: 'Notes rule' }), nts.objs);
      const dl = obj(rect(M + 780 - 40, 112, 220, 190, panel, { rx: 16, stroke: hair, strokeWidth: 1, label: 'Download card', role: 'SIDEBAR' }), text(M + 760, 130, 190, 'Get the data', { size: 20, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'SIDEBAR', label: 'Download heading' }), text(M + 760, 160, 190, 'Full dataset and chart code, free to reuse.', { size: 13, font: 'dmSans', color: soft, leading: 1.45, role: 'SIDEBAR', label: 'Download text' }), ...button(M + 760, 230, 180, 44, 'Download CSV', { fill: accent, color: paper, font: 'spaceGrotesk', size: 14, rx: 22 }));
      const cite = obj(rect(M, 520, CW, 150, panel, { rx: 16, stroke: hair, strokeWidth: 1, label: 'Cite panel', role: 'SIDEBAR' }), text(M + 32, 542, 300, 'Cite this chart', { size: 18, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'SIDEBAR', label: 'Cite heading' }), text(M + 32, 574, CW - 64, 'Numbers Desk (2026). “Rents outran paychecks in 41 of 50 cities.” Data story, 8 October. Illustrative sample data. numbersdesk.example/rents-2026', { size: 15, font: 'dmMono', color: mix(ink, -.1), leading: 1.55, role: 'SIDEBAR', label: 'Citation' }));
      const cr = table(M, 720, [{ w: 180, font: 'dmMono', color: soft, size: 12 }, { w: 380, font: 'dmSans', weight: 600 }], [['Reporting', 'Joel Adeyemi'], ['Data analysis', 'Marlon Fitch'], ['Graphics', 'The Numbers Desk'], ['Editing', 'Priya Natarajan']], { size: 15, font: 'dmSans', color: ink, rule: hair, ruleW: 1, pad: 9, label: 'Credits' });
      const news = obj(rect(M + 600, 720, CW - 600, 190, accent, { rx: 16, label: 'Newsletter card', role: 'SIDEBAR' }), text(M + 628, 744, CW - 656, 'One chart, every Thursday', { size: 22, font: 'spaceGrotesk', weight: 700, color: paper, wrap: false, role: 'SIDEBAR', label: 'Newsletter heading' }), text(M + 628, 778, CW - 656, 'The story behind a number you keep hearing.', { size: 14, font: 'dmSans', color: alpha(paper, .85), leading: 1.4, role: 'SIDEBAR', label: 'Newsletter pitch' }), ...button(M + 628, 836, 220, 44, 'Subscribe', { fill: paper, color: ink, font: 'spaceGrotesk', size: 14, rx: 22 }));
      const rel = obj(text(M, 960, 500, 'More from the Numbers Desk', { size: 22, font: 'spaceGrotesk', weight: 700, color: ink, wrap: false, role: 'HEADLINE', label: 'Related heading' }), hr(M, 998, CW, ink, 2, { label: 'Related rule' }), ...[['Housing', 'Why vacancy rates tell you less than you think'], ['Wages', 'Who got the raise: pay growth by decile'], ['Cities', 'The 50 metros, ranked by permits per resident']].flatMap(([k, t], i) => { const cw = (CW - 48) / 3, x = M + i * (cw + 24); const im = figure(x, 1022, cw, 120, { tone: 'dark', shade: mix(paper, .08), hint: 'Chart thumbnail', label: 'Related thumbnail' }); return [im.objs, text(x, 1154, cw, k.toUpperCase(), { size: 11, font: 'dmMono', color: accent, tracking: .1, wrap: false, role: 'LABEL', label: 'Related kicker' }), text(x, 1174, cw, t, { size: 17, font: 'spaceGrotesk', weight: 700, color: ink, leading: 1.25, role: 'HEADLINE', label: 'Related headline' })]; }).flat());
      return obj(G, bar(), notes, dl, cite, cr.objs, news, rel, foot('Illustrative sample data for the template preview.'));
    }
  }
};

// ═════════════════════════════════════════════════════════════════════════════
// 8 · art-photoessay — Frame by Frame (landscape; dark gallery pages, numbered plates)
// ═════════════════════════════════════════════════════════════════════════════
const PE = {
  head: 'The Night Market\nat Quay Street',
  deck: 'Nine hours with the fishmongers, porters and ice-sellers who open the harbour before the town wakes.',
  statement: [
    'Quay Street begins at nine in the evening and ends when the ice runs out. In between, it is the busiest square mile in the city and the only one that does not appear on any tourist map.',
    'I first came here to photograph the boats. I stayed for the hands: hands scaling, hands weighing, hands counting change in three currencies without looking. Everything on the quay is done by touch, because the lights are too weak to do anything else.',
    'I made these pictures over eleven nights in the spring, with one camera and one lens, never using flash. The market has a rule that nobody is photographed without being shown the picture first. That rule slowed me down. It also made every frame a conversation.',
    'Hana, who sells eels from the third stall, asked me to make her look tired because she was. Old Mr. Okeke asked for the opposite. I did both, and printed both, and left them in a box at the corner café.',
    'Photographs of work tend to flatter or pity. I wanted neither. I wanted what the quay itself offers: attention. Somebody is awake while the rest of us sleep, and their labour has a texture, a sound and a light of its own.',
    'The sequence runs from the first lorry to the last bucket of ice. It is not a story. It is a night.',
  ],
  plates: [['I', 'Ice, 21:05', 'A porter tips the first crate of the night into the weighing trough.'], ['II', 'The third stall', 'Hana arranges eels on cracked ice. “Don’t make me smile,” she said.'], ['III', 'Counting', 'Three currencies, one hand, no looking.'], ['IV', 'Lorry lights', 'Headlights from the 02:10 delivery fill the street with steam.'], ['V', 'The scale', 'Mr. Okeke checks the weight twice, then once more for luck.'], ['VI', 'Last bucket', 'By five the ice has gone and the quay belongs to the gulls.']] as Array<[string, string, string]>,
};

const photoEssay: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex } = ctx;
  const M = 60, soft = mix(ink, -.4), hair = alpha(ink, .22), shade = mix(paper, .1);
  const G = rect(0, 0, W, H, paper, { role: 'GROUND', label: 'Page ground' });
  const plateNo = (x: number, y: number, n: string, o: { size?: number; color?: string } = {}): TelaVectorObject => text(x, y, 80, n, { size: o.size ?? 11, font: 'tenor', color: o.color ?? accent, tracking: .06, wrap: false, label: 'Plate number', role: 'LABEL' });
  const cap = (x: number, y: number, w: number, title: string, body: string, color = soft): TelaVectorObject[] => { const t = text(x, y, w, title.toUpperCase(), { size: 8.5, font: 'tenor', color: ink, tracking: .2, wrap: false, label: 'Plate title', role: 'CAPTION' }); const b = text(x, y + 16, w, body, { size: 13, font: 'cormorant', italic: true, color, leading: 1.35, label: 'Caption', role: 'CAPTION' }); const c = text(x, below(b, 4), w, 'Photograph: Nadia Farouk', { size: 7.5, font: 'tenor', color: soft, tracking: .18, transform: 'uppercase', wrap: false, opacity: .8, label: 'Photo credit', role: 'CREDIT' }); return [t, b, c]; };
  const folioLine = (): TelaVectorObject[] => obj(text(M, H - 34, 400, 'Frame by Frame  ·  The Night Market at Quay Street', { size: 8, font: 'tenor', color: soft, tracking: .2, transform: 'uppercase', wrap: false, label: 'Running head', role: 'FOLIO' }), text(W - M - 60, H - 34, 60, String(pageIndex + 1).padStart(2, '0'), { size: 9, font: 'tenor', color: soft, tracking: .2, align: 'right', wrap: false, label: 'Folio', role: 'FOLIO' }));
  const flow = pour(PE.statement.map((t, i) => (i ? { t } : { t, drop: { font: 'cormorant' as const, lines: 3, color: accent, weight: 400 } })), [[{ x: M, y: 150, w: 270, h: 410 }, { x: M + 310, y: 150, w: 270, h: 410 }]], { size: 15, font: 'ebGaramond', color: alpha(ink, .88), leading: 1.6, after: 10 });

  switch (pageType) {
    case 'LONG-FORM OPENER': {
      const px = 620;
      const img = figure(0, 0, px, H, { tone: 'dark', shade: mix(paper, .1), vignette: true, hint: 'Plate I · full-height photograph', hero: true, label: 'Hero plate' });
      const hed = text(px + 44, 150, W - px - 88, PE.head, { size: 50, font: 'cormorant', weight: 300, italic: true, color: ink, leading: 1.02, tracking: -.005, label: 'Headline', role: 'HEADLINE' });
      const deck = text(px + 44, below(hed, 22), W - px - 100, PE.deck, { size: 16, font: 'ebGaramond', color: alpha(ink, .8), leading: 1.55, label: 'Standfirst', role: 'DECK' });
      const by = obj(hr(px + 44, below(deck, 28), 56, accent, 2, { label: 'Byline rule' }), text(px + 44, below(deck, 40), 300, 'PHOTOGRAPHS AND TEXT BY NADIA FAROUK', { size: 8.5, font: 'tenor', color: ink, tracking: .22, wrap: false, label: 'Byline', role: 'BYLINE' }), text(px + 44, below(deck, 58), 300, 'QUAY STREET  ·  APRIL 2026  ·  6 PLATES', { size: 8, font: 'tenor', color: soft, tracking: .22, wrap: false, label: 'Dateline', role: 'DATELINE' }));
      const dots = PE.plates.flatMap(([n], i) => [circle(px + 52 + i * 34, H - 110, 4, i === 0 ? accent : 'none', { stroke: i === 0 ? accent : soft, strokeWidth: 1, label: 'Plate dot' }), text(px + 38 + i * 34, H - 98, 28, n, { size: 7.5, font: 'tenor', color: i === 0 ? accent : soft, align: 'center', wrap: false, label: 'Plate numeral', role: 'LABEL' })]);
      return obj(G, img.objs, vr(px, 0, H, accent, 1.5, { label: 'Gold rule' }), plateNo(px + 44, 60, 'PLATE I'), text(px + 44, 78, 300, 'A photo essay', { size: 9, font: 'tenor', color: soft, tracking: .24, transform: 'uppercase', wrap: false, label: 'Kicker', role: 'KICKER' }), hed, deck, by, dots, text(px + 44, H - 60, 340, 'Ice, 21:05. A porter tips the first crate of the night.', { size: 12, font: 'cormorant', italic: true, color: soft, wrap: false, label: 'Hero caption', role: 'CAPTION' }));
    }
    case 'PHOTO GALLERY': {
      if (pageIndex === 1) {
        const a = figure(M, 54, 640, 420, { tone: 'dark', shade: shade, vignette: true, hint: 'Plate II · landscape · 3:2', label: 'Plate II' });
        const b = figure(752, 54, 244, 262, { tone: 'dark', shade: shade, vignette: true, hint: 'Plate III · portrait', label: 'Plate III' });
        const c = figure(752, 408, 244, 160, { tone: 'dark', shade: shade, vignette: true, hint: 'Plate IV · detail', label: 'Plate IV' });
        return obj(G, a.objs, b.objs, c.objs, plateNo(M, 498, 'II'), ...cap(M + 40, 494, 400, PE.plates[1][1], PE.plates[1][2], alpha(ink, .75)), plateNo(752, 326, 'III'), ...cap(752 + 34, 322, 210, PE.plates[2][1], PE.plates[2][2], alpha(ink, .75)), plateNo(752, 580, 'IV'), ...cap(752 + 34, 576, 210, PE.plates[3][1], PE.plates[3][2], alpha(ink, .75)), hr(M, 640, 640, hair, 1, { label: 'Caption rule' }), text(M, 656, 560, 'The pictures are sequenced by the clock rather than by subject. Plate II was made at 21:40, plate III at 23:15, plate IV at 02:10 when the lorries arrive.', { size: 14, font: 'ebGaramond', color: alpha(ink, .8), leading: 1.6, label: 'Sequence note', role: 'BODY' }), folioLine());
      }
      const pano = figure(0, 0, W, 360, { tone: 'dark', shade: shade, vignette: true, hint: 'Plate V · panorama · full bleed · 1056 × 360', label: 'Plate V', hero: false });
      const l = figure(M, 462, 450, 244, { tone: 'dark', shade: shade, vignette: true, hint: 'Plate VI · 16:9', label: 'Plate VI' });
      const r = figure(W - M - 450, 462, 450, 244, { tone: 'dark', shade: shade, vignette: true, hint: 'Plate VII · 16:9', label: 'Plate VII' });
      return obj(G, pano.objs, plateNo(M, 376, 'V'), ...cap(M + 40, 372, 520, PE.plates[3][1], PE.plates[3][2], alpha(ink, .75)), l.objs, r.objs, plateNo(M, 718, 'VI'), text(M + 40, 716, 400, 'A thin line of steam, a long night.', { size: 13, font: 'cormorant', italic: true, color: alpha(ink, .75), wrap: false, label: 'Caption', role: 'CAPTION' }), plateNo(W - M - 450, 718, 'VII'), text(W - M - 410, 716, 400, 'Mr. Okeke checks the scale twice.', { size: 13, font: 'cormorant', italic: true, color: alpha(ink, .75), wrap: false, label: 'Caption', role: 'CAPTION' }), folioLine());
    }
    case 'BODY PAGE': {
      const img = figure(660, 54, 336, 466, { tone: 'dark', shade: shade, hint: 'Plate · portrait · 3:4', caption: 'Hana, third stall, 22:30. “Don’t make me smile.”', credit: 'Nadia Farouk', capFont: 'cormorant', capSize: 13, capItalic: true, capColor: alpha(ink, .75), creditFont: 'tenor', label: 'Statement portrait' });
      const hd = obj(text(M, 58, 400, 'Photographer’s statement', { size: 30, font: 'cormorant', weight: 300, italic: true, color: ink, wrap: false, label: 'Section title', role: 'HEADLINE' }), hr(M, 108, 56, accent, 2, { label: 'Title rule' }));
      const q = pullQuote(660, 584, 336, '“Everything on the quay is done by touch.”', { size: 24, font: 'cormorant', italic: true, color: accent, rule: 'top', ruleColor: accent, ruleW: 1.5, pad: 16, leading: 1.15, attrib: 'Nadia Farouk', attribColor: soft, attribFont: 'tenor' });
      return obj(G, hd, flow[0].objs, img.objs, q.objs, folioLine());
    }
    case 'SIDEBAR': {
      const fw = 118, fh = 70, gx = 14, gy = 26; const sheet: TelaVectorObject[] = [text(M, 60, 400, 'Contact sheet', { size: 30, font: 'cormorant', weight: 300, italic: true, color: ink, wrap: false, role: 'HEADLINE', label: 'Section title' }), hr(M, 108, 56, accent, 2)];
      for (let i = 0; i < 24; i++) { const x = M + (i % 6) * (fw + gx), y = 140 + Math.floor(i / 6) * (fh + gy); sheet.push(rect(x, y, fw, fh, shade, { stroke: i === 9 ? accent : 'none', strokeWidth: i === 9 ? 2 : 0, label: 'Contact frame', role: 'IMAGE_SLOT' }), text(x, y + fh + 6, fw, String(i + 1).padStart(2, '0') + (i === 9 ? '  ·  PICK' : ''), { size: 7.5, font: 'tenor', color: i === 9 ? accent : soft, tracking: .2, wrap: false, label: 'Frame number', role: 'LABEL' })); }
      const ex = table(M, 590, [{ w: 70, font: 'tenor', size: 9, color: accent }, { w: 190, font: 'ebGaramond', size: 13 }, { w: 130, font: 'dmMono', size: 11, color: soft }, { w: 130, font: 'dmMono', size: 11, color: soft }, { w: 140, font: 'dmMono', size: 11, color: soft }], [['I', 'Ice, 21:05', '35mm  f/1.4', '1/60 s', 'ISO 3200'], ['II', 'The third stall', '35mm  f/1.4', '1/50 s', 'ISO 4000'], ['III', 'Counting', '35mm  f/2', '1/80 s', 'ISO 3200'], ['IV', 'Lorry lights', '35mm  f/1.4', '1/30 s', 'ISO 6400']], { size: 13, font: 'ebGaramond', color: ink, rule: hair, pad: 7, head: ['Plate', 'Title', 'Lens', 'Shutter', 'Sensitivity'], headFont: 'tenor', headSize: 8, headColor: soft, headRule: ink, label: 'Exposure log' });
      const note = text(M + 740, 140, 196, 'The ten plates published here were chosen from 1,104 frames. Plate selection follows the clock: the first, the tenth and the last frame of each hour that mattered.', { size: 13, font: 'ebGaramond', italic: true, color: alpha(ink, .8), leading: 1.55, label: 'Selection note', role: 'SIDEBAR' });
      return obj(G, sheet, ex.objs, note, folioLine());
    }
    default: {
      const list = PE.plates.flatMap(([n, t, d], i) => { const y = 120 + i * 84; return [text(M, y, 44, n, { size: 26, font: 'cormorant', weight: 300, italic: true, color: accent, wrap: false, label: 'Plate numeral', role: 'LABEL' }), text(M + 60, y + 2, 320, t, { size: 17, font: 'cormorant', weight: 500, color: ink, wrap: false, label: 'Plate title', role: 'CAPTION' }), text(M + 60, y + 26, 360, d, { size: 12, font: 'ebGaramond', italic: true, color: soft, leading: 1.4, label: 'Plate caption', role: 'CAPTION' }), hr(M, y + 70, 440, hair, .75, { label: 'List rule' })]; });
      const cr = table(M + 560, 120, [{ w: 150, font: 'tenor', size: 8.5, color: accent, tracking: .18 }, { w: 270, font: 'cormorant', size: 17 }], [['Photographs', 'Nadia Farouk'], ['Text', 'Nadia Farouk'], ['Editing', 'Priya Natarajan'], ['Printing', 'Okoro Lab, Leith'], ['Design', 'Frame by Frame studio']], { size: 14, font: 'cormorant', color: ink, rule: hair, pad: 8, label: 'Credits', head: ['Credits', ''], headFont: 'tenor', headSize: 8.5, headColor: accent, headRule: ink });
      const closing = text(M + 560, 440, 360, 'Thank you to the porters, fishmongers and ice-sellers of Quay Street, who agreed to be looked at.', { size: 22, font: 'cormorant', weight: 300, italic: true, color: ink, leading: 1.25, label: 'Closing line', role: 'DECK' });
      const colo = text(M + 560, 680, 380, 'Frame by Frame is set in Cormorant Garamond, EB Garamond and Tenor Sans. Photographs were made with natural and available light only. All sitters saw their picture before publication.', { size: 9.5, font: 'tenor', color: soft, leading: 1.6, label: 'Colophon', role: 'FOOTNOTE' });
      return obj(G, list, vr(M + 510, 100, 600, hair, 1, { label: 'Column rule' }), cr.objs, closing, colo, folioLine());
    }
  }
};

export const DESIGNS_B: Record<string, PublicationDesigner> = { 'art-interview': interview, 'art-explainer': explainer, 'art-data': dataStory, 'art-photoessay': photoEssay };

export const LESSONS_B: Record<string, DesignLesson> = {
  'art-data': { principle: 'A chart earns its place by making one comparison obvious: a giant number states the claim, and the frames underneath let the reader check it.', history: 'Data journalism took shape in the 2010s as newsrooms such as the Guardian’s Datablog and FiveThirtyEight began publishing the numbers behind their stories. The conventions it settled on, annotated charts, oversized key figures, source lines and downloadable data, descend from William Playfair’s eighteenth-century line and bar charts and from Edward Tufte’s argument that the ink should carry information.', tryThis: 'Delete the gridlines from the column chart and check whether the callout still tells the story. Then put one back.', interestTag: 'Data journalism', related: ['Data visualisation', 'Chart design', 'Annotation'] },
  'art-photoessay': { principle: 'A photo essay is edited by the clock and the caption: plates are numbered, sizes change with importance, and the text stays quiet so the pictures carry the argument.', history: 'The photo essay was shaped by Life magazine from 1936 and by W. Eugene Smith’s long sequences, and later by agencies such as Magnum, which treated the edit as part of the authorship. Numbered plates and long captions come from the monograph tradition, where the sequence of pictures matters as much as any single frame.', tryThis: 'Swap plates II and V and read the essay again. Note which picture needed the one before it.', interestTag: 'Photography', related: ['Photo essay', 'Photo editing', 'Captions'] },
  'art-interview': { principle: 'In a conversation the typography is the speaker change: a hanging Q and A in the margin lets the reader hear the exchange before reading a word.', history: 'The question-and-answer format runs from Plato’s dialogues to the Paris Review’s “Art of Fiction” series, begun in 1953, which printed whole interviews as text with the speaker’s name in small capitals. Magazines later added speaker cards, margin notes and quick-fire rounds to keep a long transcript moving.', tryThis: 'Swap the Q marker for the interviewer’s initials and notice how the page changes from a set text into a transcript.', interestTag: 'Interview design', related: ['Q&A format', 'Oral history', 'Margin notes'] },
  'art-explainer': { principle: 'An explainer teaches in the order the reader needs it: a short version first, then numbered steps, with the vocabulary in a rail beside them.', history: 'Explanatory journalism grew from the encyclopaedia entry and the how-it-works book, then from the graphic explainers of Scientific American and the Guardian. On the web, the numbered step, the table of contents rail and the glossary became standard because readers arrive mid-page and need to find their place.', tryThis: 'Rewrite step one so it fits on one line, then check the numeral and heading still read as a single idea.', interestTag: 'Explanatory journalism', related: ['Information design', 'Glossary', 'Web typography'] },
};
