// catalogsA — CATALOG templates 1–3: Supply Catalog (products + spec tables), Lookbook (fashion),
// Publisher Catalog (cover grid, ISBN/price lines, rights, author storefront).
//
// Catalog pages are built from the same parts a print catalog uses — cards with SKU / price lines, spec tables,
// order forms, an alphabetical index — drawn as editable objects with templateRole SKU / PRICE / SPEC where it
// helps a product feed bind to them.
import type { TelaVectorObject } from '../../../../types';
import type { DesignLesson } from '../types';
import type { PublicationDesigner } from './types';
import { rect, circle, hr, vr, path, text, below, imageSlot, mix, alpha } from '../../templateKit';
import * as orn from '../../ornaments';
import { typeset, cols, figure, pullQuote, table, pill, button, barcode, checkbox, runningFoot, label, verso } from './pubKit';

const obj = (...parts: Array<TelaVectorObject | TelaVectorObject[]>): TelaVectorObject[] => parts.flat();
const stars = (x: number, y: number, n: number, size: number, color: string, empty: string): TelaVectorObject[] => Array.from({ length: 5 }, (_, i) => path(x + i * (size + 3), y, size, size, orn.starPath(5, .42), i < n ? color : empty, { label: 'Rating star' }));

// ═════════════════════════════════════════════════════════════════════════════
// 1 · cat-product — Supply Catalog (Letter; spec-sheet system, orange + ink)
// ═════════════════════════════════════════════════════════════════════════════
const PRODUCTS: Array<[string, string, string, string]> = [
  ['FS-1001', 'Torque driver, 2–10 N·m', 'Preset click-release, reversible ratchet, calibrated to ±4%.', '$48.00'],
  ['FS-1002', 'Torque driver, 10–50 N·m', 'Same mechanism in a longer handle for larger fasteners.', '$64.00'],
  ['FS-1010', 'Bit set, 42 piece', 'Hardened S2 steel with a magnetic holder and a labelled case.', '$22.50'],
  ['FS-1015', 'Hex key set, long arm', 'Metric 1.5–10 mm, ball end on one side, chrome-vanadium.', '$14.80'],
  ['FS-1022', 'Digital caliper, 150 mm', 'Stainless, 0.01 mm resolution, with a thumb wheel and a case.', '$39.00'],
  ['FS-1030', 'Steel rule, 300 mm', 'Etched graduations in millimetres and thirty-seconds of an inch.', '$7.20'],
  ['FS-1041', 'Deadblow mallet, 24 oz', 'Shot-filled head; no rebound, no marks on finished surfaces.', '$18.40'],
  ['FS-1048', 'Pull saw, 240 mm', 'Fine 17 tpi blade for flush cuts, with a replaceable edge.', '$26.00'],
  ['FS-1055', 'Chisel set, 4 piece', 'Boxwood handles and bevelled edges, 6, 12, 19 and 25 mm.', '$58.00'],
  ['FS-1062', 'Marking gauge, brass', 'Brass-faced beam with a hardened pin and a locking thumbscrew.', '$31.50'],
  ['FS-1070', 'Bench hook, beech', 'Reversible for left- and right-handed use, with a stop.', '$19.00'],
  ['FS-1077', 'Shop apron, waxed canvas', 'Twelve-ounce canvas, cross-back straps and a deep hip pocket.', '$44.00'],
];
const SECTIONS = ['Measuring', 'Hand tools', 'Workholding', 'Fasteners', 'Finishing', 'Workwear', 'Storage', 'Bulk and trade'];
const SEC_PAGES = ['6', '14', '38', '52', '81', '96', '104', '112'];

const supply: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex, seed } = ctx;
  const M = 40, R = W - M, CW = W - 2 * M, soft = mix(ink, .45), hair = alpha(ink, .22), card = '#FFFFFF';
  const G = rect(0, 0, W, H, paper, { role: 'GROUND', label: 'Page ground' });
  const head = (sec: string, pg: string): TelaVectorObject[] => obj(rect(0, 0, W, 6, accent, { label: 'Top bar', role: 'ORNAMENT' }), label(M, 24, 300, sec, { size: 10, font: 'archivo', color: ink, weight: 800, tracking: .2 }), label(R - 300, 24, 300, 'Foundry Supply Co.  ·  2027  ·  ' + pg, { size: 8.5, font: 'jetbrains', color: soft, align: 'right', tracking: .1, transform: 'none' }), hr(M, 46, CW, ink, 1.5, { label: 'Head rule' }));
  const foot = (): TelaVectorObject[] => obj(hr(M, H - 40, CW, hair, .75, { label: 'Foot rule' }), text(verso(pageIndex) ? M : R - 60, H - 30, 60, String(pageIndex * 2 + 5), { size: 9, font: 'jetbrains', weight: 700, color: ink, align: verso(pageIndex) ? 'left' : 'right', wrap: false, label: 'Folio', role: 'FOLIO' }), text(verso(pageIndex) ? M + 40 : M, H - 30, 500, 'Free shipping over $150  ·  Order by 4 p.m. for same-day dispatch', { size: 8.5, font: 'inter', color: soft, wrap: false, label: 'Running foot', role: 'FOLIO' }));
  const reg = (x: number, y: number, c: string): TelaVectorObject[] => [circle(x, y, 7, 'none', { stroke: c, strokeWidth: 1, label: 'Registration mark' }), hr(x - 12, y, 24, c, 1, { label: 'Registration mark' }), vr(x, y - 12, 24, c, 1, { label: 'Registration mark' })];

  const productCard = (x: number, y: number, w: number, h: number, p: [string, string, string, string], big: boolean): TelaVectorObject[] => {
    const imgH = big ? 168 : 92; const o: TelaVectorObject[] = [rect(x, y, w, h, card, { stroke: hair, strokeWidth: 1, label: 'Product card', role: 'SIDEBAR' }), ...imageSlot(x, y, w, imgH, { tone: 'light', shade: mix(paper, -.05), caption: big ? 'Product photograph' : '', silent: !big, label: 'Product image' })];
    const sx = x + 14, sw = w - 28;
    o.push(text(sx, y + imgH + 10, sw, p[0], { size: big ? 10 : 9, font: 'jetbrains', weight: 700, color: accent, wrap: false, label: 'SKU', role: 'SKU' }));
    const nm = text(sx, y + imgH + (big ? 26 : 24), sw, p[1], { size: big ? 16 : 12, font: 'archivo', weight: 800, color: ink, leading: 1.15, label: 'Product name', role: 'HEADLINE' }); o.push(nm);
    if (big) o.push(text(sx, below(nm, 4), sw, p[2], { size: 11, font: 'inter', color: soft, leading: 1.4, label: 'Product description', role: 'BODY' }));
    if (!big) o.push(text(sx, y + imgH + 42, sw, p[2], { size: 9, font: 'inter', color: soft, leading: 1.35, label: 'Product description', role: 'BODY' }));
    o.push(text(sx, y + h - (big ? 40 : 30), 120, p[3], { size: big ? 22 : 15, font: 'archivo', weight: 800, color: ink, wrap: false, label: 'Price', role: 'PRICE' }));
    o.push(label(x + w - 92, y + h - (big ? 36 : 28), 40, 'Qty', { size: 7.5, font: 'jetbrains', color: soft, tracking: .1, transform: 'none' }), rect(x + w - 66, y + h - (big ? 42 : 32), 52, big ? 26 : 20, 'none', { stroke: ink, strokeWidth: 1, label: 'Quantity box', role: 'ORNAMENT' }));
    return o;
  };

  switch (pageType) {
    case 'COVER': {
      const block = rect(0, 56, W, 600, accent, { label: 'Cover block', role: 'ORNAMENT' });
      const bar = obj(rect(0, 0, W, 56, ink, { label: 'Cover bar', role: 'ORNAMENT' }), text(M, 18, 400, 'FOUNDRY SUPPLY CO.', { size: 18, font: 'archivo', weight: 800, color: paper, tracking: .12, wrap: false, label: 'Masthead', role: 'LOGO' }), label(R - 300, 22, 300, 'Trade and workshop  ·  Est. 1974', { size: 9, font: 'jetbrains', color: paper, align: 'right', tracking: .12, transform: 'none' }));
      const yr = text(M - 8, 62, 760, '2027', { size: 330, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, tracking: -.02, label: 'Catalog year', role: 'HEADLINE' });
      const title = text(M, 432, 560, 'The Supply\nCatalog', { size: 78, font: 'archivo', weight: 800, color: ink, leading: .98, tracking: -.02, label: 'Title', role: 'HEADLINE' });
      const tag = text(M, 612, 700, 'Edition 41  ·  1,284 products  ·  Prices effective 1 January 2027', { size: 11, font: 'jetbrains', weight: 600, color: ink, label: 'Edition line', role: 'LABEL' });
      const imgs = [0, 1, 2].flatMap(i => imageSlot(M + i * (CW / 3 + 4), 690, CW / 3 - 8, 210, { tone: 'light', shade: mix(paper, -.06), caption: ['Measuring', 'Cutting', 'Workholding'][i], label: 'Cover product image' }));
      const sections = obj(hr(M, 930, CW, ink, 2, { label: 'Rule' }), ...SECTIONS.slice(0, 4).map((s, i) => text(M + i * 186, 946, 180, `0${i + 1}  ${s}`, { size: 11, font: 'archivo', weight: 700, color: ink, wrap: false, label: 'Section teaser', role: 'LABEL' })), ...SECTIONS.slice(4).map((s, i) => text(M + i * 186, 970, 180, `0${i + 5}  ${s}`, { size: 11, font: 'archivo', weight: 700, color: ink, wrap: false, label: 'Section teaser', role: 'LABEL' })));
      return obj(G, block, bar, reg(M + 10, 80, ink), reg(R - 10, 80, ink), reg(M + 10, 634, ink), reg(R - 10, 634, ink), yr, title, tag, imgs, sections, ...barcode(R - 120, H - 66, 120, 36, ink, seed), text(R - 120, H - 26, 120, '9 780000 270412', { size: 8, font: 'jetbrains', color: soft, align: 'center', wrap: false, label: 'Barcode number', role: 'SKU' }), text(M, H - 42, 400, 'foundrysupply.example  ·  1 800 555 0127', { size: 11, font: 'jetbrains', weight: 600, color: ink, wrap: false, label: 'Contact line', role: 'LABEL' }));
    }
    case 'CONTENTS': {
      const t = text(M, 70, 520, 'Contents', { size: 64, font: 'archivo', weight: 800, color: ink, tracking: -.02, wrap: false, label: 'Contents title', role: 'HEADLINE' });
      const rows = SECTIONS.flatMap((s, i) => { const y = 186 + i * 62; return [text(M, y, 56, String(i + 1).padStart(2, '0'), { size: 14, font: 'jetbrains', weight: 700, color: accent, wrap: false, label: 'Section number', role: 'LABEL' }), text(M + 56, y - 8, 300, s, { size: 28, font: 'archivo', weight: 800, color: ink, wrap: false, label: 'Section name', role: 'HEADLINE' }), hr(M + 56 + s.length * 17 + 20, y + 22, 400 - s.length * 17 - 20, soft, 1, { dash: [2, 5], label: 'Leader' }), text(M + 456, y - 4, 60, SEC_PAGES[i], { size: 22, font: 'jetbrains', weight: 700, color: ink, align: 'right', wrap: false, label: 'Page number', role: 'FOLIO' }), hr(M, y + 40, 516, hair, .75, { label: 'Row rule' })]; });
      const hx = 580, hw = R - hx;
      const how = obj(rect(hx, 186, hw, 490, ink, { label: 'How to order panel', role: 'SIDEBAR' }), rect(hx, 188, hw, 8, accent, { label: 'Panel bar', role: 'RULE' }), text(hx + 20, 214, hw - 40, 'How to order', { size: 24, font: 'archivo', weight: 800, color: paper, wrap: false, role: 'SIDEBAR', label: 'Panel title' }), typeset(['Find the SKU. Every product has one, in the form FS-0000.', 'Order online, by phone or on the form on page 118.', 'Trade accounts receive net 30 terms and quantity breaks.', 'Orders before 4 p.m. ship the same day.'].map((tt, i) => ({ t: tt, marker: { t: String(i + 1), dx: -26, size: 15, font: 'jetbrains' as const, color: accent, weight: 700 }, after: 12 })), [{ x: hx + 46, y: 262, w: hw - 66, h: 300 }], { size: 12.5, font: 'inter', color: paper, leading: 1.5 }).objs, hr(hx + 20, 560, hw - 40, alpha(paper, .3), 1), text(hx + 20, 574, hw - 40, '1 800 555 0127\norders@fsupply.example', { size: 11, font: 'jetbrains', weight: 600, color: accent, leading: 1.6, role: 'SIDEBAR', label: 'Contact details' }));
      const neu = obj(label(M, 724, 300, 'New for 2027', { size: 10, font: 'archivo', color: accent, weight: 800, tracking: .22 }), hr(M, 742, CW, ink, 2), ...PRODUCTS.slice(0, 3).flatMap((p, i) => { const w = CW / 3 - 12, x = M + i * (w + 18); return [...imageSlot(x, 756, w, 110, { tone: 'light', shade: mix(paper, -.06), silent: true, label: 'New product image' }), text(x, 874, w, p[0], { size: 9, font: 'jetbrains', weight: 700, color: accent, wrap: false, role: 'SKU', label: 'SKU' }), text(x, 890, w, p[1], { size: 14, font: 'archivo', weight: 800, color: ink, leading: 1.15, role: 'HEADLINE', label: 'Product name' }), text(x, 940, w, p[3], { size: 18, font: 'archivo', weight: 800, color: ink, wrap: false, role: 'PRICE', label: 'Price' })]; }));
      return obj(G, head('Contents', 'p. 3'), t, rows, how, neu, foot());
    }
    case 'SECTION OPENER': {
      const panel = rect(0, 0, 300, H, accent, { label: 'Section panel', role: 'ORNAMENT' });
      const num = text(18, 40, 300, '02', { size: 330, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, tracking: -.03, label: 'Section number', role: 'HERO' });
      const lab = text(40, H - 120, 220, 'SECTION', { size: 11, font: 'jetbrains', weight: 700, color: ink, tracking: .3, wrap: false, rotation: 0, label: 'Section label', role: 'KICKER' });
      const title = text(340, 60, 440, 'Hand\ntools', { size: 120, font: 'archivo', weight: 800, color: ink, leading: .95, tracking: -.03, label: 'Section title', role: 'HEADLINE' });
      const intro = text(340, below(title, 24), 400, 'Tools that earn their place on the bench. Every item in this section is tested by our own makers for at least a season before it is listed, and every one carries a lifetime guarantee against defects.', { size: 15, font: 'inter', color: mix(ink, .15), leading: 1.55, label: 'Section introduction', role: 'DECK' });
      const img = figure(340, below(intro, 28), 436, 230, { tone: 'light', shade: mix(paper, -.06), hint: 'Section photograph', hero: true, label: 'Section hero image' });
      const lst = table(340, img.bottom + 30, [{ w: 80, font: 'jetbrains', size: 9, color: accent, weight: 700 }, { w: 270, font: 'archivo', size: 13, weight: 700 }, { w: 86, font: 'jetbrains', size: 9, align: 'right', color: soft }], PRODUCTS.slice(0, 7).map((p, i) => [p[0], p[1], 'p. ' + (15 + i * 2)]), { size: 13, font: 'archivo', color: ink, rule: hair, pad: 6, head: ['SKU', 'In this section', 'Page'], headFont: 'jetbrains', headSize: 8, headColor: soft, headRule: ink, label: 'Section index' });
      return obj(G, panel, num, lab, title, intro, img.objs, lst.objs, hr(340, H - 40, R - 340, hair, .75, { label: 'Foot rule' }), text(R - 60, H - 30, 60, '13', { size: 9, font: 'jetbrains', weight: 700, color: ink, align: 'right', wrap: false, label: 'Folio', role: 'FOLIO' }));
    }
    case 'PRODUCT GRID': {
      if (pageIndex === 3) {
        const cw2 = (CW - 24) / 2, ch = 292, y0 = 88;
        const cards = PRODUCTS.slice(0, 6).flatMap((p, i) => productCard(M + (i % 2) * (cw2 + 24), y0 + Math.floor(i / 2) * (ch + 14), cw2, ch, p, true));
        return obj(G, head('02  Hand tools', 'p. 15'), cards, foot());
      }
      const cw3 = (CW - 32) / 3, ch = 208, y0 = 88;
      const cards = PRODUCTS.flatMap((p, i) => productCard(M + (i % 3) * (cw3 + 16), y0 + Math.floor(i / 3) * (ch + 12), cw3, ch, p, false));
      return obj(G, head('02  Hand tools  ·  continued', 'p. 17'), cards, foot());
    }
    case 'PRODUCT DETAIL': {
      const p = PRODUCTS[0];
      const big = figure(M, 90, 404, 404, { tone: 'light', shade: mix(paper, -.05), hint: 'Product photograph · 1:1', hero: true, label: 'Product hero image', frame: hair });
      const thumbs = [0, 1, 2, 3].flatMap(i => imageSlot(M + i * 102, 506, 92, 92, { tone: 'light', shade: mix(paper, -.07), silent: true, frame: i === 0 ? accent : hair, frameWidth: i === 0 ? 2 : 1, label: 'Thumbnail' }));
      const rx = 480, rw = R - rx;
      const info = obj(label(rx, 90, rw, 'Hand tools  ·  Torque', { size: 9, font: 'jetbrains', color: soft, tracking: .12, transform: 'none', role: 'KICKER' }), text(rx, 110, rw, p[1], { size: 34, font: 'archivo', weight: 800, color: ink, leading: 1.05, tracking: -.01, label: 'Product name', role: 'HEADLINE' }), text(rx, 192, rw, p[0] + '  ·  In stock', { size: 11, font: 'jetbrains', weight: 700, color: accent, wrap: false, role: 'SKU', label: 'SKU' }), ...stars(rx, 218, 4, 14, accent, hair), text(rx + 100, 218, 200, '4.7  (218 reviews)', { size: 11, font: 'inter', color: soft, wrap: false, label: 'Rating', role: 'CAPTION' }), text(rx, 244, rw, p[3], { size: 40, font: 'archivo', weight: 800, color: ink, wrap: false, label: 'Price', role: 'PRICE' }), text(rx + 160, 262, 160, 'each, ex. tax', { size: 11, font: 'inter', color: soft, wrap: false, label: 'Price note', role: 'CAPTION' }));
      const feats = typeset(['Click-release at the set torque, ±4% accuracy', 'Reversible ratchet, 72-tooth, 5° swing arc', 'Locking collar so the setting cannot drift', 'Supplied with calibration certificate and case'].map(t => ({ t, marker: { t: '■', dx: -16, size: 8, color: accent, font: 'inter' as const, dy: 4 }, after: 6 })), [{ x: rx + 18, y: 316, w: rw - 18, h: 130 }], { size: 12.5, font: 'inter', color: ink, leading: 1.45 });
      const brk = table(rx, 468, [{ w: 110, font: 'jetbrains', size: 10 }, { w: 100, font: 'archivo', size: 14, weight: 800, align: 'right' }, { w: rw - 210, font: 'jetbrains', size: 10, color: accent, align: 'right', weight: 700 }], [['1 – 9', '$48.00', ''], ['10 – 24', '$44.50', 'save 7%'], ['25 +', '$41.00', 'save 15%']], { size: 12, font: 'inter', color: ink, rule: hair, pad: 7, head: ['Quantity', 'Unit price', 'Saving'], headFont: 'jetbrains', headSize: 8, headColor: soft, headRule: ink, label: 'Quantity breaks' });
      const add = button(rx, 590, rw, 46, 'Add to order', { fill: accent, color: ink, font: 'archivo', size: 15, rx: 0 });
      const specs = table(M, 640, [{ w: 150, font: 'jetbrains', size: 9, color: soft }, { w: 200, font: 'inter', size: 11 }, { w: 150, font: 'jetbrains', size: 9, color: soft }, { w: 236, font: 'inter', size: 11 }], [['Range', '2 – 10 N·m', 'Drive', '1/4 in hex'], ['Accuracy', '±4% of reading', 'Length', '168 mm'], ['Weight', '212 g', 'Material', 'Chrome-vanadium, glass-filled nylon'], ['Standard', 'ISO 6789-1 type II', 'Warranty', 'Lifetime, against defects']], { size: 11, font: 'inter', color: ink, rule: hair, pad: 7, head: ['Specification', '', '', ''], headFont: 'jetbrains', headSize: 8, headColor: accent, headRule: ink, label: 'Specifications', role: 'SPEC' });
      const rel = obj(label(M, 800, 300, 'Customers also bought', { size: 10, font: 'archivo', color: accent, weight: 800, tracking: .2 }), hr(M, 818, CW, ink, 2), ...PRODUCTS.slice(2, 6).flatMap((q, i) => { const w = (CW - 48) / 4, x = M + i * (w + 16); return [...imageSlot(x, 832, w, 80, { tone: 'light', shade: mix(paper, -.06), silent: true, label: 'Related image' }), text(x, 920, w, q[1], { size: 11.5, font: 'archivo', weight: 700, color: ink, leading: 1.2, role: 'HEADLINE', label: 'Related name' }), text(x, 960, w, q[3], { size: 13, font: 'archivo', weight: 800, color: ink, wrap: false, role: 'PRICE', label: 'Price' })]; }));
      return obj(G, head('02  Hand tools  ·  Torque drivers', 'p. 21'), big.objs, thumbs, info, feats.objs, brk.objs, add, specs.objs, rel, foot());
    }
    case 'SPEC TABLE': {
      const rows = [['FS-1001', 'Torque driver', '2–10 N·m', '212 g', 'Cr-V steel', '1', '$48.00'], ['FS-1002', 'Torque driver', '10–50 N·m', '388 g', 'Cr-V steel', '1', '$64.00'], ['FS-1010', 'Bit set, 42 pc', 'PH, PZ, T, H', '240 g', 'S2 steel', '1', '$22.50'], ['FS-1015', 'Hex key set', '1.5–10 mm', '156 g', 'Cr-V steel', '1', '$14.80'], ['FS-1022', 'Digital caliper', '0–150 mm', '142 g', 'Stainless', '1', '$39.00'], ['FS-1030', 'Steel rule', '300 mm', '48 g', 'Spring steel', '10', '$7.20'], ['FS-1031', 'Steel rule', '600 mm', '96 g', 'Spring steel', '10', '$11.60'], ['FS-1033', 'Try square', '150 mm', '210 g', 'Steel, rosewood', '1', '$24.00'], ['FS-1034', 'Try square', '230 mm', '330 g', 'Steel, rosewood', '1', '$31.00'], ['FS-1038', 'Combination square', '300 mm', '410 g', 'Cast iron, steel', '1', '$42.00'], ['FS-1040', 'Marking knife', 'Single bevel', '34 g', 'Carbon steel', '1', '$16.50'], ['FS-1062', 'Marking gauge', '200 mm beam', '126 g', 'Brass, beech', '1', '$31.50'], ['FS-1064', 'Mortise gauge', '200 mm beam', '154 g', 'Brass, beech', '1', '$44.00'], ['FS-1066', 'Dividers', '150 mm', '88 g', 'Hardened steel', '1', '$21.00'], ['FS-1068', 'Spirit level', '600 mm', '540 g', 'Aluminium', '1', '$36.00'], ['FS-1069', 'Spirit level', '1200 mm', '1.1 kg', 'Aluminium', '1', '$58.00']];
      const t = table(M, 112, [{ w: 78, font: 'jetbrains', size: 10, color: accent, weight: 700, role: 'SKU' }, { w: 172, font: 'archivo', size: 12, weight: 700 }, { w: 120, font: 'jetbrains', size: 10, role: 'SPEC' }, { w: 76, font: 'jetbrains', size: 10, role: 'SPEC', align: 'right' }, { w: 140, font: 'inter', size: 11, role: 'SPEC' }, { w: 50, font: 'jetbrains', size: 10, align: 'right' }, { w: 60, font: 'archivo', size: 13, weight: 800, align: 'right', role: 'PRICE' }], rows, { size: 11, font: 'inter', color: ink, rule: hair, pad: 8, head: ['SKU', 'Description', 'Range', 'Weight', 'Material', 'Pack', 'Price'], headFont: 'jetbrains', headSize: 8, headColor: paper, headRule: ink, headFill: ink, zebra: mix(paper, -.04), label: 'Specification table' });
      const hd = text(M, 62, 560, 'Measuring  ·  specifications', { size: 28, font: 'archivo', weight: 800, color: ink, wrap: false, label: 'Table title', role: 'HEADLINE' });
      const note = obj(hr(M, t.bottom + 20, CW, ink, 1.5), text(M, t.bottom + 32, 340, 'Notes', { size: 9, font: 'jetbrains', weight: 700, color: accent, tracking: .2, transform: 'uppercase', wrap: false, label: 'Notes label', role: 'LABEL' }), typeset(['Weights are for the item without packaging.', 'Pack is the minimum order quantity; prices are per unit, ex. tax.', 'All measuring tools are supplied with a certificate of conformity on request.'].map((tt, i) => ({ t: tt, marker: { t: String.fromCharCode(97 + i), dx: -18, size: 10, font: 'jetbrains' as const, color: accent, weight: 700 }, after: 4 })), [{ x: M + 22, y: t.bottom + 52, w: 600, h: 90 }], { size: 11, font: 'inter', color: soft, leading: 1.45 }).objs);
      return obj(G, head('01  Measuring', 'p. 9'), hd, t.objs, note, foot());
    }
    case 'ORDER FORM': {
      const hd = obj(text(M, 62, 500, 'Order form', { size: 40, font: 'archivo', weight: 800, color: ink, wrap: false, label: 'Form title', role: 'HEADLINE' }), text(M, 112, 640, 'Fax to 1 800 555 0128, email to orders@foundrysupply.example or post to the address overleaf. Trade accounts: include your account number.', { size: 12, font: 'inter', color: soft, leading: 1.5, label: 'Form intro', role: 'BODY' }));
      const fields = ['Name', 'Company', 'Account number', 'Phone', 'Delivery address', 'Email'];
      const fl = fields.flatMap((f, i) => { const x = M + (i % 2) * (CW / 2 + 8), y = 170 + Math.floor(i / 2) * 50, w = CW / 2 - 8; return [label(x, y, w, f, { size: 8, font: 'jetbrains', color: soft, tracking: .12, transform: 'none' }), hr(x, y + 34, w, ink, 1, { label: 'Entry line' })]; });
      const grid = table(M, 340, [{ w: 60, font: 'jetbrains', size: 10 }, { w: 100, font: 'jetbrains', size: 10 }, { w: 372, font: 'inter', size: 11 }, { w: 100, font: 'jetbrains', size: 10, align: 'right' }, { w: 104, font: 'archivo', size: 12, weight: 800, align: 'right' }], Array.from({ length: 11 }, () => ['', '', '', '', '']), { size: 11, font: 'inter', color: ink, rule: hair, pad: 9, minH: 26, head: ['Qty', 'SKU', 'Description', 'Unit price', 'Line total'], headFont: 'jetbrains', headSize: 8, headColor: paper, headRule: ink, headFill: ink, vlines: true, label: 'Order lines' });
      const ty = grid.bottom + 20;
      const totals = obj(...[['Subtotal', ''], ['Shipping', 'Free over $150'], ['Tax', ''], ['Total', '']].flatMap(([k, v], i) => [text(M + 460, ty + i * 28, 160, k, { size: i === 3 ? 14 : 12, font: 'archivo', weight: i === 3 ? 800 : 600, color: ink, wrap: false, label: 'Total label', role: 'LABEL' }), text(M + 570, ty + i * 28 + 2, 130, v, { size: 10, font: 'jetbrains', color: soft, wrap: false, label: 'Total note', role: 'CAPTION' }), hr(M + 460, ty + i * 28 + 22, 276, i === 3 ? ink : hair, i === 3 ? 2 : .75, { label: 'Total rule' })]));
      const pay = obj(label(M, ty, 200, 'Payment', { size: 9, font: 'archivo', color: accent, weight: 800, tracking: .22 }), hr(M, ty + 18, 400, ink, 1.5), ...['Trade account, net 30', 'Credit card (we will call)', 'Cheque enclosed', 'Pro-forma invoice'].flatMap((t, i) => checkbox(M, ty + 34 + i * 26, t, { color: ink, font: 'inter', textSize: 12, w: 300 })));
      const sig = obj(hr(M, ty + 170, 260, ink, 1, { label: 'Signature line' }), label(M, ty + 178, 260, 'Authorised signature', { size: 8, font: 'jetbrains', color: soft, tracking: .12, transform: 'none' }), hr(M + 300, ty + 170, 120, ink, 1, { label: 'Date line' }), label(M + 300, ty + 178, 120, 'Date', { size: 8, font: 'jetbrains', color: soft, tracking: .12, transform: 'none' }));
      return obj(G, head('Order form', 'p. 118'), hd, fl, grid.objs, totals, pay, sig, foot());
    }
    case 'INDEX': {
      const idx: Array<[string, string]> = [['A', ''], ['Aprons, canvas', '97'], ['Awls, scratch', '24'], ['B', ''], ['Bench hooks', '34'], ['Bit sets', '18'], ['Brass fittings', '60'], ['Brushes, finishing', '84'], ['C', ''], ['Calipers, digital', '8'], ['Chisels, bench', '28'], ['Clamps, F-style', '40'], ['Clamps, spring', '42'], ['D', ''], ['Dividers', '10'], ['Drill bits, brad point', '20'], ['F', ''], ['Files, cabinet', '30'], ['Finishing oils', '82'], ['G', ''], ['Gauges, marking', '11'], ['Gloves, leather', '98'], ['Glue, hide', '86'], ['H', ''], ['Hammers, claw', '16'], ['Hex keys', '19'], ['Hinges, brass', '58'], ['K', ''], ['Knives, marking', '11'], ['L', ''], ['Levels, spirit', '12'], ['M', ''], ['Mallets, deadblow', '26'], ['Mallets, joiner', '27'], ['Measuring tapes', '9'], ['N', ''], ['Nails, cut', '55'], ['Nuts, brass', '56'], ['P', ''], ['Planes, block', '32'], ['Pliers, flat nose', '22'], ['R', ''], ['Rules, steel', '9'], ['S', ''], ['Saws, pull', '29'], ['Screws, countersunk', '53'], ['Squares, try', '10'], ['T', ''], ['Toolboxes', '106'], ['Torque drivers', '21'], ['V', ''], ['Vices, bench', '39'], ['W', ''], ['Workbenches', '44'], ['Wrenches, adjustable', '23']];
      const per = Math.ceil(idx.length / 3); const colW = (CW - 40) / 3; const out: TelaVectorObject[] = [];
      for (let c = 0; c < 3; c++) { const slice = idx.slice(c * per, (c + 1) * per); const x = M + c * (colW + 20); let y = 150; slice.forEach(([a, b]) => { if (!b) { y += 8; out.push(text(x, y, 30, a, { size: 26, font: 'archivo', weight: 800, color: accent, wrap: false, label: 'Index letter', role: 'HEADLINE' }), hr(x + 34, y + 18, colW - 34, hair, .75)); y += 40; } else { out.push(text(x, y, colW - 40, a, { size: 11.5, font: 'inter', color: ink, wrap: false, label: 'Index entry', role: 'BODY' }), text(x + colW - 40, y, 40, b, { size: 11, font: 'jetbrains', weight: 700, color: ink, align: 'right', wrap: false, label: 'Index page', role: 'FOLIO' })); y += 20; } }); }
      return obj(G, head('Index', 'p. 120'), text(M, 62, 400, 'Index', { size: 40, font: 'archivo', weight: 800, color: ink, wrap: false, label: 'Index title', role: 'HEADLINE' }), text(M + 140, 78, 520, 'Find a tool by its name; a part by its number on page 126.', { size: 12, font: 'inter', color: soft, wrap: false, label: 'Index note', role: 'CAPTION' }), out, foot());
    }
    default: { // BACK COVER
      const top = obj(rect(0, 0, W, 520, accent, { label: 'Back cover block', role: 'ORNAMENT' }), text(M, 60, 600, 'Order by 4 p.m.\nWe ship today.', { size: 84, font: 'archivo', weight: 800, color: ink, leading: .98, tracking: -.02, label: 'Back cover headline', role: 'HEADLINE' }), text(M, 300, 520, 'A catalog is a promise that the thing on the page is the thing in the box. If it is not, we will make it right, and we will not argue about it.', { size: 18, font: 'inter', color: ink, leading: 1.5, label: 'Back cover promise', role: 'DECK' }), ...reg(M + 10, 490, ink), ...reg(R - 10, 490, ink));
      const info = obj(...[['Phone', '1 800 555 0127'], ['Email', 'sales@foundrysupply.example'], ['Web', 'foundrysupply.example'], ['Showroom', '14 Quay Lane, Leith']].flatMap(([k, v], i) => [label(M + (i % 2) * 360, 580 + Math.floor(i / 2) * 80, 300, k, { size: 9, font: 'jetbrains', color: accent, weight: 700, tracking: .22 }), text(M + (i % 2) * 360, 600 + Math.floor(i / 2) * 80, 340, v, { size: 22, font: 'archivo', weight: 800, color: ink, wrap: false, label: 'Contact', role: 'LABEL' })]), hr(M, 560, CW, ink, 2, { label: 'Rule' }), text(M, 760, 700, 'Trade hours: Monday to Friday, 7:30 a.m. to 6 p.m.  ·  Saturday, 9 a.m. to 1 p.m.', { size: 12, font: 'inter', color: soft, label: 'Trade hours', role: 'CAPTION' }));
      return obj(G, top, info, text(M, H - 60, 400, 'FOUNDRY SUPPLY CO.', { size: 18, font: 'archivo', weight: 800, color: ink, tracking: .12, wrap: false, label: 'Masthead', role: 'LOGO' }), ...barcode(R - 140, H - 80, 140, 44, ink, seed + 5), text(R - 140, H - 32, 140, '9 780000 270412', { size: 8.5, font: 'jetbrains', color: soft, align: 'center', wrap: false, label: 'Barcode number', role: 'SKU' }));
    }
  }
};

// ═════════════════════════════════════════════════════════════════════════════
// 2 · cat-lookbook — Lookbook (landscape; full-bleed plates, look numbers, line sheet)
// ═════════════════════════════════════════════════════════════════════════════
const LOOKS: Array<[string, string, string, string, string]> = [
  ['07', 'The Fog Coat', 'Double-faced wool, camel', 'LB-2607', '$680'], ['08', 'Low Sun Trouser', 'Pleated linen-wool, stone', 'LB-2611', '$240'], ['09', 'Harbour Knit', 'Chunky merino, oat', 'LB-2615', '$190'], ['10', 'First Frost Shirt', 'Brushed cotton, sage', 'LB-2620', '$145'],
  ['11', 'Evening Wrap', 'Cashmere blend, ink', 'LB-2624', '$420'], ['12', 'Field Boot', 'Waxed suede, tobacco', 'LB-2630', '$360'], ['13', 'Quiet Skirt', 'Bias-cut crepe, clay', 'LB-2633', '$210'], ['14', 'Slow Scarf', 'Hand-loomed wool, moss', 'LB-2640', '$95'],
];

const lookbook: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex } = ctx;
  const M = 56, R = W - M, soft = mix(ink, .45), hair = alpha(ink, .25), photo = mix(paper, -.12);
  const G = rect(0, 0, W, H, pageType === 'BACK COVER' ? ink : paper, { role: 'GROUND', label: 'Page ground' });
  const num = (x: number, y: number, n: string, size = 120, color = ink): TelaVectorObject => text(x, y, size * 1.8, n, { size, font: 'italiana', color, wrap: false, leading: 1, label: 'Look number', role: 'HERO' });
  const folioL = (c = soft): TelaVectorObject[] => obj(text(M, H - 34, 400, 'MAISON LIN  ·  SLOW WEATHER  ·  AUTUMN/WINTER 2026', { size: 8, font: 'tenor', color: c, tracking: .26, wrap: false, label: 'Running head', role: 'FOLIO' }), text(R - 60, H - 34, 60, String(pageIndex + 1).padStart(2, '0'), { size: 9, font: 'tenor', color: c, tracking: .2, align: 'right', wrap: false, label: 'Folio', role: 'FOLIO' }));
  const swatches = (x: number, y: number, cols_: string[]): TelaVectorObject[] => cols_.map((c, i) => circle(x + 8 + i * 22, y + 8, 8, c, { stroke: hair, strokeWidth: 1, label: 'Colour swatch' }));

  switch (pageType) {
    case 'COVER': {
      const img = figure(0, 0, 640, H, { tone: 'light', shade: photo, vignette: false, hint: 'Cover photograph · full height', hero: true, label: 'Cover image' });
      const frame = rect(660, 24, W - 660 - 24, H - 48, 'none', { stroke: accent, strokeWidth: 1, label: 'Hairline frame', role: 'RULE' });
      const title = text(690, 130, 340, 'Slow\nWeather', { size: 78, font: 'italiana', color: ink, leading: .98, tracking: -.01, label: 'Title', role: 'HEADLINE' });
      const aw = text(690, 340, 340, 'AW26', { size: 124, font: 'italiana', color: accent, wrap: false, leading: 1, tracking: -.02, label: 'Season', role: 'HERO' });
      const sub = text(692, 520, 320, 'A collection of twenty-four looks in wool, linen and patience, made in small runs in Leith.', { size: 17, font: 'cormorant', italic: true, color: mix(ink, .2), leading: 1.4, label: 'Deck', role: 'DECK' });
      return obj(G, img.objs, frame, text(690, 70, 340, 'MAISON LIN', { size: 14, font: 'tenor', color: ink, tracking: .4, wrap: false, label: 'Brand', role: 'LOGO' }), text(690, 90, 340, 'LOOKBOOK  ·  AUTUMN/WINTER 2026', { size: 8, font: 'tenor', color: soft, tracking: .28, wrap: false, label: 'Kicker', role: 'KICKER' }), title, aw, hr(692, 506, 56, accent, 1.5, { label: 'Rule' }), sub, text(692, H - 70, 320, 'maisonlin.example', { size: 9, font: 'tenor', color: soft, tracking: .24, wrap: false, label: 'Web address', role: 'LABEL' }));
    }
    case 'CONTENTS': {
      const t = text(M, 64, 500, 'The collection', { size: 56, font: 'italiana', color: ink, wrap: false, label: 'Contents title', role: 'HEADLINE' });
      const ch = [['I', 'Morning Fog', 'Looks 01 – 08', '04'], ['II', 'Low Sun', 'Looks 09 – 16', '10'], ['III', 'First Frost', 'Looks 17 – 24', '16']];
      const rows = ch.flatMap(([n, name, looks, pg], i) => { const y = 170 + i * 120; return [text(M, y, 60, n, { size: 44, font: 'italiana', color: accent, wrap: false, label: 'Chapter numeral', role: 'LABEL' }), text(M + 80, y + 6, 360, name, { size: 34, font: 'cormorant', weight: 300, italic: true, color: ink, wrap: false, label: 'Chapter name', role: 'HEADLINE' }), text(M + 80, y + 52, 300, looks.toUpperCase(), { size: 8.5, font: 'tenor', color: soft, tracking: .24, wrap: false, label: 'Look range', role: 'LABEL' }), text(M + 440, y + 6, 60, pg, { size: 24, font: 'italiana', color: ink, align: 'right', wrap: false, label: 'Page number', role: 'FOLIO' }), hr(M, y + 88, 500, hair, .75, { label: 'Row rule' })]; });
      const thumbs = Array.from({ length: 6 }, (_, i) => imageSlot(640 + (i % 3) * 112, 80 + Math.floor(i / 3) * 170, 100, 150, { tone: 'light', shade: photo, silent: true, label: 'Look thumbnail' })).flat();
      const note = obj(hr(640, 440, 324, ink, 1, { label: 'Note rule' }), label(640, 454, 300, 'A note from the studio', { size: 8, font: 'tenor', color: accent, tracking: .26 }), text(640, 476, 324, 'We started with the weather we wanted to wear through: slow fog, a low sun, the first hard frost. Everything else followed from the cloth.', { size: 16, font: 'cormorant', italic: true, color: ink, leading: 1.45, label: 'Studio note', role: 'BODY' }));
      return obj(G, t, rows, thumbs, note, folioL());
    }
    case 'LOOKBOOK SPREAD': {
      if (pageIndex === 2) {
        const img = figure(0, 0, 700, H, { tone: 'light', shade: photo, hint: 'Look 07 · full bleed · 700 × 816', hero: true, label: 'Look image' });
        return obj(G, img.objs, num(730, 56, '07', 150, ink), text(732, 232, 280, 'THE FOG COAT', { size: 10, font: 'tenor', color: ink, tracking: .3, wrap: false, label: 'Look name', role: 'HEADLINE' }), hr(732, 256, 56, accent, 1.5), text(732, 276, 280, 'Double-faced wool in camel, cut long with a dropped shoulder and a single horn button. The seams are bound by hand, so the inside is as quiet as the outside.', { size: 15, font: 'cormorant', italic: true, color: mix(ink, .15), leading: 1.45, label: 'Look description', role: 'BODY' }), ...table(732, 440, [{ w: 150, font: 'cormorant', size: 14 }, { w: 60, font: 'tenor', size: 8, color: soft, align: 'right' }, { w: 50, font: 'tenor', size: 11, align: 'right', role: 'PRICE' }], [['The Fog Coat', 'LB-2607', '$680'], ['Low Sun Trouser', 'LB-2611', '$240'], ['Field Boot', 'LB-2630', '$360']], { size: 14, font: 'cormorant', color: ink, rule: hair, pad: 7, label: 'Look credits' }).objs, ...swatches(732, 560, [mix(accent, .1), '#8b8478', '#2b2926', mix(secondary, .3)]), text(732, 590, 280, 'Also in stone, charcoal, sage', { size: 9, font: 'tenor', color: soft, tracking: .14, wrap: false, label: 'Colourways', role: 'CAPTION' }), folioL());
      }
      if (pageIndex === 3) {
        const a = figure(70, 70, 380, 620, { tone: 'light', shade: photo, hint: 'Look 08 · portrait', label: 'Look 08 image' });
        const b = figure(520, 140, 380, 540, { tone: 'light', shade: photo, hint: 'Look 09 · portrait', label: 'Look 09 image' });
        return obj(G, a.objs, b.objs, num(470, 70, '08', 64, accent), num(920, 140, '09', 64, accent), text(70, 704, 380, 'LOW SUN TROUSER  ·  LB-2611', { size: 8.5, font: 'tenor', color: ink, tracking: .26, wrap: false, label: 'Look name', role: 'CAPTION' }), text(70, 722, 380, 'Pleated linen-wool in stone, high waist, side adjusters.', { size: 13, font: 'cormorant', italic: true, color: soft, leading: 1.35, label: 'Look note', role: 'CAPTION' }), text(520, 704, 380, 'HARBOUR KNIT  ·  LB-2615', { size: 8.5, font: 'tenor', color: ink, tracking: .26, wrap: false, label: 'Look name', role: 'CAPTION' }), text(520, 722, 380, 'Chunky merino in oat. Dropped sleeve, ribbed hem.', { size: 13, font: 'cormorant', italic: true, color: soft, leading: 1.35, label: 'Look note', role: 'CAPTION' }), text(930, 400, 100, 'Autumn\nWinter', { size: 11, font: 'tenor', color: soft, tracking: .2, leading: 1.6, wrap: false, rotation: 0, label: 'Season mark', role: 'LABEL' }), folioL());
      }
      const imgs = [0, 1, 2].flatMap(i => figure(M + i * 330, 60 + (i === 1 ? 40 : 0), 300, 560, { tone: 'light', shade: photo, hint: `Look ${10 + i}`, label: `Look ${10 + i} image` }).objs);
      return obj(G, imgs, ...[0, 1, 2].map(i => text(M + i * 330 + 150, 640 + (i === 1 ? 40 : 0), 150, String(10 + i), { size: 46, font: 'italiana', color: accent, align: 'right', wrap: false, label: 'Look number', role: 'HERO' })), text(M, 668, 600, 'Wear it until it softens.', { size: 44, font: 'cormorant', weight: 300, italic: true, color: ink, wrap: false, label: 'Pull line', role: 'PULLQUOTE' }), text(M, 724, 500, 'FIRST FROST SHIRT  ·  EVENING WRAP  ·  FIELD BOOT', { size: 8.5, font: 'tenor', color: soft, tracking: .26, wrap: false, label: 'Credits line', role: 'CREDIT' }), hr(M, 706, 600, hair, .75), text(R - 220, 668, 220, 'Photographed in Leith,\nSeptember 2026.', { size: 13, font: 'cormorant', italic: true, color: soft, align: 'right', leading: 1.35, label: 'Photo credit', role: 'CREDIT' }), folioL());
    }
    case 'PRODUCT GRID': {
      const cw = (W - 2 * M - 3 * 20) / 4, ch = 300;
      const cards = LOOKS.flatMap(([n, name, fab, sku, price], i) => { const x = M + (i % 4) * (cw + 20), y = 96 + Math.floor(i / 4) * (ch + 40); return [...imageSlot(x, y, cw, 190, { tone: 'light', shade: photo, silent: true, label: 'Style image' }), text(x, y + 200, cw, 'LOOK ' + n, { size: 7.5, font: 'tenor', color: accent, tracking: .26, wrap: false, role: 'LABEL', label: 'Look number' }), text(x, y + 214, cw, name, { size: 17, font: 'cormorant', weight: 600, color: ink, wrap: false, role: 'HEADLINE', label: 'Style name' }), text(x, y + 238, cw, fab, { size: 11.5, font: 'cormorant', italic: true, color: soft, wrap: false, role: 'CAPTION', label: 'Fabric' }), ...swatches(x - 8, y + 256, [accent, '#8b8478', ink]), text(x + 76, y + 256, 60, sku, { size: 8, font: 'tenor', color: soft, tracking: .14, wrap: false, role: 'SKU', label: 'Style number' }), text(x + cw - 60, y + 256, 60, price, { size: 12, font: 'tenor', color: ink, align: 'right', wrap: false, role: 'PRICE', label: 'Retail price' })]; });
      return obj(G, text(M, 40, 600, 'Line sheet  ·  Autumn/Winter 2026', { size: 8.5, font: 'tenor', color: ink, tracking: .3, transform: 'uppercase', wrap: false, label: 'Page title', role: 'KICKER' }), hr(M, 62, W - 2 * M, ink, .75), cards, folioL());
    }
    case 'PRODUCT DETAIL': {
      const img = figure(M, 56, 340, 660, { tone: 'light', shade: photo, hint: 'Style photograph · 1:2', hero: true, label: 'Style image' });
      const rx = 440;
      const info = obj(label(rx, 60, 300, 'Look 07  ·  Outerwear', { size: 8.5, font: 'tenor', color: accent, tracking: .28 }), text(rx, 80, 480, 'The Fog Coat', { size: 62, font: 'italiana', color: ink, wrap: false, label: 'Style name', role: 'HEADLINE' }), text(rx, 160, 500, 'A long, quiet coat in double-faced wool. Cut with a dropped shoulder, bound seams and a single horn button, it is made to be worn open or wrapped. The cloth is woven in Hawick and finished without a lining so it softens with every winter.', { size: 15, font: 'cormorant', italic: true, color: mix(ink, .15), leading: 1.5, label: 'Style description', role: 'BODY' }));
      const size = table(rx, 300, [{ w: 110, font: 'tenor', size: 8.5, color: soft }, ...['XS', 'S', 'M', 'L', 'XL'].map(() => ({ w: 56, font: 'cormorant' as const, size: 14, align: 'right' as const }))], [['Chest (cm)', '88', '92', '96', '102', '108'], ['Waist (cm)', '70', '74', '78', '84', '90'], ['Length (cm)', '112', '114', '116', '118', '120'], ['Sleeve (cm)', '60', '61', '62', '63', '64']], { size: 14, font: 'cormorant', color: ink, rule: hair, pad: 7, head: ['Size guide', 'XS', 'S', 'M', 'L', 'XL'], headFont: 'tenor', headSize: 8, headColor: accent, headRule: ink, label: 'Size chart', role: 'SPEC' });
      const care = obj(label(rx, 470, 300, 'Fabric and care', { size: 8.5, font: 'tenor', color: accent, tracking: .28 }), hr(rx, 490, 390, ink, .75), text(rx, 504, 280, '100% virgin wool, double-faced. Dry clean only, or air and brush. Store on a wide hanger. Mend, do not replace.', { size: 14, font: 'cormorant', color: ink, leading: 1.5, label: 'Care text', role: 'BODY' }), ...['W', 'D', 'I', 'S'].flatMap((l, i) => [circle(rx + 330 + (i % 2) * 36, 520 + Math.floor(i / 2) * 36, 13, 'none', { stroke: ink, strokeWidth: 1, label: 'Care symbol' }), text(rx + 317 + (i % 2) * 36, 512 + Math.floor(i / 2) * 36, 26, l, { size: 11, font: 'tenor', color: ink, align: 'center', wrap: false, label: 'Care letter', role: 'LABEL' })]));
      const buy = obj(text(rx, 660, 200, '$680', { size: 34, font: 'italiana', color: ink, wrap: false, label: 'Retail price', role: 'PRICE' }), text(rx + 130, 676, 200, 'Wholesale $340', { size: 10, font: 'tenor', color: soft, tracking: .16, wrap: false, label: 'Wholesale price', role: 'PRICE' }), text(rx + 300, 674, 200, 'LB-2607', { size: 10, font: 'tenor', color: accent, tracking: .2, wrap: false, label: 'Style number', role: 'SKU' }), ...swatches(rx, 704, [mix(accent, .1), '#8b8478', '#2b2926']));
      return obj(G, img.objs, info, size.objs, care, buy, folioL());
    }
    case 'PRICE LIST': {
      const rows = LOOKS.map(([n, name, fab, sku, price]) => [sku, name, 'XS – XL', '3', String(parseInt(price.slice(1)) / 2), price.slice(1)]);
      const t = table(M, 110, [{ w: 90, font: 'tenor', size: 9, color: soft, role: 'SKU' }, { w: 250, font: 'cormorant', size: 17, weight: 600 }, { w: 100, font: 'tenor', size: 9, color: soft }, { w: 70, font: 'tenor', size: 10, align: 'right' }, { w: 90, font: 'tenor', size: 11, align: 'right', role: 'PRICE' }, { w: 90, font: 'tenor', size: 11, align: 'right', role: 'PRICE' }], rows, { size: 14, font: 'cormorant', color: ink, rule: hair, pad: 9, head: ['Style', 'Name', 'Sizes', 'Colours', 'Wholesale', 'Retail'], headFont: 'tenor', headSize: 8, headColor: accent, headRule: ink, label: 'Price list' });
      const terms = obj(hr(M + 760, 110, 184, ink, 1, { label: 'Terms rule' }), label(M + 760, 122, 184, 'Terms', { size: 8, font: 'tenor', color: accent, tracking: .26 }), text(M + 760, 144, 184, 'Minimum opening order eight pieces. Delivery in two windows: September and November. Net 30 on approved accounts. Prices in US dollars, ex. tax.', { size: 12.5, font: 'cormorant', italic: true, color: soft, leading: 1.5, label: 'Trade terms', role: 'BODY' }));
      const stock = obj(hr(M, 520, W - 2 * M, ink, 1, { label: 'Stockists rule' }), label(M, 534, 300, 'Stockists', { size: 8, font: 'tenor', color: accent, tracking: .26 }), ...[['Edinburgh', 'Maison Lin, 14 Quay Lane'], ['London', 'Alder & Finch, Marylebone'], ['Copenhagen', 'Hus Studio, Vesterbro'], ['New York', 'The Weather Room, Soho'], ['Tokyo', 'Tane, Daikanyama'], ['Online', 'maisonlin.example']].flatMap(([c, s], i) => [text(M + (i % 3) * 300, 564 + Math.floor(i / 3) * 70, 280, c.toUpperCase(), { size: 9, font: 'tenor', color: ink, tracking: .26, wrap: false, role: 'LABEL', label: 'City' }), text(M + (i % 3) * 300, 584 + Math.floor(i / 3) * 70, 280, s, { size: 15, font: 'cormorant', italic: true, color: soft, wrap: false, role: 'BODY', label: 'Stockist' })]));
      return obj(G, text(M, 40, 600, 'Price list  ·  Autumn/Winter 2026', { size: 8.5, font: 'tenor', color: ink, tracking: .3, transform: 'uppercase', wrap: false, label: 'Page title', role: 'KICKER' }), hr(M, 62, W - 2 * M, ink, .75), t.objs, terms, stock, folioL());
    }
    default: {
      const c = alpha(paper, .85);
      return obj(G, text(M, 220, W - 2 * M, 'MAISON LIN', { size: 44, font: 'tenor', color: paper, tracking: .5, align: 'center', wrap: false, label: 'Brand', role: 'LOGO' }), hr(W / 2 - 28, 296, 56, accent, 1.5, { label: 'Rule' }), text(M, 330, W - 2 * M, 'Slow Weather  ·  Autumn/Winter 2026', { size: 26, font: 'cormorant', italic: true, color: c, align: 'center', wrap: false, label: 'Season', role: 'DECK' }), text(M, 460, W - 2 * M, '14 Quay Lane, Leith, Edinburgh EH6 7AA\nstudio@maisonlin.example  ·  +44 131 555 0147', { size: 16, font: 'cormorant', color: c, align: 'center', leading: 1.7, label: 'Contact', role: 'LABEL' }), text(M, 590, W - 2 * M, 'Photographed in Leith  ·  Styled by the studio  ·  Made in Scotland', { size: 8.5, font: 'tenor', color: alpha(paper, .6), tracking: .26, align: 'center', transform: 'uppercase', label: 'Credits', role: 'CREDIT' }), rect(24, 24, W - 48, H - 48, 'none', { stroke: accent, strokeWidth: 1, label: 'Hairline frame', role: 'RULE' }), ...Array.from({ length: 3 }, (_, i) => circle(W / 2 - 24 + i * 24, 700, 4, 'none', { stroke: accent, strokeWidth: 1, label: 'Ornament' })));
    }
  }
};

// ═════════════════════════════════════════════════════════════════════════════
// 3 · cat-books — Publisher Catalog (Letter; cover grid, ISBN and price lines, rights page, storefront link)
// ═════════════════════════════════════════════════════════════════════════════
type Book = { t: string; a: string; fmt: string; pp: string; isbn: string; price: string; cat: string; blurb: string };
const BOOKS: Book[] = [
  { t: 'The Salt Road', a: 'Sana Qureshi', fmt: 'Hardback', pp: '352', isbn: '978-1-5555-0101-3', price: '$27.00', cat: 'Fiction', blurb: 'A cartographer’s daughter follows her mother’s last map from the Atlantic to the Atlas, and finds that every road has a price.' },
  { t: 'Small Weather', a: 'Marisol Quint', fmt: 'Paperback', pp: '224', isbn: '978-1-5555-0102-0', price: '$18.00', cat: 'Poetry', blurb: 'Forty poems on fog, lullabies and the way a house sounds when everyone has left.' },
  { t: 'Lantern Year', a: 'Imani Okafor', fmt: 'Hardback', pp: '288', isbn: '978-1-5555-0103-7', price: '$26.00', cat: 'Fiction', blurb: 'Twelve months in a lighthouse town, told by twelve neighbours who rarely agree.' },
  { t: 'What the Archive Kept', a: 'Teodor Lindqvist', fmt: 'Hardback', pp: '416', isbn: '978-1-5555-0104-4', price: '$32.00', cat: 'Nonfiction', blurb: 'A librarian’s history of what cities choose to remember, and what they quietly lose.' },
  { t: 'Ten Thousand Mornings', a: 'Ada Njoku', fmt: 'Paperback', pp: '256', isbn: '978-1-5555-0105-1', price: '$19.00', cat: 'Memoir', blurb: 'A swimmer’s account of thirty years of dawn, cold water and showing up.' },
  { t: 'The Quiet Chair', a: 'Anselm Ode', fmt: 'Hardback', pp: '192', isbn: '978-1-5555-0106-8', price: '$29.00', cat: 'Nonfiction', blurb: 'A furniture maker on repair, regret and why a chair should forgive you.' },
  { t: 'Blue Hour', a: 'Hana Petrova', fmt: 'Paperback', pp: '320', isbn: '978-1-5555-0107-5', price: '$17.00', cat: 'Fiction', blurb: 'A night-shift nurse, a missing patient and the last tram across a sleeping city.' },
  { t: 'A Field Guide to Lichens', a: 'Lena Haugen', fmt: 'Flexibound', pp: '240', isbn: '978-1-5555-0108-2', price: '$24.00', cat: 'Nonfiction', blurb: 'Two hundred species, one hand lens and a surprisingly moving theory of patience.' },
  { t: 'Boats on the Meadow', a: 'Kofi Mensah', fmt: 'Hardback', pp: '48', isbn: '978-1-5555-0109-9', price: '$17.00', cat: 'Children’s', blurb: 'When the river floods the village, the children discover that every rowing boat is a house.' },
  { t: 'The Long Division', a: 'Priya Natarajan', fmt: 'Paperback', pp: '304', isbn: '978-1-5555-0110-5', price: '$18.50', cat: 'Fiction', blurb: 'Two sisters, one inheritance and a farm that can only be sold if both agree.' },
  { t: 'Notes for a Quieter Internet', a: 'Wen Li', fmt: 'Paperback', pp: '208', isbn: '978-1-5555-0111-2', price: '$16.00', cat: 'Essays', blurb: 'Fifteen short essays on attention, slowness and the dignity of the unread message.' },
  { t: 'Where the Ice Went', a: 'Samir Batra', fmt: 'Hardback', pp: '368', isbn: '978-1-5555-0112-9', price: '$30.00', cat: 'Nonfiction', blurb: 'A glaciologist follows one meltwater river to the sea and meets everyone who lives beside it.' },
];

const publisher: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex, seed } = ctx;
  const M = 48, R = W - M, CW = W - 2 * M, soft = mix(ink, .45), hair = alpha(ink, .2), shelf = mix(paper, -.05);
  const G = rect(0, 0, W, H, paper, { role: 'GROUND', label: 'Page ground' });
  const jackets = [accent, ink, mix(secondary, -.1), mix(accent, -.35), mix(ink, .2), mix(secondary, -.4)];
  /** A drawn jacket: tonal ground, author in small caps, the title set large, one geometric motif. */
  const jacket = (x: number, y: number, w: number, h: number, i: number): TelaVectorObject[] => {
    const b = BOOKS[i % BOOKS.length], c = jackets[i % jackets.length], light = ['#FFFFFF', paper][i % 2]; const o: TelaVectorObject[] = [rect(x, y, w, h, c, { label: 'Book jacket', role: 'IMAGE_SLOT', shadow: { x: 2, y: 3, blur: 6, color: 'rgba(30,30,30,.25)' } })];
    o.push(rect(x, y, Math.max(3, w * .035), h, alpha('#000000', .18), { label: 'Spine hinge' }));
    const s = w / 150;
    o.push(text(x + w * .1, y + h * .07, w * .8, b.a.toUpperCase(), { size: Math.max(7, 8 * s), font: 'dmSans', weight: 700, color: light, tracking: .16, wrap: true, align: 'center', leading: 1.2, label: 'Jacket author', role: 'LABEL' }));
    o.push(text(x + w * .1, y + h * .3, w * .8, b.t, { size: Math.max(11, 20 * s), font: 'playfair', weight: 700, color: light, leading: 1.1, align: 'center', label: 'Jacket title', role: 'HEADLINE' }));
    const k = i % 4; const cx = x + w / 2, cy = y + h * .8, rr = w * .16;
    if (k === 0) o.push(circle(cx, cy, rr, 'none', { stroke: light, strokeWidth: 1.5, label: 'Jacket motif' }), circle(cx, cy, rr * .5, light, { label: 'Jacket motif' }));
    else if (k === 1) o.push(...[0, 1, 2].map(j => hr(cx - rr, cy - rr * .6 + j * rr * .6, rr * 2, light, 1.5, { label: 'Jacket motif' })));
    else if (k === 2) o.push(path(cx - rr, cy - rr, rr * 2, rr * 2, orn.polygonPath(3), light, { opacity: .9, label: 'Jacket motif' }));
    else o.push(rect(cx - rr, cy - rr * .5, rr * 2, rr, 'none', { stroke: light, strokeWidth: 1.5, label: 'Jacket motif' }), rect(cx - rr * .5, cy - rr * .25, rr, rr * .5, light, { label: 'Jacket motif' }));
    return o;
  };
  const bookInfo = (x: number, y: number, w: number, b: Book, full: boolean): TelaVectorObject[] => { const o: TelaVectorObject[] = []; const t = text(x, y, w, b.t, { size: full ? 16 : 12, font: 'playfair', weight: 700, color: ink, leading: 1.12, label: 'Title', role: 'HEADLINE' }); o.push(t); const a = text(x, below(t, 2), w, b.a, { size: full ? 12 : 10, font: 'crimson', italic: true, color: soft, wrap: false, label: 'Author', role: 'BYLINE' }); o.push(a); let yy = below(a, 6); if (full) { const bl = text(x, yy, w, b.blurb, { size: 11, font: 'crimson', color: ink, leading: 1.4, label: 'Blurb', role: 'BODY' }); o.push(bl); yy = below(bl, 6); } o.push(text(x, yy, w, `${b.fmt}  ·  ${b.pp} pp`, { size: full ? 9 : 8, font: 'dmSans', weight: 600, color: soft, wrap: false, label: 'Format', role: 'SPEC' }), text(x, yy + (full ? 14 : 12), w, 'ISBN ' + b.isbn, { size: full ? 9.5 : 8, font: 'dmMono', color: ink, wrap: false, label: 'ISBN', role: 'SKU' }), text(x + (full ? w - 70 : w - 56), yy, 70, b.price, { size: full ? 15 : 12, font: 'dmSans', weight: 800, color: accent, align: 'right', wrap: false, label: 'Price', role: 'PRICE' })); if (full) o.push(text(x, yy + 30, w, 'plajah.example/authors/' + b.a.toLowerCase().replace(/[^a-z]+/g, '-'), { size: 8, font: 'dmMono', color: accent, wrap: false, label: 'Author storefront link', role: 'LABEL' })); return o; };
  const head = (sec: string): TelaVectorObject[] => obj(text(M, 24, 360, 'HARBOURLIGHT BOOKS', { size: 9, font: 'dmSans', weight: 800, color: ink, tracking: .26, wrap: false, label: 'Imprint', role: 'LOGO' }), label(R - 300, 24, 300, sec + '  ·  Autumn 2026', { size: 8.5, font: 'dmSans', color: soft, align: 'right', tracking: .16, weight: 600 }), hr(M, 44, CW, ink, 1.25, { label: 'Head rule' }));
  const foot = (): TelaVectorObject[] => runningFoot(ctx, { left: M, right: R, y: H - 38, font: 'dmSans', size: 8.5, color: soft, head: 'Harbourlight Books  ·  Autumn 2026 list', rule: hair, weight: 600 });

  switch (pageType) {
    case 'COVER': {
      const top = obj(text(M, 56, CW, 'HARBOURLIGHT', { size: 64, font: 'playfair', weight: 700, color: ink, align: 'center', tracking: .06, wrap: false, label: 'Imprint masthead', role: 'LOGO' }), text(M, 136, CW, 'BOOKS', { size: 18, font: 'dmSans', weight: 700, color: accent, align: 'center', tracking: .7, wrap: false, label: 'Imprint line', role: 'LABEL' }), hr(M + 220, 176, CW - 440, secondary, 2, { label: 'Gold rule' }), text(M, 196, CW, 'Autumn 2026 list', { size: 40, font: 'playfair', italic: true, weight: 400, color: ink, align: 'center', wrap: false, label: 'Title', role: 'HEADLINE' }));
      const cw = 200, ch = 300, gx = (CW - 3 * cw) / 2;
      const grid = [0, 1, 2, 3, 4, 5].flatMap(i => jacket(M + (i % 3) * (cw + gx), 288 + Math.floor(i / 3) * (ch + 28), cw, ch, i));
      return obj(G, top, rect(M - 12, 270, CW + 24, 660, shelf, { label: 'Cover shelf panel', role: 'ORNAMENT' }), grid, text(M, 960, CW, 'Twelve new titles  ·  fiction, poetry, nonfiction, children’s', { size: 12, font: 'crimson', italic: true, color: soft, align: 'center', wrap: false, label: 'Cover note', role: 'DECK' }), text(M, 986, CW, 'Sales and rights: trade@harbourlightbooks.example', { size: 9.5, font: 'dmMono', color: soft, align: 'center', wrap: false, label: 'Contact', role: 'LABEL' }));
    }
    case 'CONTENTS': {
      const t = text(M, 70, 500, 'In this list', { size: 56, font: 'playfair', italic: true, weight: 400, color: ink, wrap: false, label: 'Contents title', role: 'HEADLINE' });
      const rows = [['Fiction', 'Five new novels, one debut', '4'], ['Nonfiction', 'History, nature, craft', '12'], ['Poetry and essays', 'Voices worth a slow read', '20'], ['Children’s', 'Picture books for ages 3 to 8', '24'], ['Backlist and price list', 'Our best-sellers, with discounts', '30'], ['Rights and contacts', 'Territories and agents', '34'], ['Order form', 'For trade customers', '36']].flatMap(([a, b, pg], i) => { const y = 170 + i * 66; return [text(M, y, 40, String(i + 1).padStart(2, '0'), { size: 13, font: 'dmMono', color: accent, wrap: false, label: 'Section number', role: 'LABEL' }), text(M + 50, y - 4, 360, a, { size: 24, font: 'playfair', weight: 600, color: ink, wrap: false, label: 'Section name', role: 'HEADLINE' }), text(M + 50, y + 28, 360, b, { size: 12.5, font: 'crimson', italic: true, color: soft, wrap: false, label: 'Section note', role: 'CAPTION' }), hr(M + 360, y + 18, 120, hair, 1, { dash: [2, 4], label: 'Leader' }), text(M + 490, y - 2, 40, pg, { size: 20, font: 'dmSans', weight: 700, color: ink, align: 'right', wrap: false, label: 'Page number', role: 'FOLIO' }), hr(M, y + 52, 530, hair, .75, { label: 'Row rule' })]; });
      const hl = obj(label(600, 170, 150, 'Highlights', { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .22 }), hr(600, 188, 150, ink, 1.25), ...[0, 3, 7].flatMap((bi, i) => { const y = 204 + i * 176; return [...jacket(620, y, 100, 150, bi), text(600, y + 156, 150, BOOKS[bi].t, { size: 11, font: 'playfair', weight: 700, color: ink, leading: 1.15, role: 'HEADLINE', label: 'Highlight title' })]; }));
      const sales = obj(rect(M, 700, 530, 190, mix(secondary, .8), { label: 'Sales note panel', role: 'SIDEBAR' }), text(M + 24, 722, 480, 'Sell more books direct', { size: 22, font: 'playfair', weight: 700, color: ink, wrap: false, role: 'SIDEBAR', label: 'Panel title' }), text(M + 24, 758, 480, 'Every author in this list has a storefront. Share the link, and readers buy the book signed from the author or delivered from the press. Orders credit the author’s share automatically.', { size: 13, font: 'crimson', color: ink, leading: 1.5, role: 'SIDEBAR', label: 'Panel text' }), text(M + 24, 840, 480, 'plajah.example/authors/…', { size: 11, font: 'dmMono', color: accent, wrap: false, role: 'SIDEBAR', label: 'Storefront link' }));
      return obj(G, head('Contents'), t, rows, hl, sales, foot());
    }
    case 'SECTION OPENER': {
      const bg = rect(0, 0, W, 560, ink, { label: 'Opener band', role: 'ORNAMENT' });
      const lead = jacket(M + 20, 90, 280, 420, 0);
      return obj(G, bg, text(M, 20, 400, 'FICTION', { size: 11, font: 'dmSans', weight: 800, color: secondary, tracking: .5, wrap: false, label: 'Section kicker', role: 'KICKER' }), lead, text(380, 100, 380, 'The Salt Road', { size: 56, font: 'playfair', weight: 700, color: paper, leading: 1.02, label: 'Lead title', role: 'HEADLINE' }), text(380, 236, 380, 'Sana Qureshi', { size: 20, font: 'crimson', italic: true, color: secondary, wrap: false, label: 'Lead author', role: 'BYLINE' }), text(380, 280, 360, BOOKS[0].blurb, { size: 16, font: 'crimson', color: alpha(paper, .9), leading: 1.55, label: 'Lead blurb', role: 'DECK' }), text(380, 420, 380, 'Hardback  ·  352 pp  ·  ISBN 978-1-5555-0101-3  ·  $27.00', { size: 10.5, font: 'dmMono', color: alpha(paper, .8), wrap: false, label: 'Lead details', role: 'SPEC' }), text(380, 450, 380, 'Publication: 8 September 2026  ·  Rights: world', { size: 10.5, font: 'dmMono', color: secondary, wrap: false, label: 'Lead pub date', role: 'SPEC' }), ...pill(380, 484, 'Lead title', { fill: secondary, color: ink, size: 9, h: 24, font: 'dmSans', tracking: .16 }).objs, text(M, 600, 300, 'Also in fiction', { size: 24, font: 'playfair', weight: 700, italic: true, color: ink, wrap: false, label: 'Subhead', role: 'HEADLINE' }), hr(M, 640, CW, ink, 1.25), ...[2, 6, 9].flatMap((bi, i) => { const x = M + i * (CW / 3 + 4); return [...jacket(x, 660, 84, 126, bi), ...bookInfo(x + 100, 664, CW / 3 - 120, BOOKS[bi], false)]; }), foot());
    }
    case 'PRODUCT GRID': {
      if (pageIndex === 3) {
        const cw = 150, ch = 225, colW = CW / 3;
        const cells = [0, 1, 2, 3, 4, 5].flatMap(i => { const x = M + (i % 3) * colW, y = 72 + Math.floor(i / 3) * 440; return [...jacket(x + (colW - cw) / 2 - 6, y, cw, ch, i), ...bookInfo(x + 6, y + ch + 22, colW - 24, BOOKS[i], true)]; });
        return obj(G, head('Fiction, poetry and nonfiction'), cells, foot());
      }
      const cw = 106, ch = 160, colW = CW / 3;
      const cells = BOOKS.flatMap((b, i) => { const x = M + (i % 3) * colW, y = 66 + Math.floor(i / 3) * 218; return [...jacket(x, y, cw, ch, i), ...bookInfo(x + cw + 14, y + 4, colW - cw - 30, b, false), text(x + cw + 14, y + 96, colW - cw - 34, b.cat.toUpperCase(), { size: 7.5, font: 'dmSans', weight: 800, color: accent, tracking: .2, wrap: false, role: 'LABEL', label: 'Category' })]; });
      return obj(G, head('Backlist'), cells, foot());
    }
    case 'PRODUCT DETAIL': {
      const b = BOOKS[0];
      const jk = jacket(M, 80, 280, 420, 0);
      const rx = 360;
      const info = obj(label(rx, 80, 300, 'Lead fiction  ·  Autumn 2026', { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .24, role: 'KICKER' }), text(rx, 100, 400, b.t, { size: 56, font: 'playfair', weight: 700, color: ink, leading: 1.02, label: 'Title', role: 'HEADLINE' }), text(rx, 168, 400, 'A novel by ' + b.a, { size: 20, font: 'crimson', italic: true, color: soft, wrap: false, label: 'Author line', role: 'BYLINE' }), text(rx, 214, 440, b.blurb + ' Told in three voices across four decades, The Salt Road is a story about inheritance, borders and the quiet cost of the shortest route.', { size: 15, font: 'crimson', color: ink, leading: 1.55, label: 'Jacket copy', role: 'BODY' }));
      const det = table(rx, 366, [{ w: 110, font: 'dmSans', size: 8.5, weight: 700, color: soft, tracking: .12 }, { w: 120, font: 'dmMono', size: 10.5, role: 'SPEC' }, { w: 110, font: 'dmSans', size: 8.5, weight: 700, color: soft, tracking: .12 }, { w: 100, font: 'dmMono', size: 10.5, role: 'SPEC' }], [['ISBN', '978-1-5555-0101-3', 'Format', 'Hardback'], ['Price', '$27.00', 'Pages', '352'], ['Trim', '6 × 9 in', 'Pub date', '8 Sep 2026'], ['Rights', 'World, all languages', 'Categories', 'Literary fiction']], { size: 10.5, font: 'dmMono', color: ink, rule: hair, pad: 6, head: ['Details', '', '', ''], headFont: 'dmSans', headSize: 8, headColor: accent, headRule: ink, label: 'Book details' });
      const bio = obj(hr(M, 540, CW, ink, 1.25), label(M, 552, 300, 'About the author', { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .22 }), ...imageSlot(M, 576, 90, 110, { tone: 'light', shade: shelf, caption: 'Author', silent: true, label: 'Author portrait' }), text(M + 110, 576, 340, 'Sana Qureshi was born in Karachi and raised in Leith. Her first novel, Blue Hour, was shortlisted for two first-book prizes. She teaches creative writing and keeps bees on a roof.', { size: 13, font: 'crimson', color: ink, leading: 1.5, label: 'Author biography', role: 'BODY' }));
      const store = obj(rect(M + 480, 540, CW - 480, 190, mix(secondary, .8), { label: 'Author storefront card', role: 'SIDEBAR' }), label(M + 498, 556, 200, 'Author storefront', { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .22, role: 'SIDEBAR' }), text(M + 498, 580, CW - 516, 'Buy signed copies directly from Sana, or share her link. Orders credit her share automatically.', { size: 12.5, font: 'crimson', color: ink, leading: 1.5, role: 'SIDEBAR', label: 'Storefront text' }), ...orn.checker(M + 498, 650, 56, 56, 8, ink, { label: 'QR code placeholder' }), text(M + 570, 660, CW - 590, 'plajah.example/\nauthors/sana-qureshi', { size: 10.5, font: 'dmMono', color: accent, leading: 1.5, role: 'SIDEBAR', label: 'Storefront URL' }));
      const rev = obj(label(M, 760, 300, 'Early praise', { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .22 }), hr(M, 778, CW, ink, 1.25), ...[['“A map that argues with itself, beautifully.”', 'The Weekend Review'], ['“Quietly devastating, and very funny about maps.”', 'Ada Njoku'], ['“I read it in one sitting and then started again.”', 'Priya Natarajan']].flatMap(([q, s], i) => { const w = CW / 3 - 12, x = M + i * (w + 18); return [text(x, 794, w, q, { size: 15, font: 'playfair', italic: true, color: ink, leading: 1.3, role: 'PULLQUOTE', label: 'Praise quote' }), text(x, 872, w, s.toUpperCase(), { size: 8, font: 'dmSans', weight: 700, color: soft, tracking: .18, wrap: false, role: 'CREDIT', label: 'Praise credit' })]; }));
      return obj(G, head('Lead fiction'), jk, info, det.objs, bio, store, rev, foot());
    }
    case 'PRICE LIST': {
      const rows = BOOKS.slice(0, 9).map(b => [b.isbn, b.t, b.a, b.fmt, b.price, '46%']);
      const t = table(M, 90, [{ w: 130, font: 'dmMono', size: 9.5, role: 'SKU' }, { w: 190, font: 'playfair', size: 11, weight: 700 }, { w: 130, font: 'crimson', size: 11.5, italic: true }, { w: 80, font: 'dmSans', size: 9.5, color: soft }, { w: 70, font: 'dmSans', size: 11, weight: 700, align: 'right', role: 'PRICE' }, { w: 98, font: 'dmMono', size: 9.5, align: 'right' }], rows, { size: 11, font: 'crimson', color: ink, rule: hair, pad: 6, head: ['ISBN', 'Title', 'Author', 'Format', 'Price', 'Trade disc.'], headFont: 'dmSans', headSize: 8, headColor: accent, headRule: ink, label: 'Price list' });
      const ry = t.bottom + 36;
      const rights = table(M, ry + 30, [{ w: 220, font: 'playfair', size: 11, weight: 700 }, { w: 120, font: 'dmSans', size: 10, color: soft }, { w: 130, font: 'dmSans', size: 10, weight: 700 }, { w: 228, font: 'crimson', size: 11.5, italic: true }], [['The Salt Road', 'World', 'Available', 'Translation rights open; offers by 31 October'], ['Small Weather', 'World', 'Available', 'Anthology and audio rights held'], ['Lantern Year', 'UK, Commonwealth', 'Sold', 'US and translation rights available'], ['What the Archive Kept', 'World', 'Available', 'Serial rights offered'], ['Boats on the Meadow', 'World', 'On offer', 'Picture-book co-edition sought']], { size: 11, font: 'crimson', color: ink, rule: hair, pad: 6, head: ['Rights guide', 'Territory', 'Status', 'Notes'], headFont: 'dmSans', headSize: 8, headColor: accent, headRule: ink, label: 'Rights table' });
      return obj(G, head('Price list and rights'), t.objs, text(M, ry, 400, 'Rights', { size: 24, font: 'playfair', weight: 700, italic: true, color: ink, wrap: false, label: 'Rights heading', role: 'HEADLINE' }), rights.objs, text(M, rights.bottom + 16, CW, 'Contact: rights@harbourlightbooks.example. Sample chapters, reading reports and cover files are sent on request. Authors with a storefront can link readers directly from their agent page.', { size: 11.5, font: 'crimson', color: soft, leading: 1.5, label: 'Rights note', role: 'FOOTNOTE' }), foot());
    }
    case 'ORDER FORM': {
      const fl = ['Account name', 'Account number', 'Purchase order', 'Delivery address', 'Contact name', 'Email'].flatMap((f, i) => { const x = M + (i % 2) * (CW / 2 + 8), y = 130 + Math.floor(i / 2) * 50, w = CW / 2 - 8; return [label(x, y, w, f, { size: 8, font: 'dmSans', color: soft, tracking: .12, weight: 700, transform: 'none' }), hr(x, y + 34, w, ink, 1, { label: 'Entry line' })]; });
      const grid = table(M, 310, [{ w: 60, font: 'dmMono', size: 10 }, { w: 150, font: 'dmMono', size: 10 }, { w: 300, font: 'crimson', size: 12 }, { w: 90, font: 'dmSans', size: 10, align: 'right' }, { w: 120, font: 'dmSans', size: 11, weight: 700, align: 'right' }], Array.from({ length: 10 }, () => ['', '', '', '', '']), { size: 11, font: 'crimson', color: ink, rule: hair, pad: 9, minH: 28, head: ['Qty', 'ISBN', 'Title', 'Price', 'Total'], headFont: 'dmSans', headSize: 8, headColor: paper, headRule: ink, headFill: ink, vlines: true, label: 'Order lines' });
      return obj(G, head('Trade order form'), text(M, 60, 500, 'Trade order form', { size: 40, font: 'playfair', weight: 700, color: ink, wrap: false, label: 'Form title', role: 'HEADLINE' }), fl, grid.objs, text(M, grid.bottom + 24, CW, 'Standard trade terms: 46% discount on 10 or more copies, net 60 days, free delivery on orders over $300. Returns accepted within twelve months in saleable condition.', { size: 12, font: 'crimson', italic: true, color: soft, leading: 1.5, label: 'Terms', role: 'FOOTNOTE' }), ...[0, 1].flatMap(i => [hr(M + i * 300, grid.bottom + 100, 260, ink, 1, { label: 'Signature line' }), label(M + i * 300, grid.bottom + 108, 260, ['Authorised signature', 'Date'][i], { size: 8, font: 'dmSans', color: soft, tracking: .12, weight: 700, transform: 'none' })]), foot());
    }
    case 'INDEX': {
      const authors = BOOKS.map(b => [b.a.split(' ').slice(-1)[0] + ', ' + b.a.split(' ').slice(0, -1).join(' '), b.t, String(4 + BOOKS.indexOf(b) * 2)]).sort((x, y) => x[0].localeCompare(y[0]));
      const colW = (CW - 40) / 2; const out: TelaVectorObject[] = [];
      let y = 130; let lastL = '';
      authors.forEach(([a, t, pg]) => { const l = a[0]; if (l !== lastL) { lastL = l; y += 10; out.push(text(M, y, 30, l, { size: 24, font: 'playfair', weight: 700, italic: true, color: accent, wrap: false, role: 'HEADLINE', label: 'Index letter' }), hr(M + 30, y + 16, colW - 30, hair, .75)); y += 34; } out.push(text(M, y, colW - 40, a, { size: 13, font: 'crimson', weight: 600, color: ink, wrap: false, role: 'BYLINE', label: 'Index author' }), text(M, y + 16, colW - 40, t, { size: 11.5, font: 'crimson', italic: true, color: soft, wrap: false, role: 'CAPTION', label: 'Index title' }), text(M + colW - 40, y + 2, 40, pg, { size: 11, font: 'dmSans', weight: 700, color: ink, align: 'right', wrap: false, role: 'FOLIO', label: 'Index page' })); y += 44; });
      const titles = [...BOOKS].sort((a, b) => a.t.localeCompare(b.t)); const tx = M + colW + 40;
      let ty = 130; const tt: TelaVectorObject[] = [label(tx, ty - 30, 200, 'Titles', { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .22 })];
      titles.forEach(b => { tt.push(text(tx, ty, colW - 40, b.t, { size: 12, font: 'playfair', weight: 600, color: ink, wrap: false, role: 'HEADLINE', label: 'Index title' }), text(tx + colW - 80, ty + 2, 80, b.isbn.slice(-6), { size: 9, font: 'dmMono', color: soft, align: 'right', wrap: false, role: 'SKU', label: 'Index ISBN' })); ty += 26; });
      return obj(G, head('Index'), text(M, 60, 400, 'Index', { size: 40, font: 'playfair', weight: 700, italic: true, color: ink, wrap: false, label: 'Index title', role: 'HEADLINE' }), out, tt, foot());
    }
    default: {
      const top = obj(rect(0, 0, W, 420, ink, { label: 'Back cover band', role: 'ORNAMENT' }), text(M + 20, 70, CW - 40, 'Books are how we keep the conversation going.', { size: 44, font: 'playfair', italic: true, weight: 400, color: paper, leading: 1.15, label: 'Back cover line', role: 'DECK' }), text(M + 20, 270, 440, 'Harbourlight Books is an independent press publishing fiction, poetry, nonfiction and picture books from Leith since 1998.', { size: 15, font: 'crimson', color: alpha(paper, .85), leading: 1.55, label: 'Imprint statement', role: 'BODY' }));
      const info = obj(...[['Sales', 'trade@harbourlightbooks.example'], ['Rights', 'rights@harbourlightbooks.example'], ['Publicity', 'press@harbourlightbooks.example'], ['Orders', '+44 131 555 0188']].flatMap(([k, v], i) => [label(M + (i % 2) * 360, 480 + Math.floor(i / 2) * 80, 300, k, { size: 9, font: 'dmSans', color: accent, weight: 800, tracking: .22 }), text(M + (i % 2) * 360, 500 + Math.floor(i / 2) * 80, 340, v, { size: 16, font: 'dmMono', color: ink, wrap: false, label: 'Contact', role: 'LABEL' })]));
      return obj(G, top, info, hr(M, 660, CW, ink, 1.25), text(M, 676, CW, 'Distributed to the trade by Coastline Distribution. Titles are available in print, ebook and audio. Prices are recommended retail and subject to change.', { size: 12, font: 'crimson', italic: true, color: soft, leading: 1.5, label: 'Distribution note', role: 'FOOTNOTE' }), text(M, H - 110, 400, 'HARBOURLIGHT', { size: 28, font: 'playfair', weight: 700, color: ink, tracking: .06, wrap: false, label: 'Imprint', role: 'LOGO' }), ...barcode(R - 150, H - 130, 150, 56, ink, seed + 9), text(R - 150, H - 66, 150, 'ISBN 978-1-5555-0000-6', { size: 8.5, font: 'dmMono', color: soft, align: 'center', wrap: false, label: 'Barcode number', role: 'SKU' }));
    }
  }
};

export const DESIGNS_CA: Record<string, PublicationDesigner> = { 'cat-product': supply, 'cat-lookbook': lookbook, 'cat-books': publisher };
export const LESSONS_CA: Record<string, DesignLesson> = {
  'cat-product': { principle: 'A product catalog is a lookup tool before it is a brochure: every item gets a SKU, a price and a spec in the same place, so the eye learns the pattern on page one and never has to relearn it.', history: 'The mail-order catalog began with Aaron Montgomery Ward in 1872 and Richard Sears in the 1890s, whose books taught rural customers to order by number. Industrial catalogs such as McMaster-Carr and the Swiss modernists’ spec sheets later refined the grid of image, code and table that this layout inherits.', tryThis: 'Swap two SKUs and watch how quickly the grid stops being trustworthy. Consistency is the content.', interestTag: 'Catalog design', related: ['Product photography', 'Information design', 'Tables'] },
  'cat-lookbook': { principle: 'A lookbook sells a mood by editing: large plates, look numbers instead of captions, and the business details pushed to the back where buyers will find them.', history: 'Fashion lookbooks grew from the Parisian plates of the nineteenth century and the seasonal books houses sent to buyers, then became art objects in the 1990s when designers such as Margiela and Helmut Lang used plain white covers and grainy photographs. The line sheet and price list remain the working half of the book.', tryThis: 'Replace one full-bleed plate with a smaller image on a wide margin and see how the pacing changes.', interestTag: 'Fashion editorial', related: ['Lookbooks', 'Line sheets', 'Italiana'] },
  'cat-books': { principle: 'A publisher’s catalog gives every book the same three lines, title, author and ISBN with a price, then lets the lead title break the pattern once.', history: 'Trade catalogs descend from the printed booklists of the Aldine Press in Venice and from the Victorian publishers’ announcements bound into the backs of books. Modern seasonal catalogs add the rights page and the metadata that sales reps, booksellers and agents need, and now often link out to author storefronts.', tryThis: 'Remove the covers from the grid and read only the text. If the list still sells the books, the copy is working.', interestTag: 'Book publishing', related: ['ISBN', 'Rights', 'Author storefronts'] },
};
