// catalogsB — CATALOG templates 4–6: Parts and Hardware (dense order-code lists), Auction Catalog (lot pages),
// Course Catalog (event / course listings with a timetable and registration form).
import type { TelaVectorObject } from '../../../../types';
import type { DesignLesson } from '../types';
import type { PublicationDesigner } from './types';
import { rect, circle, hr, vr, path, text, below, imageSlot, mix, alpha } from '../../templateKit';
import * as orn from '../../ornaments';
import { typeset, cols, figure, pullQuote, table, pill, button, barcode, checkbox, meter, runningFoot, label, verso } from './pubKit';

const obj = (...parts: Array<TelaVectorObject | TelaVectorObject[]>): TelaVectorObject[] => parts.flat();

// ═════════════════════════════════════════════════════════════════════════════
// 4 · cat-parts — Parts and Hardware (Letter; dense order-code tables, drawn icons, exploded view)
// ═════════════════════════════════════════════════════════════════════════════
const PITCH: Record<number, string> = { 6: '1.00', 8: '1.25', 10: '1.50', 12: '1.75' };
const BOLTS: string[][] = ([[6, [20, 25, 30, 40, 50]], [8, [25, 30, 40, 50, 60]], [10, [30, 40, 50, 60]], [12, [40, 50, 60, 80]]] as Array<[number, number[]]>).flatMap(([d, ls]) => ls.map(l => [`HB-${d}${String(l).padStart(3, '0')}`, `Hex bolt M${d} × ${l}`, PITCH[d], `${l} mm`, '8.8', 'Zinc', d <= 8 ? '100' : '50', (d * l * .0094 + 2.4).toFixed(2)]));
const NUTS: string[][] = [6, 8, 10, 12, 16].flatMap(d => [[`HN-${d}`, `Hex nut M${d}`, PITCH[d] || '2.00', 'A2 stainless', d <= 8 ? '200' : '100', (d * .21 + 1.1).toFixed(2)], [`NL-${d}`, `Nyloc nut M${d}`, PITCH[d] || '2.00', 'Zinc', d <= 8 ? '100' : '50', (d * .29 + 1.8).toFixed(2)]]);
const WASH: string[][] = [6, 8, 10, 12, 16].map(d => [`FW-${d}`, `Flat washer M${d}`, `${d + 1.5} × ${d * 2 + 2}`, '500', (d * .08 + .9).toFixed(2)]);

const parts: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex, seed } = ctx;
  const M = 36, R = W - M, CW = W - 2 * M, soft = mix(ink, .45), hair = alpha(ink, .25), card = '#FFFFFF';
  const G = rect(0, 0, W, H, paper, { role: 'GROUND', label: 'Page ground' });
  const head = (sec: string, tab: number): TelaVectorObject[] => obj(rect(0, 0, W, 34, ink, { label: 'Header band', role: 'ORNAMENT' }), text(M, 8, 400, sec.toUpperCase(), { size: 17, font: 'bigShoulders', weight: 800, color: accent, tracking: .08, wrap: false, label: 'Section name', role: 'LABEL' }), text(R - 300, 11, 300, 'PARTS AND HARDWARE  ·  No. 27', { size: 9, font: 'ibmPlexMono', color: paper, align: 'right', wrap: false, tracking: .08, label: 'Catalogue name', role: 'LABEL' }), ...[0, 1, 2, 3, 4].map(i => rect(W - 12, 60 + i * 56, 12, 44, i === tab ? accent : mix(ink, .6), { label: 'Edge tab', role: 'ORNAMENT' })));
  const foot = (): TelaVectorObject[] => obj(hr(M, H - 36, CW - 8, hair, .75, { label: 'Foot rule' }), text(verso(pageIndex) ? M : R - 68, H - 26, 60, String(pageIndex * 2 + 3), { size: 10, font: 'ibmPlexMono', weight: 600, color: ink, align: verso(pageIndex) ? 'left' : 'right', wrap: false, label: 'Folio', role: 'FOLIO' }), text(verso(pageIndex) ? M + 60 : M, H - 26, 500, 'All prices ex. tax, per pack  ·  Order code first, then quantity in packs', { size: 8.5, font: 'workSans', color: soft, wrap: false, label: 'Running foot', role: 'FOLIO' }));
  const hex = (x: number, y: number, w: number, fill: string, o: { stroke?: string } = {}): TelaVectorObject => path(x, y, w, w * .866, orn.polygonPath(6, 0), fill, { stroke: o.stroke, strokeWidth: o.stroke ? 1.5 : 0, label: 'Hex form', role: 'ORNAMENT' });
  /** Little drawn parts so the grid reads as hardware, not placeholders. */
  const icon = (kind: number, x: number, y: number, w: number, h: number): TelaVectorObject[] => {
    const cx = x + w / 2, cy = y + h / 2, u = Math.min(w, h) * .36; const c = mix(ink, .15);
    switch (kind % 8) {
      case 0: return [hex(cx - u, cy - u * .866, u * 2, c), circle(cx, cy, u * .5, card, { label: 'Nut bore' }), circle(cx, cy, u * .5, 'none', { stroke: soft, strokeWidth: 1, label: 'Thread' })];
      case 1: return [circle(cx, cy, u, c, { label: 'Washer' }), circle(cx, cy, u * .45, card, { label: 'Washer bore' })];
      case 2: return [hex(cx - u * 1.5, cy - u * .43, u * .9, c), rect(cx - u * .6, cy - u * .22, u * 2.1, u * .44, mix(ink, .35), { label: 'Bolt shank' }), ...Array.from({ length: 6 }, (_, i) => vr(cx + u * .45 + i * u * .17, cy - u * .22, u * .44, card, 1, { label: 'Thread line' }))];
      case 3: return [rect(cx - u * 1.5, cy - u * .22, u * 2.6, u * .44, mix(ink, .35), { label: 'Screw shank' }), circle(cx + u * 1.3, cy, u * .55, c, { label: 'Screw head' }), hr(cx + u * .95, cy, u * .7, card, 2, { label: 'Slot' })];
      case 4: return [rect(cx - u * 1.2, cy - u * .2, u * 2, u * .4, mix(ink, .35), { label: 'Rivet shank' }), circle(cx - u * 1.2, cy, u * .5, c, { label: 'Rivet head' })];
      case 5: return [path(cx - u * 1.4, cy - u * .6, u * 2.8, u * 1.2, orn.sineOpenPath(4, 40), 'none', { stroke: c, strokeWidth: 3, open: true, label: 'Spring' })];
      case 6: return [rect(cx - u * .25, cy - u * 1.2, u * .5, u * 2.4, c, { rx: u * .25, label: 'Pin' }), circle(cx, cy - u * 1.2, u * .4, c, { label: 'Pin head' })];
      default: return [circle(cx, cy, u * 1.1, 'none', { stroke: c, strokeWidth: 5, dash: [u * 1.6, u * .5], label: 'Clip' })];
    }
  };
  const names = ['Hex nut', 'Flat washer', 'Hex bolt', 'Pan screw', 'Pop rivet', 'Spring, comp.', 'Dowel pin', 'Circlip'];

  switch (pageType) {
    case 'COVER': {
      const block = rect(0, 0, W, 740, accent, { label: 'Cover block', role: 'ORNAMENT' });
      const nut = obj(hex(420, 96, 360, ink), circle(600, 252, 96, accent, { label: 'Nut bore' }), circle(600, 252, 96, 'none', { stroke: ink, strokeWidth: 3, label: 'Thread ring' }), circle(600, 252, 76, 'none', { stroke: ink, strokeWidth: 1, dash: [4, 4], label: 'Thread ring' }), hr(420, 76, 360, ink, 1.5, { label: 'Dimension line' }), vr(420, 68, 16, ink, 1.5, { label: 'Dimension tick' }), vr(780, 68, 16, ink, 1.5, { label: 'Dimension tick' }), text(420, 82 - 36, 360, '36 mm across flats', { size: 11, font: 'ibmPlexMono', weight: 600, color: ink, align: 'center', wrap: false, label: 'Dimension label', role: 'CAPTION' }));
      const parts_ = text(M - 4, 250, 700, 'PARTS', { size: 330, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, tracking: -.02, label: 'Cover title', role: 'HEADLINE' });
      const and = text(M, 560, 760, 'AND HARDWARE', { size: 110, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, label: 'Cover subtitle', role: 'HEADLINE' });
      const band = obj(rect(0, 740, W, 316, ink, { label: 'Cover band', role: 'ORNAMENT' }), ...[['14,200', 'stocked parts'], ['M3 – M24', 'thread sizes'], ['4 p.m.', 'same-day dispatch'], ['27', 'catalogue number']].flatMap(([v, l], i) => [text(M + i * 190, 776, 180, v, { size: 40, font: 'bigShoulders', weight: 800, color: accent, wrap: false, label: 'Stat', role: 'LABEL' }), text(M + i * 190, 826, 180, l.toUpperCase(), { size: 8.5, font: 'ibmPlexMono', color: paper, tracking: .1, wrap: false, label: 'Stat label', role: 'CAPTION' }), ...(i ? [vr(M + i * 190 - 12, 780, 70, alpha(paper, .3), 1, { label: 'Stat divider' })] : [])]), hr(M, 880, CW, alpha(paper, .3), 1, { label: 'Band rule' }), text(M, 900, 560, 'Fasteners, fittings and fixings for the trade counter, the workshop and the weekend repair.', { size: 16, font: 'workSans', color: paper, leading: 1.5, label: 'Cover promise', role: 'DECK' }), ...barcode(R - 150, 910, 150, 70, paper, seed), text(R - 150, 986, 150, '9 780000 270429', { size: 8.5, font: 'ibmPlexMono', color: paper, align: 'center', wrap: false, label: 'Barcode number', role: 'SKU' }), text(M, 1010, 500, 'fsupply.example  ·  1 800 555 0127', { size: 11, font: 'ibmPlexMono', weight: 600, color: accent, wrap: false, label: 'Contact line', role: 'LABEL' }));
      return obj(G, block, nut, parts_, and, band);
    }
    case 'CONTENTS': {
      const t = text(M, 54, 500, 'CONTENTS', { size: 96, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, label: 'Contents title', role: 'HEADLINE' });
      const secs = [['Fasteners', 'Bolts, screws, rivets, pins', '4'], ['Nuts and washers', 'Hex, nyloc, flat, spring', '12'], ['Fittings', 'Couplings, elbows, tees', '20'], ['Fixings', 'Plugs, anchors, clips', '30'], ['Springs and pins', 'Compression, dowel, circlip', '38'], ['Tools for the counter', 'Spanners, drivers, taps', '44'], ['Reference', 'Thread charts and torque', '52']];
      const rows = secs.flatMap(([a, b, pg], i) => { const y = 176 + i * 66; return [rect(M, y, 8, 50, i % 2 ? secondary : accent, { label: 'Section tab', role: 'ORNAMENT' }), text(M + 24, y - 2, 340, a.toUpperCase(), { size: 30, font: 'bigShoulders', weight: 800, color: ink, wrap: false, label: 'Section name', role: 'HEADLINE' }), text(M + 24, y + 30, 340, b, { size: 12, font: 'workSans', color: soft, wrap: false, label: 'Section note', role: 'CAPTION' }), text(M + 440, y - 2, 70, pg, { size: 36, font: 'bigShoulders', weight: 800, color: ink, align: 'right', wrap: false, label: 'Page number', role: 'FOLIO' }), hr(M + 24, y + 56, 486, hair, .75, { label: 'Row rule' })]; });
      const qf = table(M + 560, 176, [{ w: 50, font: 'ibmPlexMono', size: 10, weight: 600 }, { w: 62, font: 'ibmPlexMono', size: 10 }, { w: 62, font: 'ibmPlexMono', size: 10, align: 'right' }], [['M6', 'HB-6020', 'HN-6'], ['M8', 'HB-8025', 'HN-8'], ['M10', 'HB-10030', 'HN-10'], ['M12', 'HB-12040', 'HN-12'], ['M16', 'HB-16050', 'HN-16']], { size: 10, font: 'ibmPlexMono', color: ink, rule: hair, pad: 6, head: ['Size', 'Bolt', 'Nut'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, label: 'Quick finder' });
      const qfl = text(M + 560, 150, 174, 'QUICK FINDER', { size: 18, font: 'bigShoulders', weight: 800, color: ink, wrap: false, label: 'Quick finder title', role: 'LABEL' });
      const how = obj(rect(M, 660, CW - 8, 300, card, { stroke: hair, strokeWidth: 1, label: 'Ordering panel', role: 'SIDEBAR' }), rect(M, 660, 10, 300, accent, { label: 'Panel bar', role: 'RULE' }), text(M + 34, 680, 400, 'ORDER BY CODE', { size: 40, font: 'bigShoulders', weight: 800, color: ink, wrap: false, role: 'SIDEBAR', label: 'Panel title' }), typeset(['Find the code. Two letters, a dash, then size and length: HB-10030 is a hex bolt, M10, 30 mm.', 'Orders are in packs. The pack size is in the table, and prices are per pack.', 'Phone, post or use the quick-order sheet on page 54. Trade accounts get net 30.'].map((tt, i) => ({ t: tt, marker: { t: String(i + 1), dx: -26, size: 16, font: 'bigShoulders' as const, color: accent, weight: 800 }, after: 10 })), [{ x: M + 64, y: 744, w: 400, h: 200 }], { size: 13, font: 'workSans', color: ink, leading: 1.5 }).objs, text(M + 520, 696, 180, '1 800\n555 0127', { size: 40, font: 'bigShoulders', weight: 800, color: accent, leading: 1, role: 'SIDEBAR', label: 'Phone number' }), text(M + 520, 790, 180, 'Mon–Fri 7:30–18:00\nSat 9:00–13:00', { size: 11, font: 'ibmPlexMono', color: soft, leading: 1.6, role: 'SIDEBAR', label: 'Trade hours' }));
      return obj(G, head('Contents', 0), t, rows, qfl, qf.objs, how, foot());
    }
    case 'SPEC TABLE': {
      if (pageIndex === 2) {
        const dg = obj(rect(R - 300, 56, 292, 150, card, { stroke: hair, strokeWidth: 1, label: 'Diagram panel', role: 'SIDEBAR' }), hex(R - 280, 96, 56, ink), rect(R - 236, 112, 176, 22, mix(ink, .35), { label: 'Bolt shank' }), ...Array.from({ length: 12 }, (_, i) => vr(R - 208 + i * 12, 112, 22, card, 1.2, { label: 'Thread line' })), hr(R - 236, 160, 176, ink, 1, { label: 'Dimension line' }), vr(R - 236, 154, 12, ink, 1, { label: 'Dimension tick' }), vr(R - 60, 154, 12, ink, 1, { label: 'Dimension tick' }), text(R - 236, 168, 176, 'l  length', { size: 10, font: 'ibmPlexMono', color: ink, align: 'center', wrap: false, role: 'CAPTION', label: 'Dimension label' }), text(R - 280, 70, 240, 'ISO 4017 · FULL THREAD', { size: 9, font: 'ibmPlexMono', weight: 600, color: soft, wrap: false, role: 'CAPTION', label: 'Diagram title' }), text(R - 292, 184, 280, 'd  nominal diameter  ·  P  pitch', { size: 10, font: 'ibmPlexMono', color: soft, wrap: false, role: 'CAPTION', label: 'Diagram key' }));
        const t = table(M, 224, [{ w: 84, font: 'ibmPlexMono', size: 10, weight: 600, color: accent, role: 'SKU' }, { w: 168, font: 'workSans', size: 11.5, weight: 600 }, { w: 60, font: 'ibmPlexMono', size: 10, align: 'right', role: 'SPEC' }, { w: 70, font: 'ibmPlexMono', size: 10, align: 'right', role: 'SPEC' }, { w: 56, font: 'ibmPlexMono', size: 10, align: 'center' }, { w: 70, font: 'workSans', size: 11 }, { w: 54, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 66, font: 'ibmPlexMono', size: 11, weight: 700, align: 'right', role: 'PRICE' }], BOLTS, { size: 11, font: 'workSans', color: ink, rule: hair, pad: 5, head: ['Code', 'Description', 'Pitch', 'Length', 'Grade', 'Finish', 'Pack', 'Price'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, zebra: mix(paper, -.04), label: 'Bolt table' });
        return obj(G, head('Fasteners', 0), text(M, 52, 420, 'HEX BOLTS', { size: 64, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, label: 'Table title', role: 'HEADLINE' }), text(M, 130, 380, 'Grade 8.8, zinc-plated, fully threaded. Metric coarse thread. Sold by the pack; prices are per pack.', { size: 12, font: 'workSans', color: soft, leading: 1.5, label: 'Table intro', role: 'DECK' }), dg, t.objs, foot());
      }
      const t1 = table(M, 150, [{ w: 62, font: 'ibmPlexMono', size: 10, weight: 600, color: accent, role: 'SKU' }, { w: 120, font: 'workSans', size: 11.5, weight: 600 }, { w: 44, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 76, font: 'workSans', size: 10.5 }, { w: 40, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 52, font: 'ibmPlexMono', size: 11, weight: 700, align: 'right', role: 'PRICE' }], NUTS, { size: 11, font: 'workSans', color: ink, rule: hair, pad: 5, head: ['Code', 'Nut', 'P', 'Material', 'Pack', 'Price'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, zebra: mix(paper, -.04), label: 'Nut table' });
      const t2 = table(M + 420, 150, [{ w: 58, font: 'ibmPlexMono', size: 10, weight: 600, color: accent, role: 'SKU' }, { w: 108, font: 'workSans', size: 11.5, weight: 600 }, { w: 72, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 40, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 50, font: 'ibmPlexMono', size: 11, weight: 700, align: 'right', role: 'PRICE' }], WASH, { size: 11, font: 'workSans', color: ink, rule: hair, pad: 5, head: ['Code', 'Washer', 'ID × OD', 'Pack', 'Price'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, zebra: mix(paper, -.04), label: 'Washer table' });
      const chart = table(M + 420, t2.bottom + 50, [{ w: 50, font: 'ibmPlexMono', size: 10, weight: 600 }, { w: 60, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 70, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 70, font: 'ibmPlexMono', size: 10, align: 'right' }], [['M6', '1.00', '5.0 mm', '6.6 mm'], ['M8', '1.25', '6.8 mm', '9.0 mm'], ['M10', '1.50', '8.5 mm', '11 mm'], ['M12', '1.75', '10.2 mm', '13.5 mm'], ['M16', '2.00', '14 mm', '17.5 mm']], { size: 10, font: 'ibmPlexMono', color: ink, rule: hair, pad: 5, head: ['Size', 'Pitch', 'Tap drill', 'Clearance'], headFont: 'ibmPlexMono', headSize: 8, headColor: ink, headRule: ink, label: 'Thread chart', role: 'SPEC' });
      const SCR = [6, 8, 10].flatMap(d => [20, 30, 40].map(l => [`SS-${d}${String(l).padStart(3, '0')}`, `Socket cap screw M${d} × ${l}`, PITCH[d], 'A2 stainless', d <= 8 ? '100' : '50', (d * l * .012 + 3.1).toFixed(2)]));
      const t3 = table(M, Math.max(t1.bottom + 90, chart.bottom + 40), [{ w: 90, font: 'ibmPlexMono', size: 10, weight: 600, color: accent, role: 'SKU' }, { w: 230, font: 'workSans', size: 11.5, weight: 600 }, { w: 70, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 130, font: 'workSans', size: 10.5 }, { w: 60, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 70, font: 'ibmPlexMono', size: 11, weight: 700, align: 'right', role: 'PRICE' }], SCR.slice(0, 7), { size: 11, font: 'workSans', color: ink, rule: hair, pad: 5, head: ['Code', 'Socket screws', 'Pitch', 'Material', 'Pack', 'Price'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, zebra: mix(paper, -.04), label: 'Screw table' });
      return obj(G, head('Nuts and washers', 1), t3.objs, text(M, 52, 600, 'NUTS AND WASHERS', { size: 64, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, label: 'Table title', role: 'HEADLINE' }), t1.objs, t2.objs, text(M + 420, t2.bottom + 20, 300, 'THREAD CHART', { size: 18, font: 'bigShoulders', weight: 800, color: ink, wrap: false, label: 'Chart title', role: 'LABEL' }), chart.objs, text(M, t1.bottom + 24, 380, 'Use a nyloc nut where vibration may loosen a joint. Never reuse a nyloc nut more than twice.', { size: 11, font: 'workSans', italic: true, color: soft, leading: 1.5, label: 'Note', role: 'FOOTNOTE' }), foot());
    }
    case 'PRODUCT GRID': {
      const cw = (CW - 8 - 24) / 3, ch = 200, y0 = 52;
      const cards = Array.from({ length: 12 }, (_, i) => { const x = M + (i % 3) * (cw + 12), y = y0 + Math.floor(i / 3) * (ch + 10); const code = ['HN-8', 'FW-8', 'HB-8025', 'PS-4016', 'PR-3210', 'SC-0820', 'DP-6030', 'CC-0012'][i % 8] + (i > 7 ? 'A' : ''); return [rect(x, y, cw, ch, card, { stroke: hair, strokeWidth: 1, label: 'Part card', role: 'SIDEBAR' }), rect(x, y, cw, 74, mix(paper, -.04), { label: 'Icon field' }), ...icon(i, x, y, cw, 74), text(x + 12, y + 84, cw - 24, code, { size: 11, font: 'ibmPlexMono', weight: 700, color: accent, wrap: false, label: 'Order code', role: 'SKU' }), text(x + 12, y + 102, cw - 24, names[i % 8] + (i > 7 ? ', stainless' : ''), { size: 17, font: 'bigShoulders', weight: 800, color: ink, wrap: false, label: 'Part name', role: 'HEADLINE' }), text(x + 12, y + 126, cw - 24, 'Pack of ' + [100, 200, 50, 100, 500, 25][i % 6] + '  ·  ' + ['M8', 'M8', 'M8 × 25', '4.0 × 16', '3.2 × 10', '0.8 × 20', '6 × 30', '12 mm'][i % 8], { size: 10, font: 'workSans', color: soft, wrap: false, label: 'Pack and size', role: 'SPEC' }), text(x + 12, y + ch - 36, 100, '$' + (2.4 + i * .85).toFixed(2), { size: 30, font: 'bigShoulders', weight: 800, color: ink, wrap: false, label: 'Price', role: 'PRICE' }), text(x + cw - 74, y + ch - 28, 62, 'QTY ▢', { size: 10, font: 'ibmPlexMono', color: soft, align: 'right', wrap: false, label: 'Quantity', role: 'LABEL' })]; }).flat();
      return obj(G, head('Fixings', 3), cards, foot());
    }
    case 'PRODUCT DETAIL': {
      const ax = 150, ay = 270;
      const pieces = obj(hr(M + 20, ay, 560, soft, 1, { dash: [8, 5], label: 'Centre line' }),
        hex(M + 40, ay - 22, 52, mix(ink, .15)), rect(M + 92, ay - 12, 50, 24, mix(ink, .35), { label: 'Bolt shank' }),
        circle(M + 170, ay, 24, 'none', { stroke: ink, strokeWidth: 8, label: 'Washer' }), circle(M + 170, ay, 8, card, { label: 'Washer bore' }),
        rect(M + 220, ay - 54, 80, 108, mix(ink, .1), { rx: 4, label: 'Coupling body' }), rect(M + 232, ay - 10, 56, 20, card, { label: 'Coupling bore' }),
        ellipse2(M + 330, ay, 14, 40), rect(M + 370, ay - 46, 54, 92, mix(ink, .25), { rx: 4, label: 'Collar' }),
        hex(M + 460, ay - 22, 52, mix(ink, .15)), circle(M + 486, ay, 10, card, { label: 'Nut bore' }));
      const nums = [[M + 66, 1], [M + 170, 2], [M + 260, 3], [M + 330, 4], [M + 397, 5], [M + 486, 6]].flatMap(([x, n]) => [vr(x, ay - 100, 46, ink, 1, { label: 'Leader' }), circle(x, ay - 112, 13, accent, { label: 'Callout' }), text(x - 13, ay - 121, 26, String(n), { size: 14, font: 'bigShoulders', weight: 800, color: ink, align: 'center', wrap: false, label: 'Callout number', role: 'LABEL' })]);
      const tbl = table(M, ay + 90, [{ w: 40, font: 'bigShoulders', size: 18, weight: 800, color: accent }, { w: 100, font: 'ibmPlexMono', size: 10, weight: 600, role: 'SKU' }, { w: 280, font: 'workSans', size: 12 }, { w: 44, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 70, font: 'ibmPlexMono', size: 11, weight: 700, align: 'right', role: 'PRICE' }], [['1', 'HB-8040', 'Hex bolt M8 × 40, grade 8.8', '4', '$5.80'], ['2', 'FW-8', 'Flat washer M8, zinc', '8', '$1.58'], ['3', 'CP-2200', 'Coupling body, brass, 22 mm', '1', '$14.90'], ['4', 'OR-2216', 'O-ring 22 × 2.5, nitrile', '2', '$1.20'], ['5', 'CL-2201', 'Compression collar, brass', '1', '$6.40'], ['6', 'NL-8', 'Nyloc nut M8, zinc', '4', '$2.12']], { size: 12, font: 'workSans', color: ink, rule: hair, pad: 8, head: ['No.', 'Code', 'Part', 'Qty', 'Price'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, zebra: mix(paper, -.04), label: 'Parts list' });
      const steps = obj(text(M, tbl.bottom + 30, 400, 'ASSEMBLY', { size: 28, font: 'bigShoulders', weight: 800, color: ink, wrap: false, label: 'Assembly title', role: 'LABEL' }), typeset(['Seat the O-rings in their grooves and wipe them with a little silicone grease.', 'Slide the collar over the pipe, then offer up the coupling body until it stops.', 'Fit the bolts with a washer under each head and a nyloc nut on the other side.', 'Tighten in a cross pattern to 18 N·m. Do not over-tighten the brass.'].map((tt, i) => ({ t: tt, marker: { t: String(i + 1), dx: -30, size: 20, font: 'bigShoulders' as const, color: accent, weight: 800, dy: -3 }, after: 10 })), [{ x: M + 40, y: tbl.bottom + 66, w: 440, h: 230 }], { size: 13, font: 'workSans', color: ink, leading: 1.5 }).objs);
      const kit = obj(rect(R - 220, tbl.bottom + 30, 212, 220, ink, { label: 'Kit card', role: 'SIDEBAR' }), text(R - 204, tbl.bottom + 46, 180, 'COMPLETE KIT', { size: 26, font: 'bigShoulders', weight: 800, color: accent, wrap: false, role: 'SIDEBAR', label: 'Kit title' }), text(R - 204, tbl.bottom + 82, 180, 'CK-2200', { size: 12, font: 'ibmPlexMono', weight: 600, color: paper, wrap: false, role: 'SKU', label: 'Kit code' }), text(R - 204, tbl.bottom + 108, 180, '$36.40', { size: 54, font: 'bigShoulders', weight: 800, color: paper, wrap: false, role: 'PRICE', label: 'Kit price' }), text(R - 204, tbl.bottom + 170, 180, 'Saves $4.10 against buying the parts one by one.', { size: 11, font: 'workSans', color: alpha(paper, .8), leading: 1.45, role: 'SIDEBAR', label: 'Kit note' }));
      return obj(G, head('Fittings', 2), text(M, 52, 700, 'COUPLING KIT, 22 MM', { size: 64, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, label: 'Product title', role: 'HEADLINE' }), text(M, 124, 700, 'Exploded view  ·  CK-2200  ·  brass body, nitrile seals', { size: 11, font: 'ibmPlexMono', color: soft, wrap: false, label: 'Product subtitle', role: 'DECK' }), pieces, nums, tbl.objs, steps, kit, foot());
    }
    case 'PRICE LIST': {
      const items = [['HB-6020', 'Hex bolt M6 × 20', '100'], ['HB-8025', 'Hex bolt M8 × 25', '100'], ['HB-10030', 'Hex bolt M10 × 30', '50'], ['HB-12040', 'Hex bolt M12 × 40', '50'], ['HN-8', 'Hex nut M8', '200'], ['HN-10', 'Hex nut M10', '100'], ['NL-8', 'Nyloc nut M8', '100'], ['FW-8', 'Flat washer M8', '500'], ['FW-10', 'Flat washer M10', '500'], ['PS-4016', 'Pan screw 4.0 × 16', '200'], ['PR-3210', 'Pop rivet 3.2 × 10', '500'], ['DP-6030', 'Dowel pin 6 × 30', '100'], ['SC-0820', 'Compression spring', '25'], ['CC-0012', 'Circlip 12 mm', '100']];
      const rows = items.map(([c, d, p], i) => { const base = 2.4 + i * .95; return [c, d, p, base.toFixed(2), (base * .93).toFixed(2), (base * .86).toFixed(2), (base * .78).toFixed(2), '−22%']; });
      const t = table(M, 164, [{ w: 84, font: 'ibmPlexMono', size: 10, weight: 600, color: accent, role: 'SKU' }, { w: 190, font: 'workSans', size: 11.5, weight: 600 }, { w: 50, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 70, font: 'ibmPlexMono', size: 11, align: 'right', role: 'PRICE' }, { w: 70, font: 'ibmPlexMono', size: 11, align: 'right', role: 'PRICE' }, { w: 70, font: 'ibmPlexMono', size: 11, align: 'right', role: 'PRICE' }, { w: 70, font: 'ibmPlexMono', size: 11, weight: 700, align: 'right', role: 'PRICE' }, { w: 60, font: 'ibmPlexMono', size: 10, align: 'right', color: secondary, weight: 700 }], rows, { size: 11, font: 'workSans', color: ink, rule: hair, pad: 7, head: ['Code', 'Part', 'Pack', '1 – 9', '10 – 99', '100 – 499', '500 +', 'Best'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, zebra: mix(paper, -.04), label: 'Quantity price matrix' });
      const notes = obj(rect(M, t.bottom + 30, CW - 8, 150, card, { stroke: hair, strokeWidth: 1, label: 'Terms panel', role: 'SIDEBAR' }), rect(M, t.bottom + 30, 10, 150, accent, { label: 'Panel bar', role: 'RULE' }), text(M + 30, t.bottom + 46, 400, 'TRADE TERMS', { size: 30, font: 'bigShoulders', weight: 800, color: ink, wrap: false, role: 'SIDEBAR', label: 'Terms title' }), text(M + 30, t.bottom + 86, 640, 'Quantity breaks apply per order line, in packs. Trade accounts receive a further 5% on orders above $500. Carriage is free over $150; below that, a flat $9. Returns of unopened packs are accepted within 28 days.', { size: 12.5, font: 'workSans', color: ink, leading: 1.55, role: 'SIDEBAR', label: 'Terms text' }));
      return obj(G, head('Price list', 4), text(M, 52, 600, 'QUANTITY PRICES', { size: 80, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, label: 'Page title', role: 'HEADLINE' }), text(M, 130, 640, 'Price per pack at each quantity break. Order more, pay less.', { size: 13, font: 'workSans', color: soft, wrap: false, label: 'Page intro', role: 'DECK' }), t.objs, notes, foot());
    }
    case 'ORDER FORM': {
      const fl = ['Name', 'Company', 'Account', 'Phone', 'Delivery address', 'Email'].flatMap((f, i) => { const x = M + (i % 3) * 244, y = 120 + Math.floor(i / 3) * 56, w = 228; return [label(x, y, w, f, { size: 8, font: 'ibmPlexMono', color: soft, tracking: .08, transform: 'none' }), hr(x, y + 36, w, ink, 1, { label: 'Entry line' })]; });
      const lines = (x: number) => table(x, 264, [{ w: 56, font: 'ibmPlexMono', size: 10 }, { w: 130, font: 'ibmPlexMono', size: 11 }, { w: 164, font: 'workSans', size: 10 }], Array.from({ length: 22 }, () => ['', '', '']), { size: 10, font: 'workSans', color: ink, rule: hair, pad: 6, minH: 26, head: ['Qty', 'Order code', 'Notes'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, vlines: true, label: 'Quick-order lines' });
      const a = lines(M), b = lines(M + 368);
      const ship = obj(label(M, 262 + 26 * 22 + 56, 300, 'Delivery', { size: 8.5, font: 'ibmPlexMono', color: accent, weight: 600, tracking: .2 }), ...['Standard, 2 days', 'Next day before noon', 'Collect from the counter'].flatMap((tt, i) => checkbox(M + i * 230, 262 + 26 * 22 + 76, tt, { color: ink, font: 'workSans', textSize: 11, w: 200 })));
      return obj(G, head('Quick order', 4), text(M, 52, 600, 'QUICK ORDER', { size: 64, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, label: 'Form title', role: 'HEADLINE' }), fl, a.objs, b.objs, ship, foot());
    }
    case 'INDEX': {
      const codes = ['CC', 'CK', 'CL', 'CP', 'DP', 'FW', 'HB', 'HN', 'NL', 'OR', 'PR', 'PS', 'SC'];
      const labels: Record<string, string> = { CC: 'Circlips', CK: 'Coupling kits', CL: 'Compression collars', CP: 'Coupling bodies', DP: 'Dowel pins', FW: 'Flat washers', HB: 'Hex bolts', HN: 'Hex nuts', NL: 'Nyloc nuts', OR: 'O-rings', PR: 'Pop rivets', PS: 'Pan screws', SC: 'Springs' };
      const pagesNo: Record<string, string> = { CC: '40', CK: '24', CL: '22', CP: '21', DP: '39', FW: '14', HB: '5', HN: '12', NL: '13', OR: '25', PR: '36', PS: '32', SC: '38' };
      const out: TelaVectorObject[] = []; let y = 140;
      codes.forEach((c, i) => { const x = M + (i % 3) * 244; if (i % 3 === 0 && i) y += 130; const yy = y; out.push(text(x, yy, 80, c, { size: 72, font: 'bigShoulders', weight: 800, color: i % 2 ? secondary : accent, wrap: false, leading: 1, role: 'HEADLINE', label: 'Prefix' }), text(x + 96, yy + 8, 130, labels[c], { size: 14, font: 'workSans', weight: 600, color: ink, leading: 1.25, role: 'CAPTION', label: 'Prefix description' }), text(x + 96, yy + 52, 130, 'page ' + pagesNo[c], { size: 11, font: 'ibmPlexMono', color: soft, wrap: false, role: 'FOLIO', label: 'Page' }), hr(x, yy + 90, 228, hair, .75)); });
      const lst = table(M, y + 190, [{ w: 90, font: 'ibmPlexMono', size: 10, weight: 600, color: accent }, { w: 250, font: 'workSans', size: 11 }, { w: 60, font: 'ibmPlexMono', size: 10, align: 'right' }, { w: 90, font: 'ibmPlexMono', size: 10, weight: 600, color: accent }, { w: 250, font: 'workSans', size: 11 }, { w: 40, font: 'ibmPlexMono', size: 10, align: 'right' }], [['AN-0612', 'Anchor, wall, M6 × 60', '31', 'FN-1610', 'Fibre washer 16 mm', '15'], ['BP-0008', 'Brass plug, 1/4 in', '27', 'GS-0340', 'Grub screw M3 × 4', '33'], ['CB-1204', 'Cable clip, 12 mm', '34', 'KB-0820', 'Key bolt, M8', '9'], ['CS-0420', 'Csk screw 4.0 × 20', '34', 'TW-0630', 'T-nut, M6', '35']], { size: 11, font: 'workSans', color: ink, rule: hair, pad: 7, head: ['Code', 'Part', 'Page', 'Code', 'Part', 'Page'], headFont: 'ibmPlexMono', headSize: 8, headColor: paper, headFill: ink, headRule: ink, label: 'Code index' });
      return obj(G, head('Index', 4), text(M, 52, 600, 'PART NUMBER INDEX', { size: 64, font: 'bigShoulders', weight: 800, color: ink, wrap: false, leading: 1, label: 'Index title', role: 'HEADLINE' }), out, text(M, y + 160, 400, 'ALSO LISTED', { size: 18, font: 'bigShoulders', weight: 800, color: ink, wrap: false, label: 'Also title', role: 'LABEL' }), lst.objs, foot());
    }
    default: {
      return obj(G, rect(0, 0, W, H, accent, { label: 'Back cover ground', role: 'ORNAMENT' }), text(M, 60, 740, 'NEED IT\nTOMORROW?', { size: 190, font: 'bigShoulders', weight: 800, color: ink, leading: .88, tracking: -.01, label: 'Back cover headline', role: 'HEADLINE' }), text(M, 450, 560, 'Order by 4 p.m. and we dispatch the same day. Free carriage on trade orders over $150.', { size: 22, font: 'workSans', weight: 500, color: ink, leading: 1.45, label: 'Back cover promise', role: 'DECK' }), hr(M, 600, CW, ink, 3, { label: 'Rule' }), ...[['Phone', '1 800 555 0127'], ['Email', 'orders@fsupply.example'], ['Counter', '14 Quay Lane, Leith'], ['Hours', 'Mon–Fri 7:30–18:00']].flatMap(([k, v], i) => [text(M + (i % 2) * 380, 628 + Math.floor(i / 2) * 96, 340, k.toUpperCase(), { size: 10, font: 'ibmPlexMono', weight: 600, color: ink, tracking: .2, wrap: false, label: 'Contact label', role: 'LABEL' }), text(M + (i % 2) * 380, 648 + Math.floor(i / 2) * 96, 360, v, { size: 28, font: 'bigShoulders', weight: 800, color: ink, wrap: false, label: 'Contact', role: 'LABEL' })]), hex(560, 840, 180, ink), circle(650, 840 + 78, 44, accent, { label: 'Nut bore' }), text(M, H - 70, 400, 'PARTS AND HARDWARE', { size: 26, font: 'bigShoulders', weight: 800, color: ink, tracking: .08, wrap: false, label: 'Masthead', role: 'LOGO' }), ...barcode(M, H - 130, 150, 44, ink, seed + 11));
    }
  }
};
function ellipse2(cx: number, cy: number, rx: number, ry: number): TelaVectorObject { return rect(cx - rx, cy - ry, rx * 2, ry * 2, 'none', { rx: rx, stroke: '#1A1F1C', strokeWidth: 6, label: 'O-ring', role: 'ORNAMENT' }); }

// ═════════════════════════════════════════════════════════════════════════════
// 5 · cat-auction — Auction Catalog (A4; lot pages, estimates, provenance, conditions, bid form)
// ═════════════════════════════════════════════════════════════════════════════
interface Lot { n: string; artist: string; life: string; title: string; year: string; medium: string; dims: string; sign: string; est: string; prov: string[]; lit: string; essay: string }
const LOTS: Lot[] = [
  { n: '12', artist: 'Ilse Brandt', life: 'b. 1951', title: 'Harbour at Dusk', year: '1998', medium: 'oil on canvas', dims: '120 × 160 cm (47¼ × 63 in.)', sign: 'signed, titled and dated 1998 on the reverse', est: '£80,000 – 120,000', prov: ['The artist', 'Galerie Nord, Hamburg, 1999', 'Private collection, Edinburgh, acquired from the above in 2003'], lit: 'I. Brandt, Light and Water, Hamburg, 2002, p. 88, illustrated in colour', essay: 'Painted the year Brandt moved from Hamburg to the Baltic coast, Harbour at Dusk gathers the cold blues and ochres of the northern evening into a single horizontal pulse. The boats are no more than strokes; the water is a ledger of every light that has crossed it. Brandt has said that she painted the harbour “until it forgave me,” and the surface carries that long negotiation in its layered glazes.' },
  { n: '13', artist: 'Tomas Ekwueme', life: '1938–2011', title: 'Study for a Monument', year: '1974', medium: 'charcoal and gouache on paper', dims: '76 × 56 cm (30 × 22 in.)', sign: 'signed and dated lower right', est: '£15,000 – 20,000', prov: ['The artist’s estate', 'Anon. sale, London, 2014, lot 41'], lit: 'T. Ekwueme: Drawings 1960–1985, Lagos, 2016, no. 112', essay: 'A preparatory drawing for the unrealised memorial that occupied Ekwueme through the 1970s, this sheet shows the forms at their most severe: a stack of rectangles leaning like a tide table. The gouache is laid on so thinly that the paper breathes through it.' },
  { n: '14', artist: 'Marguerite Dalle', life: 'b. 1974', title: 'Untitled (Weather)', year: '2012', medium: 'acrylic and graphite on linen', dims: '90 × 90 cm (35½ × 35½ in.)', sign: 'signed and dated on the stretcher', est: '£30,000 – 50,000', prov: ['Galerie Mercier, Paris', 'Private collection, Brussels'], lit: 'M. Dalle, Weather Reports, Paris, 2013, p. 40, illustrated', essay: 'Dalle’s grids are not drawn but weathered into being: she lets the linen sit outdoors for months before the paint is applied. The result is a surface that records its own history as faint rain tracks across a fixed geometry.' },
  { n: '15', artist: 'Oskar Winther', life: '1912–1988', title: 'Two Chairs', year: '1956', medium: 'oil on board', dims: '61 × 76 cm (24 × 30 in.)', sign: 'signed lower left', est: '£40,000 – 60,000', prov: ['The artist', 'Thence by descent'], lit: 'O. Winther, Catalogue Raisonné, Oslo, 1994, no. 318', essay: 'Winther painted the same two chairs for more than thirty years. In this version, one chair has turned to face the other, an event the artist described in his diary as “the great change of 1956.”' },
  { n: '16', artist: 'Nadia Farouk', life: 'b. 1983', title: 'Ice, 21:05', year: '2021', medium: 'archival pigment print, edition 2/5', dims: '100 × 150 cm (39¼ × 59 in.)', sign: 'signed, numbered and dated on a label on the reverse', est: '£6,000 – 9,000', prov: ['Galerie Quay, Edinburgh', 'Acquired from the above by the present owner'], lit: 'N. Farouk, Night Market, Edinburgh, 2022, plate 1', essay: 'From the artist’s Night Market series, Ice, 21:05 shows the first crate of the evening tipped into the trough at Quay Street. It is a picture about attention: the arc of the ice, a porter’s braced shoulder, the weight of cold.' },
  { n: '17', artist: 'Anselm Ode', life: 'b. 1968', title: 'The Wobble Chair', year: '1994', medium: 'ash, brass', dims: '84 × 42 × 44 cm (33 × 16½ × 17¼ in.)', sign: 'brass plate beneath the seat, inscribed “Mend me”', est: '£4,000 – 6,000', prov: ['The artist', 'Private collection, Leith'], lit: 'A. Ode, The Quiet Chair, Leith, 2026, pp. 12–19', essay: 'The first of the chairs Ode never allowed himself to repair: a plain ash dining chair with a left rear leg a quarter inch short. It has become, in the artist’s words, “the chair that reminds me who I work for.”' },
];
const CONDITIONS = ['The auctioneer acts as agent for the seller. All lots are offered subject to these Conditions of Sale and to any additional notices displayed in the sale room.', 'Estimates are an opinion of the likely hammer price and are not a guarantee. A lot may be withdrawn at any time before the fall of the hammer.', 'The buyer’s premium is payable on the hammer price at the rates shown. Value added tax is payable on the premium.', 'Condition reports are available on request. Lots are sold as seen; viewing is encouraged and is the buyer’s responsibility.', 'Absentee and telephone bids must be registered at least 24 hours before the sale and are accepted at the bidder’s risk.', 'Payment is due within seven days of the sale. Title passes only on receipt of cleared funds. Lots not collected within thirty days will be moved to storage at the buyer’s cost.', 'Exports may require a licence. It is the buyer’s responsibility to obtain any export licence needed and to pay any duty or tax that arises.', 'These conditions are governed by the law of England and Wales, and disputes will be heard in the courts of London.'];

const auction: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex, seed } = ctx;
  const M = 64, R = W - M, CW = W - 2 * M, soft = mix(ink, .45), hair = alpha(ink, .22), tint = mix(paper, -.04);
  const G = rect(0, 0, pageType === 'BACK COVER' ? W : W, H, pageType === 'BACK COVER' ? ink : paper, { role: 'GROUND', label: 'Page ground' });
  const head = (): TelaVectorObject[] => obj(text(M, 34, 480, 'ALDWYCH & ROWE', { size: 10, font: 'tenor', color: ink, tracking: .36, wrap: false, label: 'House name', role: 'LOGO' }), text(R - 400, 34, 400, 'MODERN AND CONTEMPORARY ART  ·  12 NOVEMBER 2026', { size: 8, font: 'tenor', color: soft, tracking: .22, align: 'right', wrap: false, label: 'Sale name', role: 'LABEL' }), hr(M, 56, CW, ink, .75, { label: 'Head rule' }));
  const foot = (): TelaVectorObject[] => obj(hr(M, H - 52, CW, hair, .75, { label: 'Foot rule' }), text(verso(pageIndex) ? M : R - 60, H - 40, 60, String(pageIndex * 2 + 18), { size: 9, font: 'tenor', color: ink, align: verso(pageIndex) ? 'left' : 'right', wrap: false, tracking: .14, label: 'Folio', role: 'FOLIO' }), text(verso(pageIndex) ? M + 60 : M, H - 40, 560, 'Lots are sold subject to the Conditions of Sale printed in this catalogue', { size: 8, font: 'tenor', color: soft, tracking: .16, wrap: false, label: 'Running foot', role: 'FOLIO' }));
  const lotNo = (n: string, x: number, y: number, size = 96): TelaVectorObject => text(x, y, size * 2, n, { size, font: 'cormorant', weight: 300, color: accent, wrap: false, leading: 1, label: 'Lot number', role: 'HERO' });
  const lotData = (x: number, y: number, w: number, L: Lot, size = 1): TelaVectorObject[] => { const a = text(x, y, w, L.artist.toUpperCase(), { size: 14, font: 'tenor', color: ink, tracking: .24, wrap: false, label: 'Artist', role: 'BYLINE' }); const life = text(x, below(a, 4), w, '(' + L.life + ')', { size: 14, font: 'cormorant', color: soft, wrap: false, label: 'Artist dates', role: 'DATELINE' }); const t = text(x, below(life, 14), w, L.title, { size: 34, font: 'cormorant', weight: 500, italic: true, color: ink, leading: 1.05, label: 'Lot title', role: 'HEADLINE' }); const meta = text(x, below(t, 10), w, `${L.year}\n${L.medium}\n${L.dims}\n${L.sign}`, { size: 12.5, font: 'ebGaramond', color: mix(ink, .15), leading: 1.45, label: 'Lot details', role: 'SPEC' }); const est = obj(hr(x, below(meta, 14), w, ink, .75, { label: 'Estimate rule' }), label(x, below(meta, 24), w, 'Estimate', { size: 8, font: 'tenor', color: soft, tracking: .24 }), text(x, below(meta, 40), w, L.est, { size: 20, font: 'cormorant', weight: 600, color: accent, wrap: false, label: 'Estimate', role: 'PRICE' })); return obj(a, life, t, meta, est); };
  const prov = (x: number, y: number, w: number, L: Lot): { objs: TelaVectorObject[]; bottom: number } => { const o: TelaVectorObject[] = [label(x, y, w, 'Provenance', { size: 8, font: 'tenor', color: accent, tracking: .26 })]; const t = typeset(L.prov.map((p, i) => ({ t: p, marker: { t: String(i + 1), dx: -16, size: 9, font: 'tenor' as const, color: soft, weight: 400, dy: 2 }, after: 3 })), [{ x: x + 16, y: y + 18, w: w - 16, h: 160 }], { size: 11.5, font: 'ebGaramond', color: ink, leading: 1.4 }); const lit = text(x, t.ends[0] + 8, w, 'Literature  ' + L.lit, { size: 11, font: 'ebGaramond', italic: true, color: soft, leading: 1.4, label: 'Literature', role: 'FOOTNOTE' }); o.push(...t.objs, lit); return { objs: o, bottom: below(lit, 0) }; };

  const relRow = (y: number, skip: number): TelaVectorObject[] => obj(hr(M, y, CW, ink, .75, { label: 'Related rule' }), label(M, y + 12, 300, 'Also in this sale', { size: 8, font: 'tenor', color: accent, tracking: .26 }), ...LOTS.filter((_, i) => i !== skip).slice(0, 3).flatMap((L, i) => { const w = (CW - 40) / 3, x = M + i * (w + 20); return [...imageSlot(x, y + 36, 70, 90, { tone: 'light', shade: mix(paper, -.12), silent: true, frame: hair, label: 'Related lot image' }), text(x + 84, y + 34, w - 84, 'LOT ' + L.n, { size: 8, font: 'tenor', color: accent, tracking: .2, wrap: false, role: 'LABEL', label: 'Related lot' }), text(x + 84, y + 50, w - 84, L.artist, { size: 13, font: 'cormorant', weight: 600, color: ink, leading: 1.15, role: 'BYLINE', label: 'Related artist' }), text(x + 84, y + 84, w - 84, L.title, { size: 12.5, font: 'cormorant', italic: true, color: soft, leading: 1.15, role: 'HEADLINE', label: 'Related title' })]; }));
  switch (pageType) {
    case 'COVER': {
      const img = figure(W / 2 - 190, 150, 380, 500, { tone: 'light', shade: mix(paper, -.12), hint: 'Cover lot · Lot 12', hero: true, label: 'Cover lot image', frame: hair });
      return obj(G, rect(36, 36, W - 72, H - 72, 'none', { stroke: accent, strokeWidth: 1, label: 'Hairline frame', role: 'RULE' }), text(M, 68, CW, 'ALDWYCH & ROWE', { size: 20, font: 'tenor', color: ink, tracking: .5, align: 'center', wrap: false, label: 'House name', role: 'LOGO' }), text(M, 96, CW, 'FINE ART AUCTIONEERS  ·  SINCE 1884', { size: 8, font: 'tenor', color: soft, tracking: .34, align: 'center', wrap: false, label: 'House line', role: 'LABEL' }), img.objs, text(W / 2 - 190, 662, 380, 'LOT 12  ·  ILSE BRANDT  ·  HARBOUR AT DUSK (DETAIL)', { size: 7.5, font: 'tenor', color: soft, tracking: .2, align: 'center', wrap: false, label: 'Cover caption', role: 'CAPTION' }), text(M, 716, CW, 'Modern &\nContemporary Art', { size: 62, font: 'cormorant', weight: 400, italic: true, color: ink, align: 'center', leading: 1.0, label: 'Sale title', role: 'HEADLINE' }), hr(W / 2 - 30, 884, 60, accent, 1.5, { label: 'Rule' }), text(M, 900, CW, 'EVENING SALE', { size: 12, font: 'tenor', color: accent, tracking: .5, align: 'center', wrap: false, label: 'Sale type', role: 'KICKER' }), text(M, 926, CW, 'Thursday 12 November 2026 at 6 p.m.\n14 Aldwych Place, London WC2', { size: 15, font: 'cormorant', color: ink, align: 'center', leading: 1.6, label: 'Sale details', role: 'DATELINE' }), text(M, H - 90, CW, 'VIEWING  ·  6 – 11 NOVEMBER  ·  SALE CODE  ARX-2611', { size: 8, font: 'tenor', color: soft, tracking: .3, align: 'center', wrap: false, label: 'Viewing line', role: 'LABEL' }));
    }
    case 'CONTENTS': {
      const t = text(M, 90, 600, 'The sale', { size: 60, font: 'cormorant', weight: 300, italic: true, color: ink, wrap: false, label: 'Contents title', role: 'HEADLINE' });
      const sec = table(M, 200, [{ w: 80, font: 'tenor', size: 10, color: accent, tracking: .2 }, { w: 270, font: 'cormorant', size: 20, italic: true }, { w: 90, font: 'tenor', size: 10, align: 'right', color: soft }, { w: 80, font: 'cormorant', size: 18, align: 'right' }], [['I', 'Works on paper', 'Lots 1 – 11', '20'], ['II', 'Paintings', 'Lots 12 – 24', '32'], ['III', 'Photography', 'Lots 25 – 31', '56'], ['IV', 'Sculpture and design', 'Lots 32 – 38', '66'], ['V', 'Editions', 'Lots 39 – 47', '74']], { size: 18, font: 'cormorant', color: ink, rule: hair, pad: 11, label: 'Sale structure' });
      const info = table(M, sec.bottom + 70, [{ w: 150, font: 'tenor', size: 9, color: soft, tracking: .2 }, { w: 350, font: 'ebGaramond', size: 14 }], [['Sale', 'Evening Sale, Thursday 12 November 2026, 6 p.m.'], ['Venue', '14 Aldwych Place, London WC2'], ['Viewing', 'Friday 6 to Wednesday 11 November, 10 a.m. to 6 p.m.'], ['Auctioneer', 'Edmund Rowe (licence 0412)'], ['Enquiries', '+44 20 7555 0147  ·  art@aldwychrowe.example'], ['Catalogue', '£30, or free to view online']], { size: 14, font: 'ebGaramond', color: ink, rule: hair, pad: 9, head: ['Sale information', ''], headFont: 'tenor', headSize: 8.5, headColor: accent, headRule: ink, label: 'Sale information' });
      const bid = obj(rect(M, info.bottom + 40, CW, 140, tint, { label: 'How to bid panel', role: 'SIDEBAR' }), label(M + 28, info.bottom + 58, 300, 'How to bid', { size: 9, font: 'tenor', color: accent, tracking: .28, role: 'SIDEBAR' }), ...['In the room', 'By telephone', 'Absentee', 'Online'].flatMap((b, i) => [text(M + 28 + i * 124, info.bottom + 88, 116, b, { size: 17, font: 'cormorant', weight: 600, italic: true, color: ink, wrap: false, role: 'SIDEBAR', label: 'Bid method' }), text(M + 28 + i * 124, info.bottom + 116, 110, ['Register at the desk', 'Booked 24 hours ahead', 'Form on page 82', 'Live from the website'][i], { size: 10.5, font: 'ebGaramond', color: soft, leading: 1.35, role: 'SIDEBAR', label: 'Bid note' })]));
      return obj(G, head(), t, sec.objs, info.objs, bid, foot());
    }
    case 'SECTION OPENER': {
      return obj(G, head(), text(M, 130, 400, 'II', { size: 260, font: 'cormorant', weight: 300, color: accent, wrap: false, leading: 1, label: 'Part numeral', role: 'HERO' }), text(M, 400, 600, 'Paintings', { size: 78, font: 'cormorant', weight: 400, italic: true, color: ink, wrap: false, label: 'Part title', role: 'HEADLINE' }), text(M, 504, 300, 'LOTS 12 – 24', { size: 11, font: 'tenor', color: ink, tracking: .4, wrap: false, label: 'Lot range', role: 'LABEL' }), hr(M, 536, 60, accent, 1.5, { label: 'Rule' }), ...typeset(['A decade of painting, from the cold harbours of the Baltic to the weathered grids of a Paris studio. What these canvases share is patience: each took years, and each shows it.', 'The section opens with Ilse Brandt’s Harbour at Dusk, a picture the artist has described as the one she needed to finish before she could finish anything else. It is followed by the quiet rooms of Oskar Winther and the weathered geometry of Marguerite Dalle.'].map(t => ({ t })), [{ x: M, y: 566, w: 440, h: 260 }], { size: 15, font: 'ebGaramond', color: ink, leading: 1.6, after: 12 }).objs, ...figure(M + 500, 130, 170, 700, { tone: 'light', shade: mix(paper, -.1), hint: 'Section image · tall', label: 'Section image', frame: hair }).objs, foot());
    }
    case 'PRODUCT DETAIL': {
      if (pageIndex === 3) {
        const L = LOTS[0];
        const img = figure(M, 100, 360, 470, { tone: 'light', shade: mix(paper, -.12), hint: 'Lot 12 · portrait', hero: true, label: 'Lot image', frame: hair });
        const pv = prov(M, 604, 360, L);
        const es = typeset([L.essay], [{ x: M + 400, y: 600, w: CW - 400, h: 380 }], { size: 12.5, font: 'ebGaramond', color: ink, leading: 1.55 });
        return obj(G, head(), lotNo(L.n, M + 392, 84, 110), lotData(M + 396, 218, CW - 396, L), img.objs, pv.objs, label(M + 400, 580, 200, 'Catalogue note', { size: 8, font: 'tenor', color: accent, tracking: .26 }), es.objs, relRow(880, 0), foot());
      }
      const L = LOTS[4];
      const img = figure(M, 100, CW, 380, { tone: 'light', shade: mix(paper, -.12), hint: 'Lot 16 · landscape', hero: true, label: 'Lot image', frame: hair });
      const pv = prov(M, 700, 300, L);
      const es = typeset([L.essay], [{ x: M + 340, y: 700, w: CW - 340, h: 260 }], { size: 12.5, font: 'ebGaramond', color: ink, leading: 1.55 });
      return obj(G, head(), img.objs, lotNo(L.n, M, 500, 110), lotData(M + 160, 500, CW - 160, L), pv.objs, label(M + 340, 680, 200, 'Catalogue note', { size: 8, font: 'tenor', color: accent, tracking: .26 }), es.objs, relRow(900, 4), foot());
    }
    case 'PRODUCT GRID': {
      const cw = (CW - 28) / 2, ch = 296;
      const cells = LOTS.flatMap((L, i) => { const x = M + (i % 2) * (cw + 28), y = 92 + Math.floor(i / 2) * (ch + 22); return [...imageSlot(x, y, 150, 200, { tone: 'light', shade: mix(paper, -.12), silent: true, frame: hair, label: 'Lot thumbnail' }), text(x + 170, y - 6, 100, L.n, { size: 56, font: 'cormorant', weight: 300, color: accent, wrap: false, leading: 1, label: 'Lot number', role: 'HERO' }), text(x + 170, y + 62, cw - 170, L.artist.toUpperCase(), { size: 10, font: 'tenor', color: ink, tracking: .2, leading: 1.4, label: 'Artist', role: 'BYLINE' }), text(x + 170, y + 100, cw - 170, L.title, { size: 18, font: 'cormorant', italic: true, color: ink, leading: 1.15, label: 'Lot title', role: 'HEADLINE' }), text(x + 170, y + 150, cw - 170, L.year + '\n' + L.medium, { size: 11, font: 'ebGaramond', color: soft, leading: 1.4, label: 'Lot medium', role: 'SPEC' }), text(x + 170, y + 190, cw - 170, L.est, { size: 12.5, font: 'cormorant', weight: 700, color: accent, wrap: false, label: 'Estimate', role: 'PRICE' }), hr(x, y + 224, cw, hair, .75, { label: 'Cell rule' })]; });
      return obj(G, head(), text(M, 62, 500, 'Lots 12 – 17', { size: 15, font: 'tenor', color: ink, tracking: .3, wrap: false, label: 'Lot range', role: 'LABEL' }), cells, foot());
    }
    case 'PRICE LIST': {
      const est = table(M, 110, [{ w: 40, font: 'cormorant', size: 18, color: accent, weight: 600 }, { w: 220, font: 'tenor', size: 9.5, tracking: .08 }, { w: 190, font: 'cormorant', size: 14, italic: true }, { w: 100, font: 'cormorant', size: 14, weight: 600, align: 'right', role: 'PRICE' }], LOTS.map(L => [L.n, L.artist.toUpperCase(), L.title, L.est.split(' – ')[0].replace('£', '£')]), { size: 14, font: 'cormorant', color: ink, rule: hair, pad: 6, head: ['Lot', 'Artist', 'Title', 'Low estimate'], headFont: 'tenor', headSize: 8, headColor: accent, headRule: ink, label: 'Estimate summary' });
      const prem = table(M, est.bottom + 50, [{ w: 250, font: 'ebGaramond', size: 13 }, { w: 90, font: 'cormorant', size: 20, weight: 600, align: 'right', color: accent }], [['Up to £800,000', '26%'], ['£800,000 to £4,000,000', '21%'], ['Above £4,000,000', '15%']], { size: 13, font: 'ebGaramond', color: ink, rule: hair, pad: 9, head: ['Buyer’s premium (on hammer price)', 'Rate'], headFont: 'tenor', headSize: 8, headColor: accent, headRule: ink, label: 'Buyer premium' });
      const cond = typeset(CONDITIONS.map((c, i) => ({ t: c, marker: { t: String(i + 1), dx: -18, size: 9, font: 'tenor' as const, color: accent, dy: 1 }, after: 5 })), [{ x: M + 18, y: prem.bottom + 70, w: 200, h: 440 }, { x: M + 18 + 232, y: prem.bottom + 70, w: 200, h: 440 }], { size: 9.5, font: 'ebGaramond', color: soft, leading: 1.4 });
      return obj(G, head(), text(M, 62, 500, 'Estimates and conditions', { size: 15, font: 'tenor', color: ink, tracking: .3, wrap: false, label: 'Page title', role: 'LABEL' }), est.objs, prem.objs, label(M, prem.bottom + 46, 300, 'Conditions of sale', { size: 9, font: 'tenor', color: accent, tracking: .28 }), hr(M, prem.bottom + 64, CW - 150, ink, .75), cond.objs, foot());
    }
    case 'ORDER FORM': {
      const fl = ['Name', 'Address', 'Telephone', 'Email', 'Bank reference', 'Client number'].flatMap((f, i) => { const x = M + (i % 2) * (CW / 2 + 12), y = 130 + Math.floor(i / 2) * 52, w = CW / 2 - 12; return [label(x, y, w, f, { size: 8, font: 'tenor', color: soft, tracking: .2 }), hr(x, y + 34, w, ink, .75, { label: 'Entry line' })]; });
      const grid = table(M, 330, [{ w: 70, font: 'cormorant', size: 14 }, { w: 330, font: 'cormorant', size: 14 }, { w: 130, font: 'cormorant', size: 14, align: 'right' }], Array.from({ length: 10 }, () => ['', '', '']), { size: 14, font: 'cormorant', color: ink, rule: hair, pad: 9, minH: 30, head: ['Lot', 'Artist and title', 'Maximum hammer bid (£)'], headFont: 'tenor', headSize: 8, headColor: accent, headRule: ink, vlines: true, label: 'Bid lines' });
      const by = grid.bottom + 24;
      const opt = obj(...['Absentee bid', 'Telephone bid (we will call you)', 'Online bid'].flatMap((t, i) => checkbox(M + i * 190, by, t, { color: ink, font: 'ebGaramond', textSize: 12, w: 180 })), text(M, by + 36, CW, 'Bids are placed at the lowest price the reserve and other bids allow. Forms must reach us at least 24 hours before the sale. I have read the Conditions of Sale and agree to be bound by them.', { size: 11, font: 'ebGaramond', italic: true, color: soft, leading: 1.5, label: 'Bid terms', role: 'FOOTNOTE' }), hr(M, by + 120, 260, ink, .75, { label: 'Signature line' }), label(M, by + 128, 260, 'Signature', { size: 8, font: 'tenor', color: soft, tracking: .2 }), hr(M + 300, by + 120, 140, ink, .75, { label: 'Date line' }), label(M + 300, by + 128, 140, 'Date', { size: 8, font: 'tenor', color: soft, tracking: .2 }));
      return obj(G, head(), text(M, 60, 600, 'Absentee bid form', { size: 46, font: 'cormorant', weight: 300, italic: true, color: ink, wrap: false, label: 'Form title', role: 'HEADLINE' }), fl, grid.objs, opt, foot());
    }
    case 'INDEX': {
      const artists = [...LOTS].sort((a, b) => a.artist.split(' ').slice(-1)[0].localeCompare(b.artist.split(' ').slice(-1)[0]));
      const extra: Array<[string, string]> = [['Alder, Piet', '3, 8'], ['Calloway, Rue', '22'], ['Ferreira, Odile', '27, 28'], ['Haugen, Lena', '31'], ['Lindqvist, Teodor', '19'], ['Okafor, Imani', '24, 36'], ['Sato, Mei', '41'], ['Varga, Ines', '9']];
      const rows: Array<[string, string]> = [...artists.map(a => [a.artist.split(' ').slice(-1)[0] + ', ' + a.artist.split(' ').slice(0, -1).join(' '), a.n] as [string, string]), ...extra].sort((a, b) => a[0].localeCompare(b[0]));
      const colW = (CW - 40) / 2; const out: TelaVectorObject[] = [];
      const half = Math.ceil(rows.length / 2);
      [rows.slice(0, half), rows.slice(half)].forEach((col, c) => { const x = M + c * (colW + 40); let y = 130; let last = ''; col.forEach(([n, lots]) => { const l = n[0]; if (l !== last) { last = l; y += 8; out.push(text(x, y, 30, l, { size: 28, font: 'cormorant', weight: 300, italic: true, color: accent, wrap: false, role: 'HEADLINE', label: 'Index letter' })); y += 34; } out.push(text(x, y, colW - 100, n, { size: 15, font: 'cormorant', color: ink, wrap: false, role: 'BYLINE', label: 'Index artist' }), hr(x + 8 + n.length * 7.6, y + 12, colW - 108 - n.length * 7.6, hair, 1, { dash: [1, 4], label: 'Leader' }), text(x + colW - 96, y + 1, 96, lots, { size: 11, font: 'tenor', color: soft, tracking: .1, align: 'right', wrap: false, role: 'FOLIO', label: 'Lot numbers' })); y += 26; }); });
      return obj(G, head(), text(M, 62, 500, 'Index of artists', { size: 46, font: 'cormorant', weight: 300, italic: true, color: ink, wrap: false, label: 'Index title', role: 'HEADLINE' }), text(M + 330, 82, 300, 'Lot numbers', { size: 8, font: 'tenor', color: soft, tracking: .24, wrap: false, label: 'Index key', role: 'CAPTION' }), out, foot());
    }
    default: {
      const c = alpha(paper, .85);
      return obj(G, rect(36, 36, W - 72, H - 72, 'none', { stroke: accent, strokeWidth: 1, label: 'Hairline frame', role: 'RULE' }), text(M, 330, CW, 'ALDWYCH & ROWE', { size: 28, font: 'tenor', color: paper, tracking: .5, align: 'center', wrap: false, label: 'House name', role: 'LOGO' }), hr(W / 2 - 24, 390, 48, accent, 1.5, { label: 'Rule' }), text(M, 420, CW, '14 Aldwych Place, London WC2B 4AA\n+44 20 7555 0147  ·  art@aldwychrowe.example\naldwychrowe.example', { size: 16, font: 'cormorant', color: c, align: 'center', leading: 1.8, label: 'Contact', role: 'LABEL' }), text(M + 40, 640, CW - 80, 'Aldwych & Rowe Ltd, registered in England 0412873. Auctioneer’s licence 0412. Prices are in pounds sterling. Estimates are not guarantees. Please read the Conditions of Sale before bidding.', { size: 9, font: 'tenor', color: alpha(paper, .55), tracking: .14, align: 'center', leading: 1.9, label: 'Legal line', role: 'FOOTNOTE' }), ...barcode(W / 2 - 60, H - 150, 120, 36, alpha(paper, .8), seed + 3), text(M, H - 100, CW, 'SALE CODE  ARX-2611', { size: 8, font: 'tenor', color: alpha(paper, .6), tracking: .3, align: 'center', wrap: false, label: 'Sale code', role: 'SKU' }));
    }
  }
};

// ═════════════════════════════════════════════════════════════════════════════
// 6 · cat-events — Course Catalog (Letter; course cards, schedule, fees, registration)
// ═════════════════════════════════════════════════════════════════════════════
interface Course { code: string; title: string; day: number; start: number; dur: number; weeks: string; price: string; level: string; tutor: string; left: number; cap: number; blurb: string; cat: string }
const COURSES: Course[] = [
  { code: 'QS-101', title: 'Choir for Strangers', day: 0, start: 18.5, dur: 1.5, weeks: '10 weeks', price: '£96', level: 'All levels', tutor: 'Marisol Quint', left: 6, cap: 40, blurb: 'Learn songs by ear in a room of people who have never met. No reading music, no auditions.', cat: 'Music' },
  { code: 'QS-114', title: 'Letterpress for Beginners', day: 1, start: 10, dur: 3, weeks: '8 weeks', price: '£184', level: 'Beginner', tutor: 'Ada Njoku', left: 3, cap: 10, blurb: 'Set type by hand, ink the press and print your own poster, card and a small book.', cat: 'Making' },
  { code: 'QS-122', title: 'Bread, Slowly', day: 2, start: 18, dur: 2.5, weeks: '6 weeks', price: '£132', level: 'Beginner', tutor: 'Imani Wright', left: 9, cap: 14, blurb: 'Sourdough, rye and the patience to leave them alone. Take a loaf home every week.', cat: 'Food' },
  { code: 'QS-130', title: 'Life Drawing, Open Studio', day: 3, start: 19, dur: 2, weeks: '10 weeks', price: '£80', level: 'All levels', tutor: 'Anselm Ode', left: 14, cap: 20, blurb: 'A relaxed evening with a model, easels and tea. Bring paper; we lend the charcoal.', cat: 'Art' },
  { code: 'QS-141', title: 'Writing the Short Story', day: 4, start: 10.5, dur: 2, weeks: '8 weeks', price: '£120', level: 'Intermediate', tutor: 'Hana Petrova', left: 5, cap: 12, blurb: 'Plot, voice and the ending you did not plan. Read each other’s drafts and send one to a magazine.', cat: 'Writing' },
  { code: 'QS-148', title: 'Furniture Repair Clinic', day: 5, start: 10, dur: 6, weeks: '4 weeks', price: '£160', level: 'All levels', tutor: 'Anselm Ode', left: 2, cap: 8, blurb: 'Bring a broken chair, table or drawer. Leave with it mended and the tools to do it again.', cat: 'Making' },
  { code: 'QS-156', title: 'Beginner’s Ukulele', day: 5, start: 11, dur: 1.5, weeks: '8 weeks', price: '£88', level: 'Beginner', tutor: 'Kofi Mensah', left: 11, cap: 16, blurb: 'Four chords, a hundred songs. Instruments available to borrow for the term.', cat: 'Music' },
  { code: 'QS-163', title: 'Natural Dyes Workshop', day: 6, start: 13, dur: 4, weeks: '1 day', price: '£45', level: 'All levels', tutor: 'Lena Haugen', left: 8, cap: 12, blurb: 'Colour cloth with onion skin, madder and walnut, then learn to make it last.', cat: 'Making' },
];
const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const fmtTime = (s: number, d: number) => { const f = (t: number) => `${String(Math.floor(t)).padStart(2, '0')}:${t % 1 ? '30' : '00'}`; return `${f(s)}–${f(s + d)}`; };

const events: PublicationDesigner = (ctx) => {
  const { W, H, paper, ink, accent, secondary, pageType, pageIndex, seed } = ctx;
  const M = 48, R = W - M, CW = W - 2 * M, soft = mix(ink, .5), hair = alpha(ink, .16), card = '#FFFFFF';
  const catColor: Record<string, string> = { Music: accent, Making: secondary, Food: '#E0B63F', Art: '#7C5CBF', Writing: '#E1566A' };
  const G = rect(0, 0, W, H, paper, { role: 'GROUND', label: 'Page ground' });
  const head = (sec: string): TelaVectorObject[] => obj(circle(M + 8, 34, 8, accent, { label: 'Logo dot' }), circle(M + 22, 34, 8, secondary, { label: 'Logo dot' }), text(M + 40, 24, 300, 'Quay Street Arts Centre', { size: 14, font: 'outfit', weight: 700, color: ink, wrap: false, label: 'Organisation', role: 'LOGO' }), text(R - 320, 28, 320, sec + '  ·  Autumn Term 2026', { size: 10, font: 'dmMono', color: soft, align: 'right', wrap: false, label: 'Running head', role: 'LABEL' }), hr(M, 56, CW, ink, 1.5, { label: 'Head rule' }));
  const foot = (): TelaVectorObject[] => obj(text(verso(pageIndex) ? M : R - 60, H - 36, 60, String(pageIndex * 2 + 3), { size: 10, font: 'dmMono', weight: 500, color: ink, align: verso(pageIndex) ? 'left' : 'right', wrap: false, label: 'Folio', role: 'FOLIO' }), text(verso(pageIndex) ? M + 60 : M, H - 36, 600, 'Enrol at quaystreet.example  ·  Concessions and bursaries available', { size: 10, font: 'dmSans', color: soft, wrap: false, label: 'Running foot', role: 'FOLIO' }));
  const chip = (x: number, y: number, t: string, col: string): { objs: TelaVectorObject[]; right: number } => { const p = pill(x, y, t, { fill: mix(col, .82), color: mix(col, -.45), size: 9, h: 22, font: 'dmMono', weight: 500, tracking: .04, padX: 10 }); return { objs: p.objs, right: p.right }; };
  const seats = (x: number, y: number, w: number, c: Course): TelaVectorObject[] => obj(...meter(x, y, w, 8, c.cap - c.left, c.cap, c.left <= 3 ? secondary : accent, hair), text(x, y + 14, w, c.left <= 3 ? `Only ${c.left} places left` : `${c.left} places left of ${c.cap}`, { size: 10, font: 'dmMono', color: c.left <= 3 ? secondary : soft, weight: c.left <= 3 ? 600 : 400, wrap: false, label: 'Places left', role: 'CAPTION' }));

  switch (pageType) {
    case 'COVER': {
      const blobs = obj(circle(W - 40, 220, 330, accent, { label: 'Cover circle' }), circle(80, H - 140, 220, secondary, { label: 'Cover circle' }), path(40, 730, 380, 150, orn.blobPath(seed, 7, .2), mix(accent, .6), { label: 'Cover blob' }), circle(W - 120, 700, 70, '#E0B63F', { label: 'Cover dot' }));
      const imgs = imageSlot(W - 330, 150, 250, 330, { tone: 'light', shade: alpha(paper, .6), rx: 125, caption: 'Cover photograph', label: 'Cover image' });
      return obj(G, blobs, imgs, text(M, 56, 400, 'Quay Street Arts Centre', { size: 18, font: 'outfit', weight: 700, color: ink, wrap: false, label: 'Organisation', role: 'LOGO' }), text(M, 150, 560, 'Autumn\nTerm', { size: 136, font: 'outfit', weight: 800, color: ink, leading: .88, tracking: -.03, label: 'Cover title', role: 'HEADLINE' }), text(M, 430, 520, '2026', { size: 136, font: 'outfit', weight: 300, color: ink, wrap: false, leading: 1, tracking: -.03, label: 'Cover year', role: 'HERO' }), text(M, 592, 480, '29 September – 4 December', { size: 22, font: 'dmSans', weight: 600, color: ink, wrap: false, label: 'Term dates', role: 'DATELINE' }), text(M, 628, 440, '48 courses and workshops in music, making, food, art and writing. Beginners welcome. Bursaries available.', { size: 16, font: 'dmSans', color: ink, leading: 1.5, label: 'Cover intro', role: 'DECK' }), ...['Music', 'Making', 'Food', 'Art', 'Writing'].reduce<{ x: number; o: TelaVectorObject[] }>((a, c) => { const p = chip(a.x, H - 150, c, catColor[c]); return { x: p.right + 8, o: [...a.o, ...p.objs] }; }, { x: M, o: [] }).o, text(M, H - 90, 400, 'quaystreet.example  ·  0131 555 0147', { size: 14, font: 'dmMono', weight: 500, color: ink, wrap: false, label: 'Contact line', role: 'LABEL' }));
    }
    case 'CONTENTS': {
      const t = text(M, 90, 500, 'What’s on', { size: 72, font: 'outfit', weight: 800, color: ink, wrap: false, tracking: -.02, label: 'Contents title', role: 'HEADLINE' });
      const cats = [['Music', 'Choirs, ukulele, singing for the shy', '6'], ['Making', 'Letterpress, repair, natural dyes', '12'], ['Food', 'Bread, preserves, supper clubs', '18'], ['Art', 'Drawing, painting, printmaking', '22'], ['Writing', 'Stories, poems and memoir', '28']];
      const rows = cats.flatMap(([c, d, pg], i) => { const y = 200 + i * 88; return [circle(M + 20, y + 28, 20, catColor[c], { label: 'Category dot' }), text(M + 58, y + 2, 300, c, { size: 34, font: 'outfit', weight: 700, color: ink, wrap: false, label: 'Category', role: 'HEADLINE' }), text(M + 58, y + 44, 340, d, { size: 13, font: 'dmSans', color: soft, wrap: false, label: 'Category note', role: 'CAPTION' }), text(M + 400, y + 6, 100, pg, { size: 38, font: 'outfit', weight: 300, color: ink, align: 'right', wrap: false, label: 'Page number', role: 'FOLIO' }), hr(M, y + 74, 500, hair, 1, { label: 'Row rule' })]; });
      const cal = table(M + 540, 200, [{ w: 80, font: 'dmMono', size: 10, color: soft }, { w: 130, font: 'dmSans', size: 12, weight: 600 }], [['29 Sep', 'Term begins'], ['27 Oct', 'Half-term break'], ['3 Nov', 'Classes resume'], ['4 Dec', 'Term ends']], { size: 12, font: 'dmSans', color: ink, rule: hair, pad: 8, head: ['Term dates', ''], headFont: 'dmMono', headSize: 9, headColor: accent, headRule: ink, label: 'Term dates' });
      const how = obj(rect(M, 700, CW, 250, accent, { rx: 24, label: 'Enrol panel', role: 'SIDEBAR' }), text(M + 36, 726, 400, 'How to enrol', { size: 36, font: 'outfit', weight: 800, color: '#FFFFFF', wrap: false, role: 'SIDEBAR', label: 'Panel title' }), ...[['1', 'Pick a course', 'Find its code, such as QS-101.'], ['2', 'Choose how', 'Online, by phone, or the form on page 38.'], ['3', 'Pay or ask', 'Fees are per term. Ask about bursaries.']].flatMap(([n, a, b], i) => [text(M + 36 + i * 220, 790, 40, n, { size: 54, font: 'outfit', weight: 300, color: '#FFFFFF', wrap: false, role: 'SIDEBAR', label: 'Step number' }), text(M + 36 + i * 220, 856, 200, a, { size: 16, font: 'outfit', weight: 700, color: '#FFFFFF', wrap: false, role: 'SIDEBAR', label: 'Step title' }), text(M + 36 + i * 220, 880, 190, b, { size: 12.5, font: 'dmSans', color: alpha('#FFFFFF', .9), leading: 1.45, role: 'SIDEBAR', label: 'Step detail' })]));
      return obj(G, head('Contents'), t, rows, cal.objs, how, foot());
    }
    case 'SECTION OPENER': {
      const big = text(M - 8, 80, 700, 'Making', { size: 170, font: 'outfit', weight: 800, color: secondary, wrap: false, leading: 1, tracking: -.04, label: 'Section title', role: 'HEADLINE' });
      const intro = text(M, 300, 500, 'Learn to do it with your hands, in a room full of people who are also getting it wrong. Every course supplies the tools; you supply the mess.', { size: 24, font: 'dmSans', weight: 500, color: ink, leading: 1.4, label: 'Section introduction', role: 'DECK' });
      const feat = obj(rect(M, 520, CW, 380, card, { rx: 24, stroke: hair, strokeWidth: 1, label: 'Featured course card', role: 'SIDEBAR' }), ...imageSlot(M, 520, 290, 380, { tone: 'light', shade: mix(secondary, .8), rx: 24, caption: 'Course photograph', label: 'Featured image' }), label(M + 320, 548, 300, 'Featured course', { size: 10, font: 'dmMono', color: secondary, weight: 500, tracking: .1, transform: 'none', role: 'KICKER' }), text(M + 320, 572, 400, COURSES[1].title, { size: 36, font: 'outfit', weight: 800, color: ink, leading: 1.05, label: 'Course title', role: 'HEADLINE' }), text(M + 320, 656, 380, COURSES[1].blurb, { size: 15, font: 'dmSans', color: ink, leading: 1.5, label: 'Course blurb', role: 'BODY' }), text(M + 320, 744, 160, COURSES[1].price, { size: 40, font: 'outfit', weight: 800, color: ink, wrap: false, label: 'Price', role: 'PRICE' }), text(M + 440, 758, 200, `${COURSES[1].weeks} · Tuesdays`, { size: 12, font: 'dmMono', color: soft, wrap: false, label: 'Schedule', role: 'SPEC' }), ...seats(M + 320, 812, 300, COURSES[1]), ...button(M + 320, 846, 180, 40, 'Enrol now', { fill: secondary, color: '#FFFFFF', font: 'outfit', size: 14, rx: 20 }));
      const others = ['QS-148 Furniture Repair Clinic', 'QS-156 Beginner’s Ukulele', 'QS-163 Natural Dyes Workshop'];
      return obj(G, head('Making'), big, intro, feat, label(M, 930, 300, 'Also in this section', { size: 9, font: 'dmMono', color: soft, tracking: .1, transform: 'none' }), ...others.map((o, i) => text(M + i * 250, 954, 240, o, { size: 11.5, font: 'dmSans', weight: 600, color: ink, wrap: false, label: 'Related course', role: 'LABEL' })), foot());
    }
    case 'PRODUCT GRID': {
      const cw = (CW - 20) / 2, ch = 286;
      const cards = COURSES.slice(0, 6).flatMap((c, i) => { const x = M + (i % 2) * (cw + 20), y = 76 + Math.floor(i / 2) * (ch + 14); const col = catColor[c.cat]; const o: TelaVectorObject[] = [rect(x, y, cw, ch, card, { rx: 20, stroke: hair, strokeWidth: 1, label: 'Course card', role: 'SIDEBAR' }), rect(x, y, cw, 10, col, { rx: 5, label: 'Card bar', role: 'RULE' })]; const k = chip(x + 18, y + 26, c.cat, col); o.push(...k.objs, text(x + cw - 100, y + 28, 82, c.code, { size: 10, font: 'dmMono', color: soft, align: 'right', wrap: false, label: 'Course code', role: 'SKU' })); const tt = text(x + 18, y + 62, cw - 36, c.title, { size: 24, font: 'outfit', weight: 800, color: ink, leading: 1.05, label: 'Course title', role: 'HEADLINE' }); o.push(tt); o.push(text(x + 18, below(tt, 8), cw - 36, c.blurb, { size: 12, font: 'dmSans', color: soft, leading: 1.45, label: 'Course blurb', role: 'BODY' })); o.push(text(x + 18, y + ch - 100, cw - 36, `${DAYS[c.day]}s  ·  ${fmtTime(c.start, c.dur)}`, { size: 12, font: 'dmMono', weight: 500, color: ink, wrap: false, label: 'Schedule', role: 'SPEC' }), text(x + 18, y + ch - 80, cw - 36, `${c.weeks}  ·  ${c.level}  ·  ${c.tutor}`, { size: 11, font: 'dmSans', color: soft, wrap: false, label: 'Course meta', role: 'SPEC' }), ...seats(x + 18, y + ch - 52, cw - 150, c), text(x + cw - 120, y + ch - 62, 102, c.price, { size: 34, font: 'outfit', weight: 800, color: ink, align: 'right', wrap: false, label: 'Price', role: 'PRICE' })); return o; });
      return obj(G, head('Courses'), cards, foot());
    }
    case 'PRODUCT DETAIL': {
      const c = COURSES[0];
      const hero = obj(rect(M, 76, CW, 250, accent, { rx: 28, label: 'Hero band', role: 'ORNAMENT' }), ...imageSlot(R - 300, 76, 300, 250, { tone: 'light', shade: alpha('#FFFFFF', .35), rx: 28, caption: 'Course photograph', label: 'Hero image' }), ...chip(M + 28, 100, c.cat, '#FFFFFF').objs, text(M + 28, 138, 480, c.title, { size: 52, font: 'outfit', weight: 800, color: '#FFFFFF', leading: 1.0, tracking: -.02, label: 'Course title', role: 'HEADLINE' }), text(M + 28, 270, 480, `${c.code}  ·  ${DAYS[c.day]}s  ·  ${fmtTime(c.start, c.dur)}  ·  ${c.weeks}`, { size: 13, font: 'dmMono', weight: 500, color: '#FFFFFF', wrap: false, label: 'Schedule line', role: 'SPEC' }));
      const intro = text(M, 352, 400, c.blurb + ' Each week we learn one new song by ear, building from rounds and call-and-response to full four-part arrangements. The term ends with a public sing at the Centre.', { size: 15, font: 'dmSans', color: ink, leading: 1.55, label: 'Course description', role: 'BODY' });
      const sched = table(M, 500, [{ w: 60, font: 'dmMono', size: 11, color: accent, weight: 500 }, { w: 90, font: 'dmMono', size: 11, color: soft }, { w: 250, font: 'dmSans', size: 12.5 }], [['Wk 1', '29 Sep', 'Warm-ups, rounds and the first song'], ['Wk 2', '6 Oct', 'Call and response from three continents'], ['Wk 3', '13 Oct', 'Harmony by ear: the thirds'], ['Wk 4', '20 Oct', 'Singing quietly, singing loudly'], ['Wk 5', '3 Nov', 'Learning “Small Weather”'], ['Wk 6', '10 Nov', 'Breath, posture and nerves'], ['Wk 7', '17 Nov', 'Arranging a song together'], ['Wk 8', '24 Nov', 'Rehearsal in the hall'], ['Wk 9', '1 Dec', 'Dress rehearsal'], ['Wk 10', '4 Dec', 'Public sing, 7 p.m.']], { size: 12.5, font: 'dmSans', color: ink, rule: hair, pad: 7, head: ['Week', 'Date', 'Focus'], headFont: 'dmMono', headSize: 9, headColor: accent, headRule: ink, label: 'Weekly schedule' });
      const rx = 500, rw = R - rx;
      const tutor = obj(rect(rx, 352, rw, 176, card, { rx: 20, stroke: hair, strokeWidth: 1, label: 'Tutor card', role: 'SIDEBAR' }), ...imageSlot(rx + 20, 372, 64, 64, { tone: 'light', shade: mix(accent, .8), rx: 32, silent: true, label: 'Tutor portrait' }), label(rx + 100, 376, rw - 120, 'Your tutor', { size: 9, font: 'dmMono', color: soft, tracking: .1, transform: 'none', role: 'SIDEBAR' }), text(rx + 100, 394, rw - 120, c.tutor, { size: 20, font: 'outfit', weight: 700, color: ink, wrap: false, role: 'SIDEBAR', label: 'Tutor name' }), text(rx + 20, 450, rw - 40, 'Composer and choir director with 200 community choirs to her name.', { size: 12.5, font: 'dmSans', color: soft, leading: 1.45, role: 'SIDEBAR', label: 'Tutor bio' }));
      const price = obj(rect(rx, 548, rw, 280, card, { rx: 20, stroke: hair, strokeWidth: 1, label: 'Price card', role: 'SIDEBAR' }), text(rx + 24, 566, rw - 48, c.price, { size: 64, font: 'outfit', weight: 800, color: ink, wrap: false, role: 'PRICE', label: 'Price' }), text(rx + 24, 640, rw - 48, 'for the full ten weeks', { size: 13, font: 'dmSans', color: soft, wrap: false, role: 'CAPTION', label: 'Price note' }), ...[['Standard', '£96'], ['Concession', '£58'], ['Bursary', 'Free']].flatMap(([k, v], i) => [text(rx + 24, 676 + i * 26, 120, k, { size: 13, font: 'dmSans', color: ink, wrap: false, role: 'SIDEBAR', label: 'Tier' }), text(rx + rw - 24 - 60, 676 + i * 26, 60, v, { size: 13, font: 'dmMono', weight: 600, color: ink, align: 'right', wrap: false, role: 'PRICE', label: 'Tier price' })]), ...seats(rx + 24, 762, rw - 48, c), ...button(rx + 24, 790, rw - 48, 0 + 28, 'Enrol now', { fill: accent, color: '#FFFFFF', font: 'outfit', size: 13, rx: 14 }));
      const bring = obj(label(M, 840, 300, 'What to bring', { size: 9, font: 'dmMono', color: accent, weight: 500, tracking: .1, transform: 'none' }), hr(M, 858, CW, ink, 1.5), ...['Comfortable shoes, you will be standing', 'A water bottle', 'A recorder on your phone, if you like', 'Nothing else. Songs are provided by ear'].flatMap((t, i) => checkbox(M + (i % 2) * 320, 872 + Math.floor(i / 2) * 30, t, { color: accent, font: 'dmSans', textSize: 13, w: 290, checked: true, accent })));
      return obj(G, head('Course detail'), hero, intro, tutor, sched.objs, price, bring, foot());
    }
    case 'PRICE LIST': {
      const gx = M + 70, gw = CW - 70, colW = gw / 7, y0 = 150, hh = 42, rowH = 56; const hours = [10, 12, 14, 16, 18, 20];
      const grid = obj(...DAYS.map((d, i) => text(gx + i * colW, y0 - 4, colW, d.slice(0, 3).toUpperCase(), { size: 11, font: 'dmMono', weight: 600, color: i > 4 ? secondary : ink, tracking: .1, align: 'center', wrap: false, role: 'LABEL', label: 'Day' })), ...hours.flatMap((h, i) => [hr(M, y0 + hh + i * rowH, CW, hair, 1, { label: 'Hour line' }), text(M, y0 + hh + i * rowH + 4, 60, `${h}:00`, { size: 10.5, font: 'dmMono', color: soft, wrap: false, role: 'CAPTION', label: 'Hour' })]), ...DAYS.slice(1).map((_, i) => vr(gx + (i + 1) * colW, y0 + 16, hours.length * rowH + hh - 16, hair, 1, { label: 'Day divider' })), ...COURSES.flatMap(c => { const lane = c.code === 'QS-156' ? 1 : 0, lanes = c.day === 5 ? 2 : 1, bw = (colW - 8) / lanes; const x = gx + c.day * colW + 4 + lane * bw, y = y0 + hh + (c.start - 10) / 2 * rowH + 2, h = c.dur / 2 * rowH - 4; const col = catColor[c.cat]; return [rect(x, y, bw - (lanes > 1 ? 3 : 0), h, mix(col, .78), { rx: 8, stroke: col, strokeWidth: 1.5, label: 'Timetable block', role: 'SIDEBAR' }), text(x + 6, y + 5, bw - 16, c.title, { size: 10, font: 'outfit', weight: 700, color: mix(col, -.55), leading: 1.1, role: 'SIDEBAR', label: 'Block title' }), ...(h > 52 ? [text(x + 6, y + h - 16, bw - 12, c.code, { size: 8.5, font: 'dmMono', color: mix(col, -.4), wrap: false, role: 'SKU', label: 'Block code' })] : [])]; }));
      const fees = table(M, 560 + 120, [{ w: 110, font: 'dmMono', size: 11, color: accent, weight: 500, role: 'SKU' }, { w: 250, font: 'outfit', size: 14, weight: 600 }, { w: 120, font: 'dmSans', size: 12, color: soft }, { w: 90, font: 'dmSans', size: 12, align: 'right', color: soft }, { w: 120, font: 'outfit', size: 16, weight: 700, align: 'right', role: 'PRICE' }], COURSES.map(c => [c.code, c.title, c.weeks, c.level, c.price]), { size: 12, font: 'dmSans', color: ink, rule: hair, pad: 6, head: ['Code', 'Course', 'Length', 'Level', 'Fee'], headFont: 'dmMono', headSize: 9, headColor: paper, headFill: ink, headRule: ink, label: 'Fees' });
      return obj(G, head('Timetable and fees'), text(M, 74, 700, 'The week at a glance', { size: 40, font: 'outfit', weight: 800, color: ink, wrap: false, label: 'Page title', role: 'HEADLINE' }), grid, text(M, 640, 400, 'Fees for the term', { size: 24, font: 'outfit', weight: 700, color: ink, wrap: false, label: 'Fees title', role: 'HEADLINE' }), fees.objs, foot());
    }
    case 'ORDER FORM': {
      const fl = ['Full name', 'Date of birth', 'Address', 'Postcode', 'Phone', 'Email'].flatMap((f, i) => { const x = M + (i % 2) * (CW / 2 + 10), y = 146 + Math.floor(i / 2) * 56, w = CW / 2 - 10; return [label(x, y, w, f, { size: 9, font: 'dmMono', color: soft, tracking: .08, transform: 'none' }), hr(x, y + 36, w, ink, 1, { label: 'Entry line' })]; });
      const sel = table(M, 340, [{ w: 90, font: 'dmMono', size: 11 }, { w: 330, font: 'dmSans', size: 12 }, { w: 130, font: 'dmMono', size: 11 }, { w: 150, font: 'dmSans', size: 12, align: 'right' }], Array.from({ length: 5 }, () => ['', '', '', '']), { size: 12, font: 'dmSans', color: ink, rule: hair, pad: 9, minH: 34, head: ['Code', 'Course title', 'Start date', 'Fee'], headFont: 'dmMono', headSize: 9, headColor: '#FFFFFF', headFill: accent, headRule: accent, vlines: true, label: 'Course choices' });
      const cy = sel.bottom + 30;
      const opts = obj(label(M, cy, 300, 'Concessions', { size: 10, font: 'dmMono', color: accent, weight: 500, tracking: .1, transform: 'none' }), ...['Under 25', 'Over 65', 'Benefits or low income', 'Full-time student'].flatMap((t, i) => checkbox(M + (i % 2) * 260, cy + 24 + Math.floor(i / 2) * 30, t, { color: ink, font: 'dmSans', textSize: 13, w: 230 })), label(M, cy + 100, 300, 'Payment', { size: 10, font: 'dmMono', color: accent, weight: 500, tracking: .1, transform: 'none' }), ...['Card, we will call you', 'Cheque, enclosed', 'Instalments (three payments)', 'I would like to apply for a bursary'].flatMap((t, i) => checkbox(M + (i % 2) * 260, cy + 124 + Math.floor(i / 2) * 30, t, { color: ink, font: 'dmSans', textSize: 13, w: 240 })), text(M, cy + 206, CW, 'I have read the terms of enrolment. I understand that a course may be cancelled if fewer than six people enrol, in which case fees are refunded in full.', { size: 11.5, font: 'dmSans', italic: true, color: soft, leading: 1.5, label: 'Terms', role: 'FOOTNOTE' }), hr(M, cy + 270, 300, ink, 1, { label: 'Signature line' }), label(M, cy + 278, 300, 'Signature', { size: 9, font: 'dmMono', color: soft, tracking: .08, transform: 'none' }), hr(M + 360, cy + 270, 160, ink, 1, { label: 'Date line' }), label(M + 360, cy + 278, 160, 'Date', { size: 9, font: 'dmMono', color: soft, tracking: .08, transform: 'none' }));
      return obj(G, head('Registration'), text(M, 74, 700, 'Registration form', { size: 44, font: 'outfit', weight: 800, color: ink, wrap: false, label: 'Form title', role: 'HEADLINE' }), fl, sel.objs, opts, foot());
    }
    case 'INDEX': {
      const list = [...COURSES].sort((a, b) => a.title.localeCompare(b.title)).map(c => [c.title, c.code, String(6 + COURSES.indexOf(c) * 3)]);
      const t1 = table(M, 170, [{ w: 250, font: 'outfit', size: 15, weight: 600 }, { w: 90, font: 'dmMono', size: 10.5, color: accent }, { w: 40, font: 'dmMono', size: 11, align: 'right' }], list, { size: 15, font: 'outfit', color: ink, rule: hair, pad: 9, head: ['Course', 'Code', 'Page'], headFont: 'dmMono', headSize: 9, headColor: soft, headRule: ink, label: 'Course index' });
      const tutors = [['Hana Petrova', 'QS-141'], ['Imani Wright', 'QS-122'], ['Kofi Mensah', 'QS-156'], ['Lena Haugen', 'QS-163'], ['Marisol Quint', 'QS-101'], ['Ada Njoku', 'QS-114'], ['Anselm Ode', 'QS-130, QS-148']];
      const t2 = table(M + 440, 170, [{ w: 170, font: 'outfit', size: 15, weight: 600 }, { w: 118, font: 'dmMono', size: 10.5, color: accent, align: 'right' }], tutors, { size: 15, font: 'outfit', color: ink, rule: hair, pad: 9, head: ['Tutor', 'Courses'], headFont: 'dmMono', headSize: 9, headColor: soft, headRule: ink, label: 'Tutor index' });
      const access = obj(rect(M, 600, CW, 190, mix(accent, .9), { rx: 24, label: 'Access panel', role: 'SIDEBAR' }), text(M + 32, 626, 500, 'Come as you are', { size: 32, font: 'outfit', weight: 800, color: ink, wrap: false, role: 'SIDEBAR', label: 'Panel title' }), text(M + 32, 672, 640, 'The Centre is step-free, with a hearing loop in the hall and a quiet room on the first floor. Tell us what you need and we will have it ready. Childcare is available on Saturday mornings.', { size: 15, font: 'dmSans', color: ink, leading: 1.55, role: 'SIDEBAR', label: 'Access text' }));
      return obj(G, head('Index'), text(M, 74, 700, 'Index', { size: 52, font: 'outfit', weight: 800, color: ink, wrap: false, label: 'Index title', role: 'HEADLINE' }), t1.objs, t2.objs, access, foot());
    }
    default: {
      const map = obj(rect(M, 120, CW, 300, mix(accent, .86), { rx: 28, label: 'Map panel', role: 'SIDEBAR' }), ...[0, 1, 2, 3, 4].map(i => hr(M + 20, 150 + i * 56, CW - 40, alpha(accent, .25), 3, { label: 'Street' })), ...[0, 1, 2, 3, 4, 5].map(i => vr(M + 80 + i * 100, 136, 268, alpha(accent, .25), 3, { label: 'Street' })), circle(M + 380, 250, 16, secondary, { label: 'Map pin' }), circle(M + 380, 250, 6, '#FFFFFF', { label: 'Map pin centre' }), text(M + 404, 238, 240, 'Quay Street Arts Centre', { size: 14, font: 'outfit', weight: 700, color: ink, wrap: false, label: 'Map label', role: 'LABEL' }));
      return obj(G, text(M, 56, 700, 'Come and\nmake something.', { size: 70, font: 'outfit', weight: 800, color: ink, leading: .98, tracking: -.02, label: 'Back cover headline', role: 'HEADLINE' }), map, ...[['Visit', '14 Quay Lane, Leith EH6 7AA'], ['Call', '0131 555 0147'], ['Write', 'hello@quaystreet.example'], ['Open', 'Mon–Sat 9–21, Sun 11–17']].flatMap(([k, v], i) => [text(M + (i % 2) * 360, 470 + Math.floor(i / 2) * 90, 300, k.toUpperCase(), { size: 10, font: 'dmMono', color: accent, weight: 500, tracking: .2, wrap: false, label: 'Contact label', role: 'LABEL' }), text(M + (i % 2) * 360, 490 + Math.floor(i / 2) * 90, 340, v, { size: 20, font: 'outfit', weight: 600, color: ink, wrap: false, label: 'Contact', role: 'LABEL' })]), circle(W - 110, H - 140, 120, secondary, { label: 'Back circle' }), circle(W - 40, H - 40, 70, accent, { label: 'Back circle' }), text(M, H - 90, 500, 'quaystreet.example', { size: 24, font: 'outfit', weight: 700, color: ink, wrap: false, label: 'Web address', role: 'LOGO' }), text(M, H - 56, 500, 'Registered charity SC012345. Bursaries made possible by the Friends of Quay Street.', { size: 10, font: 'dmSans', color: soft, label: 'Charity line', role: 'FOOTNOTE' }));
    }
  }
};

export const DESIGNS_CB: Record<string, PublicationDesigner> = { 'cat-parts': parts, 'cat-auction': auction, 'cat-events': events };
export const LESSONS_CB: Record<string, DesignLesson> = {
  'cat-parts': { principle: 'A parts catalog is read with a finger: one order code per row, one column per attribute, and a rhythm of rules and zebra bands that lets the eye land on the right line without thinking.', history: 'Hardware catalogs grew out of the Victorian ironmongers’ price books and Sears-style wish books, then hardened into industrial reference works such as the McMaster-Carr and Grainger volumes. Their dense monospaced tables, exploded-view drawings and numbered callouts come straight from engineering drawing practice.', tryThis: 'Remove the zebra bands and measure how long it takes to find HB-10030. Put them back and measure again.', interestTag: 'Technical documents', related: ['Exploded views', 'Order codes', 'Data tables'] },
  'cat-auction': { principle: 'An auction catalog is a quiet machine for confidence: every lot gets the same ordered facts, in the same place, with an essay to justify the number.', history: 'Fine-art auction catalogues evolved from the printed sale notices of eighteenth-century London houses such as Christie’s and Sotheby’s into the scholarly, illustrated volumes of today. The sequence of lot number, artist, title, medium, dimensions, provenance, literature and estimate has barely changed, because collectors and scholars rely on it.', tryThis: 'Rewrite the catalogue note for lot 13 in 60 words without losing a single fact the reader would need to bid.', interestTag: 'Auction design', related: ['Provenance', 'Catalogue raisonné', 'Cormorant'] },
  'cat-events': { principle: 'A course catalog is a decision aid: colour sorts the subjects, a seats-left meter creates honest urgency, and the timetable lets a person see the week before they choose.', history: 'Adult-education prospectuses began with the evening classes of the mechanics’ institutes in the nineteenth century and the Workers’ Educational Association in 1903. Their modern descendants, from arts-centre term brochures to festival programmes, keep the same pairing of narrative course cards with a grid of days and times.', tryThis: 'Move one course in the timetable so it clashes with another and notice how fast the page tells you.', interestTag: 'Programme design', related: ['Timetables', 'Adult education', 'Wayfinding'] },
};
