import { SignatureWork } from './signatureShaders';

export const SERIES_VI_FLUX: SignatureWork[] = [
  {
    id: "abyssal-silk", n: 61, name: "Abyssal Silk",
    series: "VI", set: "flux", setTitle: "Flux",
    kit3d: false,
    line: "Deep ocean bioluminescent tendrils using triple-nested FBM domain warping.",
    params: [{"name":"Flow","def":0.35},{"name":"Tendrils","def":0.4},{"name":"Sparkle","def":0.5}],
    reacts: [["sub","Expands the tendrils"],["low","Speeds the warp"],["pres","Teal core glow"],["sib","White hot filament bloom"],["air","Background shimmer"],["voice","Sparkle cascade"]],
    body: "// ABYSSAL SILK — Deep ocean bioluminescent tendrils, triple-nested FBM domain warping.\nvec3 silkInk(float t){ return ramp(vec3(0.01,0.02,0.15), vec3(0.0,0.6,0.8), vec3(0.8,0.95,1.0), t); }\n\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  int OCT = plajahOct();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  vec2 p = uv * (1.5 - comp(a.sub, 0.3)*0.2);\n  float t = iTime * (0.2 + iParam0*0.5) + a.low * 0.1;\n  \n  vec2 q = vec2(fbm(p + vec2(0.0, t), OCT), fbm(p + vec2(5.2, 1.3 - t), OCT));\n  vec2 r = vec2(fbm(p + 4.0*q + vec2(1.7, 9.2) + a.sub*0.3, OCT), fbm(p + 4.0*q + vec2(8.3, 2.8) - a.sub*0.3, OCT));\n  vec2 s = vec2(fbm(p + 5.0*r + vec2(t*1.2, t*0.5), OCT), fbm(p + 5.0*r + vec2(-t, t*0.8), OCT));\n  \n  float silk = fbm(p + 6.0*s, OCT);\n  float edge = smoothstep(0.3 - iParam1*0.2, 0.7, silk);\n  \n  vec3 col = silkInk(r.x * 0.5 + a.pres*0.3) * edge;\n  float hot = smoothstep(0.6 - a.sib * 0.2, 1.0, silk);\n  col += vec3(0.8, 0.9, 1.0) * hot * (1.0 + a.sib * 2.0);\n  \n  float sparkles = pow(abs(h21(uv * 100.0 + iTime)), 40.0) * (a.voice + iParam2);\n  col += vec3(0.7, 0.9, 1.0) * sparkles * edge * 5.0;\n  \n  col += silkInk(0.5) * comp(a.sub, 0.3) * 0.3 * exp(-length(uv)*3.0);\n  col += a.air * 0.1 * silkInk(0.2);\n  \n  col *= 1.0 - dot(uv, uv) * 0.7;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "aurora-nebula", n: 62, name: "Aurora Nebula",
    series: "VI", set: "flux", setTitle: "Flux",
    kit3d: false,
    line: "Volumetric 3D nebula fog, raymarched FBM accumulation along a ray.",
    params: [{"name":"Density","def":0.35},{"name":"Drift","def":0.3},{"name":"Hue","def":0.5}],
    reacts: [["sub","Nebula density pulse"],["low","Camera drift speed"],["pres","Hue shift"],["sib","Star flashes"],["air","High frequency ribbon detail"],["voice","Core glow"]],
    body: "// AURORA NEBULA — Volumetric 3D nebula fog, raymarched FBM accumulation.\nvec3 auroraInk(float t){ return ramp(vec3(0.1,0.0,0.2), vec3(0.1,0.8,0.4), vec3(0.8,0.2,0.6), t); }\nfloat mapNebula(vec3 p, float t, float a_air) {\n  float n = fbm(p.xy * 1.5 - vec2(0.0, t * 0.2), 3) * fbm(p.yz * 1.5 + vec2(t * 0.1, 0.0), 3);\n  n += 0.5 * sin(p.x * 2.0 + t) * cos(p.z * 1.5 - t) + a_air * 0.1 * h21(p.xy);\n  return max(0.0, n - 0.2);\n}\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  float t = iTime * (0.1 + iParam1*0.2) + a.low*0.5;\n  vec3 ro = vec3(0.0, 0.0, -3.0 + t);\n  vec3 rd = normalize(vec3(uv, 1.0));\n  ro.xy = rot(t * 0.2) * ro.xy;\n  rd.xy = rot(t * 0.2) * rd.xy;\n  \n  vec3 col = vec3(0.02, 0.0, 0.05);\n  vec3 dustCol = vec3(0.0);\n  float dist = 0.0;\n  \n  for(int i = 0; i < 40; i++) {\n    vec3 p = ro + rd * dist;\n    float dens = mapNebula(p, t, a.air) * (1.0 + comp(a.sub, 0.3) * 1.5 + iParam0);\n    \n    if (dens > 0.01) {\n      float hue = fract(p.y * 0.2 + a.pres * 0.5 + iParam2);\n      vec3 localCol = auroraInk(hue);\n      float alpha = (1.0 - exp(-dens * 0.3));\n      dustCol += localCol * alpha * exp(-dist * 0.15);\n    }\n    dist += 0.15;\n  }\n  \n  col += dustCol;\n  col += pu * 0.3 * vec3(0.8, 0.9, 1.0) * exp(-length(uv)*5.0);\n  float star = step(0.995 - a.sib*0.01, h21(floor(uv*100.0) + floor(iTime*10.0)));\n  col += star * a.sib * 2.0 * vec3(1.0);\n  col += a.voice * 0.4 * auroraInk(0.8) * exp(-length(uv)*2.0);\n  \n  col *= 1.0 - dot(uv, uv) * 0.6;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "tidal-breath", n: 63, name: "Tidal Breath",
    series: "VI", set: "flux", setTitle: "Flux",
    kit3d: false,
    line: "Calm ocean caustics viewed from below, Voronoi-based caustics on sapphire.",
    params: [{"name":"Flow","def":0.3},{"name":"Depth","def":0.4},{"name":"Glint","def":0.5}],
    reacts: [["sub","Breathing depth"],["low","Water flow speed"],["pres","Gold accent glow"],["sib","Surface ripple"],["air","High frequency glint"],["voice","Core caustic brightener"]],
    body: "// TIDAL BREATH — Calm ocean caustics viewed from below.\nvec3 tideInk(float t){ return ramp(vec3(0.01,0.05,0.2), vec3(0.05,0.2,0.6), vec3(0.8,0.9,1.0), t); }\nfloat voronoi(vec2 x) {\n  vec2 n = floor(x), f = fract(x);\n  float res = 8.0;\n  for(int j = -1; j <= 1; j++) {\n    for(int i = -1; i <= 1; i++) {\n      vec2 b = vec2(float(i), float(j));\n      vec2 r = b - f + vec2(h21(n + b), h21(n + b + 1.0));\n      res = min(res, dot(r, r));\n    }\n  }\n  return sqrt(res);\n}\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  float t = iTime * (0.2 + iParam0*0.5);\n  float breath = sin(t + a.sub * 2.0) * 0.5 + 0.5;\n  \n  vec2 p = uv * (3.0 - iParam1 + comp(a.sub, 0.4)*0.5);\n  p += vec2(vnoise(p + t * 0.2 + a.low), vnoise(p - t * 0.3 - a.low)) * (0.5 + a.sib*0.2);\n  \n  float v1 = voronoi(p + t);\n  float v2 = voronoi(p * 1.5 - t * 0.8);\n  float v = v1 * 0.5 + v2 * 0.5;\n  \n  float caustic = pow(1.0 - v, 4.0);\n  vec3 bg = mix(tideInk(0.0), tideInk(0.4), uv.y * 0.5 + 0.5);\n  \n  vec3 causticCol = tideInk(0.9) * caustic;\n  causticCol += vec3(0.8, 0.6, 0.2) * pow(caustic, 8.0) * a.pres * 2.0;\n  causticCol += vec3(1.0) * pow(caustic, 12.0) * (a.air + iParam2) * 2.0;\n  \n  vec3 col = bg + causticCol * (0.8 + breath * 0.4 + a.voice);\n  col += pu * 0.2 * vec3(0.8, 0.9, 1.0) * caustic;\n  \n  col *= 1.0 - dot(uv, uv) * 0.6;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "mercury-bloom", n: 64, name: "Mercury Bloom",
    series: "VI", set: "flux", setTitle: "Flux",
    kit3d: false,
    line: "Liquid chrome fluid, metallic FBM puddling, silver with iridescent rainbow Fresnel sheen.",
    params: [{"name":"Warping","def":0.4},{"name":"Sheen","def":0.5},{"name":"Shadows","def":0.4}],
    reacts: [["sub","Warping force"],["low","Pooling shadows"],["pres","Silver diffuse boost"],["sib","Specular glint"],["air","Surface ripple"],["voice","Iridescent rim rainbow"]],
    body: "// MERCURY BLOOM — Liquid chrome fluid, silver with iridescent rainbow Fresnel sheen.\nvec3 getNormal(vec2 p, int oct) {\n  vec2 e = vec2(0.01, 0.0);\n  float d = fbm(p, oct);\n  return normalize(vec3(fbm(p + e.xy, oct) - d, fbm(p + e.yx, oct) - d, 0.1));\n}\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  int OCT = plajahOct();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  vec2 p = uv * 2.0;\n  float t = iTime * (0.2 + iParam0*0.5);\n  \n  vec2 q = vec2(fbm(p + t, OCT), fbm(p - t, OCT));\n  vec2 r = vec2(fbm(p + 3.0*q + t, OCT), fbm(p + 3.0*q - t, OCT));\n  \n  float f = fbm(p + 4.0*r + a.sub * 0.5 + a.air * 0.2, OCT);\n  vec3 nor = getNormal(p + 4.0*r + a.air*0.1, OCT);\n  \n  vec3 light = normalize(vec3(sin(t), cos(t), 1.0));\n  float diff = max(dot(nor, light), 0.0);\n  float spec = pow(max(dot(reflect(-light, nor), vec3(0.0,0.0,1.0)), 0.0), 32.0);\n  \n  vec3 col = vec3(0.4, 0.42, 0.45) * diff * (1.0 + a.pres) + spec * (1.0 + a.sib * 2.0);\n  \n  float rim = 1.0 - max(dot(nor, vec3(0.0, 0.0, 1.0)), 0.0);\n  vec3 irid = 0.5 + 0.5 * cos(6.28318 * (rim + a.voice + t + vec3(0.0, 0.33, 0.67)));\n  col += irid * rim * 2.0 * (0.5 + a.voice + iParam1);\n  \n  col *= smoothstep(0.1, 0.9 - iParam2*0.4, f + a.low*0.2);\n  col += pu * 0.5 * vec3(1.0) * spec;\n  \n  col *= 1.0 - dot(uv, uv) * 0.5;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "zen-ink", n: 65, name: "Zen Ink Wash",
    series: "VI", set: "flux", setTitle: "Flux",
    kit3d: false,
    line: "Japanese sumi-e ink diffusion, heavy domain-warped FBM, white paper to black ink.",
    params: [{"name":"Diffusion","def":0.4},{"name":"Wash","def":0.5},{"name":"Accents","def":0.4}],
    reacts: [["sub","Ink diffusion spread"],["low","Wash warping"],["pres","Ochre edge brightness"],["sib","Splatter on paper"],["air","Grain"],["voice","Deepens black ink"]],
    body: "// ZEN INK WASH — Japanese sumi-e ink diffusion, heavy domain-warped FBM.\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  int OCT = plajahOct();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  vec2 p = uv * (2.0 + iParam1);\n  float t = iTime * (0.1 + iParam0*0.2);\n  \n  vec2 q = vec2(fbm(p + t, OCT), fbm(p + vec2(1.0), OCT));\n  vec2 r = vec2(fbm(p + 4.0*q + a.sub, OCT), fbm(p + 4.0*q - a.low, OCT));\n  float ink = fbm(p + 6.0*r, OCT);\n  \n  vec3 paper = vec3(0.95, 0.93, 0.9);\n  vec3 inkColor = vec3(0.05, 0.05, 0.06);\n  \n  vec3 col = mix(paper, vec3(0.5, 0.5, 0.52), smoothstep(0.4, 0.7, ink));\n  col = mix(col, inkColor, smoothstep(0.6, 0.9 + a.voice*0.2, ink));\n  \n  float edge = smoothstep(0.5, 0.6, ink) - smoothstep(0.6, 0.7, ink);\n  col += vec3(0.8, 0.5, 0.2) * edge * (a.pres * 2.0 + iParam2);\n  \n  col -= vnoise(uv * 50.0) * (0.05 + a.air*0.1);\n  float splatter = step(0.98 - a.sib*0.02, h21(uv * 20.0 + floor(iTime*12.0)));\n  col = mix(col, inkColor, splatter * a.sib);\n  \n  col = mix(col, inkColor, pu * 0.8 * exp(-length(uv)*5.0));\n  \n  col *= 1.0 - dot(uv, uv) * 0.4;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "ember-cascade", n: 66, name: "Ember Cascade",
    series: "VI", set: "flux", setTitle: "Flux",
    kit3d: false,
    line: "Falling ember particles in thermal convection, layered parallax fields.",
    params: [{"name":"Convection","def":0.4},{"name":"Embers","def":0.5},{"name":"Heat","def":0.3}],
    reacts: [["sub","Upward thermal gust"],["low","Convection warping"],["pres","Amber glow"],["sib","Ember spawn rate"],["air","White sparks"],["voice","Brightens thermal gradient"]],
    body: "// EMBER CASCADE — Falling ember particles in thermal convection.\nfloat embers(vec2 uv, float scale, float t, float a_sib) {\n  uv *= scale;\n  uv.y -= t;\n  vec2 id = floor(uv);\n  vec2 f = fract(uv);\n  float n = h21(id);\n  if (n > 0.1 + a_sib*0.1) return 0.0;\n  vec2 p = vec2(h21(id + 1.0), h21(id + 2.0)) - 0.5;\n  p.x += sin(t * 2.0 + id.y) * 0.3;\n  float d = length(f - 0.5 - p);\n  return 0.01 / d * smoothstep(0.1, 0.0, d);\n}\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  float t = iTime * (0.3 + iParam0*0.5) + a.sub * 1.0;\n  uv.x += fbm(uv * 2.0 + t*0.1, 2) * a.low * 0.2;\n  \n  vec3 bg = vec3(0.05, 0.03, 0.03);\n  bg += vec3(0.2, 0.05, 0.0) * max(0.0, 1.0 - (uv.y + 1.0) * 0.5) * (1.0 + a.voice + iParam2);\n  vec3 col = bg;\n  \n  float e1 = embers(uv, 10.0, t * 1.5, a.sib * iParam1);\n  float e2 = embers(uv + 12.3, 20.0, t * 2.5, a.sib * iParam1);\n  float e3 = embers(uv + 45.6, 30.0, t * 3.5, a.sib * iParam1);\n  \n  vec3 emberCol = vec3(1.0, 0.4, 0.1);\n  float pulse = 1.0 + a.pres * 2.0;\n  col += emberCol * e1 * pulse * 2.0;\n  col += mix(emberCol, vec3(1.0, 0.8, 0.4), 0.5) * e2 * pulse;\n  col += vec3(1.0) * e3 * pulse * 0.5 * (1.0 + a.air * 3.0);\n  \n  col += emberCol * a.air * 0.2;\n  col += pu * 0.4 * vec3(1.0, 0.6, 0.2) * exp(-length(uv)*3.0);\n  \n  col *= 1.0 - dot(uv, uv) * 0.6;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "supernova-plasma", n: 67, name: "Supernova Plasma",
    series: "VI", set: "ignition", setTitle: "Ignition",
    kit3d: false,
    line: "Explosive volumetric plasma burst, expanding shockwave with dense noise.",
    params: [{"name":"Expansion","def":0.4},{"name":"Noise","def":0.5},{"name":"Aberration","def":0.3}],
    reacts: [["sub","Shockwave expansion"],["low","Plasma noise"],["pres","Chromatic aberration"],["sib","Strobe flash"],["air","Outer glow"],["voice","Core heat"]],
    body: "// SUPERNOVA PLASMA — Explosive volumetric plasma burst.\nfloat mapShock(vec3 p, float t, float a_sub) {\n  float d = length(p) - (1.0 + a_sub);\n  d += fbm(p.xy * 3.0 - t, 3) * fbm(p.yz * 3.0 + t, 3) * 1.5;\n  return d;\n}\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  float ca = length(uv) * (0.02 + iParam2*0.05) * a.pres;\n  vec3 ro = vec3(0.0, 0.0, -3.0);\n  vec3 rd = normalize(vec3(uv, 1.0));\n  float t = iTime * (1.0 + iParam0) + a.low;\n  \n  vec3 col = vec3(0.0);\n  float dist = 0.0;\n  for(int i = 0; i < 40; i++) {\n    vec3 p = ro + rd * dist;\n    float d = mapShock(p, t, comp(a.sub, 0.5)*1.5);\n    if (d < 0.01) {\n      float iter = float(i) / 40.0;\n      vec3 plasma = mix(vec3(1.0), vec3(0.1, 0.5, 1.0), smoothstep(0.0, 0.5, iter));\n      plasma = mix(plasma, vec3(1.0, 0.1, 0.8), smoothstep(0.5, 1.0, iter));\n      col = plasma * (1.0 - iter) * (2.0 + a.voice * 2.0);\n      break;\n    }\n    float glow = 0.01 / (0.01 + abs(d));\n    col += vec3(1.0, 0.2, 0.6) * glow * 0.05 * (1.0 + a.air * 2.0);\n    dist += d * 0.5;\n    if (dist > 5.0) break;\n  }\n  \n  col += vec3(1.0) * pow(a.sib, 2.0) * 0.5;\n  col += pu * vec3(1.0, 0.5, 0.8) * exp(-length(uv)*4.0);\n  col.r += a.pres * 0.1 * ca;\n  col.b -= a.pres * 0.1 * ca;\n  \n  col *= 1.0 - dot(uv, uv) * 0.8;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "cyber-vortex", n: 68, name: "Cyber Vortex",
    series: "VI", set: "ignition", setTitle: "Ignition",
    kit3d: false,
    line: "Neon cyberpunk liquid centrifuge, spiral arms in polar coords with FBM distortion.",
    params: [{"name":"Spin","def":0.4},{"name":"Arms","def":0.5},{"name":"Glitch","def":0.3}],
    reacts: [["sub","Centrifuge speed"],["low","Arm thickness"],["pres","Core neon glow"],["sib","Grid highlights"],["air","Glitch offsets"],["voice","Magenta shift"]],
    body: "// CYBER VORTEX — Neon cyberpunk liquid centrifuge, spiral arms in polar coords.\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  int OCT = plajahOct();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  if (a.air > 0.5 && h21(vec2(iTime, uv.y)) > (0.9 - iParam2*0.2)) {\n    uv.x += 0.05 * a.air;\n  }\n  \n  float r = length(uv);\n  float ang = atan(uv.y, uv.x);\n  float t = iTime * (1.0 + iParam0 + a.sub * 2.0);\n  ang += t - r * 3.0;\n  \n  vec2 polar = vec2(ang, r);\n  float noise = fbm(polar * 5.0 + vec2(t, -t), OCT);\n  \n  float arms = sin(ang * 4.0 + noise * 2.0) * 0.5 + 0.5;\n  arms = pow(arms, 4.0 - a.low * 2.0 + iParam1);\n  \n  vec3 cCol = mix(vec3(0.0, 1.0, 1.0), vec3(1.0, 0.0, 1.0), r + a.voice * 0.5);\n  vec3 col = cCol * 0.1 / (r + 0.01) * (1.0 + a.pres * 2.0);\n  col += cCol * arms * (2.0 + a.pres);\n  \n  float grid = abs(fract(r * 10.0 - t * 2.0) - 0.5) * 2.0;\n  col += vec3(1.0) * smoothstep(0.1, 0.0, grid) * arms * (1.0 + a.sib * 3.0);\n  \n  col += pu * 0.5 * vec3(0.0, 1.0, 1.0) * exp(-r * 8.0);\n  \n  col *= 1.0 - dot(uv, uv) * 0.7;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "storm-cell", n: 69, name: "Storm Cell",
    series: "VI", set: "ignition", setTitle: "Ignition",
    kit3d: false,
    line: "Plasma lightning arcs in magnetic field, branching patterns via noise subtraction.",
    params: [{"name":"Activity","def":0.4},{"name":"Branches","def":0.5},{"name":"Corona","def":0.3}],
    reacts: [["sub","Thunderhead density"],["low","Background rumble"],["pres","Pink corona intensity"],["sib","White-blue arcs"],["air","Small branch forks"],["hit","Main strike"]],
    body: "// STORM CELL — Plasma lightning arcs in magnetic field.\nfloat lightning(vec2 uv, float t, float forks) {\n  float d = 1.0;\n  vec2 p = uv;\n  for (int i = 0; i < 4; i++) {\n    p.x += sin(p.y * 5.0 + t) * 0.1;\n    float n = fbm(p * 10.0, 2);\n    d = min(d, abs(p.x + n * (0.2 + forks)));\n    p.y *= 1.2;\n  }\n  return 0.01 / (d + 0.001);\n}\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  float t = iTime * (1.5 + iParam0);\n  vec3 col = vec3(0.02, 0.0, 0.05);\n  \n  float boltPos = (h11(floor(iTime * 4.0)) - 0.5) * 1.5;\n  \n  if (pu > 0.1 || a.sib > 0.3) {\n    vec2 luv = uv;\n    luv.x -= boltPos;\n    float l = lightning(luv, t, a.air * iParam1);\n    vec3 lCol = vec3(0.6, 0.8, 1.0);\n    col += lCol * l * (pu * 3.0 + a.sib * 2.0);\n    col += vec3(1.0, 0.1, 0.6) * l * (0.2 + a.pres + iParam2);\n  }\n  \n  float clouds = fbm(uv * 2.0 + t * 0.1, 3);\n  col += vec3(0.1, 0.05, 0.2) * clouds * (1.0 + a.sub * 2.0 + a.low);\n  \n  col *= 1.0 - dot(uv, uv) * 0.6;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "magma-core", n: 70, name: "Magma Core",
    series: "VI", set: "ignition", setTitle: "Ignition",
    kit3d: false,
    line: "Volcanic lava with Bénard convection, Voronoi cells with FBM distortion.",
    params: [{"name":"Heat","def":0.4},{"name":"Cracks","def":0.5},{"name":"Flow","def":0.3}],
    reacts: [["sub","Crack expansion"],["low","Convection speed"],["pres","Orange lava heat"],["sib","Ash sparks"],["air","Surface cooling"],["voice","Yellow eruption surges"]],
    body: "// MAGMA CORE — Volcanic lava with Bénard convection.\nfloat voronoi(vec2 x) {\n  vec2 n = floor(x), f = fract(x);\n  float res = 8.0;\n  for(int j = -1; j <= 1; j++) {\n    for(int i = -1; i <= 1; i++) {\n      vec2 b = vec2(float(i), float(j));\n      vec2 r = b - f + vec2(h21(n + b), h21(n + b + 1.0));\n      res = min(res, dot(r, r));\n    }\n  }\n  return sqrt(res);\n}\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  int OCT = plajahOct();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  float t = iTime * (0.1 + iParam2*0.2 + a.low * 0.1);\n  vec2 p = uv * 2.0;\n  p += vec2(fbm(p + t, OCT), fbm(p - t, OCT));\n  \n  float v = voronoi(p * 2.0);\n  float crackWidth = 0.05 + a.sub * 0.1 + iParam1 * 0.05;\n  float cracks = smoothstep(crackWidth, 0.0, v);\n  \n  vec3 obsidian = vec3(0.05) * (1.0 - a.air * 0.5);\n  vec3 red = vec3(0.8, 0.1, 0.0);\n  vec3 orange = vec3(1.0, 0.5, 0.0);\n  vec3 yellow = vec3(1.0, 0.9, 0.1);\n  \n  vec3 col = obsidian;\n  if (cracks > 0.0) {\n    float temp = cracks * (1.0 + fbm(p * 5.0 - t * 2.0, 2));\n    col = mix(red, orange, smoothstep(0.2, 0.6, temp));\n    col = mix(col, yellow, smoothstep(0.6, 1.0, temp));\n    col *= (1.0 + a.pres * 1.5 + iParam0);\n  }\n  \n  col += yellow * pow(a.voice, 2.0) * cracks * 3.0;\n  float ash = step(0.98 - a.sib*0.02, h21(uv * 30.0 + t * 10.0));\n  col += ash * vec3(1.0, 0.5, 0.0) * a.sib * 2.0;\n  col += pu * 0.5 * orange * exp(-length(uv)*2.0);\n  \n  col *= 1.0 - dot(uv, uv) * 0.5;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "solar-flare", n: 71, name: "Solar Flare",
    series: "VI", set: "ignition", setTitle: "Ignition",
    kit3d: false,
    line: "Solar surface granulation with flare ejections, Voronoi granules.",
    params: [{"name":"Pulse","def":0.4},{"name":"Heat","def":0.5},{"name":"Flares","def":0.4}],
    reacts: [["sub","Granule pulsing"],["low","Surface heat"],["pres","Flare length"],["sib","Small coronal ejections"],["air","White-hot tips"],["voice","Large flare arch"]],
    body: "// SOLAR FLARE — Solar surface granulation with flare ejections.\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  vec2 p = uv * 5.0;\n  float t = iTime * (0.3 + iParam0*0.2) + a.sub * 0.5;\n  \n  float n = fbm(p + t, 3);\n  vec2 id = floor(p + n);\n  vec2 f = fract(p + n);\n  float d = length(f - 0.5);\n  float granules = smoothstep(0.4, 0.0, d);\n  \n  vec3 surface = mix(vec3(0.8, 0.2, 0.0), vec3(1.0, 0.7, 0.0), granules); \n  surface *= (1.0 + a.low * 1.5 + iParam1);\n  \n  float loop = length(uv - vec2(0.0, -0.5));\n  float arch = abs(loop - (0.5 + a.pres*0.2)); \n  \n  float angle = atan(uv.x, uv.y + 0.5);\n  float flareFlow = fbm(vec2(angle * 5.0, iTime * 2.0), 2);\n  \n  float flare = 0.01 / (arch + 0.01) * flareFlow * (1.0 + iParam2);\n  flare *= smoothstep(0.0, 0.5, uv.y + 0.5); \n  \n  vec3 col = surface;\n  vec3 flareCol = vec3(1.0, 0.9, 0.8) * flare * (1.0 + a.voice * 3.0 + a.sib * 2.0);\n  col += flareCol;\n  col += vec3(1.0) * flare * a.air * 2.0;\n  col += pu * 0.6 * vec3(1.0, 0.8, 0.5) * exp(-length(uv-vec2(0.0, -0.5))*3.0);\n  \n  col *= 1.0 - dot(uv, uv) * 0.6;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  },
  {
    id: "acid-cascade", n: 72, name: "Acid Cascade",
    series: "VI", set: "ignition", setTitle: "Ignition",
    kit3d: false,
    line: "Toxic neon rain through dark void, vertical rain streaks with bloom.",
    params: [{"name":"Intensity","def":0.4},{"name":"Fog","def":0.5},{"name":"Speed","def":0.4}],
    reacts: [["sub","Rain volume"],["low","Acid fog density"],["pres","Splash bloom"],["sib","Rain speed"],["air","Sparse fast streaks"],["voice","Lime highlights"]],
    body: "// ACID CASCADE — Toxic neon rain through dark void.\nfloat drop(vec2 uv, float t, float scale) {\n  uv *= scale;\n  uv.y += t * scale;\n  vec2 id = floor(uv);\n  vec2 f = fract(uv);\n  float speed = h11(id.x) * 0.5 + 0.5;\n  uv.y += t * speed * 5.0;\n  f = fract(uv);\n  float d = length(vec2(f.x - 0.5, (f.y - 0.5) * 0.1));\n  return 0.01 / (d + 0.01) * step(h21(id), 0.1);\n}\nvoid mainImage(out vec4 o, in vec2 C){\n  Aud a = plajahAudio();\n  float pu = plajahPunch();\n  vec2 uv = (C - 0.5*iResolution.xy)/iResolution.y;\n  \n  float t = iTime * (1.0 + iParam2 + a.sib * 2.0);\n  vec3 col = vec3(0.02, 0.05, 0.02);\n  \n  float rainIntensity = 1.0 + a.sub * 3.0 + iParam0;\n  float r1 = drop(uv, t, 10.0);\n  float r2 = drop(uv + 5.1, t, 20.0);\n  float r3 = drop(uv + 12.3, t, 30.0 + a.air * 20.0);\n  float totalRain = (r1 + r2 * 0.5 + r3 * 0.25) * rainIntensity;\n  \n  vec3 green = vec3(0.2, 1.0, 0.3);\n  vec3 yellow = vec3(0.8, 1.0, 0.2);\n  \n  col += green * totalRain;\n  col += yellow * pow(totalRain, 2.0) * a.voice * 2.0;\n  \n  col += green * fbm(uv * 2.0 - vec2(0.0, t * 0.5), 2) * (0.1 + a.low * 0.5 + iParam1 * 0.2);\n  col += pu * 0.5 * green * exp(-length(uv)*3.0);\n  col += a.pres * 0.3 * green * totalRain;\n  \n  col *= 1.0 - dot(uv, uv) * 0.6;\n  col = max(col, 0.0); col = col/(1.0+col*0.72);\n  o = vec4(pow(col, vec3(0.88)), 1.0);\n}"
  }
];
