// AUTO-GENERATED by scripts/genBuildLog.mjs — do not edit by hand.
// Regenerate: npm run changelog:build
export interface BuildLogEntry { hash: string; date: string; time: string; area: string; subject: string; }
export const BUILD_LOG_GENERATED_AT = "2026-09-07T06:14:16.209Z";
export const BUILD_LOG: BuildLogEntry[] = [
  {
    "hash": "3cbc171",
    "date": "2026-09-07",
    "time": "02:13",
    "area": "Melos",
    "subject": "Melos: Music Council + Virtual Composer design + chord/progression repository (P0)"
  },
  {
    "hash": "954af99",
    "date": "2026-09-07",
    "time": "02:09",
    "area": "Docs",
    "subject": "docs(melos): RX-class wave/spectral repair suite design spec"
  },
  {
    "hash": "90efd73",
    "date": "2026-09-07",
    "time": "02:06",
    "area": "Melos",
    "subject": "Melos: add-instrument destination menu (MEKA pad vs independent MIDI track) + send-to-MEKA/Glass"
  },
  {
    "hash": "cef6193",
    "date": "2026-09-07",
    "time": "02:00",
    "area": "Chora",
    "subject": "Chora: Music Locker Phase 1 — unified single-scroll locker (drop tabs + Saved Music)"
  },
  {
    "hash": "96f5e42",
    "date": "2026-09-07",
    "time": "01:44",
    "area": "Fabula",
    "subject": "Fabula: blue local-glow on timeline clips playing off the drive"
  },
  {
    "hash": "1fc9ad3",
    "date": "2026-09-07",
    "time": "01:40",
    "area": "Fabula",
    "subject": "Fabula: proxies-off falls back to local proxy (not cloud); close still-image cloud leak in Local mode"
  },
  {
    "hash": "8d942fe",
    "date": "2026-09-07",
    "time": "01:28",
    "area": "Fabula",
    "subject": "Fabula: disk-first single-file import (persistent handles) + \"Switch to Local\" master toggle"
  },
  {
    "hash": "ccd8ead",
    "date": "2026-09-07",
    "time": "01:14",
    "area": "Fabula",
    "subject": "Fabula: disk-first by default — read originals off the drive, never auto-download from cloud"
  },
  {
    "hash": "7f650ab",
    "date": "2026-09-07",
    "time": "01:02",
    "area": "Fabula",
    "subject": "Fabula: real JKL shuttle — L/J play 1x first (with audio), tap to accelerate 1→2→4→8x, K resets"
  },
  {
    "hash": "99d7cd9",
    "date": "2026-09-07",
    "time": "00:59",
    "area": "Fabula",
    "subject": "Fabula: background conforming yields to playback + scrubbing; conform whole timeline when idle"
  },
  {
    "hash": "83ee640",
    "date": "2026-09-07",
    "time": "00:49",
    "area": "Fabula",
    "subject": "Fabula: lightweight audio (AAC) + picture (WebP) proxies — preview plays light, export stays native"
  },
  {
    "hash": "59a4009",
    "date": "2026-09-07",
    "time": "00:37",
    "area": "Fabula",
    "subject": "Fabula: byte-prefetch upcoming cloud clips to disk so video stops reloading/buffering cold"
  },
  {
    "hash": "d360c50",
    "date": "2026-09-07",
    "time": "00:28",
    "area": "Fabula",
    "subject": "Fabula: reconnect drives at project open so local-first reads the ORIGINAL file off disk"
  },
  {
    "hash": "58797c4",
    "date": "2026-09-07",
    "time": "00:00",
    "area": "Fabula",
    "subject": "Fabula playback: cache cloud audio locally on first stream (local-first)"
  },
  {
    "hash": "f494a56",
    "date": "2026-09-06",
    "time": "23:47",
    "area": "Fabula",
    "subject": "Fabula mixer P4: group submix buses (A-D) with insert FX"
  },
  {
    "hash": "909d207",
    "date": "2026-09-06",
    "time": "23:40",
    "area": "Fabula",
    "subject": "Fabula mixer: peak-hold meters (mirrors Melos)"
  },
  {
    "hash": "3bb3aa4",
    "date": "2026-09-06",
    "time": "23:37",
    "area": "Fabula",
    "subject": "Fabula mixer P6: master Mastering (Era/Engineer) + Spectra EQ"
  },
  {
    "hash": "9e8ec9d",
    "date": "2026-09-06",
    "time": "22:58",
    "area": "Melos",
    "subject": "Melos: fix instrument-channel mixer FX (was reconciled only for audio tracks)"
  },
  {
    "hash": "bb3d0bf",
    "date": "2026-09-06",
    "time": "22:32",
    "area": "Meter Bridge",
    "subject": "Meter Bridge: React component + mount in Melos and Fabula (B)"
  },
  {
    "hash": "8225d37",
    "date": "2026-09-06",
    "time": "22:14",
    "area": "Meter Bridge",
    "subject": "Meter Bridge: shared real-time metering engine (for Melos + Fabula)"
  },
  {
    "hash": "fd2ec73",
    "date": "2026-09-06",
    "time": "22:04",
    "area": "Melos",
    "subject": "Melos composer: hum/sing -> MIDI bridge"
  },
  {
    "hash": "2dd6d68",
    "date": "2026-09-06",
    "time": "22:01",
    "area": "Melos",
    "subject": "Melos composer: expand the progression repository (13 -> 32)"
  },
  {
    "hash": "b478f27",
    "date": "2026-09-06",
    "time": "21:37",
    "area": "Melos",
    "subject": "Melos timeline: per-track height resize (Bitwig-style)"
  },
  {
    "hash": "14010c5",
    "date": "2026-09-06",
    "time": "21:32",
    "area": "Fabula",
    "subject": "Fabula mixer↔Melos P6a: master FX suite"
  },
  {
    "hash": "1ecd380",
    "date": "2026-09-06",
    "time": "20:35",
    "area": "Fabula",
    "subject": "Fabula: make the Audio panels and Color timeline resizable"
  },
  {
    "hash": "530c6c6",
    "date": "2026-09-06",
    "time": "20:32",
    "area": "Fabula",
    "subject": "Fabula mixer↔Melos P5: mount Melos's FX rack on the mixer"
  },
  {
    "hash": "4bb7a3f",
    "date": "2026-09-06",
    "time": "20:23",
    "area": "Fabula",
    "subject": "Fabula mixer↔Melos P3: element-path FX inserts + soft-clip master limiter"
  },
  {
    "hash": "70dd8cd",
    "date": "2026-09-06",
    "time": "19:55",
    "area": "Fabula",
    "subject": "Fabula mixer↔Melos: share Melos's FX core + per-track insert seam (P1-2)"
  },
  {
    "hash": "339814b",
    "date": "2026-09-06",
    "time": "19:32",
    "area": "Fabula",
    "subject": "Fabula audio: keep cross-origin cloud tracks in the mix via proxy fallback"
  },
  {
    "hash": "345cf1b",
    "date": "2026-09-06",
    "time": "19:25",
    "area": "Fabula",
    "subject": "Fabula: move the edit toolset above the timeline it acts on"
  },
  {
    "hash": "1927bf1",
    "date": "2026-09-06",
    "time": "18:47",
    "area": "Fix",
    "subject": "Fix music-locker overlays opening off-screen at page top"
  },
  {
    "hash": "deb486f",
    "date": "2026-09-06",
    "time": "18:20",
    "area": "Fabula",
    "subject": "Fabula FX library: preview effects over real photo stills"
  },
  {
    "hash": "a8271e6",
    "date": "2026-09-06",
    "time": "16:54",
    "area": "Add",
    "subject": "Add Universal Library preview page"
  },
  {
    "hash": "0330df6",
    "date": "2026-09-06",
    "time": "16:51",
    "area": "Command menu bar",
    "subject": "Command menu bar: Plajah gradient icon treatment"
  },
  {
    "hash": "360aed5",
    "date": "2026-09-06",
    "time": "16:51",
    "area": "Fabula",
    "subject": "Fabula: restore mixer audio playback + separate picture proxies from original audio"
  },
  {
    "hash": "36fda0c",
    "date": "2026-09-06",
    "time": "15:49",
    "area": "Keep",
    "subject": "Keep timeline clips and playhead behind track headers"
  },
  {
    "hash": "60d0fb3",
    "date": "2026-09-06",
    "time": "15:23",
    "area": "Use",
    "subject": "Use readable local media first for audio and video recovery"
  },
  {
    "hash": "653946c",
    "date": "2026-09-06",
    "time": "15:03",
    "area": "Chora",
    "subject": "Chora bulk playlist editing + privacy-focused network diagnostics"
  },
  {
    "hash": "5b3c204",
    "date": "2026-09-06",
    "time": "14:58",
    "area": "Stabilize",
    "subject": "Stabilize Fabula playback and introduce shared media runtime"
  },
  {
    "hash": "b03cd95",
    "date": "2026-09-05",
    "time": "23:58",
    "area": "Move",
    "subject": "Move selected Melos clips as a group"
  },
  {
    "hash": "82bbc48",
    "date": "2026-09-05",
    "time": "23:34",
    "area": "Add",
    "subject": "Add marquee selection to timelines and assets"
  },
  {
    "hash": "3bae5af",
    "date": "2026-09-05",
    "time": "23:31",
    "area": "Universal Library",
    "subject": "Universal Library: opaque panel background (was translucent over the editor)"
  },
  {
    "hash": "30675af",
    "date": "2026-09-05",
    "time": "23:29",
    "area": "Standardize",
    "subject": "Standardize multi-select across creative tools"
  },
  {
    "hash": "4669068",
    "date": "2026-09-05",
    "time": "23:22",
    "area": "Unify",
    "subject": "Unify Chora locker playback and FX stage"
  },
  {
    "hash": "086d1e7",
    "date": "2026-09-05",
    "time": "23:13",
    "area": "Fabula",
    "subject": "Fabula: Media Pool reads as project contents; import tools collapse away"
  },
  {
    "hash": "de04cb6",
    "date": "2026-09-05",
    "time": "23:09",
    "area": "Universal Library",
    "subject": "Universal Library: live Personal shelf from the signed-in user's DAM (Phase 3)"
  },
  {
    "hash": "e8ae8e7",
    "date": "2026-09-05",
    "time": "22:55",
    "area": "Melos",
    "subject": "Melos: link each song to its own .dawproject (GrooveDoc)"
  },
  {
    "hash": "61934bb",
    "date": "2026-09-05",
    "time": "22:46",
    "area": "Melos",
    "subject": "Melos Studio: New Song opens a blank timeline (stop auto-resuming a prior groove)"
  },
  {
    "hash": "839d312",
    "date": "2026-09-05",
    "time": "22:33",
    "area": "Universal Library",
    "subject": "Universal Library: mount in Melos, Tela and Fabula (Phase 2b)"
  },
  {
    "hash": "4984271",
    "date": "2026-09-05",
    "time": "21:32",
    "area": "Universal Library",
    "subject": "Universal Library: mount in Plajah Pixels (Phase 2a)"
  },
  {
    "hash": "3fd5af0",
    "date": "2026-09-05",
    "time": "20:58",
    "area": "Universal Library",
    "subject": "Universal Library: shared dockable media/preset viewer (Phase 1)"
  },
  {
    "hash": "90195ce",
    "date": "2026-09-05",
    "time": "18:34",
    "area": "Fix",
    "subject": "fix: persist Melos project audio assets"
  },
  {
    "hash": "8648c0b",
    "date": "2026-09-05",
    "time": "18:09",
    "area": "Feat",
    "subject": "feat: dock Melos library and refine floating controls"
  },
  {
    "hash": "af40c72",
    "date": "2026-09-05",
    "time": "17:32",
    "area": "Melos",
    "subject": "Melos: fix ClipLauncher crash — missing DrumPatternThumb import"
  },
  {
    "hash": "8efb5b0",
    "date": "2026-09-05",
    "time": "17:16",
    "area": "Melos",
    "subject": "Melos: pattern thumbnails in the clip launcher + cover-art gallery for every instrument"
  },
  {
    "hash": "638b43b",
    "date": "2026-09-05",
    "time": "17:00",
    "area": "Feat",
    "subject": "feat: add studio editing history and media reuse"
  },
  {
    "hash": "90b3f62",
    "date": "2026-09-05",
    "time": "16:56",
    "area": "Melos",
    "subject": "Melos: genre patterns and basslines as thumbnail previews"
  },
  {
    "hash": "08e7e9c",
    "date": "2026-09-05",
    "time": "16:34",
    "area": "Pixels",
    "subject": "Plajah Pixels: live animated thumbnails in the library rail"
  },
  {
    "hash": "83da575",
    "date": "2026-09-05",
    "time": "16:21",
    "area": "Fabula",
    "subject": "Fabula FX page: LOTTIE originals show real animated previews"
  },
  {
    "hash": "54429c1",
    "date": "2026-09-05",
    "time": "16:17",
    "area": "Fabula",
    "subject": "Fabula FX page: FILTERS previews show the reference scene under the filter"
  }
];
