// scripts/emitOfxManifest.ts — writes the Forge registry as OFX descriptors for the native shell.
//   npx tsx scripts/emitOfxManifest.ts
//     → rust/fabula-ofx/manifest.json          (human/diff-friendly copy of the descriptors)
//     → rust/fabula-ofx/src/manifest_gen.rs    (static Rust data + one entry trampoline per plugin)
// The Rust crate has NO dependencies and NO build script on purpose: `cargo check` then works
// on machines without a native linker (no MSVC), and the shell carries zero runtime parsing.
// Deterministic output (no timestamps) so both files can be committed and diffed.
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { ofxManifestJson, buildOfxManifest } from '../services/fabula/ofxManifest';

const outDir = resolve(process.cwd(), 'rust/fabula-ofx');
mkdirSync(resolve(outDir, 'src'), { recursive: true });
const json = ofxManifestJson();
writeFileSync(resolve(outDir, 'manifest.json'), json + '\n');
const m = buildOfxManifest();

const rs = (s: string) => JSON.stringify(String(s)); // JSON string escapes are valid Rust string literals for our content
const num = (v: number) => (Number.isFinite(v) ? (Number.isInteger(v) ? `${v}.0` : `${v}`) : '0.0');
let out = '';
out += '// @generated by scripts/emitOfxManifest.ts — do not edit. Run `npm run ofx:manifest`.\n';
out += '#![allow(clippy::all, dead_code)]\nuse crate::ofx::*;\nuse crate::shell::{self, ClipDesc, ParamDesc, PluginDesc};\n\n';
out += `pub const PLUGIN_COUNT: usize = ${m.plugins.length};\n\n`;
m.plugins.forEach((p, i) => {
  const params = p.params.map(q => `    ParamDesc { name: ${rs(q.name)}, label: ${rs(q.label)}, kind: ${rs(q.type)}, default: ${num(q.default)}, min: ${num(q.min)}, max: ${num(q.max)}, display_min: ${num(q.displayMin)}, display_max: ${num(q.displayMax)}, increment: ${q.increment != null ? num(q.increment) : '0.0'}, hint: ${q.hint ? rs(q.hint) : '""'}, options: &[${(q.options || []).map(rs).join(', ')}] },`).join('\n');
  const clips = p.clips.map(c => `ClipDesc { name: ${rs(c.name)}, optional: ${c.optional ? 'true' : 'false'} }`).join(', ');
  const passes = p.kernel ? p.kernel.passes.map(ps => `(${rs(ps.id)}, ${rs(ps.source)})`).join(', ') : '';
  const abi = p.kernel ? p.kernel.paramAbi.map(rs).join(', ') : '';
  out += `static ID_${i}: &[u8] = b${rs(p.pluginIdentifier)}.as_bytes(); // ${p.label}\n`;
  out += `static PARAMS_${i}: &[ParamDesc] = &[\n${params}\n];\n`;
  out += `pub static DESC_${i}: PluginDesc = PluginDesc { identifier: ${rs(p.pluginIdentifier)}, label: ${rs(p.label)}, grouping: ${rs(p.grouping)}, description: ${rs(p.description)}, contexts: &[${p.contexts.map(rs).join(', ')}], clips: &[${clips}], params: PARAMS_${i}, temporal: ${p.temporalClipAccess ? 'true' : 'false'}, kernel_passes: &[${passes}], param_abi: &[${abi}], header_hash: ${p.kernel ? rs(p.kernel.headerHash) : '""'} };\n`;
  out += `unsafe extern "C" fn entry_${i}(action: *const std::os::raw::c_char, handle: *const std::os::raw::c_void, in_args: OfxPropertySetHandle, out_args: OfxPropertySetHandle) -> OfxStatus { shell::dispatch(&DESC_${i}, action, handle, in_args, out_args) }\n`;
  out += `static PLUGIN_${i}: OfxPlugin = OfxPlugin { plugin_api: OFX_IMAGE_EFFECT_PLUGIN_API.as_ptr() as *const _, api_version: 1, plugin_identifier: ID_${i}.as_ptr() as *const _, plugin_version_major: ${p.versionMajor}, plugin_version_minor: ${p.versionMinor}, set_host: Some(shell::set_host), main_entry: Some(entry_${i}) };\n\n`;
});
out += 'pub static PLUGIN_TABLE: &[&OfxPlugin] = &[\n' + m.plugins.map((_, i) => `    &PLUGIN_${i},`).join('\n') + '\n];\n';
out += 'pub static DESCRIPTORS: &[&PluginDesc] = &[\n' + m.plugins.map((_, i) => `    &DESC_${i},`).join('\n') + '\n];\n';
// Identifier byte strings need a trailing NUL for the C ABI — emit them as separate NUL-terminated statics.
out = out.replace(/static ID_(\d+): &\[u8\] = b("[^"]*")\.as_bytes\(\);/g, (_s, i, lit) => `static ID_${i}: &[u8] = concat!(${lit}, "\\0").as_bytes();`);
writeFileSync(resolve(outDir, 'src/manifest_gen.rs'), out);
console.log(`wrote rust/fabula-ofx/manifest.json + src/manifest_gen.rs — ${m.plugins.length} plugins (${m.plugins.filter(p => p.kernel).length} effects, ${m.plugins.filter(p => !p.kernel).length} transitions), ${Math.round(out.length / 1024)} KB of Rust`);
