// genBuildLog — writes data/buildLog.generated.ts from recent git history so the in-app "Recent builds"
// list reflects what actually shipped, even when nobody hand-wrote a curated changelog entry. Safe by
// construction: any failure (no git, shallow clone, etc.) still writes a VALID file and exits 0, so it
// can be wired into a build (`npm run changelog:build`, or a prebuild/CI step) without ever breaking it.
//
// Curated, plain-English notes still live in data/changelog.ts (the source of truth for the update
// notification). This is the raw technical build feed that supplements it — never stale.

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'data', 'buildLog.generated.ts');
const MAX = 60;

// Infer a product area from a conventional-ish commit subject ("Fabula: …", "Melos: …", "docs(melos): …").
function areaOf(subject) {
  const m = subject.match(/^([a-zA-Z][\w .+/-]*?)[:(]/);
  const raw = (m ? m[1] : subject.split(/[\s:]/)[0] || '').trim();
  const key = raw.toLowerCase();
  const map = {
    fabula: 'Fabula', melos: 'Melos', chora: 'Chora', pixels: 'Pixels', lorea: 'Lorea',
    taleo: 'Taleo', reello: 'Reello', terra: 'Terra', docs: 'Docs', tela: 'Tela',
  };
  for (const k of Object.keys(map)) if (key.includes(k)) return map[k];
  return raw ? raw.charAt(0).toUpperCase() + raw.slice(1) : 'General';
}

let entries = [];
try {
  // hash | ISO date | subject — unit-separated to survive punctuation in subjects.
  const raw = execSync(`git log -n ${MAX} --no-merges --pretty=format:%h%x1f%cI%x1f%s`, {
    encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
  });
  entries = raw.split('\n').filter(Boolean).map((line) => {
    const [hash, iso, subject] = line.split('\x1f');
    return { hash, date: (iso || '').slice(0, 10), time: (iso || '').slice(11, 16), area: areaOf(subject || ''), subject: (subject || '').trim() };
  });
} catch {
  entries = []; // no git / shallow / detached — degrade to an empty feed, never throw
}

const banner = `// AUTO-GENERATED by scripts/genBuildLog.mjs — do not edit by hand.\n// Regenerate: npm run changelog:build\n`;
const body = `export interface BuildLogEntry { hash: string; date: string; time: string; area: string; subject: string; }\n`
  + `export const BUILD_LOG_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};\n`
  + `export const BUILD_LOG: BuildLogEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

try {
  writeFileSync(OUT, banner + body, 'utf8');
  console.log(`[genBuildLog] wrote ${entries.length} entries → data/buildLog.generated.ts`);
} catch (e) {
  console.warn('[genBuildLog] could not write build log:', e?.message || e);
}
process.exit(0);
