import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
let staticServer;
let base = process.env.SACRED_PREVIEW_URL || 'http://127.0.0.1:4318/tests/fixtures/sacred-reader-preview.html';
if (process.argv.includes('--static')) {
  staticServer = http.createServer(async (req, res) => {
    try {
      const pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
      const root = path.resolve(pathname.startsWith('/sacred/') ? 'public' : 'tmp/sacred-reader-build');
      const file = path.resolve(root, `.${pathname}`);
      if (!file.startsWith(`${root}${path.sep}`)) { res.writeHead(403); res.end(); return; }
      const content = await fs.readFile(file);
      const type = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.txt': 'text/plain' }[path.extname(file)] || 'application/octet-stream';
      res.writeHead(200, { 'Content-Type': `${type}; charset=utf-8` }); res.end(content);
    } catch { res.writeHead(404); res.end('Missing preview asset'); }
  });
  await new Promise(resolve => staticServer.listen(0, '127.0.0.1', resolve));
  base = `http://127.0.0.1:${staticServer.address().port}/tests/fixtures/sacred-reader-preview.html`;
}
const output = 'tmp/lectio-qa';
await fs.mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  page.setDefaultTimeout(60000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') console.log('Browser:', message.text()); });
  await page.goto(`${base}?tool=concordance`);
  await page.getByText(/100% of chapters available locally/).waitFor();
  await page.getByLabel('Concordance query', { exact: true }).fill('Nicodemus');
  await page.getByText(/John 3:1/, { exact: false }).first().waitFor();
  await page.getByText(/John 7:50/, { exact: false }).first().waitFor();
  await page.getByText(/John 19:39/, { exact: false }).first().waitFor();
  await page.goto(`${base}?tool=words`);
  await page.getByRole('button', { name: /Study word group .*the Word/ }).first().click();
  await page.getByRole('button', { name: 'G3056', exact: true }).click();
  await page.getByText(/Source Greek forms:/).waitFor();
  await page.getByText(/tagged groups in .* verses/).waitFor();
  assert.equal(await page.getByLabel('Lexicon query').inputValue(), 'G3056');
  await page.getByRole('link', { name: 'Verify this dictionary entry' }).waitFor();
  await page.getByLabel('Strong concordance book').selectOption('43');
  await page.getByRole('button', { name: /John 1:1.*3 groups/ }).waitFor();
  await page.getByRole('button', { name: 'Next occurrences' }).click();
  await page.screenshot({ path: `${output}/aligned-word-study.png` });
  await page.goto(`${base}?faith=islam`);
  await page.getByRole('heading', { name: /Al-Faatiha/ }).waitFor();
  assert.equal(await page.locator('main article').count(), 7);
  await page.getByRole('button', { name: 'Study 1:1', exact: true }).click();
  await page.getByPlaceholder('Observations, questions, and sources…').fill('Reader verification note');
  await page.getByRole('button', { name: 'Save passage to research notebook' }).click();
  await page.getByRole('button', { name: 'Notebook', exact: true }).click();
  await page.getByText(/1 saved sources/).waitFor();
  await page.screenshot({ path: `${output}/quran-desktop.png` });
  await page.goto(`${base}?faith=hinduism`);
  await page.getByRole('heading', { name: 'Bhagavad Gita · Chapter 1', exact: true }).waitFor();
  await page.getByLabel('Chapter', { exact: true }).selectOption('18');
  await page.getByRole('heading', { name: 'Bhagavad Gita · Chapter 18', exact: true }).waitFor();
  await page.locator('main article button').first().click();
  await page.getByRole('button', { name: 'Save passage to research notebook' }).click();
  await page.getByRole('button', { name: 'Notebook', exact: true }).click();
  const values = await page.getByLabel('left comparison source').locator('option').evaluateAll(options => options.map(option => option.value).filter(Boolean));
  assert.equal(values.length, 2);
  await page.getByLabel('left comparison source').selectOption(values[0]);
  await page.getByLabel('right comparison source').selectOption(values[1]);
  await page.getByLabel('Similarities', { exact: true }).fill('Test similarity');
  await page.getByLabel('Differences', { exact: true }).fill('Test difference');
  await page.getByLabel('Context and limits', { exact: true }).fill('These are test notes, not theological claims.');
  await page.getByRole('button', { name: 'Save comparison', exact: true }).click();
  await page.getByText(/2 saved sources · 1 comparisons/).waitFor();
  const notebook = await page.evaluate(() => JSON.parse(localStorage.getItem('plajah_sacred_research_v1')));
  assert.equal(notebook.comparisons[0].status, 'personal interpretation');
  assert.ok(notebook.sources.every(source => source.edition && source.sourceUrl));
  await page.goto(`${base}?tool=history`);
  await page.getByRole('heading', { name: /Taylor Prism/ }).waitFor();
  await page.getByRole('button', { name: 'Explore timeline' }).click();
  await page.getByRole('heading', { name: 'Mesha Stele', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Save evidence to notebook' }).first().click();
  await page.screenshot({ path: `${output}/history-desktop.png` });
  await page.goto(`${base}?tool=words`);
  await page.getByLabel('Lexicon query').fill('G3056');
  await page.getByRole('button', { name: /G3056/ }).click();
  await page.getByRole('link', { name: 'Verify this dictionary entry' }).waitFor();
  assert.match(await page.locator('article').innerText(), /λόγος/);
  await page.getByLabel('Original-language dictionary').selectOption('strongshebrew');
  await page.getByLabel('Lexicon query').fill('H7225');
  await page.getByRole('button', { name: /H07225/ }).click();
  await page.getByRole('link', { name: 'Verify this dictionary entry' }).waitFor();
  await page.screenshot({ path: `${output}/word-study-desktop.png` });
  await page.goto(`${base}?faith=buddhism`);
  await page.getByRole('heading', { name: /Dhammapada · 1/ }).waitFor();
  await page.getByLabel('Chapter', { exact: true }).selectOption('26');
  await page.getByRole('button', { name: 'Study Dhammapada 423', exact: true }).waitFor();
  await page.goto(`${base}?tool=compare`);
  await page.getByLabel('Cross-faith search words').fill('love');
  await page.getByRole('button', { name: 'Search source texts', exact: true }).click();
  await page.getByRole('button', { name: 'Save for comparison', exact: true }).first().waitFor();
  assert.ok(await page.locator('article').count() > 0);
  await page.getByLabel('Cross-faith tradition filter').selectOption('hinduism');
  await page.getByRole('button', { name: 'Search source texts', exact: true }).click();
  await page.getByRole('button', { name: 'Save for comparison', exact: true }).first().waitFor();
  assert.match(await page.locator('article').first().innerText(), /hinduism/);
  if (process.argv.includes('--live')) {
    await page.goto(`${base}?faith=judaism`);
    await page.getByRole('heading', { name: 'Genesis 1', exact: true }).waitFor();
    assert.equal(await page.locator('main article').count(), 31);
    await page.screenshot({ path: `${output}/tanakh-desktop.png` });
    await context.route('https://www.sefaria.org/**', route => route.abort());
    await page.getByLabel('Chapter', { exact: true }).selectOption('2');
    await page.getByRole('alert').waitFor();
    assert.equal(await page.locator('main article').count(), 0);
    await page.getByRole('button', { name: 'Retry loading this section', exact: true }).waitFor();
    await context.unroute('https://www.sefaria.org/**');
    await page.goto(`${base}?faith=sikhism`);
    await page.getByRole('heading', { name: 'Sri Guru Granth Sahib Ji · Ang 1', exact: true }).waitFor();
    assert.equal(await page.locator('main article').count(), 23);
    await page.screenshot({ path: `${output}/gurbani-desktop.png` });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${base}?faith=islam`);
  await page.getByRole('heading', { name: /Al-Faatiha/ }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: `${output}/quran-mobile.png` });
  await page.getByRole('button', { name: 'Study 1:1', exact: true }).click();
  assert.equal(await page.getByPlaceholder('Observations, questions, and sources…').inputValue(), 'Reader verification note');
  await context.setOffline(true);
  await page.getByLabel('Surah', { exact: true }).selectOption('2');
  await page.getByRole('heading', { name: /Al-Baqara/ }).waitFor();
  assert.equal(await page.locator('main article').count(), 286);
  await context.setOffline(false);
  assert.deepEqual(errors, []);
  console.log(`PASS: complete KJV text and tagged Strong concordances, passage-to-dictionary links, Quran, Gita and Dhammapada readers${process.argv.includes('--live') ? ', live Jewish and Sikh sources' : ''}, chapter navigation, persistent notes, cross-faith notebook, historical evidence, Hebrew/Greek lexicons, and mobile layout.`);
  await context.close();
} finally { await browser.close(); if (staticServer) await new Promise(resolve => staticServer.close(resolve)); }
