import type { TelaChartStyle } from '../../types';

export type FabulaBroadcastFamily='GLOBAL_TRADITIONS'|'SPORTS'|'IMAGE_MATTE'|'COUNTERCULTURE';
export type FabulaBroadcastAssetKind='OPENER'|'LOWER_THIRD'|'FULL_PAGE'|'BUG'|'STINGER'|'TRANSITION'|'SCORE_STRIP'|'OVERLAY'|'CREDITS';
export interface FabulaBroadcastPack {
  id:string; name:string; family:FabulaBroadcastFamily; region?:string; period?:string;
  premise:string; motionGrammar:string; typography:string; imageTreatment:string;
  palette:[string,string,string,string]; assets:FabulaBroadcastAssetKind[];
  guardrail?:string; collaborationRequired?:boolean; tags:string[]; councilStyle:TelaChartStyle;
}
const STACK:FabulaBroadcastAssetKind[]=['OPENER','LOWER_THIRD','FULL_PAGE','BUG','STINGER','TRANSITION','SCORE_STRIP','OVERLAY','CREDITS'];
const pack=(id:string,name:string,family:FabulaBroadcastFamily,premise:string,motionGrammar:string,typography:string,imageTreatment:string,palette:[string,string,string,string],tags:string[],councilStyle:TelaChartStyle,extra:Partial<FabulaBroadcastPack>={}):FabulaBroadcastPack=>({id,name,family,premise,motionGrammar,typography,imageTreatment,palette,tags,councilStyle,assets:STACK,...extra});

/** Complete broadcast identities, not isolated templates. Each entry resolves to all nine STACK assets. */
export const FABULA_BROADCAST_PACKS:FabulaBroadcastPack[]=[
  // ── Global traditions: specific design histories, never a generic “ethnic” skin. ──
  pack('rinpa-gold-rain','Rinpa · Gold Rain','GLOBAL_TRADITIONS','Asymmetric botanical staging and generous gold field translated into contemporary broadcast depth.','Forms drift on separate shallow planes; pauses and negative space carry more weight than impact.','High-contrast Japanese-capable serif with quiet grotesk metadata.','User images enter as offset screens with mineral-pigment edge bloom.',['#201A19','#C8A64B','#687D58','#EEE4CC'],['japan','rinpa','asymmetry'],'CEREMONIAL',{region:'Japan',period:'Edo period roots · contemporary translation',guardrail:'Use compositional principles and licensed botanical work; never copy a historic screen or signature.'}),
  pack('ukiyo-current','Ukiyo Current','GLOBAL_TRADITIONS','A flat, decisive image system built from cropped waves, horizon bands, and publisher-mark scale.','Layered bands travel at different velocities like printed colors finding registration.','Humanist Japanese gothic with compact seal-scale labels.','Images posterize into three controllable value bands; no imitation artist signatures.',['#EEE0BE','#173A52','#D55B45','#75A3A0'],['japan','ukiyoe','print'],'INK',{region:'Japan',period:'Edo print architecture',guardrail:'Reference print mechanics and cropping—not copied figures, famous waves, or seals.'}),
  pack('sumi-space','Sumi Space','GLOBAL_TRADITIONS','Ink density, paper breath, and ma become a restrained documentary system.','One pressure-sensitive stroke reveals the frame; secondary information arrives only after stillness.','Mincho display with neutral multilingual sans.','User imagery dissolves through an editable ink matte with feathered capillary edges.',['#EFECE3','#171918','#777B72','#A34A3B'],['japan','sumi-e','ma'],'INK',{region:'Japan',period:'Ink-painting lineage · contemporary editorial',guardrail:'Do not simulate calligraphy as decoration; use commissioned marks for language-bearing strokes.'}),
  pack('song-mist','Song Mist Atlas','GLOBAL_TRADITIONS','Monumental landscape depth, shifting scale, and scroll-like reveals organize long-form information.','Camera travels laterally through four atmospheric planes; labels anchor like colophons without imitating them.','Song-capable serif paired with precise modern sans.','Images occupy distant, middle, and near planes with editable mist masks.',['#E7E1D2','#243633','#718076','#A66743'],['china','song','landscape'],'TOPOGRAPHIC',{region:'China',period:'Northern/Southern Song visual principles',guardrail:'Use spatial structure and tonal atmosphere; never fabricate seals or calligraphic inscriptions.'}),
  pack('dancheong-rhythm','Dancheong Rhythm','GLOBAL_TRADITIONS','Architectural color rhythm and interlocking geometry become a vivid modular broadcast grid.','Bands interlock, hinge, and settle with architectural weight rather than ornamental sparkle.','Korean-capable geometric sans with carefully spaced bilingual hierarchy.','Portraits sit inside deep painted-beam frames with replaceable geometric edge modules.',['#173E45','#C64B3D','#D7A73E','#E5DFCC'],['korea','dancheong','architecture'],'BAUHAUS',{region:'Korea',period:'Architectural painting tradition',guardrail:'Use studied structural rhythm; sacred and institution-specific motifs require expert review.'}),
  pack('persian-garden','Persian Garden Index','GLOBAL_TRADITIONS','Nested gardens, precise borders, and jewel-like scale shifts create an information-rich but lucid frame.','Borders draw in four directions; interior fields bloom sequentially from the center.','Persian-capable text system with refined serif display and open captions.','Images become intimate miniatures inside original botanical border systems.',['#132E48','#C69A3B','#8C3D5C','#E9DDBD'],['persian','garden','manuscript'],'CEREMONIAL',{region:'Iran / Persianate traditions',period:'Manuscript and garden design lineages',guardrail:'Do not invent Persian text, signatures, or copy manuscript illustrations; use licensed art and correct shaping.'}),
  pack('zellige-signal','Maghrebi Zellige Signal','GLOBAL_TRADITIONS','Mathematical tile logic becomes an expandable, responsive on-air information lattice.','Stars construct from straight segments, then the lattice opens to reveal footage.','Arabic-capable contemporary sans with restrained Latin companion.','Footage appears behind parametric apertures; pattern density remains user-controlled.',['#0F5660','#233C76','#C69235','#EFE3C4'],['maghreb','zellige','geometry'],'BAUHAUS',{region:'Morocco / Maghreb',period:'Architectural geometric traditions',guardrail:'Geometry is generated, not traced from a monument; religious calligraphy is excluded.'}),
  pack('mashrabiya-light','Mashrabiya Light','GLOBAL_TRADITIONS','Filtered light and architectural privacy screens produce a cinematic Arab-region editorial package.','Apertures rotate by fractions, producing bands of light that cross title and portrait planes.','Arabic-first variable sans with a compatible Latin grotesk.','User images sit behind live lattice mattes with physically plausible light falloff.',['#211B2D','#B98A45','#7B4D3C','#E8D8BB'],['arab','mashrabiya','light'],'GLASS',{region:'Arab world · region-specific variants required',period:'Architectural screen traditions · contemporary translation',guardrail:'Label the regional reference; avoid a single pan-Arab ornamental shorthand.'}),
  pack('mughal-album','Mughal Album Motion','GLOBAL_TRADITIONS','Precise border architecture and botanical margins frame portraits with ceremonial clarity.','Borders assemble hairline by hairline; blossoms move sparingly as page turns create transitions.','South Asian language-capable serif system with fine caption sans.','Portraits use replaceable album-page fields with controllable paper and gold finishes.',['#E9D7AE','#315A4B','#9D3A32','#C69A3A'],['india','mughal','album'],'EDITORIAL',{region:'South Asia',period:'Mughal album-page tradition',guardrail:'Use original borders and licensed botanical studies; do not copy miniatures or sacred/court calligraphy.'}),
  pack('chandigarh-grid','Chandigarh Civic Modern','GLOBAL_TRADITIONS','Indian modernism, exposed concrete, climatic brise-soleil, and civic signage form a bold public-information system.','Sun-breaker modules cast sliding shadows; typography locks into the architectural grid.','Indian multilingual grotesk with monumental numerals.','Images crop through modular façade openings and warm concrete mattes.',['#D8C9AB','#2B3030','#C65135','#3D7B74'],['india','modernism','chandigarh'],'MONO',{region:'India',period:'Post-independence modernism',guardrail:'Credit the architectural lineage; avoid reducing Indian design to ornament.'}),
  pack('sahel-earth-signal','Sahel Earth Signal','GLOBAL_TRADITIONS','Earthen architecture, timber rhythm, and intense shadow produce a tactile West African broadcast system.','Vertical modules rise with structural mass; light sweeps expose hand-built surface variation.','Strong contemporary African grotesk with expansive display scale.','Images integrate into earthen portals with editable relief and shadow depth.',['#4C2E25','#C58A55','#E0C596','#244B49'],['west-africa','sahel','architecture'],'TOPOGRAPHIC',{region:'Sahel · local attribution required',period:'Earthen architectural lineages · contemporary design',guardrail:'Name the location and makers represented; never present a broad region as one culture.'}),
  pack('diaspora-cosmic-score','Diaspora Cosmic Score','GLOBAL_TRADITIONS','Afrofuturist world-building joins ancestral time, speculative technology, and musical structure.','Constellations respond like polyrhythm: independent cycles resolve into one title cadence.','Expressive display face supported by exact technical sans.','Portraits receive spectral rim light, orbital masks, and deep-space parallax.',['#15102B','#6F3CC3','#E6B84A','#18A6A6'],['afrofuturism','diaspora','music'],'PLAJAH',{region:'African diaspora · international',period:'20th century–present',guardrail:'Ground every use in the subject and named creative lineage; this is not a generic “tribal future” skin.'}),
  pack('anishinaabe-led-screen','Anishinaabe-led Living Screen','GLOBAL_TRADITIONS','A collaboration-ready system centered on land, language, continuity, and the commissioned artist’s own visual vocabulary.','Motion timing follows the partner artist’s authored story structure; no stock motif grammar is assumed.','Language-capable typography selected with community reviewers.','User images remain primary; commissioned elements frame rather than appropriate them.',['#E8DFC8','#29453E','#A55235','#55788C'],['indigenous','anishinaabe','collaboration'],'CEREMONIAL',{region:'Anishinaabe communities · partner-specific',period:'Living contemporary practice',collaborationRequired:true,guardrail:'Do not ship borrowed motifs. Requires a named community/artist, license, language review, and cultural permission.'}),
  pack('diné-led-horizon','Diné-led Horizon System','GLOBAL_TRADITIONS','A partner-authored broadcast identity for contemporary Diné stories, sovereignty, and place.','Horizon, pace, and transitions are defined with the commissioned artist; no generic Southwest symbols.','Diné language support and typography reviewed by project partners.','Landscape and portrait imagery are integrated through neutral, editable masks until commissioned assets are supplied.',['#E9DFC9','#40382E','#A7553A','#52737A'],['indigenous','dine','collaboration'],'TOPOGRAPHIC',{region:'Diné Nation · partner-specific',period:'Living contemporary practice',collaborationRequired:true,guardrail:'No weaving, sacred, or ceremonial motifs without explicit artist/community authorization.'}),
  pack('vitruvian-counterpoint','Vitruvian Counterpoint','GLOBAL_TRADITIONS','Classical proportion and musical counterpoint organize a contemporary, multilingual civic identity.','Measured columns enter like voices in a fugue, resolving at a shared harmonic grid.','Inscriptional serif with a lucid humanist text face.','Portraits inhabit proportional frames with stone, vellum, and restrained metal finishes.',['#E9E0CC','#292722','#7D3040','#8A7445'],['council','classical','architecture'],'CLASSICAL',{region:'Mediterranean classical lineages · contemporary synthesis',guardrail:'Use proportional and musical principles, not copied monuments, imperial symbols, or pseudo-Latin decoration.'}),
  pack('wet-paint-insurrection','Wet Paint Insurrection','GLOBAL_TRADITIONS','A rebellious public-wall language where urgent marks interrupt institutional order.','Spray passes overshoot the frame; wet ink runs downward while headlines hold their ground.','Hand-cut caps, marker annotation, and a sturdy reading grotesk.','Images are wheat-pasted, overprinted, crossed out, and selectively reclaimed.',['#E8DDC7','#121212','#F02E2E','#2459C7'],['council','rebel','street-print'],'REBEL',{guardrail:'Use original marks and licensed photography; never reproduce identifiable tags without the writer’s permission.'}),
  pack('post-gravity-protocol','Post-Gravity Protocol','GLOBAL_TRADITIONS','A spatial identity for information that behaves as light, mass, and responsive architecture.','Panels orbit a shared attractor, reconfigure with live state, and preserve real occlusion.','Engineered variable sans with machine-readable microtype.','People and places occupy volumetric windows with physically coherent light and depth.',['#030B12','#EAFBFF','#00EDFF','#925CFF'],['council','futurist','spatial'],'FUTURIST'),
  pack('atlas-of-encounters','Atlas of Encounters','GLOBAL_TRADITIONS','A documentary field-atlas built from routes, captions, material samples, and attributed local voices.','Map lines travel between images; field notes arrive at the pace of observation rather than spectacle.','Multilingual humanist sans with cartographic mono and local script support.','User photographs retain documentary integrity alongside provenance, location, and maker credit.',['#DDD2BA','#29332E','#B64B32','#2E7168'],['council','world-eclectic','documentary'],'WORLD_ATLAS',{guardrail:'Every cultural element carries a named source, maker, place, license, and pronunciation/language review where relevant.'}),
  pack('gilded-tempest','Gilded Tempest','GLOBAL_TRADITIONS','Sculptural folds, operatic chiaroscuro, and luminous ornament create unapologetic dramatic scale.','Forms unfurl in deep Z-space; highlights travel across relief before titles arrive at the emotional crest.','High-contrast display serif with restrained small-cap captions.','Portraits emerge from darkness through sculpted light, fabric-like mattes, and gilded edge detail.',['#130D12','#F1DFC0','#C9A24A','#7E2340'],['council','baroque','sculpture'],'BAROQUE'),
  pack('quiet-monolith','Quiet Monolith','GLOBAL_TRADITIONS','One plane, one aperture, one typographic decision, and enough silence for the subject to remain primary.','A single surface shifts by a few precise pixels; transitions occur through absence and exact cuts.','Neutral neo-grotesk with optical spacing and no decorative display voice.','Images use one rigorously placed crop, natural color, and no unnecessary treatment.',['#F6F5F0','#111111','#CFCFC9','#D33A2F'],['council','minimal','architecture'],'RADICAL_MINIMAL'),

  // ── Sports: twelve genuinely different broadcast identities. ─────────────
  pack('arena-carbon','Arena Carbon','SPORTS','Premium arena spectacle: carbon texture, sharp bevels, and hot edge light.','Plates slam on along camera-facing Z depth; scores snap with four-frame impact holds.','Wide athletic grotesk with condensed numeric companion.','Player cutouts receive controllable stadium rim light and floor reflection.',['#080B10','#E9EDF2','#FF3B30','#1778FF'],['arena','premium','3d'],'BROADCAST'),
  pack('varsity-letterpress','Varsity Letterpress','SPORTS','Campus sport through ink, felt, stitched numbers, and imperfect press registration.','Cards flip like scoreboard slats; ink layers land a few frames apart.','Collegiate slab with utilitarian roster sans.','Photos become duotone halftones with editable paper grain and stitched matte.',['#EFE3CA','#172538','#A62E2A','#C79B43'],['college','letterpress','heritage'],'INK'),
  pack('continental-football','Continental Football','SPORTS','International football elegance with pitch geometry and editorial restraint.','Passing lanes draw into modular fields; possession data glides rather than punches.','Contemporary multilingual grotesk with tabular score numerals.','Players break the grid through soft depth mattes and pitch-line occlusion.',['#081D18','#F0F4EC','#21B675','#E6C84D'],['football','soccer','global'],'SWISS'),
  pack('neon-hardwood','Neon Hardwood','SPORTS','Basketball nightlife: lacquered court reflections, shot-clock urgency, electric color.','Moves pivot on 90-degree court angles; stats bounce once, then lock.','Compressed display caps with huge clock figures.','Player cutouts receive colored arena haze and animated floor reflection.',['#100B22','#F8F4FF','#FF4E8A','#20D5FF'],['basketball','neon','court'],'NEON'),
  pack('scorebook-classic','Scorebook Classic','SPORTS','Baseball’s penciled notation, stitched leather, and broadcast scorekeeping heritage.','Diamond paths trace; inning cells flip with tactile mechanical easing.','News serif, scorebook mono, and engraved numerals.','Photos enter through card windows with paper fiber and archival edge wear.',['#F2E8D0','#24352C','#9E332C','#B98A3B'],['baseball','scorebook','archive'],'EDITORIAL'),
  pack('telemetry-redline','Telemetry Redline','SPORTS','Motorsport precision: timing towers, heat maps, carbon, and velocity traces.','Elements accelerate, overshoot minimally, and brake into exact alignment.','Technical square sans with uncompromising tabular digits.','Cars and drivers integrate with motion-vector streaks and thermal edge maps.',['#090B0E','#EDF2F5','#FF2E32','#00B7E8'],['motorsport','telemetry','speed'],'SPORTS'),
  pack('tale-of-tape','Tale of the Tape','SPORTS','Combat presentation built around measured comparison, tension, and material impact.','Opposing columns approach center; the final stat lands like a bell strike.','Heavy condensed face with clinical measurement labels.','Fighter cutouts use opposing rim colors, sweat highlights, and controlled smoke.',['#111113','#F4EDE3','#D53732','#3076D2'],['combat','boxing','mma'],'BROADCAST'),
  pack('velocity-lanes','Velocity Lanes','SPORTS','Track and field clarity: lanes, split times, photo-finish precision.','Motion sweeps left to right with staggered lane delays and finish-line freezes.','Aerodynamic sans with optical numeric spacing.','Athlete cutouts trail restrained velocity ribbons and lane-colored shadows.',['#102133','#F4F7F9','#FF6B35','#19B5A5'],['track','athletics','timing'],'SPORTS'),
  pack('ice-prism','Ice Prism','SPORTS','Winter sport through crystalline depth, cold spectrum, and clean scoring.','Facets refract across the frame; scores settle with low-friction glide.','Sharp contemporary sans with light-weight labels.','Athletes receive ice reflections, frost mattes, and prismatic edge separation.',['#071824','#F6FBFF','#48C8FF','#8E70FF'],['winter','ice','prism'],'GLASS'),
  pack('tidal-tour','Tidal Tour','SPORTS','Surf and water sport coverage driven by swell, tide, and sun angle.','Score cards rise and recede on long easing curves; transitions curl and reveal.','Rounded sport sans paired with weather-station mono.','Rider cutouts merge with foam mattes and translucent water layers.',['#082831','#EFF8F2','#20A7B5','#F0A447'],['surf','water','tide'],'TOPOGRAPHIC'),
  pack('hologrid-esports','Hologrid Esports','SPORTS','Competitive gaming without generic cyber clutter: lucid spatial brackets and team identity.','Panels rotate in real 3D hierarchy; live state changes travel as light through connections.','Variable display sans with code-adjacent metadata.','Players and avatars occupy glass volumes with reactive team-color lighting.',['#070817','#F5F5FF','#7B5CFF','#00E0CF'],['esports','holographic','bracket'],'FUTURIST'),
  pack('global-games-ceremony','Global Games Ceremony','SPORTS','Ceremonial scale, international clarity, and modular identity for multi-sport events.','Rings and routes converge slowly; event stingers use one decisive kinetic signature.','Multilingual humanist sans with dignified display numerals.','Athletes remain natural-color inside luminous geographic and event fields.',['#102442','#F5F1E8','#E34A4A','#E4B83F'],['multi-sport','ceremony','international'],'CEREMONIAL'),
  pack('olympian-measure','Olympian Measure','SPORTS','Athletic competition framed through classical proportion, human anatomy, and dignified record keeping.','Measured divisions accumulate like a musical score before the final record locks into place.','Inscriptional display serif with exact tabular numerals.','Athletes are staged against proportional fields with restrained bronze and stone depth.',['#E9E1CF','#24231F','#8A5B32','#2E5567'],['council','classical','sport'],'CLASSICAL'),
  pack('street-court-uprising','Street Court Uprising','SPORTS','Pickup intensity, asphalt texture, spray paint, and hand-marked brackets reject polished arena sameness.','Scores snap on like fresh tags; paint trails follow drives and cuts across the court.','Custom marker caps with condensed utility numerals.','Player cutouts carry hard flash, asphalt contact shadow, tape, and overspray.',['#171717','#F2E7D0','#F13A2C','#2B68D1'],['council','rebel','street-sport'],'REBEL'),
  pack('quantum-league','Quantum League','SPORTS','Predictive sport graphics model momentum, probability, and spatial advantage as a living simulation.','Forecast paths branch ahead of players, collapse at decisions, and preserve uncertainty.','Technical variable sans with probability-scaled numerals.','Athletes sit inside responsive lightfields with vector trails and spatial telemetry.',['#020A12','#EAFBFF','#00E7FF','#8D5CFF'],['council','futurist','simulation'],'FUTURIST'),
  pack('nomad-games-atlas','Nomad Games Atlas','SPORTS','A documentary competition package built around place, climate, routes, local language, and participant stories.','Terrain traces reveal the course while photo captions and conditions arrive as field observations.','Multilingual humanist sans, cartographic mono, locally reviewed scripts.','Natural-color documentary imagery includes place, maker, and participant attribution.',['#DCCFB4','#26322E','#BC5037','#2B7069'],['council','world-eclectic','field-sport'],'WORLD_ATLAS',{guardrail:'Local sport traditions require participant/community review; avoid exoticizing place or ritual.'}),
  pack('baroque-victory','Baroque Victory','SPORTS','Operatic lighting, sculpted statistics, banners, and deep spatial reveals turn victory into theatre.','Data unfurls like fabric, trophies rotate through chiaroscuro, and results arrive on the cadence of a fanfare.','High-contrast serif with monumental engraved numerals.','Athletes receive sculpted rim light, volumetric shadow, and restrained metallic relief.',['#120C12','#F0DFC0','#D0A64B','#812841'],['council','baroque','victory'],'BAROQUE'),
  pack('essential-score','Essential Score','SPORTS','Only the score, clock, possession, and one decisive team signal remain.','State changes cut instantly; no transition lasts longer than the information requires.','Neutral grotesk with extremely legible tabular numerals.','Imagery is optional; when present it uses one unambiguous crop and no effects.',['#F7F7F3','#101010','#CBCBC5','#D43C30'],['council','minimal','score'],'RADICAL_MINIMAL'),

  // ── User-image cutout, mask and matte systems. Each carries its own palette; the two that used to cycle here made half the library a colour swap. ──
  ...[
    ['editorial-window','Editorial Window','Modular image apertures crop, pan, and hand off focus.','Grid shutters pass focus in a measured editorial cadence.','neutral editorial serif','EDITORIAL',['#F3EFE6','#1E1B1A','#B8452E','#7C7669']],
    ['paper-rip-reveal','Paper Rip Reveal','A tactile torn edge reveals the subject without hiding the face.','Fiber edges tear directionally, then settle with believable paper weight.','bold grotesk','REBEL',['#1A1917','#F4EFE4','#6B655B','#D8432B']],
    ['silhouette-halo','Silhouette Halo','A rotoscoped subject carries layered color and orbital light.','Independent halo planes orbit, breathe, and resolve behind the silhouette.','display sans','NEON',['#0E0B1E','#F6F1FF','#FF4E8A','#20D5FF']],
    ['contact-sheet-motion','Contact Sheet Motion','Multiple user images advance like a live photographer contact sheet.','Frames advance through a loupe, pause for selection, then re-index.','mono + serif','EDITORIAL',['#1C1B19','#EEE9DC','#D9A441','#D43D2E']],
    ['polaroid-constellation','Instant Print Constellation','Prints drift into a spatial story map with editable captions.','Prints spring into weighted positions and connect as a spatial memory map.','handwritten accent','INK',['#DED6C4','#27241F','#FAF7F0','#C6473A']],
    ['liquid-matte','Liquid Matte','Surface-tension masks merge images in a continuous organic field.','Viscous mattes merge with surface tension, drag, and coherent volume.','soft grotesk','PLAJAH',['#0B0E16','#F2F4F8','#00B7D6','#D13B72']],
    ['prism-portrait','Prism Portrait','A portrait separates through spectral glass planes and recombines.','Optical planes split by wavelength, refract, and precisely recombine.','high-fashion serif','GLASS',['#101013','#F5F2EE','#FF2E6E','#00D4FF']],
    ['film-strip-depth','Film Strip Depth','Frames travel through a physical film path with parallax and gate weave.','Frames travel through a camera gate with transport inertia and subtle weave.','film titling sans','MONO',['#141311','#E8E3D8','#E0A93A','#8A8478']],
    ['architectural-cutout','Architectural Cutout','People move through designed rooms, arches, and depth masks.','Rooms reveal in perspective while the subject crosses true occlusion planes.','architectural grotesk','BAUHAUS',['#EAE4D8','#1E1F22','#C7502F','#3D7B74']],
    ['botanical-occlusion','Botanical Occlusion','Editable foreground leaves integrate portraits into a living scene.','Growth follows stems while leaves respond with layered, low-frequency breeze.','humanist serif','TOPOGRAPHIC',['#F1EBDD','#2B2A25','#4F7A4A','#B7772C']],
    ['ink-collage','Ink Collage','Duotone portraits and ink mattes assemble with print-shop energy.','Ink plates register sequentially, overshoot microscopically, and dry into place.','condensed display','INK',['#EFE7D6','#1A1A1A','#D93A2B','#2F5FB3']],
    ['mirror-stage','Mirror Stage','Reflection, shadow, and floor mattes place cutouts on a dimensional stage.','The stage revolves while reflection, contact shadow, and subject remain coherent.','luxury sans','GLASS',['#07070A','#F2EEE8','#C9A35B','#8FA3B8']],
    ['classical-portico','Classical Portico','Measured columns and a central aperture stage the subject with enduring proportion.','Architectural planes open in contrapuntal sequence and resolve symmetrically.','inscriptional serif','CLASSICAL',['#ECE5D4','#26231D','#8A7A5A','#7A3A3A']],
    ['spray-cutout','Spray Cutout','A sharp subject silhouette collides with fresh aerosol, marker, and paste texture.','Overspray blooms, marker lines chase the contour, then the cutout punches through.','marker caps + utility sans','REBEL',['#F2ECDF','#151515','#FF3D2E','#2B7BE6']],
    ['lightfield-avatar','Lightfield Avatar','A person occupies a volumetric lattice with responsive light and true spatial parallax.','Depth slices scan, predict movement, and reassemble into a luminous whole.','engineered variable sans','FUTURIST',['#050A12','#EAFBFF','#00E1FF','#8B5CFF']],
    ['travelogue-layers','Travelogue Layers','Photographs, routes, tickets, captions, and attributed field material build a lived atlas.','Layers arrive like observations logged across a journey, never as generic souvenir collage.','multilingual humanist + map mono','WORLD_ATLAS',['#D9D0BC','#2A2C2A','#FBF8F1','#B8492F']],
    ['baroque-cameo','Baroque Cameo','A portrait emerges through sculpted shadow, fabric-like folds, and a luminous oval field.','The matte unfurls with operatic depth before a travelling highlight reveals the face.','high-contrast display serif','BAROQUE',['#120C10','#F1DFC0','#D9C8A6','#C9A24A']],
    ['single-aperture','Single Aperture','One exact window gives the image complete authority.','The aperture opens once, holds without ornament, and closes on the editorial beat.','radical neutral grotesk','RADICAL_MINIMAL',['#FAFAF7','#111111','#8E8E88','#D33A2F']]
  ].map(([id,name,premise,motion,typography,councilStyle,palette])=>pack(id as string,name as string,'IMAGE_MATTE',premise as string,motion as string,typography as string,'Drop-zone image, video, or cutout with editable alpha, luma matte, crop, feather, spill, shadow, and color integration.',palette as [string,string,string,string],['user-media','mask','matte','cutout'],councilStyle as TelaChartStyle)),

  // ── Punk, grunge and postmodern: twelve authored print/motion positions. ──
  ...[
    ['punk-xerox-stack','Punk Xerox Stack','Photocopy urgency, torn hierarchy, and deterministic roughness.','Tape lands, type scrambles, toner blooms.','Ransom display + typewriter','REBEL',['#EDE7DA','#111111','#D42B1F','#C8C1B0']],
    ['riot-grrrl-cutpaste','Riot Grrrl Cut & Paste','Personal, political zine intimacy with handwritten interruption.','Cut fragments collide, pause, then annotate.','Marker caps + sturdy grotesk','REBEL',['#F4EEE2','#1B1B1B','#E63E8B','#2E9FD1']],
    ['hardcore-stencil','Hardcore Stencil','One-color venue-poster force with spray edges and hard timing.','Stencil wipes and two-frame impacts.','Industrial stencil','MONO',['#E9E4D8','#131313','#8B8B8B','#5A5A5A']],
    ['postpunk-coldgrid','Post-Punk Cold Grid','Severe negative space, thin rules, and emotionally distant photography.','Rules scan; images hold; type arrives late.','Narrow grotesk + serif','SWISS',['#1B1D22','#D8DAD6','#8C919A','#3E4450']],
    ['grunge-misregister','Grunge Misregister','Offset inks and distressed scale make imperfection structural.','Color plates arrive out of register.','Weathered condensed + slab','INK',['#D9D0B8','#1F1B17','#A8382C','#3F6E64']],
    ['acid-house-flyer','Acid House Flyer','Day-glo event systems, smile-scale circles, and cheap-print intensity.','Radial pulses and photocopier zooms.','Extended grotesk','NEON',['#F5F51A','#151515','#FF2D95','#00C2FF']],
    ['newwave-elastic','New Wave Elastic Type','The Swiss grid bends, layers, and changes scale without losing intent.','Type blocks step across elastic columns.','Experimental sans/serif collision','BAUHAUS',['#F2F0EA','#161616','#E43A2E','#2557C7']],
    ['neo-dada-broadcast','Neo-Dada Broadcast','Chance-looking collage built from deterministic editorial rules.','Found fragments interrupt the frame.','Clashing job-printer voices','REBEL',['#E6DFCE','#121212','#C63A2A','#E3B93A']],
    ['deconstructed-editorial','Deconstructed Editorial','Footnotes, crop marks, and the hidden production system become content.','Annotations chase and revise the headline.','Didone + mono + grotesk','EDITORIAL',['#F7F5EF','#141414','#D13C2F','#8E8B84']],
    ['radical-typeset','Radical Typeset','Type alone creates image, rhythm, and transition.','Words shear, wrap, and become masks.','Variable grotesk extremes','RADICAL_MINIMAL',['#FFFFFF','#111111','#D43C2F','#B8B8B2']],
    ['cyber-collage','Cyber Collage','Browser fragments, scans, and luminous compression artifacts form a lucid stack.','Windows recurse; data tears remain localized.','Pixel mono + contemporary sans','FUTURIST',['#0A0C14','#14172A','#39E6FF','#FF3CD1']],
    ['artschool-assemblage','Art School Assemblage','Sculptural paper, paint, diagram, and found-photo relations.','Objects obey tabletop weight and shadow.','Humanist sans + eccentric serif','BAUHAUS',['#EDE8DE','#25231F','#D96B2B','#3F7FB5']],
    ['black-ink-barricade','Black Ink Barricade','Flooded ink, dry-brush resistance, and hand-cut blocks make every frame feel physically printed.','Ink rolls across the plate, catches paper tooth, and breaks into a hard title stop.','hand-cut wood type + mono','INK',['#ECE6D8','#0F0F0F','#C8352B','#7A7468']],
    ['aerosol-palimpsest','Aerosol Palimpsest','Successive graffiti gestures accumulate, get crossed out, and remain visible as urban memory.','Caps change pressure and distance; drips obey gravity while fresh lines chase older marks.','original graffiti lettering + transit sans','REBEL',['#5A5754','#F6E9C8','#E8562E','#2E86D6']],
    ['wheatpaste-city','Wheatpaste City','Layered posters, paste wrinkles, ripped faces, and municipal surfaces become a moving wall.','Posters slap down with wet weight; corners lift, tear, and expose earlier messages.','oversized poster grotesk + marker notes','REBEL',['#8C8378','#F1E8D2','#D9C79A','#C74A32']],
    ['marker-riot','Marker Riot','Fast permanent-marker drawings, circles, arrows, and underlines argue directly with the image.','Lines draw at human speed, hesitate, double back, and stab the final annotation.','custom marker script + compressed caps','REBEL',['#F5F1E8','#141414','#E23B2E','#2D6ED1']],
    ['toner-avalanche','Toner Avalanche','Overexposed photocopies, crushed blacks, scan streaks, and cascading paper multiply the message.','Copies enlarge generation by generation until toner noise consumes the cut.','distressed grotesk + office mono','REBEL',['#DCD7CB','#111111','#7C776D','#B0AA9C']],
    ['rust-and-noise','Rust & Noise','Corroded metal, paint chips, industrial stamping, and audio-reactive grime form a brutal material system.','Oxide spreads along edges, stamps hit off-register, and noise shakes only loose surface matter.','industrial stamp + narrow slab','MONO',['#2B2622','#C9C2B4','#8A4A22','#D8A03A']]
  ].map(([id,name,premise,motion,typography,councilStyle,palette])=>pack(id as string,name as string,'COUNTERCULTURE',premise as string,motion as string,typography as string,'User images can be photocopied, posterized, torn, overprinted, or kept clean per layer.',palette as [string,string,string,string],['punk','grunge','postmodern','editorial'],councilStyle as TelaChartStyle))
];

export const FABULA_SPORTS_PACKS=FABULA_BROADCAST_PACKS.filter(pack=>pack.family==='SPORTS');
export const FABULA_IMAGE_MATTE_PACKS=FABULA_BROADCAST_PACKS.filter(pack=>pack.family==='IMAGE_MATTE');
export const FABULA_COUNTERCULTURE_PACKS=FABULA_BROADCAST_PACKS.filter(pack=>pack.family==='COUNTERCULTURE');
export const FABULA_GLOBAL_PACKS=FABULA_BROADCAST_PACKS.filter(pack=>pack.family==='GLOBAL_TRADITIONS');
