import type { TelaChartStyle } from '../../types';

export type DataVizGrid='RULES'|'DOTS'|'CROSSHAIR'|'RADIAL'|'CONTOUR'|'NONE';
export type DataVizMark='SHARP'|'ROUNDED'|'CAPSULE'|'DOT'|'TICK'|'FACET';
export interface DataVizArtDirection {
  id:TelaChartStyle; name:string; studioVoice:string; premise:string;
  bg:string; fg:string; muted:string; series:string[]; font:string;
  grid:DataVizGrid; mark:DataVizMark; lineWidth:number; titleCase:'NORMAL'|'UPPER'|'ITALIC';
  texture:'CLEAN'|'PAPER'|'GLOW'|'GLASS'|'INK'|'TOPO'|'SCAN'|'GRAIN';
}

export const DATA_VIZ_ART_DIRECTIONS:Record<TelaChartStyle,DataVizArtDirection>={
  PLAJAH:{id:'PLAJAH',name:'Signal Bloom',studioVoice:'Generative music studio',premise:'Data behaves like an audiovisual signal: blooming, bending, and resolving in time.',bg:'#100B17',fg:'#FAF5FF',muted:'#9F93A9',series:['#D40055','#6B0099','#00DAF3','#FF8C00'],font:'Manrope,Arial,sans-serif',grid:'RADIAL',mark:'ROUNDED',lineWidth:5,titleCase:'NORMAL',texture:'GLOW'},
  SWISS:{id:'SWISS',name:'Index / 01',studioVoice:'International typographic office',premise:'Information hierarchy is the image; one red intervention directs the eye.',bg:'#F6F5F0',fg:'#151515',muted:'#74736E',series:['#E12D2D','#151515','#6B6B66','#C7C6C0'],font:'Arial,Helvetica,sans-serif',grid:'RULES',mark:'SHARP',lineWidth:2,titleCase:'UPPER',texture:'CLEAN'},
  BAUHAUS:{id:'BAUHAUS',name:'Primary Orbit',studioVoice:'Geometric theatre workshop',premise:'Circles, bars, and measured primary forms turn quantities into spatial choreography.',bg:'#EFE3C7',fg:'#171717',muted:'#675F51',series:['#D83A31','#185AA6','#E1B52E','#181818'],font:'Futura,Century Gothic,Arial,sans-serif',grid:'RADIAL',mark:'CAPSULE',lineWidth:7,titleCase:'UPPER',texture:'GRAIN'},
  EDITORIAL:{id:'EDITORIAL',name:'Measured Poise',studioVoice:'Independent magazine art desk',premise:'Fine rules, generous margins, footnotes, and selective color make evidence feel considered.',bg:'#F2EFE8',fg:'#211D20',muted:'#756D73',series:['#7B2CBF','#00A7B5','#C84C58','#C79B32'],font:'Georgia,Times New Roman,serif',grid:'RULES',mark:'TICK',lineWidth:2,titleCase:'ITALIC',texture:'PAPER'},
  NEON:{id:'NEON',name:'Night Current',studioVoice:'Electronic performance collective',premise:'Marks emit light, trails retain musical memory, and the grid feels like an instrument.',bg:'#07091A',fg:'#F3FAFF',muted:'#7582A6',series:['#38F2FF','#FF3CD1','#8D5BFF','#FFD166'],font:'Arial Narrow,Impact,sans-serif',grid:'CROSSHAIR',mark:'DOT',lineWidth:6,titleCase:'UPPER',texture:'GLOW'},
  GLASS:{id:'GLASS',name:'Refractive Field',studioVoice:'Optical-material laboratory',premise:'Translucent volumes, caustic highlights, and real depth turn numbers into physical objects.',bg:'#18202C',fg:'#F7FAFF',muted:'#A5B4C8',series:['#73E0FF','#B791FF','#FF8FB9','#FFD28B'],font:'Avenir Next,Arial,sans-serif',grid:'NONE',mark:'FACET',lineWidth:4,titleCase:'NORMAL',texture:'GLASS'},
  INK:{id:'INK',name:'Quiet Evidence',studioVoice:'Printmaker and data journalist',premise:'Imperfect pressure, handmade dots, and quiet annotation make the dataset feel observed.',bg:'#EEE9DD',fg:'#1D2525',muted:'#626A66',series:['#1D2525','#A33E32','#315E5B','#B4863F'],font:'Georgia,Times New Roman,serif',grid:'NONE',mark:'DOT',lineWidth:4,titleCase:'ITALIC',texture:'INK'},
  TOPOGRAPHIC:{id:'TOPOGRAPHIC',name:'Terrain Signal',studioVoice:'Landscape information atelier',premise:'Contour, elevation, and layered terrain make relationships feel geographic and continuous.',bg:'#102924',fg:'#EAF3DA',muted:'#9CAF98',series:['#A8D59B','#E7C76E','#65B4A4','#D78062'],font:'Trebuchet MS,Arial,sans-serif',grid:'CONTOUR',mark:'ROUNDED',lineWidth:3,titleCase:'NORMAL',texture:'TOPO'},
  SPORTS:{id:'SPORTS',name:'Velocity Readout',studioVoice:'Live competition graphics unit',premise:'Oversized numerals, lane geometry, impact timing, and instant comparison prioritize the moment.',bg:'#071322',fg:'#FFFFFF',muted:'#8EA2B8',series:['#FF4B2B','#00C2FF','#F5C542','#42E087'],font:'Arial Narrow,Impact,sans-serif',grid:'CROSSHAIR',mark:'SHARP',lineWidth:7,titleCase:'UPPER',texture:'SCAN'},
  BROADCAST:{id:'BROADCAST',name:'Live Decision',studioVoice:'Network newsroom design team',premise:'Modular information straps, breaking-state accents, and disciplined density support live storytelling.',bg:'#0D1017',fg:'#F8FAFC',muted:'#8B96A8',series:['#FF304F','#1DB7FF','#7657FF','#FFB329'],font:'Arial,Helvetica,sans-serif',grid:'DOTS',mark:'CAPSULE',lineWidth:4,titleCase:'UPPER',texture:'CLEAN'},
  MONO:{id:'MONO',name:'Absolute Contrast',studioVoice:'Brutalist information publisher',premise:'No decoration, no chromatic hierarchy: scale, weight, and rhythm carry the entire argument.',bg:'#111111',fg:'#F4F4F4',muted:'#929292',series:['#F4F4F4','#A9A9A9','#686868','#393939'],font:'Courier New,monospace',grid:'NONE',mark:'SHARP',lineWidth:2,titleCase:'UPPER',texture:'SCAN'},
  CEREMONIAL:{id:'CEREMONIAL',name:'Constellation',studioVoice:'Civic ceremony and mapping studio',premise:'Routes, rings, and luminous nodes gather separate measures into a dignified shared whole.',bg:'#171329',fg:'#F5EAD0',muted:'#B9A986',series:['#D5AC4E','#744B91','#1E8A8C','#B8525A'],font:'Georgia,Times New Roman,serif',grid:'RADIAL',mark:'FACET',lineWidth:3,titleCase:'NORMAL',texture:'GRAIN'},
  CLASSICAL:{id:'CLASSICAL',name:'Harmonic Measure',studioVoice:'Classical architect and chamber composer',premise:'Proportion, cadence, and contrapuntal series create an ordered score that rewards sustained reading.',bg:'#EEE8D8',fg:'#22201D',muted:'#766E61',series:['#7A263A','#344D69','#9A793A','#53634B'],font:'Baskerville,Georgia,serif',grid:'RULES',mark:'TICK',lineWidth:2,titleCase:'NORMAL',texture:'PAPER'},
  REBEL:{id:'REBEL',name:'Raw Count',studioVoice:'Graffiti writer and radical printmaker',premise:'Sprayed axes, inked marks, crossed-out annotations, and unstable registration turn evidence into confrontation.',bg:'#E7DFCE',fg:'#111111',muted:'#625E56',series:['#EF2B2D','#111111','#2864C7','#E7B52F'],font:'Impact,Arial Black,sans-serif',grid:'NONE',mark:'SHARP',lineWidth:8,titleCase:'UPPER',texture:'INK'},
  FUTURIST:{id:'FUTURIST',name:'Predictive Lattice',studioVoice:'Computational light and spatial-interface studio',premise:'Values inhabit a responsive spatial lattice with forecast trails, depth cues, and machine-legible precision.',bg:'#030B12',fg:'#EAFBFF',muted:'#6D8C99',series:['#00F0FF','#8B5CFF','#4DFF9B','#FF4FA3'],font:'Eurostile,Arial,sans-serif',grid:'DOTS',mark:'FACET',lineWidth:4,titleCase:'UPPER',texture:'GLOW'},
  WORLD_ATLAS:{id:'WORLD_ATLAS',name:'Field Atlas',studioVoice:'Documentary photographer and cultural cartographer',premise:'Mapped routes, field notes, multilingual labels, and material samples situate every number in a specific place.',bg:'#DCD2BB',fg:'#26302D',muted:'#766F61',series:['#B44932','#2E6F68','#C18D35','#4D5E87'],font:'Trebuchet MS,Arial,sans-serif',grid:'CONTOUR',mark:'DOT',lineWidth:3,titleCase:'NORMAL',texture:'PAPER'},
  BAROQUE:{id:'BAROQUE',name:'Grand Chiaroscuro',studioVoice:'Sculptor, opera designer, and cinematic lighting director',premise:'Sweeping curves, deep shadow, gilded highlights, and dramatic reveals make magnitude physically felt.',bg:'#120D12',fg:'#F3E3C1',muted:'#A38C78',series:['#D4A84E','#8B2744','#4A6A75','#E5D2A6'],font:'Didot,Bodoni MT,Georgia,serif',grid:'RADIAL',mark:'CAPSULE',lineWidth:7,titleCase:'ITALIC',texture:'GLASS'},
  RADICAL_MINIMAL:{id:'RADICAL_MINIMAL',name:'One Necessary Line',studioVoice:'Radical minimalist architect and typographer',premise:'A single rule, exact spacing, and one meaningful contrast remove everything that does not carry information.',bg:'#FAFAF7',fg:'#111111',muted:'#8B8B86',series:['#111111','#D43C2F','#B8B8B2','#666661'],font:'Helvetica Neue,Arial,sans-serif',grid:'NONE',mark:'TICK',lineWidth:1,titleCase:'NORMAL',texture:'CLEAN'},
};

export const DATA_VIZ_STYLES=Object.keys(DATA_VIZ_ART_DIRECTIONS) as TelaChartStyle[];
