import React from 'react';
import { ArrowRight, BookOpen, ChevronLeft, Clock3, FileBarChart, FilePlus2, FileText, GraduationCap, Grid3X3, Import, LayoutPanelTop, Newspaper, PenLine, ScrollText, Sparkles } from 'lucide-react';
import type { TelaDocMeta } from '../../types';
import type { TelaStyleEra } from '../../services/telaStyleEraLibrary';
import type { TelaPublicationTemplate } from '../../services/telaPublicationTemplates';
import TelaTemplateGallery from './TelaTemplateGallery';
import type { TelaDesignTemplate } from '../../services/tela/telaTemplateRegistry';

export type TelaHomeDocumentKind = 'BLANK'|'REPORT'|'PROPOSAL'|'RESUME'|'LESSON'|'NEWSLETTER'|'SCREENPLAY'|'RESEARCH'|'BOARD';
const kinds:Array<{id:TelaHomeDocumentKind;name:string;note:string;icon:React.ElementType;wash:string}>=[
  {id:'BLANK',name:'Blank document',note:'A quiet page, ready for anything.',icon:FilePlus2,wash:'#7C3AED'},
  {id:'REPORT',name:'Report',note:'Structured findings and recommendations.',icon:FileBarChart,wash:'#2563EB'},
  {id:'PROPOSAL',name:'Proposal',note:'Frame an idea and make its case.',icon:ScrollText,wash:'#D40055'},
  {id:'RESUME',name:'Résumé & portfolio',note:'Present work, experience, and voice.',icon:FileText,wash:'#0F9F8F'},
  {id:'LESSON',name:'Lesson plan',note:'Objectives, activities, and assessment.',icon:GraduationCap,wash:'#E07819'},
  {id:'NEWSLETTER',name:'Newsletter',note:'An editorial rhythm for your community.',icon:Newspaper,wash:'#A33BC2'},
  {id:'SCREENPLAY',name:'Script treatment',note:'Story, characters, beats, and scenes.',icon:PenLine,wash:'#C13939'},
  {id:'RESEARCH',name:'Research notes',note:'Sources, questions, evidence, and synthesis.',icon:BookOpen,wash:'#34715C'},
  {id:'BOARD',name:'Freeform board',note:'Arrange pages, references, and systems.',icon:Grid3X3,wash:'#5056B8'},
];

export default function TelaHome({recent,onOpen,onCreate,onChooseStyle,onChoosePublication,onChooseTemplate,onImport,onBack}:{recent:TelaDocMeta[];onOpen:(id:string)=>void;onCreate:(kind:TelaHomeDocumentKind)=>void;onChooseStyle:(style:TelaStyleEra)=>void;onChoosePublication:(template:TelaPublicationTemplate)=>void;onChooseTemplate:(template:TelaDesignTemplate)=>void;onImport:()=>void;onBack?:()=>void}) {
  return <div className="flex-1 h-screen overflow-y-auto custom-scrollbar text-white" style={{background:'radial-gradient(circle at 75% -10%,rgba(212,0,85,.22),transparent 32%),radial-gradient(circle at 10% 20%,rgba(107,0,153,.23),transparent 30%),linear-gradient(160deg,#100A18 0%,#08070B 56%,#0B0810 100%)'}}>
    <header className="sticky top-0 z-30 h-16 px-4 sm:px-7 flex items-center gap-3 backdrop-blur-2xl" style={{background:'rgba(10,7,14,.72)',borderBottom:'1px solid rgba(255,255,255,.08)'}}>{onBack&&<button onClick={onBack} className="grid place-items-center w-9 h-9 rounded-[11px] text-white/65 bg-white/[.05] border border-white/[.08]"><ChevronLeft size={16}/></button>}<span className="grid place-items-center w-9 h-9 rounded-[11px]" style={{background:'linear-gradient(135deg,#6B0099,#D40055,#FF8A00)'}}><LayoutPanelTop size={17}/></span><div><div className="font-display italic text-[1.08rem] leading-none">Tela</div><div className="mt-1 text-[8px] font-black tracking-[.16em] text-white/28">DOCUMENT STUDIO</div></div><button onClick={onImport} className="ml-auto h-9 px-3 flex items-center gap-2 rounded-[10px] text-[.68rem] font-bold text-white/65 bg-white/[.05] border border-white/[.09]"><Import size={13}/>Import</button><button onClick={()=>onCreate('BLANK')} className="h-9 px-4 flex items-center gap-2 rounded-[10px] text-[.68rem] font-black" style={{background:'linear-gradient(135deg,#6B0099,#D40055)'}}><FilePlus2 size={13}/>New document</button></header>
    <main className="mx-auto max-w-[1440px] px-4 sm:px-7 pb-20">
      <section className="pt-12 pb-9"><div className="inline-flex items-center gap-2 text-[9px] font-black tracking-[.2em] text-fuchsia-200/65"><Sparkles size={13}/> MAKE A PLACE FOR THE IDEA</div><div className="mt-3 flex flex-col lg:flex-row lg:items-end gap-5"><div className="mr-auto"><h1 className="font-display italic text-[clamp(2.3rem,5vw,4.8rem)] leading-[.9] tracking-[-.035em]">What will you make<br/><span className="text-transparent bg-clip-text" style={{backgroundImage:'linear-gradient(90deg,#D8B4FE,#FF76A8,#FFB05B)'}}>clear and beautiful?</span></h1><p className="mt-5 max-w-xl text-[.82rem] leading-relaxed text-white/45">Begin with the shape of your work, return to something in progress, or borrow a design language from history and make it unmistakably yours.</p></div><div className="hidden lg:block w-[280px] p-4 rounded-[18px]" style={{background:'linear-gradient(145deg,rgba(255,255,255,.08),rgba(255,255,255,.025))',border:'1px solid rgba(255,255,255,.1)'}}><div className="text-[9px] font-black tracking-[.14em] text-white/30">ARIA, BESIDE YOU</div><p className="mt-2 text-[.7rem] leading-relaxed text-white/55">Ask for structure, a design critique, a historical reference study, or help finding the last ten percent.</p></div></div></section>
      <section><div className="flex items-center gap-3 mb-4"><h2 className="font-display italic text-[1.3rem]">Start by document type</h2><span className="h-px flex-1 bg-white/[.08]"/></div><div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-3">{kinds.map(({id,name,note,icon:Icon,wash})=><button key={id} onClick={()=>onCreate(id)} className="group min-h-[145px] p-4 rounded-[18px] text-left transition-all hover:-translate-y-1" style={{background:`radial-gradient(circle at 100% 0%,${wash}32,transparent 45%),rgba(255,255,255,.045)`,border:'1px solid rgba(255,255,255,.1)',boxShadow:'0 16px 40px rgba(0,0,0,.16)'}}><span className="grid place-items-center w-9 h-9 rounded-[11px]" style={{background:`${wash}32`,color:wash}}><Icon size={16}/></span><div className="mt-5 flex items-center gap-2 text-[.78rem] font-extrabold text-white">{name}<ArrowRight size={12} className="ml-auto opacity-0 -translate-x-1 group-hover:opacity-70 group-hover:translate-x-0 transition-all"/></div><p className="mt-1 text-[.62rem] leading-relaxed text-white/35">{note}</p></button>)}</div></section>
      <section className="mt-12"><div className="flex items-center gap-3 mb-4"><h2 className="font-display italic text-[1.3rem]">Recent documents</h2><span className="h-px flex-1 bg-white/[.08]"/><span className="text-[9px] text-white/25">{recent.length} saved</span></div>{recent.length?<div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">{recent.slice(0,8).map((doc,index)=><button key={doc.id} onClick={()=>onOpen(doc.id)} className="group flex items-center gap-3 p-3 rounded-[15px] text-left bg-white/[.035] border border-white/[.085] hover:bg-white/[.065]"><span className="grid place-items-center w-12 h-14 rounded-[9px] text-white/70" style={{background:index%3===0?'linear-gradient(145deg,#6B0099,#30103E)':index%3===1?'linear-gradient(145deg,#174B65,#142333)':'linear-gradient(145deg,#9B3D2E,#382019)'}}><FileText size={17}/></span><span className="min-w-0"><strong className="block truncate text-[.72rem] text-white/85">{doc.title||'Untitled document'}</strong><span className="mt-1 flex items-center gap-1 text-[8px] text-white/28"><Clock3 size={9}/>{new Date(doc.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric',year:doc.updatedAt<Date.now()-31_536_000_000?'numeric':undefined})}</span></span><ArrowRight size={12} className="ml-auto text-white/15 group-hover:text-white/50"/></button>)}</div>:<button onClick={()=>onCreate('BLANK')} className="w-full py-9 rounded-[18px] text-center text-[.72rem] text-white/35 border border-dashed border-white/[.13]">Your recent documents will gather here. Start the first one.</button>}</section>
      <section className="mt-14"><div className="mb-5"><div className="text-[9px] font-black tracking-[.18em] text-fuchsia-200/55">TEMPLATE GALLERY</div><h2 className="mt-1 font-display italic text-[1.8rem]">Designed starting points, with a lesson in each</h2><p className="mt-2 text-[.7rem] text-white/38">Design-history documents, magazines, books, comics, posters, social, presentations and Fabula lower thirds — every page editable, every style with its history and a way to keep learning on Plajah.</p></div><TelaTemplateGallery onUse={onChooseTemplate}/></section>
    </main>
  </div>;
}
