import React, { forwardRef, Suspense, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import { Canvas, useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { clone as cloneSkinned } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { MascotRig, type FurQuality, type MascotMood, type MascotReaction } from './mascotRuntime';

/**
 * PlajahMascot — the rigged 3D Chora / Reello on any page.
 *
 * Models, clips and props are generated by scripts/blender/build_mascots.py:
 *   public/models/mascots/{chora,reello}.glb   (Draco — decoder at /draco/)
 *   public/models/mascots/props/{book,camera}.glb   (interchangeable, attach to the `prop` socket)
 * All shading, spring physics and hand-hold IK live in ./mascotRuntime (shared with the preview tooling).
 *
 *   <PlajahMascot who="chora" mood="listen" energy={streak / 10} prop="book" ref={coach} />
 *   coach.current?.react('nod_yes')
 *
 * Inside an existing <Canvas>, use <MascotModel .../> instead of the self-contained widget.
 */

export type MascotWho = 'chora' | 'reello';
export type { MascotMood, MascotReaction, FurQuality };
export interface MascotHandle { react: (r: MascotReaction) => void }

export const MASCOT_URL = (who: MascotWho) => `/models/mascots/${who}.glb`;
export const PROP_URL = (name: string) => `/models/mascots/props/${name}.glb`;
const DRACO = '/draco/';

/** Voca → mascot. One place so every reading surface reacts the same way. */
export type VocaEvent = 'start' | 'word_correct' | 'word_miss' | 'coaching' | 'comeback' | 'page_done' | 'unclear';
export function mascotCue(e: VocaEvent): { mood?: MascotMood; react?: MascotReaction } {
  switch (e) {
    case 'start': return { mood: 'listen', react: 'wave' };
    case 'word_correct': return { mood: 'listen' };
    case 'comeback': return { mood: 'listen', react: 'nod_yes' };
    case 'word_miss': return { mood: 'encourage', react: 'almost' };
    case 'coaching': return { mood: 'encourage' };
    case 'unclear': return { mood: 'think' };          // noise is never "wrong": the coach just leans in
    case 'page_done': return { mood: 'idle', react: 'cheer' };
  }
}

function prefersReducedMotion() {
  return typeof window !== 'undefined' && !!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
}

/** Phones/TV get lighter fur; desktop gets the full shell stack. */
export function defaultFur(): FurQuality {
  if (typeof window === 'undefined') return 'medium';
  const small = Math.min(window.innerWidth, window.innerHeight) < 700;
  const lowCores = (navigator as any).hardwareConcurrency && (navigator as any).hardwareConcurrency <= 4;
  return small || lowCores ? 'low' : 'high';
}

function PropLoader({ name, onReady }: { name: string; onReady: (o: THREE.Object3D) => void }) {
  const g = useGLTF(PROP_URL(name), DRACO);
  useEffect(() => { onReady(g.scene.clone(true)); }, [g.scene, onReady]);
  return null;
}

interface ModelProps {
  who: MascotWho;
  mood?: MascotMood;
  energy?: number;
  /** Prop file name under /models/mascots/props (e.g. 'book', 'camera'), or null for empty hands. */
  prop?: string | null;
  fur?: FurQuality;
  position?: [number, number, number];
  rotationY?: number;
  scale?: number;
}

export const MascotModel = forwardRef<MascotHandle, ModelProps>(function MascotModel(
  { who, mood = 'idle', energy = 0, prop = null, fur, position = [0, 0, 0], rotationY = 0, scale = 1 }, ref,
) {
  const gltf = useGLTF(MASCOT_URL(who), DRACO);
  const furQ = useMemo(() => fur ?? defaultFur(), [fur]);
  // SkeletonUtils clone: the skin/fins/horns are skinned; a plain clone would stay bound to the cached skeleton.
  // Never dispose the clone's geometry — it is shared with useGLTF's cache.
  const rig = useMemo(
    () => new MascotRig({ scene: cloneSkinned(gltf.scene) as THREE.Object3D, animations: gltf.animations }, { fur: furQ, reducedMotion: prefersReducedMotion() }),
    [gltf.scene, gltf.animations, furQ],
  );
  useEffect(() => () => rig.dispose(), [rig]);
  useEffect(() => { rig.setMood(mood); }, [rig, mood]);
  useEffect(() => { rig.setEnergy(energy); }, [rig, energy]);
  useEffect(() => { if (!prop) rig.setProp(null); }, [rig, prop]);
  useImperativeHandle(ref, () => ({ react: (r: MascotReaction) => rig.react(r) }), [rig]);
  useFrame((_, dt) => rig.update(dt));
  const onProp = useMemo(() => (o: THREE.Object3D) => rig.setProp(o), [rig]);
  return (
    <group position={position} rotation={[0, rotationY, 0]} scale={scale}>
      <primitive object={rig.root} />
      {prop ? <Suspense fallback={null}><PropLoader name={prop} onReady={onProp} /></Suspense> : null}
    </group>
  );
});

interface WidgetProps extends Omit<ModelProps, 'position' | 'rotationY' | 'scale'> {
  /** CSS size of the square widget (px or any CSS length). */
  size?: number | string;
  className?: string;
  /** Slight 3/4 turn reads better than dead-on front. */
  turn?: number;
  ariaLabel?: string;
}

/** Self-contained transparent widget: drop it into any layout (Homeroom greeting, Voca coach corner, etc). */
export const PlajahMascot = forwardRef<MascotHandle, WidgetProps>(function PlajahMascot(
  { who, mood, energy, prop, fur, size = 200, className, turn = -0.3, ariaLabel }, ref,
) {
  const host = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(true);
  useEffect(() => {
    // stop rendering while scrolled off-screen — these sit on busy pages and phones
    const el = host.current; if (!el || typeof IntersectionObserver === 'undefined') return;
    const io = new IntersectionObserver(([e]) => setVisible(e.isIntersecting), { rootMargin: '120px' });
    io.observe(el); return () => io.disconnect();
  }, []);
  return (
    <div ref={host} className={className} role="img" aria-label={ariaLabel ?? (who === 'chora' ? 'Chora' : 'Reello')}
      style={{ width: size, height: size, position: 'relative' }}>
      <Canvas frameloop={visible ? 'always' : 'never'} dpr={[1, 2]}
        gl={{ alpha: true, antialias: true, toneMapping: THREE.NeutralToneMapping }}
        camera={{ fov: 28, position: [0, 0.7, 3.5], near: 0.05, far: 20 }}
        onCreated={({ camera }) => camera.lookAt(0, 0.6, 0)}>
        <hemisphereLight args={[0xf1ebff, 0x2a1530, 0.7]} />
        <directionalLight position={[-1.8, 2.8, 2.4]} intensity={2.4} color={0xfff4ec} />
        <directionalLight position={[0.8, 1.9, -2.6]} intensity={2.0} color={0xff86c2} />
        <directionalLight position={[2.4, 0.7, 1.4]} intensity={0.55} color={0xa9d6ff} />
        <Suspense fallback={null}>
          <MascotModel ref={ref} who={who} mood={mood} energy={energy} prop={prop} fur={fur} rotationY={turn} />
        </Suspense>
      </Canvas>
    </div>
  );
});

export function preloadMascots() {
  try { useGLTF.preload(MASCOT_URL('chora'), DRACO); useGLTF.preload(MASCOT_URL('reello'), DRACO); } catch { /* never break a page over a preload */ }
}

export default PlajahMascot;
